project:
  type: website
  output-dir: ../docs

website:
  title: "Analysis of Teaching"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 10_download.qmd
        text: Download
      - href: 20_clean.qmd
        text: Clean
      - href: 30_explore.qmd
        text: Explore

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  