---
title: Analysis of Teaching
author: John Leonard
date: last-modified
---

This web report looks at teaching across the College of Engineering since Fall 2020.

This is intended to be a living analysis.  As additions and corrections are found please let me know and we can implement the necessary changes and re-render the report.

This report was developed using [Quarto](https://quarto.org/), an open-source scientific and technical publishing designed with reproducibility in mind.  Analyses were performed using python.  The source code for the pages on this site are available in a [github repository](https://github.com/vcu-ssg/ssg-quarto-soc-analysis).

## Report organization

The site is organized as follow:

* [Download](./10_download.qmd) - this section describes the source of data (VCU reports) and shows the files and semesters downloaded.  This section is provided so that others can obtain the same data used for this report.

* [Clean](./20_clean.qmd) - this section documents the cleaning strategies applied to the data obtained above. This section refactors and reshapes the data, adds new columns and corrects known errors. The data
are stored in this repo, and are also uploaded to this [google sheet](https://docs.google.com/spreadsheets/d/1ZK7k8M85CXLof6FdeJYJuGFbfjsOXrCv5mc7OgUInWw/edit#gid=1728987696).

* [Explore](./30_explore.qmd) - this section offers several sample analysis using the cleaned data. This report is generated using python and matplotlib. The examples are offered as demonstrations of the possible, not as part of a real analysis of workload.

## Worksheet sandbox

Data from the [cleaning step](./20_clean.qmd) are used to support the example output in the [explore](./30_explore.qmd) document.

The resulting data are also [uploaded to google sheets](https://docs.google.com/spreadsheets/d/1ZK7k8M85CXLof6FdeJYJuGFbfjsOXrCv5mc7OgUInWw/edit#gid=1728987696) and complementary analysis is done in the google sheet:

* [Sample instructor reports](https://docs.google.com/spreadsheets/d/1ZK7k8M85CXLof6FdeJYJuGFbfjsOXrCv5mc7OgUInWw/edit#gid=1722375566) highlight the use of the google sheeet QUERY command to build summaries from the raw data.

* [Sample workload report](https://docs.google.com/spreadsheets/d/1ZK7k8M85CXLof6FdeJYJuGFbfjsOXrCv5mc7OgUInWw/edit#gid=1484314377) offers examples of how computations from a [sample workload model](https://vcu-ssg.github.io/ssg-quarto-soc-analysis/20_clean.html#sample-workload-model) can be used to support QUERYs in a google sheet.

These were sample reports are intended to highlight the possible with examples. I did not conduct a full analysis.

## Persistent data

The analyses also expect that there are persistent data stored outside of the VCU report, data that are important for helping classify faculty and courses.

[Instructor data](https://docs.google.com/spreadsheets/d/1ZK7k8M85CXLof6FdeJYJuGFbfjsOXrCv5mc7OgUInWw/edit#gid=654840116) - these data provide instructor departments and instructor roles, and an instructor
workload designation. This table is necessary for the analysis.

[Instructor notes](https://docs.google.com/spreadsheets/d/1ZK7k8M85CXLof6FdeJYJuGFbfjsOXrCv5mc7OgUInWw/edit#gid=211942472) - these data offer additional details about instructors.  It is expected that these data might be incorporated into a subsequent workload report. This table is optional to this analysis.

[Course notes](https://docs.google.com/spreadsheets/d/1ZK7k8M85CXLof6FdeJYJuGFbfjsOXrCv5mc7OgUInWw/edit#gid=498592034) - these data offer additional details about the courses. This table is optional to this analysis.

