---
title: Teaching activity for Da Silva Soares,Joao Filipe
date: last-modified
---

Below is a listing of teaching over time for department EGRM


## Joao Filipe Da Silva Soares

<style type="text/css">
#T_5fac7 table {
  width: 100%;
  border-collapse: collapse;
}
#T_5fac7 th {
  text-align: center;
  padding: 8px;
}
#T_5fac7 td:nth-child(1) {
  padding-right: 10px;
  text-align: left;
}
#T_5fac7 td:nth-child(2) {
  padding-right: 5px;
  text-align: left;
}
#T_5fac7  td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_5fac7 td:nth-child(3) {
  text-align: center;
}
#T_5fac7  td:nth-child(5) {
  text-align: center;
}
#T_5fac7 td:nth-child(6) {
  text-align: right;
}
#T_5fac7  td:nth-child(7) {
  text-align: right;
}
#T_5fac7_row0_col0, #T_5fac7_row0_col1, #T_5fac7_row0_col2, #T_5fac7_row0_col3, #T_5fac7_row0_col4, #T_5fac7_row0_col5, #T_5fac7_row0_col6, #T_5fac7_row1_col0, #T_5fac7_row1_col1, #T_5fac7_row1_col2, #T_5fac7_row1_col3, #T_5fac7_row1_col4, #T_5fac7_row1_col5, #T_5fac7_row1_col6, #T_5fac7_row2_col0, #T_5fac7_row2_col1, #T_5fac7_row2_col2, #T_5fac7_row2_col3, #T_5fac7_row2_col4, #T_5fac7_row2_col5, #T_5fac7_row2_col6, #T_5fac7_row15_col0, #T_5fac7_row15_col1, #T_5fac7_row15_col2, #T_5fac7_row15_col3, #T_5fac7_row15_col4, #T_5fac7_row15_col5, #T_5fac7_row15_col6, #T_5fac7_row16_col0, #T_5fac7_row16_col1, #T_5fac7_row16_col2, #T_5fac7_row16_col3, #T_5fac7_row16_col4, #T_5fac7_row16_col5, #T_5fac7_row16_col6, #T_5fac7_row17_col0, #T_5fac7_row17_col1, #T_5fac7_row17_col2, #T_5fac7_row17_col3, #T_5fac7_row17_col4, #T_5fac7_row17_col5, #T_5fac7_row17_col6, #T_5fac7_row18_col0, #T_5fac7_row18_col1, #T_5fac7_row18_col2, #T_5fac7_row18_col3, #T_5fac7_row18_col4, #T_5fac7_row18_col5, #T_5fac7_row18_col6, #T_5fac7_row21_col0, #T_5fac7_row21_col1, #T_5fac7_row21_col2, #T_5fac7_row21_col3, #T_5fac7_row21_col4, #T_5fac7_row21_col5, #T_5fac7_row21_col6, #T_5fac7_row22_col0, #T_5fac7_row22_col1, #T_5fac7_row22_col2, #T_5fac7_row22_col3, #T_5fac7_row22_col4, #T_5fac7_row22_col5, #T_5fac7_row22_col6, #T_5fac7_row38_col0, #T_5fac7_row38_col1, #T_5fac7_row38_col2, #T_5fac7_row38_col3, #T_5fac7_row38_col4, #T_5fac7_row38_col5, #T_5fac7_row38_col6, #T_5fac7_row39_col0, #T_5fac7_row39_col1, #T_5fac7_row39_col2, #T_5fac7_row39_col3, #T_5fac7_row39_col4, #T_5fac7_row39_col5, #T_5fac7_row39_col6, #T_5fac7_row40_col0, #T_5fac7_row40_col1, #T_5fac7_row40_col2, #T_5fac7_row40_col3, #T_5fac7_row40_col4, #T_5fac7_row40_col5, #T_5fac7_row40_col6, #T_5fac7_row41_col0, #T_5fac7_row41_col1, #T_5fac7_row41_col2, #T_5fac7_row41_col3, #T_5fac7_row41_col4, #T_5fac7_row41_col5, #T_5fac7_row41_col6, #T_5fac7_row42_col0, #T_5fac7_row42_col1, #T_5fac7_row42_col2, #T_5fac7_row42_col3, #T_5fac7_row42_col4, #T_5fac7_row42_col5, #T_5fac7_row42_col6, #T_5fac7_row43_col0, #T_5fac7_row43_col1, #T_5fac7_row43_col2, #T_5fac7_row43_col3, #T_5fac7_row43_col4, #T_5fac7_row43_col5, #T_5fac7_row43_col6, #T_5fac7_row44_col0, #T_5fac7_row44_col1, #T_5fac7_row44_col2, #T_5fac7_row44_col3, #T_5fac7_row44_col4, #T_5fac7_row44_col5, #T_5fac7_row44_col6 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_5fac7_row3_col0, #T_5fac7_row3_col1, #T_5fac7_row3_col2, #T_5fac7_row3_col3, #T_5fac7_row3_col4, #T_5fac7_row3_col5, #T_5fac7_row3_col6, #T_5fac7_row10_col0, #T_5fac7_row10_col1, #T_5fac7_row10_col2, #T_5fac7_row10_col3, #T_5fac7_row10_col4, #T_5fac7_row10_col5, #T_5fac7_row10_col6, #T_5fac7_row19_col0, #T_5fac7_row19_col1, #T_5fac7_row19_col2, #T_5fac7_row19_col3, #T_5fac7_row19_col4, #T_5fac7_row19_col5, #T_5fac7_row19_col6, #T_5fac7_row23_col0, #T_5fac7_row23_col1, #T_5fac7_row23_col2, #T_5fac7_row23_col3, #T_5fac7_row23_col4, #T_5fac7_row23_col5, #T_5fac7_row23_col6, #T_5fac7_row29_col0, #T_5fac7_row29_col1, #T_5fac7_row29_col2, #T_5fac7_row29_col3, #T_5fac7_row29_col4, #T_5fac7_row29_col5, #T_5fac7_row29_col6, #T_5fac7_row45_col0, #T_5fac7_row45_col1, #T_5fac7_row45_col2, #T_5fac7_row45_col3, #T_5fac7_row45_col4, #T_5fac7_row45_col5, #T_5fac7_row45_col6 {
  background-color: #f0f0f0;
  border-bottom: 1px solid #ccc;
}
#T_5fac7_row4_col0, #T_5fac7_row4_col1, #T_5fac7_row4_col2, #T_5fac7_row4_col3, #T_5fac7_row4_col4, #T_5fac7_row4_col5, #T_5fac7_row4_col6, #T_5fac7_row5_col0, #T_5fac7_row5_col1, #T_5fac7_row5_col2, #T_5fac7_row5_col3, #T_5fac7_row5_col4, #T_5fac7_row5_col5, #T_5fac7_row5_col6, #T_5fac7_row6_col0, #T_5fac7_row6_col1, #T_5fac7_row6_col2, #T_5fac7_row6_col3, #T_5fac7_row6_col4, #T_5fac7_row6_col5, #T_5fac7_row6_col6, #T_5fac7_row7_col0, #T_5fac7_row7_col1, #T_5fac7_row7_col2, #T_5fac7_row7_col3, #T_5fac7_row7_col4, #T_5fac7_row7_col5, #T_5fac7_row7_col6, #T_5fac7_row8_col0, #T_5fac7_row8_col1, #T_5fac7_row8_col2, #T_5fac7_row8_col3, #T_5fac7_row8_col4, #T_5fac7_row8_col5, #T_5fac7_row8_col6, #T_5fac7_row11_col0, #T_5fac7_row11_col1, #T_5fac7_row11_col2, #T_5fac7_row11_col3, #T_5fac7_row11_col4, #T_5fac7_row11_col5, #T_5fac7_row11_col6, #T_5fac7_row12_col0, #T_5fac7_row12_col1, #T_5fac7_row12_col2, #T_5fac7_row12_col3, #T_5fac7_row12_col4, #T_5fac7_row12_col5, #T_5fac7_row12_col6, #T_5fac7_row13_col0, #T_5fac7_row13_col1, #T_5fac7_row13_col2, #T_5fac7_row13_col3, #T_5fac7_row13_col4, #T_5fac7_row13_col5, #T_5fac7_row13_col6, #T_5fac7_row24_col0, #T_5fac7_row24_col1, #T_5fac7_row24_col2, #T_5fac7_row24_col3, #T_5fac7_row24_col4, #T_5fac7_row24_col5, #T_5fac7_row24_col6, #T_5fac7_row25_col0, #T_5fac7_row25_col1, #T_5fac7_row25_col2, #T_5fac7_row25_col3, #T_5fac7_row25_col4, #T_5fac7_row25_col5, #T_5fac7_row25_col6, #T_5fac7_row26_col0, #T_5fac7_row26_col1, #T_5fac7_row26_col2, #T_5fac7_row26_col3, #T_5fac7_row26_col4, #T_5fac7_row26_col5, #T_5fac7_row26_col6, #T_5fac7_row27_col0, #T_5fac7_row27_col1, #T_5fac7_row27_col2, #T_5fac7_row27_col3, #T_5fac7_row27_col4, #T_5fac7_row27_col5, #T_5fac7_row27_col6, #T_5fac7_row30_col0, #T_5fac7_row30_col1, #T_5fac7_row30_col2, #T_5fac7_row30_col3, #T_5fac7_row30_col4, #T_5fac7_row30_col5, #T_5fac7_row30_col6, #T_5fac7_row31_col0, #T_5fac7_row31_col1, #T_5fac7_row31_col2, #T_5fac7_row31_col3, #T_5fac7_row31_col4, #T_5fac7_row31_col5, #T_5fac7_row31_col6, #T_5fac7_row32_col0, #T_5fac7_row32_col1, #T_5fac7_row32_col2, #T_5fac7_row32_col3, #T_5fac7_row32_col4, #T_5fac7_row32_col5, #T_5fac7_row32_col6, #T_5fac7_row33_col0, #T_5fac7_row33_col1, #T_5fac7_row33_col2, #T_5fac7_row33_col3, #T_5fac7_row33_col4, #T_5fac7_row33_col5, #T_5fac7_row33_col6, #T_5fac7_row34_col0, #T_5fac7_row34_col1, #T_5fac7_row34_col2, #T_5fac7_row34_col3, #T_5fac7_row34_col4, #T_5fac7_row34_col5, #T_5fac7_row34_col6, #T_5fac7_row35_col0, #T_5fac7_row35_col1, #T_5fac7_row35_col2, #T_5fac7_row35_col3, #T_5fac7_row35_col4, #T_5fac7_row35_col5, #T_5fac7_row35_col6, #T_5fac7_row36_col0, #T_5fac7_row36_col1, #T_5fac7_row36_col2, #T_5fac7_row36_col3, #T_5fac7_row36_col4, #T_5fac7_row36_col5, #T_5fac7_row36_col6, #T_5fac7_row46_col0, #T_5fac7_row46_col1, #T_5fac7_row46_col2, #T_5fac7_row46_col3, #T_5fac7_row46_col4, #T_5fac7_row46_col5, #T_5fac7_row46_col6, #T_5fac7_row47_col0, #T_5fac7_row47_col1, #T_5fac7_row47_col2, #T_5fac7_row47_col3, #T_5fac7_row47_col4, #T_5fac7_row47_col5, #T_5fac7_row47_col6, #T_5fac7_row48_col0, #T_5fac7_row48_col1, #T_5fac7_row48_col2, #T_5fac7_row48_col3, #T_5fac7_row48_col4, #T_5fac7_row48_col5, #T_5fac7_row48_col6, #T_5fac7_row49_col0, #T_5fac7_row49_col1, #T_5fac7_row49_col2, #T_5fac7_row49_col3, #T_5fac7_row49_col4, #T_5fac7_row49_col5, #T_5fac7_row49_col6, #T_5fac7_row50_col0, #T_5fac7_row50_col1, #T_5fac7_row50_col2, #T_5fac7_row50_col3, #T_5fac7_row50_col4, #T_5fac7_row50_col5, #T_5fac7_row50_col6, #T_5fac7_row51_col0, #T_5fac7_row51_col1, #T_5fac7_row51_col2, #T_5fac7_row51_col3, #T_5fac7_row51_col4, #T_5fac7_row51_col5, #T_5fac7_row51_col6, #T_5fac7_row52_col0, #T_5fac7_row52_col1, #T_5fac7_row52_col2, #T_5fac7_row52_col3, #T_5fac7_row52_col4, #T_5fac7_row52_col5, #T_5fac7_row52_col6 {
  background-color: #ffffff;
  border-bottom: none;
}
#T_5fac7_row9_col0, #T_5fac7_row9_col1, #T_5fac7_row9_col2, #T_5fac7_row9_col3, #T_5fac7_row9_col4, #T_5fac7_row9_col5, #T_5fac7_row9_col6, #T_5fac7_row14_col0, #T_5fac7_row14_col1, #T_5fac7_row14_col2, #T_5fac7_row14_col3, #T_5fac7_row14_col4, #T_5fac7_row14_col5, #T_5fac7_row14_col6, #T_5fac7_row20_col0, #T_5fac7_row20_col1, #T_5fac7_row20_col2, #T_5fac7_row20_col3, #T_5fac7_row20_col4, #T_5fac7_row20_col5, #T_5fac7_row20_col6, #T_5fac7_row28_col0, #T_5fac7_row28_col1, #T_5fac7_row28_col2, #T_5fac7_row28_col3, #T_5fac7_row28_col4, #T_5fac7_row28_col5, #T_5fac7_row28_col6, #T_5fac7_row37_col0, #T_5fac7_row37_col1, #T_5fac7_row37_col2, #T_5fac7_row37_col3, #T_5fac7_row37_col4, #T_5fac7_row37_col5, #T_5fac7_row37_col6, #T_5fac7_row53_col0, #T_5fac7_row53_col1, #T_5fac7_row53_col2, #T_5fac7_row53_col3, #T_5fac7_row53_col4, #T_5fac7_row53_col5, #T_5fac7_row53_col6 {
  background-color: #ffffff;
  border-bottom: 1px solid #ccc;
}
</style>
<table id="T_5fac7">
  <thead>
    <tr>
      <th id="T_5fac7_level0_col0" class="col_heading level0 col0" >Term</th>
      <th id="T_5fac7_level0_col1" class="col_heading level0 col1" >Crse</th>
      <th id="T_5fac7_level0_col2" class="col_heading level0 col2" >Sect</th>
      <th id="T_5fac7_level0_col3" class="col_heading level0 col3" >Crse Title</th>
      <th id="T_5fac7_level0_col4" class="col_heading level0 col4" >W.Type</th>
      <th id="T_5fac7_level0_col5" class="col_heading level0 col5" >Stdnts</th>
      <th id="T_5fac7_level0_col6" class="col_heading level0 col6" >Hours</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_5fac7_row0_col0" class="data row0 col0" >Fall 2020</td>
      <td id="T_5fac7_row0_col1" class="data row0 col1" >EGMN606</td>
      <td id="T_5fac7_row0_col2" class="data row0 col2" >901</td>
      <td id="T_5fac7_row0_col3" class="data row0 col3" >MECH & NUC ENGINEER CONTINUUM</td>
      <td id="T_5fac7_row0_col4" class="data row0 col4" >LEC</td>
      <td id="T_5fac7_row0_col5" class="data row0 col5" >9</td>
      <td id="T_5fac7_row0_col6" class="data row0 col6" >27</td>
    </tr>
    <tr>
      <td id="T_5fac7_row1_col0" class="data row1 col0" >Fall 2020</td>
      <td id="T_5fac7_row1_col1" class="data row1 col1" >EGMN606</td>
      <td id="T_5fac7_row1_col2" class="data row1 col2" >C90</td>
      <td id="T_5fac7_row1_col3" class="data row1 col3" >MECH & NUC ENGINEER CONTINUUM</td>
      <td id="T_5fac7_row1_col4" class="data row1 col4" >LEC</td>
      <td id="T_5fac7_row1_col5" class="data row1 col5" >54</td>
      <td id="T_5fac7_row1_col6" class="data row1 col6" >162</td>
    </tr>
    <tr>
      <td id="T_5fac7_row2_col0" class="data row2 col0" >Fall 2020</td>
      <td id="T_5fac7_row2_col1" class="data row2 col1" >EGMN697</td>
      <td id="T_5fac7_row2_col2" class="data row2 col2" >100</td>
      <td id="T_5fac7_row2_col3" class="data row2 col3" >DIRECTED RESEARCH</td>
      <td id="T_5fac7_row2_col4" class="data row2 col4" >RES</td>
      <td id="T_5fac7_row2_col5" class="data row2 col5" >2</td>
      <td id="T_5fac7_row2_col6" class="data row2 col6" >12</td>
    </tr>
    <tr>
      <td id="T_5fac7_row3_col0" class="data row3 col0" >Fall 2020</td>
      <td id="T_5fac7_row3_col1" class="data row3 col1" >ENGR497</td>
      <td id="T_5fac7_row3_col2" class="data row3 col2" >L25</td>
      <td id="T_5fac7_row3_col3" class="data row3 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5fac7_row3_col4" class="data row3 col4" >VIP</td>
      <td id="T_5fac7_row3_col5" class="data row3 col5" >3</td>
      <td id="T_5fac7_row3_col6" class="data row3 col6" >3</td>
    </tr>
    <tr>
      <td id="T_5fac7_row4_col0" class="data row4 col0" >Spring 2021</td>
      <td id="T_5fac7_row4_col1" class="data row4 col1" >EGMN202</td>
      <td id="T_5fac7_row4_col2" class="data row4 col2" >001</td>
      <td id="T_5fac7_row4_col3" class="data row4 col3" >MECHANICS OF DEFORMABLES</td>
      <td id="T_5fac7_row4_col4" class="data row4 col4" >LEC</td>
      <td id="T_5fac7_row4_col5" class="data row4 col5" >19</td>
      <td id="T_5fac7_row4_col6" class="data row4 col6" >57</td>
    </tr>
    <tr>
      <td id="T_5fac7_row5_col0" class="data row5 col0" >Spring 2021</td>
      <td id="T_5fac7_row5_col1" class="data row5 col1" >EGMN202</td>
      <td id="T_5fac7_row5_col2" class="data row5 col2" >002</td>
      <td id="T_5fac7_row5_col3" class="data row5 col3" >MECHANICS OF DEFORMABLES</td>
      <td id="T_5fac7_row5_col4" class="data row5 col4" >LEC</td>
      <td id="T_5fac7_row5_col5" class="data row5 col5" >52</td>
      <td id="T_5fac7_row5_col6" class="data row5 col6" >156</td>
    </tr>
    <tr>
      <td id="T_5fac7_row6_col0" class="data row6 col0" >Spring 2021</td>
      <td id="T_5fac7_row6_col1" class="data row6 col1" >EGMN403</td>
      <td id="T_5fac7_row6_col2" class="data row6 col2" >L27</td>
      <td id="T_5fac7_row6_col3" class="data row6 col3" >SENIOR DESIGN STUDIO(LAB/PROJ)</td>
      <td id="T_5fac7_row6_col4" class="data row6 col4" >CAP</td>
      <td id="T_5fac7_row6_col5" class="data row6 col5" >4</td>
      <td id="T_5fac7_row6_col6" class="data row6 col6" >8</td>
    </tr>
    <tr>
      <td id="T_5fac7_row7_col0" class="data row7 col0" >Spring 2021</td>
      <td id="T_5fac7_row7_col1" class="data row7 col1" >EGMN697</td>
      <td id="T_5fac7_row7_col2" class="data row7 col2" >097</td>
      <td id="T_5fac7_row7_col3" class="data row7 col3" >DIRECTED RESEARCH</td>
      <td id="T_5fac7_row7_col4" class="data row7 col4" >RES</td>
      <td id="T_5fac7_row7_col5" class="data row7 col5" >2</td>
      <td id="T_5fac7_row7_col6" class="data row7 col6" >18</td>
    </tr>
    <tr>
      <td id="T_5fac7_row8_col0" class="data row8 col0" >Spring 2021</td>
      <td id="T_5fac7_row8_col1" class="data row8 col1" >ENGR497</td>
      <td id="T_5fac7_row8_col2" class="data row8 col2" >L31</td>
      <td id="T_5fac7_row8_col3" class="data row8 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5fac7_row8_col4" class="data row8 col4" >VIP</td>
      <td id="T_5fac7_row8_col5" class="data row8 col5" >6</td>
      <td id="T_5fac7_row8_col6" class="data row8 col6" >6</td>
    </tr>
    <tr>
      <td id="T_5fac7_row9_col0" class="data row9 col0" >Spring 2021</td>
      <td id="T_5fac7_row9_col1" class="data row9 col1" >ENGR497</td>
      <td id="T_5fac7_row9_col2" class="data row9 col2" >L32</td>
      <td id="T_5fac7_row9_col3" class="data row9 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5fac7_row9_col4" class="data row9 col4" >VIP</td>
      <td id="T_5fac7_row9_col5" class="data row9 col5" >1</td>
      <td id="T_5fac7_row9_col6" class="data row9 col6" >2</td>
    </tr>
    <tr>
      <td id="T_5fac7_row10_col0" class="data row10 col0" >Summer 2021</td>
      <td id="T_5fac7_row10_col1" class="data row10 col1" >EGMN697</td>
      <td id="T_5fac7_row10_col2" class="data row10 col2" >077</td>
      <td id="T_5fac7_row10_col3" class="data row10 col3" >DIRECTED RESEARCH</td>
      <td id="T_5fac7_row10_col4" class="data row10 col4" >RES</td>
      <td id="T_5fac7_row10_col5" class="data row10 col5" >1</td>
      <td id="T_5fac7_row10_col6" class="data row10 col6" >3</td>
    </tr>
    <tr>
      <td id="T_5fac7_row11_col0" class="data row11 col0" >Fall 2021</td>
      <td id="T_5fac7_row11_col1" class="data row11 col1" >EGMN606</td>
      <td id="T_5fac7_row11_col2" class="data row11 col2" >901</td>
      <td id="T_5fac7_row11_col3" class="data row11 col3" >MECH & NUC ENGINEER CONTINUUM</td>
      <td id="T_5fac7_row11_col4" class="data row11 col4" >LEC</td>
      <td id="T_5fac7_row11_col5" class="data row11 col5" >7</td>
      <td id="T_5fac7_row11_col6" class="data row11 col6" >21</td>
    </tr>
    <tr>
      <td id="T_5fac7_row12_col0" class="data row12 col0" >Fall 2021</td>
      <td id="T_5fac7_row12_col1" class="data row12 col1" >EGMN606</td>
      <td id="T_5fac7_row12_col2" class="data row12 col2" >C90</td>
      <td id="T_5fac7_row12_col3" class="data row12 col3" >MECH & NUC ENGINEER CONTINUUM</td>
      <td id="T_5fac7_row12_col4" class="data row12 col4" >LEC</td>
      <td id="T_5fac7_row12_col5" class="data row12 col5" >12</td>
      <td id="T_5fac7_row12_col6" class="data row12 col6" >36</td>
    </tr>
    <tr>
      <td id="T_5fac7_row13_col0" class="data row13 col0" >Fall 2021</td>
      <td id="T_5fac7_row13_col1" class="data row13 col1" >ENGR497</td>
      <td id="T_5fac7_row13_col2" class="data row13 col2" >L25</td>
      <td id="T_5fac7_row13_col3" class="data row13 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5fac7_row13_col4" class="data row13 col4" >VIP</td>
      <td id="T_5fac7_row13_col5" class="data row13 col5" >7</td>
      <td id="T_5fac7_row13_col6" class="data row13 col6" >7</td>
    </tr>
    <tr>
      <td id="T_5fac7_row14_col0" class="data row14 col0" >Fall 2021</td>
      <td id="T_5fac7_row14_col1" class="data row14 col1" >ENGR701</td>
      <td id="T_5fac7_row14_col2" class="data row14 col2" >034</td>
      <td id="T_5fac7_row14_col3" class="data row14 col3" >POST-CANDIDACY DOCT RESEARCH</td>
      <td id="T_5fac7_row14_col4" class="data row14 col4" >RES</td>
      <td id="T_5fac7_row14_col5" class="data row14 col5" >2</td>
      <td id="T_5fac7_row14_col6" class="data row14 col6" >18</td>
    </tr>
    <tr>
      <td id="T_5fac7_row15_col0" class="data row15 col0" >Spring 2022</td>
      <td id="T_5fac7_row15_col1" class="data row15 col1" >EGMN202</td>
      <td id="T_5fac7_row15_col2" class="data row15 col2" >001</td>
      <td id="T_5fac7_row15_col3" class="data row15 col3" >MECHANICS OF DEFORMABLES</td>
      <td id="T_5fac7_row15_col4" class="data row15 col4" >LEC</td>
      <td id="T_5fac7_row15_col5" class="data row15 col5" >60</td>
      <td id="T_5fac7_row15_col6" class="data row15 col6" >180</td>
    </tr>
    <tr>
      <td id="T_5fac7_row16_col0" class="data row16 col0" >Spring 2022</td>
      <td id="T_5fac7_row16_col1" class="data row16 col1" >EGMN403</td>
      <td id="T_5fac7_row16_col2" class="data row16 col2" >L27</td>
      <td id="T_5fac7_row16_col3" class="data row16 col3" >SENIOR DESIGN STUDIO(LAB/PROJ)</td>
      <td id="T_5fac7_row16_col4" class="data row16 col4" >CAP</td>
      <td id="T_5fac7_row16_col5" class="data row16 col5" >4</td>
      <td id="T_5fac7_row16_col6" class="data row16 col6" >8</td>
    </tr>
    <tr>
      <td id="T_5fac7_row17_col0" class="data row17 col0" >Spring 2022</td>
      <td id="T_5fac7_row17_col1" class="data row17 col1" >EGMN697</td>
      <td id="T_5fac7_row17_col2" class="data row17 col2" >003</td>
      <td id="T_5fac7_row17_col3" class="data row17 col3" >DIRECTED RESEARCH</td>
      <td id="T_5fac7_row17_col4" class="data row17 col4" >RES</td>
      <td id="T_5fac7_row17_col5" class="data row17 col5" >1</td>
      <td id="T_5fac7_row17_col6" class="data row17 col6" >6</td>
    </tr>
    <tr>
      <td id="T_5fac7_row18_col0" class="data row18 col0" >Spring 2022</td>
      <td id="T_5fac7_row18_col1" class="data row18 col1" >ENGR497</td>
      <td id="T_5fac7_row18_col2" class="data row18 col2" >L31</td>
      <td id="T_5fac7_row18_col3" class="data row18 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5fac7_row18_col4" class="data row18 col4" >VIP</td>
      <td id="T_5fac7_row18_col5" class="data row18 col5" >4</td>
      <td id="T_5fac7_row18_col6" class="data row18 col6" >4</td>
    </tr>
    <tr>
      <td id="T_5fac7_row19_col0" class="data row19 col0" >Spring 2022</td>
      <td id="T_5fac7_row19_col1" class="data row19 col1" >ENGR701</td>
      <td id="T_5fac7_row19_col2" class="data row19 col2" >034</td>
      <td id="T_5fac7_row19_col3" class="data row19 col3" >POST-CANDIDACY DOCT RESEARCH</td>
      <td id="T_5fac7_row19_col4" class="data row19 col4" >RES</td>
      <td id="T_5fac7_row19_col5" class="data row19 col5" >1</td>
      <td id="T_5fac7_row19_col6" class="data row19 col6" >9</td>
    </tr>
    <tr>
      <td id="T_5fac7_row20_col0" class="data row20 col0" >Summer 2022</td>
      <td id="T_5fac7_row20_col1" class="data row20 col1" >EGMN697</td>
      <td id="T_5fac7_row20_col2" class="data row20 col2" >077</td>
      <td id="T_5fac7_row20_col3" class="data row20 col3" >DIRECTED RESEARCH</td>
      <td id="T_5fac7_row20_col4" class="data row20 col4" >RES</td>
      <td id="T_5fac7_row20_col5" class="data row20 col5" >2</td>
      <td id="T_5fac7_row20_col6" class="data row20 col6" >6</td>
    </tr>
    <tr>
      <td id="T_5fac7_row21_col0" class="data row21 col0" >Fall 2022</td>
      <td id="T_5fac7_row21_col1" class="data row21 col1" >EGMN202</td>
      <td id="T_5fac7_row21_col2" class="data row21 col2" >001</td>
      <td id="T_5fac7_row21_col3" class="data row21 col3" >MECHANICS OF DEFORMABLES</td>
      <td id="T_5fac7_row21_col4" class="data row21 col4" >LEC</td>
      <td id="T_5fac7_row21_col5" class="data row21 col5" >21</td>
      <td id="T_5fac7_row21_col6" class="data row21 col6" >63</td>
    </tr>
    <tr>
      <td id="T_5fac7_row22_col0" class="data row22 col0" >Fall 2022</td>
      <td id="T_5fac7_row22_col1" class="data row22 col1" >EGMN402</td>
      <td id="T_5fac7_row22_col2" class="data row22 col2" >L24</td>
      <td id="T_5fac7_row22_col3" class="data row22 col3" >SENIOR DESIGN STUDIO(LAB/PROJ)</td>
      <td id="T_5fac7_row22_col4" class="data row22 col4" >CAP</td>
      <td id="T_5fac7_row22_col5" class="data row22 col5" >2</td>
      <td id="T_5fac7_row22_col6" class="data row22 col6" >4</td>
    </tr>
    <tr>
      <td id="T_5fac7_row23_col0" class="data row23 col0" >Fall 2022</td>
      <td id="T_5fac7_row23_col1" class="data row23 col1" >ENGR497</td>
      <td id="T_5fac7_row23_col2" class="data row23 col2" >L25</td>
      <td id="T_5fac7_row23_col3" class="data row23 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5fac7_row23_col4" class="data row23 col4" >VIP</td>
      <td id="T_5fac7_row23_col5" class="data row23 col5" >4</td>
      <td id="T_5fac7_row23_col6" class="data row23 col6" >4</td>
    </tr>
    <tr>
      <td id="T_5fac7_row24_col0" class="data row24 col0" >Spring 2023</td>
      <td id="T_5fac7_row24_col1" class="data row24 col1" >EGMN403</td>
      <td id="T_5fac7_row24_col2" class="data row24 col2" >L27</td>
      <td id="T_5fac7_row24_col3" class="data row24 col3" >SENIOR DESIGN STUDIO(LAB/PROJ)</td>
      <td id="T_5fac7_row24_col4" class="data row24 col4" >CAP</td>
      <td id="T_5fac7_row24_col5" class="data row24 col5" >2</td>
      <td id="T_5fac7_row24_col6" class="data row24 col6" >4</td>
    </tr>
    <tr>
      <td id="T_5fac7_row25_col0" class="data row25 col0" >Spring 2023</td>
      <td id="T_5fac7_row25_col1" class="data row25 col1" >EGMN606</td>
      <td id="T_5fac7_row25_col2" class="data row25 col2" >901</td>
      <td id="T_5fac7_row25_col3" class="data row25 col3" >MECH & NUC ENGINEER CONTINUUM</td>
      <td id="T_5fac7_row25_col4" class="data row25 col4" >LEC</td>
      <td id="T_5fac7_row25_col5" class="data row25 col5" >12</td>
      <td id="T_5fac7_row25_col6" class="data row25 col6" >36</td>
    </tr>
    <tr>
      <td id="T_5fac7_row26_col0" class="data row26 col0" >Spring 2023</td>
      <td id="T_5fac7_row26_col1" class="data row26 col1" >EGMN697</td>
      <td id="T_5fac7_row26_col2" class="data row26 col2" >003</td>
      <td id="T_5fac7_row26_col3" class="data row26 col3" >DIRECTED RESEARCH</td>
      <td id="T_5fac7_row26_col4" class="data row26 col4" >RES</td>
      <td id="T_5fac7_row26_col5" class="data row26 col5" >2</td>
      <td id="T_5fac7_row26_col6" class="data row26 col6" >12</td>
    </tr>
    <tr>
      <td id="T_5fac7_row27_col0" class="data row27 col0" >Spring 2023</td>
      <td id="T_5fac7_row27_col1" class="data row27 col1" >ENGR497</td>
      <td id="T_5fac7_row27_col2" class="data row27 col2" >L31</td>
      <td id="T_5fac7_row27_col3" class="data row27 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5fac7_row27_col4" class="data row27 col4" >VIP</td>
      <td id="T_5fac7_row27_col5" class="data row27 col5" >4</td>
      <td id="T_5fac7_row27_col6" class="data row27 col6" >4</td>
    </tr>
    <tr>
      <td id="T_5fac7_row28_col0" class="data row28 col0" >Spring 2023</td>
      <td id="T_5fac7_row28_col1" class="data row28 col1" >ENGR497</td>
      <td id="T_5fac7_row28_col2" class="data row28 col2" >L32</td>
      <td id="T_5fac7_row28_col3" class="data row28 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5fac7_row28_col4" class="data row28 col4" >VIP</td>
      <td id="T_5fac7_row28_col5" class="data row28 col5" >2</td>
      <td id="T_5fac7_row28_col6" class="data row28 col6" >4</td>
    </tr>
    <tr>
      <td id="T_5fac7_row29_col0" class="data row29 col0" >Summer 2023</td>
      <td id="T_5fac7_row29_col1" class="data row29 col1" >EGMN697</td>
      <td id="T_5fac7_row29_col2" class="data row29 col2" >077</td>
      <td id="T_5fac7_row29_col3" class="data row29 col3" >DIRECTED RESEARCH</td>
      <td id="T_5fac7_row29_col4" class="data row29 col4" >RES</td>
      <td id="T_5fac7_row29_col5" class="data row29 col5" >1</td>
      <td id="T_5fac7_row29_col6" class="data row29 col6" >3</td>
    </tr>
    <tr>
      <td id="T_5fac7_row30_col0" class="data row30 col0" >Fall 2023</td>
      <td id="T_5fac7_row30_col1" class="data row30 col1" >EGMN402</td>
      <td id="T_5fac7_row30_col2" class="data row30 col2" >L24</td>
      <td id="T_5fac7_row30_col3" class="data row30 col3" >SENIOR DESIGN STUDIO(LAB/PROJ)</td>
      <td id="T_5fac7_row30_col4" class="data row30 col4" >CAP</td>
      <td id="T_5fac7_row30_col5" class="data row30 col5" >1</td>
      <td id="T_5fac7_row30_col6" class="data row30 col6" >2</td>
    </tr>
    <tr>
      <td id="T_5fac7_row31_col0" class="data row31 col0" >Fall 2023</td>
      <td id="T_5fac7_row31_col1" class="data row31 col1" >EGMN421</td>
      <td id="T_5fac7_row31_col2" class="data row31 col2" >001</td>
      <td id="T_5fac7_row31_col3" class="data row31 col3" >CAE ANALYSIS</td>
      <td id="T_5fac7_row31_col4" class="data row31 col4" >LAB</td>
      <td id="T_5fac7_row31_col5" class="data row31 col5" >42</td>
      <td id="T_5fac7_row31_col6" class="data row31 col6" >63</td>
    </tr>
    <tr>
      <td id="T_5fac7_row32_col0" class="data row32 col0" >Fall 2023</td>
      <td id="T_5fac7_row32_col1" class="data row32 col1" >EGMN421</td>
      <td id="T_5fac7_row32_col2" class="data row32 col2" >001</td>
      <td id="T_5fac7_row32_col3" class="data row32 col3" >CAE ANALYSIS</td>
      <td id="T_5fac7_row32_col4" class="data row32 col4" >LEC</td>
      <td id="T_5fac7_row32_col5" class="data row32 col5" >42</td>
      <td id="T_5fac7_row32_col6" class="data row32 col6" >63</td>
    </tr>
    <tr>
      <td id="T_5fac7_row33_col0" class="data row33 col0" >Fall 2023</td>
      <td id="T_5fac7_row33_col1" class="data row33 col1" >EGMN421</td>
      <td id="T_5fac7_row33_col2" class="data row33 col2" >002</td>
      <td id="T_5fac7_row33_col3" class="data row33 col3" >CAE ANALYSIS</td>
      <td id="T_5fac7_row33_col4" class="data row33 col4" >LAB</td>
      <td id="T_5fac7_row33_col5" class="data row33 col5" >40</td>
      <td id="T_5fac7_row33_col6" class="data row33 col6" >60</td>
    </tr>
    <tr>
      <td id="T_5fac7_row34_col0" class="data row34 col0" >Fall 2023</td>
      <td id="T_5fac7_row34_col1" class="data row34 col1" >EGMN421</td>
      <td id="T_5fac7_row34_col2" class="data row34 col2" >002</td>
      <td id="T_5fac7_row34_col3" class="data row34 col3" >CAE ANALYSIS</td>
      <td id="T_5fac7_row34_col4" class="data row34 col4" >LEC</td>
      <td id="T_5fac7_row34_col5" class="data row34 col5" >40</td>
      <td id="T_5fac7_row34_col6" class="data row34 col6" >60</td>
    </tr>
    <tr>
      <td id="T_5fac7_row35_col0" class="data row35 col0" >Fall 2023</td>
      <td id="T_5fac7_row35_col1" class="data row35 col1" >EGMN697</td>
      <td id="T_5fac7_row35_col2" class="data row35 col2" >166</td>
      <td id="T_5fac7_row35_col3" class="data row35 col3" >DIRECTED RESEARCH</td>
      <td id="T_5fac7_row35_col4" class="data row35 col4" >RES</td>
      <td id="T_5fac7_row35_col5" class="data row35 col5" >2</td>
      <td id="T_5fac7_row35_col6" class="data row35 col6" >6</td>
    </tr>
    <tr>
      <td id="T_5fac7_row36_col0" class="data row36 col0" >Fall 2023</td>
      <td id="T_5fac7_row36_col1" class="data row36 col1" >ENGR497</td>
      <td id="T_5fac7_row36_col2" class="data row36 col2" >L03</td>
      <td id="T_5fac7_row36_col3" class="data row36 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5fac7_row36_col4" class="data row36 col4" >VIP</td>
      <td id="T_5fac7_row36_col5" class="data row36 col5" >1</td>
      <td id="T_5fac7_row36_col6" class="data row36 col6" >2</td>
    </tr>
    <tr>
      <td id="T_5fac7_row37_col0" class="data row37 col0" >Fall 2023</td>
      <td id="T_5fac7_row37_col1" class="data row37 col1" >ENGR497</td>
      <td id="T_5fac7_row37_col2" class="data row37 col2" >L25</td>
      <td id="T_5fac7_row37_col3" class="data row37 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5fac7_row37_col4" class="data row37 col4" >VIP</td>
      <td id="T_5fac7_row37_col5" class="data row37 col5" >3</td>
      <td id="T_5fac7_row37_col6" class="data row37 col6" >3</td>
    </tr>
    <tr>
      <td id="T_5fac7_row38_col0" class="data row38 col0" >Spring 2024</td>
      <td id="T_5fac7_row38_col1" class="data row38 col1" >EGMN403</td>
      <td id="T_5fac7_row38_col2" class="data row38 col2" >L27</td>
      <td id="T_5fac7_row38_col3" class="data row38 col3" >SENIOR DESIGN STUDIO(LAB/PROJ)</td>
      <td id="T_5fac7_row38_col4" class="data row38 col4" >CAP</td>
      <td id="T_5fac7_row38_col5" class="data row38 col5" >2</td>
      <td id="T_5fac7_row38_col6" class="data row38 col6" >4</td>
    </tr>
    <tr>
      <td id="T_5fac7_row39_col0" class="data row39 col0" >Spring 2024</td>
      <td id="T_5fac7_row39_col1" class="data row39 col1" >EGMN606</td>
      <td id="T_5fac7_row39_col2" class="data row39 col2" >901</td>
      <td id="T_5fac7_row39_col3" class="data row39 col3" >MECH & NUC ENGINEER CONTINUUM</td>
      <td id="T_5fac7_row39_col4" class="data row39 col4" >LEC</td>
      <td id="T_5fac7_row39_col5" class="data row39 col5" >16</td>
      <td id="T_5fac7_row39_col6" class="data row39 col6" >48</td>
    </tr>
    <tr>
      <td id="T_5fac7_row40_col0" class="data row40 col0" >Spring 2024</td>
      <td id="T_5fac7_row40_col1" class="data row40 col1" >EGMN606</td>
      <td id="T_5fac7_row40_col2" class="data row40 col2" >C90</td>
      <td id="T_5fac7_row40_col3" class="data row40 col3" >MECH & NUC ENGINEER CONTINUUM</td>
      <td id="T_5fac7_row40_col4" class="data row40 col4" >LEC</td>
      <td id="T_5fac7_row40_col5" class="data row40 col5" >38</td>
      <td id="T_5fac7_row40_col6" class="data row40 col6" >114</td>
    </tr>
    <tr>
      <td id="T_5fac7_row41_col0" class="data row41 col0" >Spring 2024</td>
      <td id="T_5fac7_row41_col1" class="data row41 col1" >EGMN697</td>
      <td id="T_5fac7_row41_col2" class="data row41 col2" >003</td>
      <td id="T_5fac7_row41_col3" class="data row41 col3" >DIRECTED RESEARCH</td>
      <td id="T_5fac7_row41_col4" class="data row41 col4" >RES</td>
      <td id="T_5fac7_row41_col5" class="data row41 col5" >1</td>
      <td id="T_5fac7_row41_col6" class="data row41 col6" >6</td>
    </tr>
    <tr>
      <td id="T_5fac7_row42_col0" class="data row42 col0" >Spring 2024</td>
      <td id="T_5fac7_row42_col1" class="data row42 col1" >EGMN697</td>
      <td id="T_5fac7_row42_col2" class="data row42 col2" >146</td>
      <td id="T_5fac7_row42_col3" class="data row42 col3" >DIRECTED RESEARCH</td>
      <td id="T_5fac7_row42_col4" class="data row42 col4" >RES</td>
      <td id="T_5fac7_row42_col5" class="data row42 col5" >2</td>
      <td id="T_5fac7_row42_col6" class="data row42 col6" >6</td>
    </tr>
    <tr>
      <td id="T_5fac7_row43_col0" class="data row43 col0" >Spring 2024</td>
      <td id="T_5fac7_row43_col1" class="data row43 col1" >ENGR497</td>
      <td id="T_5fac7_row43_col2" class="data row43 col2" >L31</td>
      <td id="T_5fac7_row43_col3" class="data row43 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5fac7_row43_col4" class="data row43 col4" >VIP</td>
      <td id="T_5fac7_row43_col5" class="data row43 col5" >1</td>
      <td id="T_5fac7_row43_col6" class="data row43 col6" >1</td>
    </tr>
    <tr>
      <td id="T_5fac7_row44_col0" class="data row44 col0" >Spring 2024</td>
      <td id="T_5fac7_row44_col1" class="data row44 col1" >ENGR497</td>
      <td id="T_5fac7_row44_col2" class="data row44 col2" >L69</td>
      <td id="T_5fac7_row44_col3" class="data row44 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5fac7_row44_col4" class="data row44 col4" >VIP</td>
      <td id="T_5fac7_row44_col5" class="data row44 col5" >0</td>
      <td id="T_5fac7_row44_col6" class="data row44 col6" >0</td>
    </tr>
    <tr>
      <td id="T_5fac7_row45_col0" class="data row45 col0" >Spring 2024</td>
      <td id="T_5fac7_row45_col1" class="data row45 col1" >ENGR497</td>
      <td id="T_5fac7_row45_col2" class="data row45 col2" >L70</td>
      <td id="T_5fac7_row45_col3" class="data row45 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5fac7_row45_col4" class="data row45 col4" >VIP</td>
      <td id="T_5fac7_row45_col5" class="data row45 col5" >0</td>
      <td id="T_5fac7_row45_col6" class="data row45 col6" >1</td>
    </tr>
    <tr>
      <td id="T_5fac7_row46_col0" class="data row46 col0" >Fall 2024</td>
      <td id="T_5fac7_row46_col1" class="data row46 col1" >CMSC441</td>
      <td id="T_5fac7_row46_col2" class="data row46 col2" >901</td>
      <td id="T_5fac7_row46_col3" class="data row46 col3" >SR DESIGN STUDIO I (LAB/PROJ)</td>
      <td id="T_5fac7_row46_col4" class="data row46 col4" >CAP</td>
      <td id="T_5fac7_row46_col5" class="data row46 col5" >3</td>
      <td id="T_5fac7_row46_col6" class="data row46 col6" >6</td>
    </tr>
    <tr>
      <td id="T_5fac7_row47_col0" class="data row47 col0" >Fall 2024</td>
      <td id="T_5fac7_row47_col1" class="data row47 col1" >CMSC451</td>
      <td id="T_5fac7_row47_col2" class="data row47 col2" >901</td>
      <td id="T_5fac7_row47_col3" class="data row47 col3" >SENIOR PROJECT I</td>
      <td id="T_5fac7_row47_col4" class="data row47 col4" >LEC</td>
      <td id="T_5fac7_row47_col5" class="data row47 col5" >201</td>
      <td id="T_5fac7_row47_col6" class="data row47 col6" >201</td>
    </tr>
    <tr>
      <td id="T_5fac7_row48_col0" class="data row48 col0" >Fall 2024</td>
      <td id="T_5fac7_row48_col1" class="data row48 col1" >EGMN402</td>
      <td id="T_5fac7_row48_col2" class="data row48 col2" >L24</td>
      <td id="T_5fac7_row48_col3" class="data row48 col3" >SENIOR DESIGN STUDIO(LAB/PROJ)</td>
      <td id="T_5fac7_row48_col4" class="data row48 col4" >CAP</td>
      <td id="T_5fac7_row48_col5" class="data row48 col5" >2</td>
      <td id="T_5fac7_row48_col6" class="data row48 col6" >4</td>
    </tr>
    <tr>
      <td id="T_5fac7_row49_col0" class="data row49 col0" >Fall 2024</td>
      <td id="T_5fac7_row49_col1" class="data row49 col1" >EGMN421</td>
      <td id="T_5fac7_row49_col2" class="data row49 col2" >001</td>
      <td id="T_5fac7_row49_col3" class="data row49 col3" >CAE ANALYSIS</td>
      <td id="T_5fac7_row49_col4" class="data row49 col4" >LAB</td>
      <td id="T_5fac7_row49_col5" class="data row49 col5" >39</td>
      <td id="T_5fac7_row49_col6" class="data row49 col6" >58</td>
    </tr>
    <tr>
      <td id="T_5fac7_row50_col0" class="data row50 col0" >Fall 2024</td>
      <td id="T_5fac7_row50_col1" class="data row50 col1" >EGMN421</td>
      <td id="T_5fac7_row50_col2" class="data row50 col2" >001</td>
      <td id="T_5fac7_row50_col3" class="data row50 col3" >CAE ANALYSIS</td>
      <td id="T_5fac7_row50_col4" class="data row50 col4" >LEC</td>
      <td id="T_5fac7_row50_col5" class="data row50 col5" >39</td>
      <td id="T_5fac7_row50_col6" class="data row50 col6" >58</td>
    </tr>
    <tr>
      <td id="T_5fac7_row51_col0" class="data row51 col0" >Fall 2024</td>
      <td id="T_5fac7_row51_col1" class="data row51 col1" >EGMN421</td>
      <td id="T_5fac7_row51_col2" class="data row51 col2" >002</td>
      <td id="T_5fac7_row51_col3" class="data row51 col3" >CAE ANALYSIS</td>
      <td id="T_5fac7_row51_col4" class="data row51 col4" >LAB</td>
      <td id="T_5fac7_row51_col5" class="data row51 col5" >37</td>
      <td id="T_5fac7_row51_col6" class="data row51 col6" >56</td>
    </tr>
    <tr>
      <td id="T_5fac7_row52_col0" class="data row52 col0" >Fall 2024</td>
      <td id="T_5fac7_row52_col1" class="data row52 col1" >EGMN421</td>
      <td id="T_5fac7_row52_col2" class="data row52 col2" >002</td>
      <td id="T_5fac7_row52_col3" class="data row52 col3" >CAE ANALYSIS</td>
      <td id="T_5fac7_row52_col4" class="data row52 col4" >LEC</td>
      <td id="T_5fac7_row52_col5" class="data row52 col5" >37</td>
      <td id="T_5fac7_row52_col6" class="data row52 col6" >56</td>
    </tr>
    <tr>
      <td id="T_5fac7_row53_col0" class="data row53 col0" >Fall 2024</td>
      <td id="T_5fac7_row53_col1" class="data row53 col1" >EGMN606</td>
      <td id="T_5fac7_row53_col2" class="data row53 col2" >C90</td>
      <td id="T_5fac7_row53_col3" class="data row53 col3" >MECH & NUC ENGINEER CONTINUUM</td>
      <td id="T_5fac7_row53_col4" class="data row53 col4" >LEC</td>
      <td id="T_5fac7_row53_col5" class="data row53 col5" >16</td>
      <td id="T_5fac7_row53_col6" class="data row53 col6" >48</td>
    </tr>
  </tbody>
</table>


