---
title: Teaching activity for Forkins,Robert
date: last-modified
---

Below is a listing of teaching over time for department EGRC


## Robert Forkins

<style type="text/css">
#T_b45f1 table {
  width: 100%;
  border-collapse: collapse;
}
#T_b45f1 th {
  text-align: center;
  padding: 8px;
}
#T_b45f1 td:nth-child(1) {
  padding-right: 10px;
  text-align: left;
}
#T_b45f1 td:nth-child(2) {
  padding-right: 5px;
  text-align: left;
}
#T_b45f1  td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_b45f1 td:nth-child(3) {
  text-align: center;
}
#T_b45f1  td:nth-child(5) {
  text-align: center;
}
#T_b45f1 td:nth-child(6) {
  text-align: right;
}
#T_b45f1  td:nth-child(7) {
  text-align: right;
}
#T_b45f1_row0_col0, #T_b45f1_row0_col1, #T_b45f1_row0_col2, #T_b45f1_row0_col3, #T_b45f1_row0_col4, #T_b45f1_row0_col5, #T_b45f1_row0_col6, #T_b45f1_row1_col0, #T_b45f1_row1_col1, #T_b45f1_row1_col2, #T_b45f1_row1_col3, #T_b45f1_row1_col4, #T_b45f1_row1_col5, #T_b45f1_row1_col6, #T_b45f1_row2_col0, #T_b45f1_row2_col1, #T_b45f1_row2_col2, #T_b45f1_row2_col3, #T_b45f1_row2_col4, #T_b45f1_row2_col5, #T_b45f1_row2_col6, #T_b45f1_row3_col0, #T_b45f1_row3_col1, #T_b45f1_row3_col2, #T_b45f1_row3_col3, #T_b45f1_row3_col4, #T_b45f1_row3_col5, #T_b45f1_row3_col6, #T_b45f1_row4_col0, #T_b45f1_row4_col1, #T_b45f1_row4_col2, #T_b45f1_row4_col3, #T_b45f1_row4_col4, #T_b45f1_row4_col5, #T_b45f1_row4_col6 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_b45f1_row5_col0, #T_b45f1_row5_col1, #T_b45f1_row5_col2, #T_b45f1_row5_col3, #T_b45f1_row5_col4, #T_b45f1_row5_col5, #T_b45f1_row5_col6 {
  background-color: #f0f0f0;
  border-bottom: 1px solid #ccc;
}
#T_b45f1_row6_col0, #T_b45f1_row6_col1, #T_b45f1_row6_col2, #T_b45f1_row6_col3, #T_b45f1_row6_col4, #T_b45f1_row6_col5, #T_b45f1_row6_col6, #T_b45f1_row7_col0, #T_b45f1_row7_col1, #T_b45f1_row7_col2, #T_b45f1_row7_col3, #T_b45f1_row7_col4, #T_b45f1_row7_col5, #T_b45f1_row7_col6, #T_b45f1_row8_col0, #T_b45f1_row8_col1, #T_b45f1_row8_col2, #T_b45f1_row8_col3, #T_b45f1_row8_col4, #T_b45f1_row8_col5, #T_b45f1_row8_col6 {
  background-color: #ffffff;
  border-bottom: none;
}
#T_b45f1_row9_col0, #T_b45f1_row9_col1, #T_b45f1_row9_col2, #T_b45f1_row9_col3, #T_b45f1_row9_col4, #T_b45f1_row9_col5, #T_b45f1_row9_col6 {
  background-color: #ffffff;
  border-bottom: 1px solid #ccc;
}
</style>
<table id="T_b45f1">
  <thead>
    <tr>
      <th id="T_b45f1_level0_col0" class="col_heading level0 col0" >Term</th>
      <th id="T_b45f1_level0_col1" class="col_heading level0 col1" >Crse</th>
      <th id="T_b45f1_level0_col2" class="col_heading level0 col2" >Sect</th>
      <th id="T_b45f1_level0_col3" class="col_heading level0 col3" >Crse Title</th>
      <th id="T_b45f1_level0_col4" class="col_heading level0 col4" >W.Type</th>
      <th id="T_b45f1_level0_col5" class="col_heading level0 col5" >Stdnts</th>
      <th id="T_b45f1_level0_col6" class="col_heading level0 col6" >Hours</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_b45f1_row0_col0" class="data row0 col0" >Fall 2020</td>
      <td id="T_b45f1_row0_col1" class="data row0 col1" >CLSE440</td>
      <td id="T_b45f1_row0_col2" class="data row0 col2" >001</td>
      <td id="T_b45f1_row0_col3" class="data row0 col3" >UNIT OPERATIONS LABORATORY</td>
      <td id="T_b45f1_row0_col4" class="data row0 col4" >LAB</td>
      <td id="T_b45f1_row0_col5" class="data row0 col5" >19</td>
      <td id="T_b45f1_row0_col6" class="data row0 col6" >19</td>
    </tr>
    <tr>
      <td id="T_b45f1_row1_col0" class="data row1 col0" >Fall 2020</td>
      <td id="T_b45f1_row1_col1" class="data row1 col1" >CLSE440</td>
      <td id="T_b45f1_row1_col2" class="data row1 col2" >001</td>
      <td id="T_b45f1_row1_col3" class="data row1 col3" >UNIT OPERATIONS LABORATORY</td>
      <td id="T_b45f1_row1_col4" class="data row1 col4" >LAB</td>
      <td id="T_b45f1_row1_col5" class="data row1 col5" >38</td>
      <td id="T_b45f1_row1_col6" class="data row1 col6" >38</td>
    </tr>
    <tr>
      <td id="T_b45f1_row2_col0" class="data row2 col0" >Fall 2020</td>
      <td id="T_b45f1_row2_col1" class="data row2 col1" >CLSE440</td>
      <td id="T_b45f1_row2_col2" class="data row2 col2" >002</td>
      <td id="T_b45f1_row2_col3" class="data row2 col3" >UNIT OPERATIONS LABORATORY</td>
      <td id="T_b45f1_row2_col4" class="data row2 col4" >LAB</td>
      <td id="T_b45f1_row2_col5" class="data row2 col5" >14</td>
      <td id="T_b45f1_row2_col6" class="data row2 col6" >14</td>
    </tr>
    <tr>
      <td id="T_b45f1_row3_col0" class="data row3 col0" >Fall 2020</td>
      <td id="T_b45f1_row3_col1" class="data row3 col1" >CLSE440</td>
      <td id="T_b45f1_row3_col2" class="data row3 col2" >002</td>
      <td id="T_b45f1_row3_col3" class="data row3 col3" >UNIT OPERATIONS LABORATORY</td>
      <td id="T_b45f1_row3_col4" class="data row3 col4" >LAB</td>
      <td id="T_b45f1_row3_col5" class="data row3 col5" >28</td>
      <td id="T_b45f1_row3_col6" class="data row3 col6" >28</td>
    </tr>
    <tr>
      <td id="T_b45f1_row4_col0" class="data row4 col0" >Fall 2020</td>
      <td id="T_b45f1_row4_col1" class="data row4 col1" >CLSE440</td>
      <td id="T_b45f1_row4_col2" class="data row4 col2" >L01</td>
      <td id="T_b45f1_row4_col3" class="data row4 col3" >UNIT OPERATIONS LABORATORY</td>
      <td id="T_b45f1_row4_col4" class="data row4 col4" >LAB</td>
      <td id="T_b45f1_row4_col5" class="data row4 col5" >15</td>
      <td id="T_b45f1_row4_col6" class="data row4 col6" >15</td>
    </tr>
    <tr>
      <td id="T_b45f1_row5_col0" class="data row5 col0" >Fall 2020</td>
      <td id="T_b45f1_row5_col1" class="data row5 col1" >CLSE440</td>
      <td id="T_b45f1_row5_col2" class="data row5 col2" >L01</td>
      <td id="T_b45f1_row5_col3" class="data row5 col3" >UNIT OPERATIONS LABORATORY</td>
      <td id="T_b45f1_row5_col4" class="data row5 col4" >LAB</td>
      <td id="T_b45f1_row5_col5" class="data row5 col5" >30</td>
      <td id="T_b45f1_row5_col6" class="data row5 col6" >30</td>
    </tr>
    <tr>
      <td id="T_b45f1_row6_col0" class="data row6 col0" >Spring 2021</td>
      <td id="T_b45f1_row6_col1" class="data row6 col1" >CLSE320</td>
      <td id="T_b45f1_row6_col2" class="data row6 col2" >L01</td>
      <td id="T_b45f1_row6_col3" class="data row6 col3" >INSTRUMENTATION LABORATORY</td>
      <td id="T_b45f1_row6_col4" class="data row6 col4" >LAB</td>
      <td id="T_b45f1_row6_col5" class="data row6 col5" >30</td>
      <td id="T_b45f1_row6_col6" class="data row6 col6" >45</td>
    </tr>
    <tr>
      <td id="T_b45f1_row7_col0" class="data row7 col0" >Spring 2021</td>
      <td id="T_b45f1_row7_col1" class="data row7 col1" >CLSE320</td>
      <td id="T_b45f1_row7_col2" class="data row7 col2" >L02</td>
      <td id="T_b45f1_row7_col3" class="data row7 col3" >INSTRUMENTATION LABORATORY</td>
      <td id="T_b45f1_row7_col4" class="data row7 col4" >LAB</td>
      <td id="T_b45f1_row7_col5" class="data row7 col5" >30</td>
      <td id="T_b45f1_row7_col6" class="data row7 col6" >45</td>
    </tr>
    <tr>
      <td id="T_b45f1_row8_col0" class="data row8 col0" >Spring 2021</td>
      <td id="T_b45f1_row8_col1" class="data row8 col1" >CLSE320</td>
      <td id="T_b45f1_row8_col2" class="data row8 col2" >L04</td>
      <td id="T_b45f1_row8_col3" class="data row8 col3" >INSTRUMENTATION LABORATORY</td>
      <td id="T_b45f1_row8_col4" class="data row8 col4" >LAB</td>
      <td id="T_b45f1_row8_col5" class="data row8 col5" >28</td>
      <td id="T_b45f1_row8_col6" class="data row8 col6" >42</td>
    </tr>
    <tr>
      <td id="T_b45f1_row9_col0" class="data row9 col0" >Spring 2021</td>
      <td id="T_b45f1_row9_col1" class="data row9 col1" >CLSE320</td>
      <td id="T_b45f1_row9_col2" class="data row9 col2" >L05</td>
      <td id="T_b45f1_row9_col3" class="data row9 col3" >INSTRUMENTATION LABORATORY</td>
      <td id="T_b45f1_row9_col4" class="data row9 col4" >LAB</td>
      <td id="T_b45f1_row9_col5" class="data row9 col5" >34</td>
      <td id="T_b45f1_row9_col6" class="data row9 col6" >51</td>
    </tr>
  </tbody>
</table>


