---
title: Teaching activity for Mancini,Michael
date: last-modified
---

Below is a listing of teaching over time for department EGRB


## Michael Mancini

<style type="text/css">
#T_09e99 table {
  width: 100%;
  border-collapse: collapse;
}
#T_09e99 th {
  text-align: center;
  padding: 8px;
}
#T_09e99 td:nth-child(1) {
  padding-right: 10px;
  text-align: left;
}
#T_09e99 td:nth-child(2) {
  padding-right: 5px;
  text-align: left;
}
#T_09e99  td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_09e99 td:nth-child(3) {
  text-align: center;
}
#T_09e99  td:nth-child(5) {
  text-align: center;
}
#T_09e99 td:nth-child(6) {
  text-align: right;
}
#T_09e99  td:nth-child(7) {
  text-align: right;
}
#T_09e99_row0_col0, #T_09e99_row0_col1, #T_09e99_row0_col2, #T_09e99_row0_col3, #T_09e99_row0_col4, #T_09e99_row0_col5, #T_09e99_row0_col6, #T_09e99_row1_col0, #T_09e99_row1_col1, #T_09e99_row1_col2, #T_09e99_row1_col3, #T_09e99_row1_col4, #T_09e99_row1_col5, #T_09e99_row1_col6 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_09e99_row2_col0, #T_09e99_row2_col1, #T_09e99_row2_col2, #T_09e99_row2_col3, #T_09e99_row2_col4, #T_09e99_row2_col5, #T_09e99_row2_col6 {
  background-color: #f0f0f0;
  border-bottom: 1px solid #ccc;
}
#T_09e99_row3_col0, #T_09e99_row3_col1, #T_09e99_row3_col2, #T_09e99_row3_col3, #T_09e99_row3_col4, #T_09e99_row3_col5, #T_09e99_row3_col6 {
  background-color: #ffffff;
  border-bottom: none;
}
#T_09e99_row4_col0, #T_09e99_row4_col1, #T_09e99_row4_col2, #T_09e99_row4_col3, #T_09e99_row4_col4, #T_09e99_row4_col5, #T_09e99_row4_col6 {
  background-color: #ffffff;
  border-bottom: 1px solid #ccc;
}
</style>
<table id="T_09e99">
  <thead>
    <tr>
      <th id="T_09e99_level0_col0" class="col_heading level0 col0" >Term</th>
      <th id="T_09e99_level0_col1" class="col_heading level0 col1" >Crse</th>
      <th id="T_09e99_level0_col2" class="col_heading level0 col2" >Sect</th>
      <th id="T_09e99_level0_col3" class="col_heading level0 col3" >Crse Title</th>
      <th id="T_09e99_level0_col4" class="col_heading level0 col4" >W.Type</th>
      <th id="T_09e99_level0_col5" class="col_heading level0 col5" >Stdnts</th>
      <th id="T_09e99_level0_col6" class="col_heading level0 col6" >Hours</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_09e99_row0_col0" class="data row0 col0" >Spring 2022</td>
      <td id="T_09e99_row0_col1" class="data row0 col1" >EGRB301</td>
      <td id="T_09e99_row0_col2" class="data row0 col2" >001</td>
      <td id="T_09e99_row0_col3" class="data row0 col3" >BIOMEDICAL ENGINEERING PRAC II</td>
      <td id="T_09e99_row0_col4" class="data row0 col4" >LEC</td>
      <td id="T_09e99_row0_col5" class="data row0 col5" >35</td>
      <td id="T_09e99_row0_col6" class="data row0 col6" >105</td>
    </tr>
    <tr>
      <td id="T_09e99_row1_col0" class="data row1 col0" >Spring 2022</td>
      <td id="T_09e99_row1_col1" class="data row1 col1" >EGRB401</td>
      <td id="T_09e99_row1_col2" class="data row1 col2" >L01</td>
      <td id="T_09e99_row1_col3" class="data row1 col3" >BIOMED ENG SENIOR STUDIO</td>
      <td id="T_09e99_row1_col4" class="data row1 col4" >CAP</td>
      <td id="T_09e99_row1_col5" class="data row1 col5" >6</td>
      <td id="T_09e99_row1_col6" class="data row1 col6" >18</td>
    </tr>
    <tr>
      <td id="T_09e99_row2_col0" class="data row2 col0" >Spring 2022</td>
      <td id="T_09e99_row2_col1" class="data row2 col1" >EGRB402</td>
      <td id="T_09e99_row2_col2" class="data row2 col2" >L04</td>
      <td id="T_09e99_row2_col3" class="data row2 col3" >BIOMED ENG SENIOR STUDIO II</td>
      <td id="T_09e99_row2_col4" class="data row2 col4" >CAP</td>
      <td id="T_09e99_row2_col5" class="data row2 col5" >51</td>
      <td id="T_09e99_row2_col6" class="data row2 col6" >153</td>
    </tr>
    <tr>
      <td id="T_09e99_row3_col0" class="data row3 col0" >Fall 2022</td>
      <td id="T_09e99_row3_col1" class="data row3 col1" >EGRB301</td>
      <td id="T_09e99_row3_col2" class="data row3 col2" >001</td>
      <td id="T_09e99_row3_col3" class="data row3 col3" >BIOMEDICAL ENGINEERING PRAC II</td>
      <td id="T_09e99_row3_col4" class="data row3 col4" >LEC</td>
      <td id="T_09e99_row3_col5" class="data row3 col5" >15</td>
      <td id="T_09e99_row3_col6" class="data row3 col6" >45</td>
    </tr>
    <tr>
      <td id="T_09e99_row4_col0" class="data row4 col0" >Fall 2022</td>
      <td id="T_09e99_row4_col1" class="data row4 col1" >ENGR497</td>
      <td id="T_09e99_row4_col2" class="data row4 col2" >L50</td>
      <td id="T_09e99_row4_col3" class="data row4 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_09e99_row4_col4" class="data row4 col4" >VIP</td>
      <td id="T_09e99_row4_col5" class="data row4 col5" >3</td>
      <td id="T_09e99_row4_col6" class="data row4 col6" >3</td>
    </tr>
  </tbody>
</table>


