---
title: Teaching activity for Thomson-McInnes,Bridget
date: last-modified
---

Below is a listing of teaching over time for department CMSC


## Bridget Thomson-McInnes

<style type="text/css">
#T_5d3e0 table {
  width: 100%;
  border-collapse: collapse;
}
#T_5d3e0 th {
  text-align: center;
  padding: 8px;
}
#T_5d3e0 td:nth-child(1) {
  padding-right: 10px;
  text-align: left;
}
#T_5d3e0 td:nth-child(2) {
  padding-right: 5px;
  text-align: left;
}
#T_5d3e0  td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_5d3e0 td:nth-child(3) {
  text-align: center;
}
#T_5d3e0  td:nth-child(5) {
  text-align: center;
}
#T_5d3e0 td:nth-child(6) {
  text-align: right;
}
#T_5d3e0  td:nth-child(7) {
  text-align: right;
}
#T_5d3e0_row0_col0, #T_5d3e0_row0_col1, #T_5d3e0_row0_col2, #T_5d3e0_row0_col3, #T_5d3e0_row0_col4, #T_5d3e0_row0_col5, #T_5d3e0_row0_col6, #T_5d3e0_row1_col0, #T_5d3e0_row1_col1, #T_5d3e0_row1_col2, #T_5d3e0_row1_col3, #T_5d3e0_row1_col4, #T_5d3e0_row1_col5, #T_5d3e0_row1_col6, #T_5d3e0_row2_col0, #T_5d3e0_row2_col1, #T_5d3e0_row2_col2, #T_5d3e0_row2_col3, #T_5d3e0_row2_col4, #T_5d3e0_row2_col5, #T_5d3e0_row2_col6, #T_5d3e0_row3_col0, #T_5d3e0_row3_col1, #T_5d3e0_row3_col2, #T_5d3e0_row3_col3, #T_5d3e0_row3_col4, #T_5d3e0_row3_col5, #T_5d3e0_row3_col6, #T_5d3e0_row4_col0, #T_5d3e0_row4_col1, #T_5d3e0_row4_col2, #T_5d3e0_row4_col3, #T_5d3e0_row4_col4, #T_5d3e0_row4_col5, #T_5d3e0_row4_col6, #T_5d3e0_row13_col0, #T_5d3e0_row13_col1, #T_5d3e0_row13_col2, #T_5d3e0_row13_col3, #T_5d3e0_row13_col4, #T_5d3e0_row13_col5, #T_5d3e0_row13_col6, #T_5d3e0_row22_col0, #T_5d3e0_row22_col1, #T_5d3e0_row22_col2, #T_5d3e0_row22_col3, #T_5d3e0_row22_col4, #T_5d3e0_row22_col5, #T_5d3e0_row22_col6, #T_5d3e0_row23_col0, #T_5d3e0_row23_col1, #T_5d3e0_row23_col2, #T_5d3e0_row23_col3, #T_5d3e0_row23_col4, #T_5d3e0_row23_col5, #T_5d3e0_row23_col6, #T_5d3e0_row24_col0, #T_5d3e0_row24_col1, #T_5d3e0_row24_col2, #T_5d3e0_row24_col3, #T_5d3e0_row24_col4, #T_5d3e0_row24_col5, #T_5d3e0_row24_col6, #T_5d3e0_row25_col0, #T_5d3e0_row25_col1, #T_5d3e0_row25_col2, #T_5d3e0_row25_col3, #T_5d3e0_row25_col4, #T_5d3e0_row25_col5, #T_5d3e0_row25_col6, #T_5d3e0_row26_col0, #T_5d3e0_row26_col1, #T_5d3e0_row26_col2, #T_5d3e0_row26_col3, #T_5d3e0_row26_col4, #T_5d3e0_row26_col5, #T_5d3e0_row26_col6, #T_5d3e0_row27_col0, #T_5d3e0_row27_col1, #T_5d3e0_row27_col2, #T_5d3e0_row27_col3, #T_5d3e0_row27_col4, #T_5d3e0_row27_col5, #T_5d3e0_row27_col6, #T_5d3e0_row28_col0, #T_5d3e0_row28_col1, #T_5d3e0_row28_col2, #T_5d3e0_row28_col3, #T_5d3e0_row28_col4, #T_5d3e0_row28_col5, #T_5d3e0_row28_col6, #T_5d3e0_row29_col0, #T_5d3e0_row29_col1, #T_5d3e0_row29_col2, #T_5d3e0_row29_col3, #T_5d3e0_row29_col4, #T_5d3e0_row29_col5, #T_5d3e0_row29_col6, #T_5d3e0_row32_col0, #T_5d3e0_row32_col1, #T_5d3e0_row32_col2, #T_5d3e0_row32_col3, #T_5d3e0_row32_col4, #T_5d3e0_row32_col5, #T_5d3e0_row32_col6, #T_5d3e0_row33_col0, #T_5d3e0_row33_col1, #T_5d3e0_row33_col2, #T_5d3e0_row33_col3, #T_5d3e0_row33_col4, #T_5d3e0_row33_col5, #T_5d3e0_row33_col6, #T_5d3e0_row34_col0, #T_5d3e0_row34_col1, #T_5d3e0_row34_col2, #T_5d3e0_row34_col3, #T_5d3e0_row34_col4, #T_5d3e0_row34_col5, #T_5d3e0_row34_col6, #T_5d3e0_row35_col0, #T_5d3e0_row35_col1, #T_5d3e0_row35_col2, #T_5d3e0_row35_col3, #T_5d3e0_row35_col4, #T_5d3e0_row35_col5, #T_5d3e0_row35_col6, #T_5d3e0_row36_col0, #T_5d3e0_row36_col1, #T_5d3e0_row36_col2, #T_5d3e0_row36_col3, #T_5d3e0_row36_col4, #T_5d3e0_row36_col5, #T_5d3e0_row36_col6, #T_5d3e0_row37_col0, #T_5d3e0_row37_col1, #T_5d3e0_row37_col2, #T_5d3e0_row37_col3, #T_5d3e0_row37_col4, #T_5d3e0_row37_col5, #T_5d3e0_row37_col6, #T_5d3e0_row38_col0, #T_5d3e0_row38_col1, #T_5d3e0_row38_col2, #T_5d3e0_row38_col3, #T_5d3e0_row38_col4, #T_5d3e0_row38_col5, #T_5d3e0_row38_col6, #T_5d3e0_row39_col0, #T_5d3e0_row39_col1, #T_5d3e0_row39_col2, #T_5d3e0_row39_col3, #T_5d3e0_row39_col4, #T_5d3e0_row39_col5, #T_5d3e0_row39_col6, #T_5d3e0_row49_col0, #T_5d3e0_row49_col1, #T_5d3e0_row49_col2, #T_5d3e0_row49_col3, #T_5d3e0_row49_col4, #T_5d3e0_row49_col5, #T_5d3e0_row49_col6, #T_5d3e0_row60_col0, #T_5d3e0_row60_col1, #T_5d3e0_row60_col2, #T_5d3e0_row60_col3, #T_5d3e0_row60_col4, #T_5d3e0_row60_col5, #T_5d3e0_row60_col6, #T_5d3e0_row61_col0, #T_5d3e0_row61_col1, #T_5d3e0_row61_col2, #T_5d3e0_row61_col3, #T_5d3e0_row61_col4, #T_5d3e0_row61_col5, #T_5d3e0_row61_col6, #T_5d3e0_row62_col0, #T_5d3e0_row62_col1, #T_5d3e0_row62_col2, #T_5d3e0_row62_col3, #T_5d3e0_row62_col4, #T_5d3e0_row62_col5, #T_5d3e0_row62_col6, #T_5d3e0_row63_col0, #T_5d3e0_row63_col1, #T_5d3e0_row63_col2, #T_5d3e0_row63_col3, #T_5d3e0_row63_col4, #T_5d3e0_row63_col5, #T_5d3e0_row63_col6, #T_5d3e0_row64_col0, #T_5d3e0_row64_col1, #T_5d3e0_row64_col2, #T_5d3e0_row64_col3, #T_5d3e0_row64_col4, #T_5d3e0_row64_col5, #T_5d3e0_row64_col6, #T_5d3e0_row65_col0, #T_5d3e0_row65_col1, #T_5d3e0_row65_col2, #T_5d3e0_row65_col3, #T_5d3e0_row65_col4, #T_5d3e0_row65_col5, #T_5d3e0_row65_col6, #T_5d3e0_row66_col0, #T_5d3e0_row66_col1, #T_5d3e0_row66_col2, #T_5d3e0_row66_col3, #T_5d3e0_row66_col4, #T_5d3e0_row66_col5, #T_5d3e0_row66_col6, #T_5d3e0_row67_col0, #T_5d3e0_row67_col1, #T_5d3e0_row67_col2, #T_5d3e0_row67_col3, #T_5d3e0_row67_col4, #T_5d3e0_row67_col5, #T_5d3e0_row67_col6, #T_5d3e0_row68_col0, #T_5d3e0_row68_col1, #T_5d3e0_row68_col2, #T_5d3e0_row68_col3, #T_5d3e0_row68_col4, #T_5d3e0_row68_col5, #T_5d3e0_row68_col6, #T_5d3e0_row69_col0, #T_5d3e0_row69_col1, #T_5d3e0_row69_col2, #T_5d3e0_row69_col3, #T_5d3e0_row69_col4, #T_5d3e0_row69_col5, #T_5d3e0_row69_col6, #T_5d3e0_row74_col0, #T_5d3e0_row74_col1, #T_5d3e0_row74_col2, #T_5d3e0_row74_col3, #T_5d3e0_row74_col4, #T_5d3e0_row74_col5, #T_5d3e0_row74_col6, #T_5d3e0_row75_col0, #T_5d3e0_row75_col1, #T_5d3e0_row75_col2, #T_5d3e0_row75_col3, #T_5d3e0_row75_col4, #T_5d3e0_row75_col5, #T_5d3e0_row75_col6, #T_5d3e0_row76_col0, #T_5d3e0_row76_col1, #T_5d3e0_row76_col2, #T_5d3e0_row76_col3, #T_5d3e0_row76_col4, #T_5d3e0_row76_col5, #T_5d3e0_row76_col6, #T_5d3e0_row77_col0, #T_5d3e0_row77_col1, #T_5d3e0_row77_col2, #T_5d3e0_row77_col3, #T_5d3e0_row77_col4, #T_5d3e0_row77_col5, #T_5d3e0_row77_col6, #T_5d3e0_row78_col0, #T_5d3e0_row78_col1, #T_5d3e0_row78_col2, #T_5d3e0_row78_col3, #T_5d3e0_row78_col4, #T_5d3e0_row78_col5, #T_5d3e0_row78_col6, #T_5d3e0_row79_col0, #T_5d3e0_row79_col1, #T_5d3e0_row79_col2, #T_5d3e0_row79_col3, #T_5d3e0_row79_col4, #T_5d3e0_row79_col5, #T_5d3e0_row79_col6, #T_5d3e0_row80_col0, #T_5d3e0_row80_col1, #T_5d3e0_row80_col2, #T_5d3e0_row80_col3, #T_5d3e0_row80_col4, #T_5d3e0_row80_col5, #T_5d3e0_row80_col6, #T_5d3e0_row81_col0, #T_5d3e0_row81_col1, #T_5d3e0_row81_col2, #T_5d3e0_row81_col3, #T_5d3e0_row81_col4, #T_5d3e0_row81_col5, #T_5d3e0_row81_col6, #T_5d3e0_row82_col0, #T_5d3e0_row82_col1, #T_5d3e0_row82_col2, #T_5d3e0_row82_col3, #T_5d3e0_row82_col4, #T_5d3e0_row82_col5, #T_5d3e0_row82_col6 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_5d3e0_row5_col0, #T_5d3e0_row5_col1, #T_5d3e0_row5_col2, #T_5d3e0_row5_col3, #T_5d3e0_row5_col4, #T_5d3e0_row5_col5, #T_5d3e0_row5_col6, #T_5d3e0_row14_col0, #T_5d3e0_row14_col1, #T_5d3e0_row14_col2, #T_5d3e0_row14_col3, #T_5d3e0_row14_col4, #T_5d3e0_row14_col5, #T_5d3e0_row14_col6, #T_5d3e0_row30_col0, #T_5d3e0_row30_col1, #T_5d3e0_row30_col2, #T_5d3e0_row30_col3, #T_5d3e0_row30_col4, #T_5d3e0_row30_col5, #T_5d3e0_row30_col6, #T_5d3e0_row40_col0, #T_5d3e0_row40_col1, #T_5d3e0_row40_col2, #T_5d3e0_row40_col3, #T_5d3e0_row40_col4, #T_5d3e0_row40_col5, #T_5d3e0_row40_col6, #T_5d3e0_row50_col0, #T_5d3e0_row50_col1, #T_5d3e0_row50_col2, #T_5d3e0_row50_col3, #T_5d3e0_row50_col4, #T_5d3e0_row50_col5, #T_5d3e0_row50_col6, #T_5d3e0_row70_col0, #T_5d3e0_row70_col1, #T_5d3e0_row70_col2, #T_5d3e0_row70_col3, #T_5d3e0_row70_col4, #T_5d3e0_row70_col5, #T_5d3e0_row70_col6, #T_5d3e0_row83_col0, #T_5d3e0_row83_col1, #T_5d3e0_row83_col2, #T_5d3e0_row83_col3, #T_5d3e0_row83_col4, #T_5d3e0_row83_col5, #T_5d3e0_row83_col6 {
  background-color: #f0f0f0;
  border-bottom: 1px solid #ccc;
}
#T_5d3e0_row6_col0, #T_5d3e0_row6_col1, #T_5d3e0_row6_col2, #T_5d3e0_row6_col3, #T_5d3e0_row6_col4, #T_5d3e0_row6_col5, #T_5d3e0_row6_col6, #T_5d3e0_row7_col0, #T_5d3e0_row7_col1, #T_5d3e0_row7_col2, #T_5d3e0_row7_col3, #T_5d3e0_row7_col4, #T_5d3e0_row7_col5, #T_5d3e0_row7_col6, #T_5d3e0_row8_col0, #T_5d3e0_row8_col1, #T_5d3e0_row8_col2, #T_5d3e0_row8_col3, #T_5d3e0_row8_col4, #T_5d3e0_row8_col5, #T_5d3e0_row8_col6, #T_5d3e0_row9_col0, #T_5d3e0_row9_col1, #T_5d3e0_row9_col2, #T_5d3e0_row9_col3, #T_5d3e0_row9_col4, #T_5d3e0_row9_col5, #T_5d3e0_row9_col6, #T_5d3e0_row10_col0, #T_5d3e0_row10_col1, #T_5d3e0_row10_col2, #T_5d3e0_row10_col3, #T_5d3e0_row10_col4, #T_5d3e0_row10_col5, #T_5d3e0_row10_col6, #T_5d3e0_row11_col0, #T_5d3e0_row11_col1, #T_5d3e0_row11_col2, #T_5d3e0_row11_col3, #T_5d3e0_row11_col4, #T_5d3e0_row11_col5, #T_5d3e0_row11_col6, #T_5d3e0_row15_col0, #T_5d3e0_row15_col1, #T_5d3e0_row15_col2, #T_5d3e0_row15_col3, #T_5d3e0_row15_col4, #T_5d3e0_row15_col5, #T_5d3e0_row15_col6, #T_5d3e0_row16_col0, #T_5d3e0_row16_col1, #T_5d3e0_row16_col2, #T_5d3e0_row16_col3, #T_5d3e0_row16_col4, #T_5d3e0_row16_col5, #T_5d3e0_row16_col6, #T_5d3e0_row17_col0, #T_5d3e0_row17_col1, #T_5d3e0_row17_col2, #T_5d3e0_row17_col3, #T_5d3e0_row17_col4, #T_5d3e0_row17_col5, #T_5d3e0_row17_col6, #T_5d3e0_row18_col0, #T_5d3e0_row18_col1, #T_5d3e0_row18_col2, #T_5d3e0_row18_col3, #T_5d3e0_row18_col4, #T_5d3e0_row18_col5, #T_5d3e0_row18_col6, #T_5d3e0_row19_col0, #T_5d3e0_row19_col1, #T_5d3e0_row19_col2, #T_5d3e0_row19_col3, #T_5d3e0_row19_col4, #T_5d3e0_row19_col5, #T_5d3e0_row19_col6, #T_5d3e0_row20_col0, #T_5d3e0_row20_col1, #T_5d3e0_row20_col2, #T_5d3e0_row20_col3, #T_5d3e0_row20_col4, #T_5d3e0_row20_col5, #T_5d3e0_row20_col6, #T_5d3e0_row41_col0, #T_5d3e0_row41_col1, #T_5d3e0_row41_col2, #T_5d3e0_row41_col3, #T_5d3e0_row41_col4, #T_5d3e0_row41_col5, #T_5d3e0_row41_col6, #T_5d3e0_row42_col0, #T_5d3e0_row42_col1, #T_5d3e0_row42_col2, #T_5d3e0_row42_col3, #T_5d3e0_row42_col4, #T_5d3e0_row42_col5, #T_5d3e0_row42_col6, #T_5d3e0_row43_col0, #T_5d3e0_row43_col1, #T_5d3e0_row43_col2, #T_5d3e0_row43_col3, #T_5d3e0_row43_col4, #T_5d3e0_row43_col5, #T_5d3e0_row43_col6, #T_5d3e0_row44_col0, #T_5d3e0_row44_col1, #T_5d3e0_row44_col2, #T_5d3e0_row44_col3, #T_5d3e0_row44_col4, #T_5d3e0_row44_col5, #T_5d3e0_row44_col6, #T_5d3e0_row45_col0, #T_5d3e0_row45_col1, #T_5d3e0_row45_col2, #T_5d3e0_row45_col3, #T_5d3e0_row45_col4, #T_5d3e0_row45_col5, #T_5d3e0_row45_col6, #T_5d3e0_row46_col0, #T_5d3e0_row46_col1, #T_5d3e0_row46_col2, #T_5d3e0_row46_col3, #T_5d3e0_row46_col4, #T_5d3e0_row46_col5, #T_5d3e0_row46_col6, #T_5d3e0_row47_col0, #T_5d3e0_row47_col1, #T_5d3e0_row47_col2, #T_5d3e0_row47_col3, #T_5d3e0_row47_col4, #T_5d3e0_row47_col5, #T_5d3e0_row47_col6, #T_5d3e0_row51_col0, #T_5d3e0_row51_col1, #T_5d3e0_row51_col2, #T_5d3e0_row51_col3, #T_5d3e0_row51_col4, #T_5d3e0_row51_col5, #T_5d3e0_row51_col6, #T_5d3e0_row52_col0, #T_5d3e0_row52_col1, #T_5d3e0_row52_col2, #T_5d3e0_row52_col3, #T_5d3e0_row52_col4, #T_5d3e0_row52_col5, #T_5d3e0_row52_col6, #T_5d3e0_row53_col0, #T_5d3e0_row53_col1, #T_5d3e0_row53_col2, #T_5d3e0_row53_col3, #T_5d3e0_row53_col4, #T_5d3e0_row53_col5, #T_5d3e0_row53_col6, #T_5d3e0_row54_col0, #T_5d3e0_row54_col1, #T_5d3e0_row54_col2, #T_5d3e0_row54_col3, #T_5d3e0_row54_col4, #T_5d3e0_row54_col5, #T_5d3e0_row54_col6, #T_5d3e0_row55_col0, #T_5d3e0_row55_col1, #T_5d3e0_row55_col2, #T_5d3e0_row55_col3, #T_5d3e0_row55_col4, #T_5d3e0_row55_col5, #T_5d3e0_row55_col6, #T_5d3e0_row56_col0, #T_5d3e0_row56_col1, #T_5d3e0_row56_col2, #T_5d3e0_row56_col3, #T_5d3e0_row56_col4, #T_5d3e0_row56_col5, #T_5d3e0_row56_col6, #T_5d3e0_row57_col0, #T_5d3e0_row57_col1, #T_5d3e0_row57_col2, #T_5d3e0_row57_col3, #T_5d3e0_row57_col4, #T_5d3e0_row57_col5, #T_5d3e0_row57_col6, #T_5d3e0_row58_col0, #T_5d3e0_row58_col1, #T_5d3e0_row58_col2, #T_5d3e0_row58_col3, #T_5d3e0_row58_col4, #T_5d3e0_row58_col5, #T_5d3e0_row58_col6, #T_5d3e0_row71_col0, #T_5d3e0_row71_col1, #T_5d3e0_row71_col2, #T_5d3e0_row71_col3, #T_5d3e0_row71_col4, #T_5d3e0_row71_col5, #T_5d3e0_row71_col6, #T_5d3e0_row72_col0, #T_5d3e0_row72_col1, #T_5d3e0_row72_col2, #T_5d3e0_row72_col3, #T_5d3e0_row72_col4, #T_5d3e0_row72_col5, #T_5d3e0_row72_col6 {
  background-color: #ffffff;
  border-bottom: none;
}
#T_5d3e0_row12_col0, #T_5d3e0_row12_col1, #T_5d3e0_row12_col2, #T_5d3e0_row12_col3, #T_5d3e0_row12_col4, #T_5d3e0_row12_col5, #T_5d3e0_row12_col6, #T_5d3e0_row21_col0, #T_5d3e0_row21_col1, #T_5d3e0_row21_col2, #T_5d3e0_row21_col3, #T_5d3e0_row21_col4, #T_5d3e0_row21_col5, #T_5d3e0_row21_col6, #T_5d3e0_row31_col0, #T_5d3e0_row31_col1, #T_5d3e0_row31_col2, #T_5d3e0_row31_col3, #T_5d3e0_row31_col4, #T_5d3e0_row31_col5, #T_5d3e0_row31_col6, #T_5d3e0_row48_col0, #T_5d3e0_row48_col1, #T_5d3e0_row48_col2, #T_5d3e0_row48_col3, #T_5d3e0_row48_col4, #T_5d3e0_row48_col5, #T_5d3e0_row48_col6, #T_5d3e0_row59_col0, #T_5d3e0_row59_col1, #T_5d3e0_row59_col2, #T_5d3e0_row59_col3, #T_5d3e0_row59_col4, #T_5d3e0_row59_col5, #T_5d3e0_row59_col6, #T_5d3e0_row73_col0, #T_5d3e0_row73_col1, #T_5d3e0_row73_col2, #T_5d3e0_row73_col3, #T_5d3e0_row73_col4, #T_5d3e0_row73_col5, #T_5d3e0_row73_col6 {
  background-color: #ffffff;
  border-bottom: 1px solid #ccc;
}
</style>
<table id="T_5d3e0">
  <thead>
    <tr>
      <th id="T_5d3e0_level0_col0" class="col_heading level0 col0" >Term</th>
      <th id="T_5d3e0_level0_col1" class="col_heading level0 col1" >Crse</th>
      <th id="T_5d3e0_level0_col2" class="col_heading level0 col2" >Sect</th>
      <th id="T_5d3e0_level0_col3" class="col_heading level0 col3" >Crse Title</th>
      <th id="T_5d3e0_level0_col4" class="col_heading level0 col4" >W.Type</th>
      <th id="T_5d3e0_level0_col5" class="col_heading level0 col5" >Stdnts</th>
      <th id="T_5d3e0_level0_col6" class="col_heading level0 col6" >Hours</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_5d3e0_row0_col0" class="data row0 col0" >Fall 2020</td>
      <td id="T_5d3e0_row0_col1" class="data row0 col1" >CMSC516</td>
      <td id="T_5d3e0_row0_col2" class="data row0 col2" >001</td>
      <td id="T_5d3e0_row0_col3" class="data row0 col3" >ADV NATURAL LANG PROCESSING</td>
      <td id="T_5d3e0_row0_col4" class="data row0 col4" >LEC</td>
      <td id="T_5d3e0_row0_col5" class="data row0 col5" >13</td>
      <td id="T_5d3e0_row0_col6" class="data row0 col6" >39</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row1_col0" class="data row1 col0" >Fall 2020</td>
      <td id="T_5d3e0_row1_col1" class="data row1 col1" >CMSC697</td>
      <td id="T_5d3e0_row1_col2" class="data row1 col2" >091</td>
      <td id="T_5d3e0_row1_col3" class="data row1 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row1_col4" class="data row1 col4" >RES</td>
      <td id="T_5d3e0_row1_col5" class="data row1 col5" >3</td>
      <td id="T_5d3e0_row1_col6" class="data row1 col6" >6</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row2_col0" class="data row2 col0" >Fall 2020</td>
      <td id="T_5d3e0_row2_col1" class="data row2 col1" >CMSC697</td>
      <td id="T_5d3e0_row2_col2" class="data row2 col2" >092</td>
      <td id="T_5d3e0_row2_col3" class="data row2 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row2_col4" class="data row2 col4" >RES</td>
      <td id="T_5d3e0_row2_col5" class="data row2 col5" >2</td>
      <td id="T_5d3e0_row2_col6" class="data row2 col6" >6</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row3_col0" class="data row3 col0" >Fall 2020</td>
      <td id="T_5d3e0_row3_col1" class="data row3 col1" >CMSC697</td>
      <td id="T_5d3e0_row3_col2" class="data row3 col2" >093</td>
      <td id="T_5d3e0_row3_col3" class="data row3 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row3_col4" class="data row3 col4" >RES</td>
      <td id="T_5d3e0_row3_col5" class="data row3 col5" >1</td>
      <td id="T_5d3e0_row3_col6" class="data row3 col6" >6</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row4_col0" class="data row4 col0" >Fall 2020</td>
      <td id="T_5d3e0_row4_col1" class="data row4 col1" >CMSC697</td>
      <td id="T_5d3e0_row4_col2" class="data row4 col2" >094</td>
      <td id="T_5d3e0_row4_col3" class="data row4 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row4_col4" class="data row4 col4" >RES</td>
      <td id="T_5d3e0_row4_col5" class="data row4 col5" >2</td>
      <td id="T_5d3e0_row4_col6" class="data row4 col6" >18</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row5_col0" class="data row5 col0" >Fall 2020</td>
      <td id="T_5d3e0_row5_col1" class="data row5 col1" >ENGR497</td>
      <td id="T_5d3e0_row5_col2" class="data row5 col2" >L11</td>
      <td id="T_5d3e0_row5_col3" class="data row5 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5d3e0_row5_col4" class="data row5 col4" >VIP</td>
      <td id="T_5d3e0_row5_col5" class="data row5 col5" >1</td>
      <td id="T_5d3e0_row5_col6" class="data row5 col6" >1</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row6_col0" class="data row6 col0" >Spring 2021</td>
      <td id="T_5d3e0_row6_col1" class="data row6 col1" >CMSC416</td>
      <td id="T_5d3e0_row6_col2" class="data row6 col2" >001</td>
      <td id="T_5d3e0_row6_col3" class="data row6 col3" >INTRO TO NATURAL LANG PROCESS</td>
      <td id="T_5d3e0_row6_col4" class="data row6 col4" >LEC</td>
      <td id="T_5d3e0_row6_col5" class="data row6 col5" >49</td>
      <td id="T_5d3e0_row6_col6" class="data row6 col6" >147</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row7_col0" class="data row7 col0" >Spring 2021</td>
      <td id="T_5d3e0_row7_col1" class="data row7 col1" >CMSC697</td>
      <td id="T_5d3e0_row7_col2" class="data row7 col2" >252</td>
      <td id="T_5d3e0_row7_col3" class="data row7 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row7_col4" class="data row7 col4" >RES</td>
      <td id="T_5d3e0_row7_col5" class="data row7 col5" >2</td>
      <td id="T_5d3e0_row7_col6" class="data row7 col6" >4</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row8_col0" class="data row8 col0" >Spring 2021</td>
      <td id="T_5d3e0_row8_col1" class="data row8 col1" >CMSC697</td>
      <td id="T_5d3e0_row8_col2" class="data row8 col2" >253</td>
      <td id="T_5d3e0_row8_col3" class="data row8 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row8_col4" class="data row8 col4" >RES</td>
      <td id="T_5d3e0_row8_col5" class="data row8 col5" >4</td>
      <td id="T_5d3e0_row8_col6" class="data row8 col6" >12</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row9_col0" class="data row9 col0" >Spring 2021</td>
      <td id="T_5d3e0_row9_col1" class="data row9 col1" >CMSC697</td>
      <td id="T_5d3e0_row9_col2" class="data row9 col2" >256</td>
      <td id="T_5d3e0_row9_col3" class="data row9 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row9_col4" class="data row9 col4" >RES</td>
      <td id="T_5d3e0_row9_col5" class="data row9 col5" >1</td>
      <td id="T_5d3e0_row9_col6" class="data row9 col6" >6</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row10_col0" class="data row10 col0" >Spring 2021</td>
      <td id="T_5d3e0_row10_col1" class="data row10 col1" >CMSC697</td>
      <td id="T_5d3e0_row10_col2" class="data row10 col2" >259</td>
      <td id="T_5d3e0_row10_col3" class="data row10 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row10_col4" class="data row10 col4" >RES</td>
      <td id="T_5d3e0_row10_col5" class="data row10 col5" >2</td>
      <td id="T_5d3e0_row10_col6" class="data row10 col6" >18</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row11_col0" class="data row11 col0" >Spring 2021</td>
      <td id="T_5d3e0_row11_col1" class="data row11 col1" >ENGR497</td>
      <td id="T_5d3e0_row11_col2" class="data row11 col2" >L12</td>
      <td id="T_5d3e0_row11_col3" class="data row11 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5d3e0_row11_col4" class="data row11 col4" >VIP</td>
      <td id="T_5d3e0_row11_col5" class="data row11 col5" >2</td>
      <td id="T_5d3e0_row11_col6" class="data row11 col6" >2</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row12_col0" class="data row12 col0" >Spring 2021</td>
      <td id="T_5d3e0_row12_col1" class="data row12 col1" >ENGR497</td>
      <td id="T_5d3e0_row12_col2" class="data row12 col2" >L13</td>
      <td id="T_5d3e0_row12_col3" class="data row12 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5d3e0_row12_col4" class="data row12 col4" >VIP</td>
      <td id="T_5d3e0_row12_col5" class="data row12 col5" >0</td>
      <td id="T_5d3e0_row12_col6" class="data row12 col6" >1</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row13_col0" class="data row13 col0" >Summer 2021</td>
      <td id="T_5d3e0_row13_col1" class="data row13 col1" >CMSC697</td>
      <td id="T_5d3e0_row13_col2" class="data row13 col2" >037</td>
      <td id="T_5d3e0_row13_col3" class="data row13 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row13_col4" class="data row13 col4" >RES</td>
      <td id="T_5d3e0_row13_col5" class="data row13 col5" >1</td>
      <td id="T_5d3e0_row13_col6" class="data row13 col6" >1</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row14_col0" class="data row14 col0" >Summer 2021</td>
      <td id="T_5d3e0_row14_col1" class="data row14 col1" >CMSC697</td>
      <td id="T_5d3e0_row14_col2" class="data row14 col2" >039</td>
      <td id="T_5d3e0_row14_col3" class="data row14 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row14_col4" class="data row14 col4" >RES</td>
      <td id="T_5d3e0_row14_col5" class="data row14 col5" >4</td>
      <td id="T_5d3e0_row14_col6" class="data row14 col6" >12</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row15_col0" class="data row15 col0" >Fall 2021</td>
      <td id="T_5d3e0_row15_col1" class="data row15 col1" >CMSC516</td>
      <td id="T_5d3e0_row15_col2" class="data row15 col2" >001</td>
      <td id="T_5d3e0_row15_col3" class="data row15 col3" >ADV NATURAL LANG PROCESSING</td>
      <td id="T_5d3e0_row15_col4" class="data row15 col4" >LEC</td>
      <td id="T_5d3e0_row15_col5" class="data row15 col5" >15</td>
      <td id="T_5d3e0_row15_col6" class="data row15 col6" >45</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row16_col0" class="data row16 col0" >Fall 2021</td>
      <td id="T_5d3e0_row16_col1" class="data row16 col1" >CMSC697</td>
      <td id="T_5d3e0_row16_col2" class="data row16 col2" >091</td>
      <td id="T_5d3e0_row16_col3" class="data row16 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row16_col4" class="data row16 col4" >RES</td>
      <td id="T_5d3e0_row16_col5" class="data row16 col5" >2</td>
      <td id="T_5d3e0_row16_col6" class="data row16 col6" >4</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row17_col0" class="data row17 col0" >Fall 2021</td>
      <td id="T_5d3e0_row17_col1" class="data row17 col1" >CMSC697</td>
      <td id="T_5d3e0_row17_col2" class="data row17 col2" >092</td>
      <td id="T_5d3e0_row17_col3" class="data row17 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row17_col4" class="data row17 col4" >RES</td>
      <td id="T_5d3e0_row17_col5" class="data row17 col5" >3</td>
      <td id="T_5d3e0_row17_col6" class="data row17 col6" >9</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row18_col0" class="data row18 col0" >Fall 2021</td>
      <td id="T_5d3e0_row18_col1" class="data row18 col1" >CMSC697</td>
      <td id="T_5d3e0_row18_col2" class="data row18 col2" >094</td>
      <td id="T_5d3e0_row18_col3" class="data row18 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row18_col4" class="data row18 col4" >RES</td>
      <td id="T_5d3e0_row18_col5" class="data row18 col5" >2</td>
      <td id="T_5d3e0_row18_col6" class="data row18 col6" >18</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row19_col0" class="data row19 col0" >Fall 2021</td>
      <td id="T_5d3e0_row19_col1" class="data row19 col1" >ENGR497</td>
      <td id="T_5d3e0_row19_col2" class="data row19 col2" >L11</td>
      <td id="T_5d3e0_row19_col3" class="data row19 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5d3e0_row19_col4" class="data row19 col4" >VIP</td>
      <td id="T_5d3e0_row19_col5" class="data row19 col5" >2</td>
      <td id="T_5d3e0_row19_col6" class="data row19 col6" >2</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row20_col0" class="data row20 col0" >Fall 2021</td>
      <td id="T_5d3e0_row20_col1" class="data row20 col1" >ENGR497</td>
      <td id="T_5d3e0_row20_col2" class="data row20 col2" >L13</td>
      <td id="T_5d3e0_row20_col3" class="data row20 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5d3e0_row20_col4" class="data row20 col4" >VIP</td>
      <td id="T_5d3e0_row20_col5" class="data row20 col5" >1</td>
      <td id="T_5d3e0_row20_col6" class="data row20 col6" >2</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row21_col0" class="data row21 col0" >Fall 2021</td>
      <td id="T_5d3e0_row21_col1" class="data row21 col1" >ENGR701</td>
      <td id="T_5d3e0_row21_col2" class="data row21 col2" >017</td>
      <td id="T_5d3e0_row21_col3" class="data row21 col3" >POST-CANDIDACY DOCT RESEARCH</td>
      <td id="T_5d3e0_row21_col4" class="data row21 col4" >RES</td>
      <td id="T_5d3e0_row21_col5" class="data row21 col5" >1</td>
      <td id="T_5d3e0_row21_col6" class="data row21 col6" >9</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row22_col0" class="data row22 col0" >Spring 2022</td>
      <td id="T_5d3e0_row22_col1" class="data row22 col1" >CMSC416</td>
      <td id="T_5d3e0_row22_col2" class="data row22 col2" >001</td>
      <td id="T_5d3e0_row22_col3" class="data row22 col3" >INTRO TO NATURAL LANG PROCESS</td>
      <td id="T_5d3e0_row22_col4" class="data row22 col4" >LEC</td>
      <td id="T_5d3e0_row22_col5" class="data row22 col5" >53</td>
      <td id="T_5d3e0_row22_col6" class="data row22 col6" >159</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row23_col0" class="data row23 col0" >Spring 2022</td>
      <td id="T_5d3e0_row23_col1" class="data row23 col1" >CMSC492</td>
      <td id="T_5d3e0_row23_col2" class="data row23 col2" >002</td>
      <td id="T_5d3e0_row23_col3" class="data row23 col3" >INDEPENDENT STUDY</td>
      <td id="T_5d3e0_row23_col4" class="data row23 col4" >IND</td>
      <td id="T_5d3e0_row23_col5" class="data row23 col5" >1</td>
      <td id="T_5d3e0_row23_col6" class="data row23 col6" >3</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row24_col0" class="data row24 col0" >Spring 2022</td>
      <td id="T_5d3e0_row24_col1" class="data row24 col1" >CMSC697</td>
      <td id="T_5d3e0_row24_col2" class="data row24 col2" >252</td>
      <td id="T_5d3e0_row24_col3" class="data row24 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row24_col4" class="data row24 col4" >RES</td>
      <td id="T_5d3e0_row24_col5" class="data row24 col5" >3</td>
      <td id="T_5d3e0_row24_col6" class="data row24 col6" >6</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row25_col0" class="data row25 col0" >Spring 2022</td>
      <td id="T_5d3e0_row25_col1" class="data row25 col1" >CMSC697</td>
      <td id="T_5d3e0_row25_col2" class="data row25 col2" >253</td>
      <td id="T_5d3e0_row25_col3" class="data row25 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row25_col4" class="data row25 col4" >RES</td>
      <td id="T_5d3e0_row25_col5" class="data row25 col5" >2</td>
      <td id="T_5d3e0_row25_col6" class="data row25 col6" >6</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row26_col0" class="data row26 col0" >Spring 2022</td>
      <td id="T_5d3e0_row26_col1" class="data row26 col1" >CMSC697</td>
      <td id="T_5d3e0_row26_col2" class="data row26 col2" >259</td>
      <td id="T_5d3e0_row26_col3" class="data row26 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row26_col4" class="data row26 col4" >RES</td>
      <td id="T_5d3e0_row26_col5" class="data row26 col5" >2</td>
      <td id="T_5d3e0_row26_col6" class="data row26 col6" >18</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row27_col0" class="data row27 col0" >Spring 2022</td>
      <td id="T_5d3e0_row27_col1" class="data row27 col1" >CMSC697</td>
      <td id="T_5d3e0_row27_col2" class="data row27 col2" >313</td>
      <td id="T_5d3e0_row27_col3" class="data row27 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row27_col4" class="data row27 col4" >RES</td>
      <td id="T_5d3e0_row27_col5" class="data row27 col5" >1</td>
      <td id="T_5d3e0_row27_col6" class="data row27 col6" >1</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row28_col0" class="data row28 col0" >Spring 2022</td>
      <td id="T_5d3e0_row28_col1" class="data row28 col1" >ENGR497</td>
      <td id="T_5d3e0_row28_col2" class="data row28 col2" >L12</td>
      <td id="T_5d3e0_row28_col3" class="data row28 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5d3e0_row28_col4" class="data row28 col4" >VIP</td>
      <td id="T_5d3e0_row28_col5" class="data row28 col5" >1</td>
      <td id="T_5d3e0_row28_col6" class="data row28 col6" >1</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row29_col0" class="data row29 col0" >Spring 2022</td>
      <td id="T_5d3e0_row29_col1" class="data row29 col1" >ENGR497</td>
      <td id="T_5d3e0_row29_col2" class="data row29 col2" >L13</td>
      <td id="T_5d3e0_row29_col3" class="data row29 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5d3e0_row29_col4" class="data row29 col4" >VIP</td>
      <td id="T_5d3e0_row29_col5" class="data row29 col5" >1</td>
      <td id="T_5d3e0_row29_col6" class="data row29 col6" >2</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row30_col0" class="data row30 col0" >Spring 2022</td>
      <td id="T_5d3e0_row30_col1" class="data row30 col1" >ENGR701</td>
      <td id="T_5d3e0_row30_col2" class="data row30 col2" >017</td>
      <td id="T_5d3e0_row30_col3" class="data row30 col3" >POST-CANDIDACY DOCT RESEARCH</td>
      <td id="T_5d3e0_row30_col4" class="data row30 col4" >RES</td>
      <td id="T_5d3e0_row30_col5" class="data row30 col5" >1</td>
      <td id="T_5d3e0_row30_col6" class="data row30 col6" >9</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row31_col0" class="data row31 col0" >Summer 2022</td>
      <td id="T_5d3e0_row31_col1" class="data row31 col1" >CMSC697</td>
      <td id="T_5d3e0_row31_col2" class="data row31 col2" >039</td>
      <td id="T_5d3e0_row31_col3" class="data row31 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row31_col4" class="data row31 col4" >RES</td>
      <td id="T_5d3e0_row31_col5" class="data row31 col5" >3</td>
      <td id="T_5d3e0_row31_col6" class="data row31 col6" >9</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row32_col0" class="data row32 col0" >Fall 2022</td>
      <td id="T_5d3e0_row32_col1" class="data row32 col1" >CMSC441</td>
      <td id="T_5d3e0_row32_col2" class="data row32 col2" >909</td>
      <td id="T_5d3e0_row32_col3" class="data row32 col3" >SR DESIGN STUDIO I (LAB/PROJ)</td>
      <td id="T_5d3e0_row32_col4" class="data row32 col4" >CAP</td>
      <td id="T_5d3e0_row32_col5" class="data row32 col5" >8</td>
      <td id="T_5d3e0_row32_col6" class="data row32 col6" >16</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row33_col0" class="data row33 col0" >Fall 2022</td>
      <td id="T_5d3e0_row33_col1" class="data row33 col1" >CMSC516</td>
      <td id="T_5d3e0_row33_col2" class="data row33 col2" >001</td>
      <td id="T_5d3e0_row33_col3" class="data row33 col3" >ADV NATURAL LANG PROCESSING</td>
      <td id="T_5d3e0_row33_col4" class="data row33 col4" >LEC</td>
      <td id="T_5d3e0_row33_col5" class="data row33 col5" >22</td>
      <td id="T_5d3e0_row33_col6" class="data row33 col6" >66</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row34_col0" class="data row34 col0" >Fall 2022</td>
      <td id="T_5d3e0_row34_col1" class="data row34 col1" >CMSC692</td>
      <td id="T_5d3e0_row34_col2" class="data row34 col2" >001</td>
      <td id="T_5d3e0_row34_col3" class="data row34 col3" >INDEPENDENT STUDY</td>
      <td id="T_5d3e0_row34_col4" class="data row34 col4" >IND</td>
      <td id="T_5d3e0_row34_col5" class="data row34 col5" >1</td>
      <td id="T_5d3e0_row34_col6" class="data row34 col6" >1</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row35_col0" class="data row35 col0" >Fall 2022</td>
      <td id="T_5d3e0_row35_col1" class="data row35 col1" >CMSC697</td>
      <td id="T_5d3e0_row35_col2" class="data row35 col2" >092</td>
      <td id="T_5d3e0_row35_col3" class="data row35 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row35_col4" class="data row35 col4" >RES</td>
      <td id="T_5d3e0_row35_col5" class="data row35 col5" >1</td>
      <td id="T_5d3e0_row35_col6" class="data row35 col6" >3</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row36_col0" class="data row36 col0" >Fall 2022</td>
      <td id="T_5d3e0_row36_col1" class="data row36 col1" >CMSC697</td>
      <td id="T_5d3e0_row36_col2" class="data row36 col2" >094</td>
      <td id="T_5d3e0_row36_col3" class="data row36 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row36_col4" class="data row36 col4" >RES</td>
      <td id="T_5d3e0_row36_col5" class="data row36 col5" >2</td>
      <td id="T_5d3e0_row36_col6" class="data row36 col6" >18</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row37_col0" class="data row37 col0" >Fall 2022</td>
      <td id="T_5d3e0_row37_col1" class="data row37 col1" >CMSC697</td>
      <td id="T_5d3e0_row37_col2" class="data row37 col2" >122</td>
      <td id="T_5d3e0_row37_col3" class="data row37 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row37_col4" class="data row37 col4" >RES</td>
      <td id="T_5d3e0_row37_col5" class="data row37 col5" >2</td>
      <td id="T_5d3e0_row37_col6" class="data row37 col6" >2</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row38_col0" class="data row38 col0" >Fall 2022</td>
      <td id="T_5d3e0_row38_col1" class="data row38 col1" >CMSC702</td>
      <td id="T_5d3e0_row38_col2" class="data row38 col2" >001</td>
      <td id="T_5d3e0_row38_col3" class="data row38 col3" >COMPUTER SCIENCE SEMINAR</td>
      <td id="T_5d3e0_row38_col4" class="data row38 col4" >SEM</td>
      <td id="T_5d3e0_row38_col5" class="data row38 col5" >18</td>
      <td id="T_5d3e0_row38_col6" class="data row38 col6" >18</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row39_col0" class="data row39 col0" >Fall 2022</td>
      <td id="T_5d3e0_row39_col1" class="data row39 col1" >ENGR497</td>
      <td id="T_5d3e0_row39_col2" class="data row39 col2" >L11</td>
      <td id="T_5d3e0_row39_col3" class="data row39 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5d3e0_row39_col4" class="data row39 col4" >VIP</td>
      <td id="T_5d3e0_row39_col5" class="data row39 col5" >1</td>
      <td id="T_5d3e0_row39_col6" class="data row39 col6" >1</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row40_col0" class="data row40 col0" >Fall 2022</td>
      <td id="T_5d3e0_row40_col1" class="data row40 col1" >ENGR497</td>
      <td id="T_5d3e0_row40_col2" class="data row40 col2" >L13</td>
      <td id="T_5d3e0_row40_col3" class="data row40 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5d3e0_row40_col4" class="data row40 col4" >VIP</td>
      <td id="T_5d3e0_row40_col5" class="data row40 col5" >1</td>
      <td id="T_5d3e0_row40_col6" class="data row40 col6" >2</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row41_col0" class="data row41 col0" >Spring 2023</td>
      <td id="T_5d3e0_row41_col1" class="data row41 col1" >CMSC416</td>
      <td id="T_5d3e0_row41_col2" class="data row41 col2" >901</td>
      <td id="T_5d3e0_row41_col3" class="data row41 col3" >INTRO TO NATURAL LANG PROCESS</td>
      <td id="T_5d3e0_row41_col4" class="data row41 col4" >LEC</td>
      <td id="T_5d3e0_row41_col5" class="data row41 col5" >31</td>
      <td id="T_5d3e0_row41_col6" class="data row41 col6" >93</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row42_col0" class="data row42 col0" >Spring 2023</td>
      <td id="T_5d3e0_row42_col1" class="data row42 col1" >CMSC442</td>
      <td id="T_5d3e0_row42_col2" class="data row42 col2" >909</td>
      <td id="T_5d3e0_row42_col3" class="data row42 col3" >SR DESIGN STUDIO II (LAB/PROJ)</td>
      <td id="T_5d3e0_row42_col4" class="data row42 col4" >CAP</td>
      <td id="T_5d3e0_row42_col5" class="data row42 col5" >8</td>
      <td id="T_5d3e0_row42_col6" class="data row42 col6" >16</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row43_col0" class="data row43 col0" >Spring 2023</td>
      <td id="T_5d3e0_row43_col1" class="data row43 col1" >CMSC516</td>
      <td id="T_5d3e0_row43_col2" class="data row43 col2" >901</td>
      <td id="T_5d3e0_row43_col3" class="data row43 col3" >ADV NATURAL LANG PROCESSING</td>
      <td id="T_5d3e0_row43_col4" class="data row43 col4" >LEC</td>
      <td id="T_5d3e0_row43_col5" class="data row43 col5" >4</td>
      <td id="T_5d3e0_row43_col6" class="data row43 col6" >12</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row44_col0" class="data row44 col0" >Spring 2023</td>
      <td id="T_5d3e0_row44_col1" class="data row44 col1" >CMSC697</td>
      <td id="T_5d3e0_row44_col2" class="data row44 col2" >252</td>
      <td id="T_5d3e0_row44_col3" class="data row44 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row44_col4" class="data row44 col4" >RES</td>
      <td id="T_5d3e0_row44_col5" class="data row44 col5" >1</td>
      <td id="T_5d3e0_row44_col6" class="data row44 col6" >2</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row45_col0" class="data row45 col0" >Spring 2023</td>
      <td id="T_5d3e0_row45_col1" class="data row45 col1" >CMSC697</td>
      <td id="T_5d3e0_row45_col2" class="data row45 col2" >253</td>
      <td id="T_5d3e0_row45_col3" class="data row45 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row45_col4" class="data row45 col4" >RES</td>
      <td id="T_5d3e0_row45_col5" class="data row45 col5" >2</td>
      <td id="T_5d3e0_row45_col6" class="data row45 col6" >6</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row46_col0" class="data row46 col0" >Spring 2023</td>
      <td id="T_5d3e0_row46_col1" class="data row46 col1" >CMSC697</td>
      <td id="T_5d3e0_row46_col2" class="data row46 col2" >256</td>
      <td id="T_5d3e0_row46_col3" class="data row46 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row46_col4" class="data row46 col4" >RES</td>
      <td id="T_5d3e0_row46_col5" class="data row46 col5" >1</td>
      <td id="T_5d3e0_row46_col6" class="data row46 col6" >6</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row47_col0" class="data row47 col0" >Spring 2023</td>
      <td id="T_5d3e0_row47_col1" class="data row47 col1" >CMSC697</td>
      <td id="T_5d3e0_row47_col2" class="data row47 col2" >259</td>
      <td id="T_5d3e0_row47_col3" class="data row47 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row47_col4" class="data row47 col4" >RES</td>
      <td id="T_5d3e0_row47_col5" class="data row47 col5" >1</td>
      <td id="T_5d3e0_row47_col6" class="data row47 col6" >9</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row48_col0" class="data row48 col0" >Spring 2023</td>
      <td id="T_5d3e0_row48_col1" class="data row48 col1" >ENGR497</td>
      <td id="T_5d3e0_row48_col2" class="data row48 col2" >L12</td>
      <td id="T_5d3e0_row48_col3" class="data row48 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5d3e0_row48_col4" class="data row48 col4" >VIP</td>
      <td id="T_5d3e0_row48_col5" class="data row48 col5" >1</td>
      <td id="T_5d3e0_row48_col6" class="data row48 col6" >1</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row49_col0" class="data row49 col0" >Summer 2023</td>
      <td id="T_5d3e0_row49_col1" class="data row49 col1" >CMSC697</td>
      <td id="T_5d3e0_row49_col2" class="data row49 col2" >037</td>
      <td id="T_5d3e0_row49_col3" class="data row49 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row49_col4" class="data row49 col4" >RES</td>
      <td id="T_5d3e0_row49_col5" class="data row49 col5" >2</td>
      <td id="T_5d3e0_row49_col6" class="data row49 col6" >2</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row50_col0" class="data row50 col0" >Summer 2023</td>
      <td id="T_5d3e0_row50_col1" class="data row50 col1" >CMSC697</td>
      <td id="T_5d3e0_row50_col2" class="data row50 col2" >039</td>
      <td id="T_5d3e0_row50_col3" class="data row50 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row50_col4" class="data row50 col4" >RES</td>
      <td id="T_5d3e0_row50_col5" class="data row50 col5" >2</td>
      <td id="T_5d3e0_row50_col6" class="data row50 col6" >6</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row51_col0" class="data row51 col0" >Fall 2023</td>
      <td id="T_5d3e0_row51_col1" class="data row51 col1" >CMSC441</td>
      <td id="T_5d3e0_row51_col2" class="data row51 col2" >909</td>
      <td id="T_5d3e0_row51_col3" class="data row51 col3" >SR DESIGN STUDIO I (LAB/PROJ)</td>
      <td id="T_5d3e0_row51_col4" class="data row51 col4" >CAP</td>
      <td id="T_5d3e0_row51_col5" class="data row51 col5" >7</td>
      <td id="T_5d3e0_row51_col6" class="data row51 col6" >14</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row52_col0" class="data row52 col0" >Fall 2023</td>
      <td id="T_5d3e0_row52_col1" class="data row52 col1" >CMSC492</td>
      <td id="T_5d3e0_row52_col2" class="data row52 col2" >001</td>
      <td id="T_5d3e0_row52_col3" class="data row52 col3" >INDEPENDENT STUDY</td>
      <td id="T_5d3e0_row52_col4" class="data row52 col4" >IND</td>
      <td id="T_5d3e0_row52_col5" class="data row52 col5" >1</td>
      <td id="T_5d3e0_row52_col6" class="data row52 col6" >3</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row53_col0" class="data row53 col0" >Fall 2023</td>
      <td id="T_5d3e0_row53_col1" class="data row53 col1" >CMSC691</td>
      <td id="T_5d3e0_row53_col2" class="data row53 col2" >901</td>
      <td id="T_5d3e0_row53_col3" class="data row53 col3" >SP:EMERGE TRENDS NAT LANG PROC</td>
      <td id="T_5d3e0_row53_col4" class="data row53 col4" >LEC</td>
      <td id="T_5d3e0_row53_col5" class="data row53 col5" >15</td>
      <td id="T_5d3e0_row53_col6" class="data row53 col6" >45</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row54_col0" class="data row54 col0" >Fall 2023</td>
      <td id="T_5d3e0_row54_col1" class="data row54 col1" >CMSC697</td>
      <td id="T_5d3e0_row54_col2" class="data row54 col2" >091</td>
      <td id="T_5d3e0_row54_col3" class="data row54 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row54_col4" class="data row54 col4" >RES</td>
      <td id="T_5d3e0_row54_col5" class="data row54 col5" >1</td>
      <td id="T_5d3e0_row54_col6" class="data row54 col6" >2</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row55_col0" class="data row55 col0" >Fall 2023</td>
      <td id="T_5d3e0_row55_col1" class="data row55 col1" >CMSC697</td>
      <td id="T_5d3e0_row55_col2" class="data row55 col2" >092</td>
      <td id="T_5d3e0_row55_col3" class="data row55 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row55_col4" class="data row55 col4" >RES</td>
      <td id="T_5d3e0_row55_col5" class="data row55 col5" >2</td>
      <td id="T_5d3e0_row55_col6" class="data row55 col6" >6</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row56_col0" class="data row56 col0" >Fall 2023</td>
      <td id="T_5d3e0_row56_col1" class="data row56 col1" >CMSC697</td>
      <td id="T_5d3e0_row56_col2" class="data row56 col2" >122</td>
      <td id="T_5d3e0_row56_col3" class="data row56 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row56_col4" class="data row56 col4" >RES</td>
      <td id="T_5d3e0_row56_col5" class="data row56 col5" >1</td>
      <td id="T_5d3e0_row56_col6" class="data row56 col6" >1</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row57_col0" class="data row57 col0" >Fall 2023</td>
      <td id="T_5d3e0_row57_col1" class="data row57 col1" >CMSC702</td>
      <td id="T_5d3e0_row57_col2" class="data row57 col2" >001</td>
      <td id="T_5d3e0_row57_col3" class="data row57 col3" >COMPUTER SCIENCE SEMINAR</td>
      <td id="T_5d3e0_row57_col4" class="data row57 col4" >SEM</td>
      <td id="T_5d3e0_row57_col5" class="data row57 col5" >19</td>
      <td id="T_5d3e0_row57_col6" class="data row57 col6" >19</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row58_col0" class="data row58 col0" >Fall 2023</td>
      <td id="T_5d3e0_row58_col1" class="data row58 col1" >ENGR497</td>
      <td id="T_5d3e0_row58_col2" class="data row58 col2" >L11</td>
      <td id="T_5d3e0_row58_col3" class="data row58 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5d3e0_row58_col4" class="data row58 col4" >VIP</td>
      <td id="T_5d3e0_row58_col5" class="data row58 col5" >2</td>
      <td id="T_5d3e0_row58_col6" class="data row58 col6" >2</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row59_col0" class="data row59 col0" >Fall 2023</td>
      <td id="T_5d3e0_row59_col1" class="data row59 col1" >ENGR701</td>
      <td id="T_5d3e0_row59_col2" class="data row59 col2" >017</td>
      <td id="T_5d3e0_row59_col3" class="data row59 col3" >POST-CANDIDACY DOCT RESEARCH</td>
      <td id="T_5d3e0_row59_col4" class="data row59 col4" >RES</td>
      <td id="T_5d3e0_row59_col5" class="data row59 col5" >1</td>
      <td id="T_5d3e0_row59_col6" class="data row59 col6" >9</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row60_col0" class="data row60 col0" >Spring 2024</td>
      <td id="T_5d3e0_row60_col1" class="data row60 col1" >CMSC416</td>
      <td id="T_5d3e0_row60_col2" class="data row60 col2" >001</td>
      <td id="T_5d3e0_row60_col3" class="data row60 col3" >INTRO TO NATURAL LANG PROCESS</td>
      <td id="T_5d3e0_row60_col4" class="data row60 col4" >LEC</td>
      <td id="T_5d3e0_row60_col5" class="data row60 col5" >48</td>
      <td id="T_5d3e0_row60_col6" class="data row60 col6" >144</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row61_col0" class="data row61 col0" >Spring 2024</td>
      <td id="T_5d3e0_row61_col1" class="data row61 col1" >CMSC442</td>
      <td id="T_5d3e0_row61_col2" class="data row61 col2" >909</td>
      <td id="T_5d3e0_row61_col3" class="data row61 col3" >SR DESIGN STUDIO II (LAB/PROJ)</td>
      <td id="T_5d3e0_row61_col4" class="data row61 col4" >CAP</td>
      <td id="T_5d3e0_row61_col5" class="data row61 col5" >8</td>
      <td id="T_5d3e0_row61_col6" class="data row61 col6" >16</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row62_col0" class="data row62 col0" >Spring 2024</td>
      <td id="T_5d3e0_row62_col1" class="data row62 col1" >CMSC516</td>
      <td id="T_5d3e0_row62_col2" class="data row62 col2" >001</td>
      <td id="T_5d3e0_row62_col3" class="data row62 col3" >ADV NATURAL LANG PROCESSING</td>
      <td id="T_5d3e0_row62_col4" class="data row62 col4" >LEC</td>
      <td id="T_5d3e0_row62_col5" class="data row62 col5" >18</td>
      <td id="T_5d3e0_row62_col6" class="data row62 col6" >54</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row63_col0" class="data row63 col0" >Spring 2024</td>
      <td id="T_5d3e0_row63_col1" class="data row63 col1" >CMSC697</td>
      <td id="T_5d3e0_row63_col2" class="data row63 col2" >252</td>
      <td id="T_5d3e0_row63_col3" class="data row63 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row63_col4" class="data row63 col4" >RES</td>
      <td id="T_5d3e0_row63_col5" class="data row63 col5" >1</td>
      <td id="T_5d3e0_row63_col6" class="data row63 col6" >2</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row64_col0" class="data row64 col0" >Spring 2024</td>
      <td id="T_5d3e0_row64_col1" class="data row64 col1" >CMSC697</td>
      <td id="T_5d3e0_row64_col2" class="data row64 col2" >253</td>
      <td id="T_5d3e0_row64_col3" class="data row64 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row64_col4" class="data row64 col4" >RES</td>
      <td id="T_5d3e0_row64_col5" class="data row64 col5" >1</td>
      <td id="T_5d3e0_row64_col6" class="data row64 col6" >3</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row65_col0" class="data row65 col0" >Spring 2024</td>
      <td id="T_5d3e0_row65_col1" class="data row65 col1" >CMSC697</td>
      <td id="T_5d3e0_row65_col2" class="data row65 col2" >256</td>
      <td id="T_5d3e0_row65_col3" class="data row65 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row65_col4" class="data row65 col4" >RES</td>
      <td id="T_5d3e0_row65_col5" class="data row65 col5" >1</td>
      <td id="T_5d3e0_row65_col6" class="data row65 col6" >6</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row66_col0" class="data row66 col0" >Spring 2024</td>
      <td id="T_5d3e0_row66_col1" class="data row66 col1" >CMSC697</td>
      <td id="T_5d3e0_row66_col2" class="data row66 col2" >259</td>
      <td id="T_5d3e0_row66_col3" class="data row66 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row66_col4" class="data row66 col4" >RES</td>
      <td id="T_5d3e0_row66_col5" class="data row66 col5" >1</td>
      <td id="T_5d3e0_row66_col6" class="data row66 col6" >9</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row67_col0" class="data row67 col0" >Spring 2024</td>
      <td id="T_5d3e0_row67_col1" class="data row67 col1" >CMSC697</td>
      <td id="T_5d3e0_row67_col2" class="data row67 col2" >313</td>
      <td id="T_5d3e0_row67_col3" class="data row67 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row67_col4" class="data row67 col4" >RES</td>
      <td id="T_5d3e0_row67_col5" class="data row67 col5" >1</td>
      <td id="T_5d3e0_row67_col6" class="data row67 col6" >1</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row68_col0" class="data row68 col0" >Spring 2024</td>
      <td id="T_5d3e0_row68_col1" class="data row68 col1" >ENGR497</td>
      <td id="T_5d3e0_row68_col2" class="data row68 col2" >L12</td>
      <td id="T_5d3e0_row68_col3" class="data row68 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5d3e0_row68_col4" class="data row68 col4" >VIP</td>
      <td id="T_5d3e0_row68_col5" class="data row68 col5" >2</td>
      <td id="T_5d3e0_row68_col6" class="data row68 col6" >2</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row69_col0" class="data row69 col0" >Spring 2024</td>
      <td id="T_5d3e0_row69_col1" class="data row69 col1" >ENGR497</td>
      <td id="T_5d3e0_row69_col2" class="data row69 col2" >L13</td>
      <td id="T_5d3e0_row69_col3" class="data row69 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5d3e0_row69_col4" class="data row69 col4" >VIP</td>
      <td id="T_5d3e0_row69_col5" class="data row69 col5" >0</td>
      <td id="T_5d3e0_row69_col6" class="data row69 col6" >1</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row70_col0" class="data row70 col0" >Spring 2024</td>
      <td id="T_5d3e0_row70_col1" class="data row70 col1" >ENGR701</td>
      <td id="T_5d3e0_row70_col2" class="data row70 col2" >017</td>
      <td id="T_5d3e0_row70_col3" class="data row70 col3" >POST-CANDIDACY DOCT RESEARCH</td>
      <td id="T_5d3e0_row70_col4" class="data row70 col4" >RES</td>
      <td id="T_5d3e0_row70_col5" class="data row70 col5" >1</td>
      <td id="T_5d3e0_row70_col6" class="data row70 col6" >9</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row71_col0" class="data row71 col0" >Summer 2024</td>
      <td id="T_5d3e0_row71_col1" class="data row71 col1" >CMSC692</td>
      <td id="T_5d3e0_row71_col2" class="data row71 col2" >004</td>
      <td id="T_5d3e0_row71_col3" class="data row71 col3" >INDEPENDENT STUDY</td>
      <td id="T_5d3e0_row71_col4" class="data row71 col4" >IND</td>
      <td id="T_5d3e0_row71_col5" class="data row71 col5" >1</td>
      <td id="T_5d3e0_row71_col6" class="data row71 col6" >3</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row72_col0" class="data row72 col0" >Summer 2024</td>
      <td id="T_5d3e0_row72_col1" class="data row72 col1" >CMSC697</td>
      <td id="T_5d3e0_row72_col2" class="data row72 col2" >037</td>
      <td id="T_5d3e0_row72_col3" class="data row72 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row72_col4" class="data row72 col4" >RES</td>
      <td id="T_5d3e0_row72_col5" class="data row72 col5" >1</td>
      <td id="T_5d3e0_row72_col6" class="data row72 col6" >1</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row73_col0" class="data row73 col0" >Summer 2024</td>
      <td id="T_5d3e0_row73_col1" class="data row73 col1" >CMSC697</td>
      <td id="T_5d3e0_row73_col2" class="data row73 col2" >038</td>
      <td id="T_5d3e0_row73_col3" class="data row73 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row73_col4" class="data row73 col4" >RES</td>
      <td id="T_5d3e0_row73_col5" class="data row73 col5" >2</td>
      <td id="T_5d3e0_row73_col6" class="data row73 col6" >6</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row74_col0" class="data row74 col0" >Fall 2024</td>
      <td id="T_5d3e0_row74_col1" class="data row74 col1" >CMSC441</td>
      <td id="T_5d3e0_row74_col2" class="data row74 col2" >909</td>
      <td id="T_5d3e0_row74_col3" class="data row74 col3" >SR DESIGN STUDIO I (LAB/PROJ)</td>
      <td id="T_5d3e0_row74_col4" class="data row74 col4" >CAP</td>
      <td id="T_5d3e0_row74_col5" class="data row74 col5" >4</td>
      <td id="T_5d3e0_row74_col6" class="data row74 col6" >8</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row75_col0" class="data row75 col0" >Fall 2024</td>
      <td id="T_5d3e0_row75_col1" class="data row75 col1" >CMSC516</td>
      <td id="T_5d3e0_row75_col2" class="data row75 col2" >001</td>
      <td id="T_5d3e0_row75_col3" class="data row75 col3" >ADV NATURAL LANG PROCESSING</td>
      <td id="T_5d3e0_row75_col4" class="data row75 col4" >LEC</td>
      <td id="T_5d3e0_row75_col5" class="data row75 col5" >39</td>
      <td id="T_5d3e0_row75_col6" class="data row75 col6" >117</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row76_col0" class="data row76 col0" >Fall 2024</td>
      <td id="T_5d3e0_row76_col1" class="data row76 col1" >CMSC692</td>
      <td id="T_5d3e0_row76_col2" class="data row76 col2" >001</td>
      <td id="T_5d3e0_row76_col3" class="data row76 col3" >INDEPENDENT STUDY</td>
      <td id="T_5d3e0_row76_col4" class="data row76 col4" >IND</td>
      <td id="T_5d3e0_row76_col5" class="data row76 col5" >1</td>
      <td id="T_5d3e0_row76_col6" class="data row76 col6" >1</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row77_col0" class="data row77 col0" >Fall 2024</td>
      <td id="T_5d3e0_row77_col1" class="data row77 col1" >CMSC697</td>
      <td id="T_5d3e0_row77_col2" class="data row77 col2" >091</td>
      <td id="T_5d3e0_row77_col3" class="data row77 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row77_col4" class="data row77 col4" >RES</td>
      <td id="T_5d3e0_row77_col5" class="data row77 col5" >1</td>
      <td id="T_5d3e0_row77_col6" class="data row77 col6" >2</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row78_col0" class="data row78 col0" >Fall 2024</td>
      <td id="T_5d3e0_row78_col1" class="data row78 col1" >CMSC697</td>
      <td id="T_5d3e0_row78_col2" class="data row78 col2" >092</td>
      <td id="T_5d3e0_row78_col3" class="data row78 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row78_col4" class="data row78 col4" >RES</td>
      <td id="T_5d3e0_row78_col5" class="data row78 col5" >1</td>
      <td id="T_5d3e0_row78_col6" class="data row78 col6" >3</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row79_col0" class="data row79 col0" >Fall 2024</td>
      <td id="T_5d3e0_row79_col1" class="data row79 col1" >CMSC697</td>
      <td id="T_5d3e0_row79_col2" class="data row79 col2" >124</td>
      <td id="T_5d3e0_row79_col3" class="data row79 col3" >DIRECTED RESEARCH</td>
      <td id="T_5d3e0_row79_col4" class="data row79 col4" >RES</td>
      <td id="T_5d3e0_row79_col5" class="data row79 col5" >1</td>
      <td id="T_5d3e0_row79_col6" class="data row79 col6" >1</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row80_col0" class="data row80 col0" >Fall 2024</td>
      <td id="T_5d3e0_row80_col1" class="data row80 col1" >CMSC702</td>
      <td id="T_5d3e0_row80_col2" class="data row80 col2" >001</td>
      <td id="T_5d3e0_row80_col3" class="data row80 col3" >COMPUTER SCIENCE SEMINAR</td>
      <td id="T_5d3e0_row80_col4" class="data row80 col4" >SEM</td>
      <td id="T_5d3e0_row80_col5" class="data row80 col5" >24</td>
      <td id="T_5d3e0_row80_col6" class="data row80 col6" >24</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row81_col0" class="data row81 col0" >Fall 2024</td>
      <td id="T_5d3e0_row81_col1" class="data row81 col1" >ENGR497</td>
      <td id="T_5d3e0_row81_col2" class="data row81 col2" >L11</td>
      <td id="T_5d3e0_row81_col3" class="data row81 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5d3e0_row81_col4" class="data row81 col4" >VIP</td>
      <td id="T_5d3e0_row81_col5" class="data row81 col5" >2</td>
      <td id="T_5d3e0_row81_col6" class="data row81 col6" >2</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row82_col0" class="data row82 col0" >Fall 2024</td>
      <td id="T_5d3e0_row82_col1" class="data row82 col1" >ENGR497</td>
      <td id="T_5d3e0_row82_col2" class="data row82 col2" >L13</td>
      <td id="T_5d3e0_row82_col3" class="data row82 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_5d3e0_row82_col4" class="data row82 col4" >VIP</td>
      <td id="T_5d3e0_row82_col5" class="data row82 col5" >1</td>
      <td id="T_5d3e0_row82_col6" class="data row82 col6" >2</td>
    </tr>
    <tr>
      <td id="T_5d3e0_row83_col0" class="data row83 col0" >Fall 2024</td>
      <td id="T_5d3e0_row83_col1" class="data row83 col1" >ENGR701</td>
      <td id="T_5d3e0_row83_col2" class="data row83 col2" >017</td>
      <td id="T_5d3e0_row83_col3" class="data row83 col3" >POST-CANDIDACY DOCT RESEARCH</td>
      <td id="T_5d3e0_row83_col4" class="data row83 col4" >RES</td>
      <td id="T_5d3e0_row83_col5" class="data row83 col5" >1</td>
      <td id="T_5d3e0_row83_col6" class="data row83 col6" >9</td>
    </tr>
  </tbody>
</table>


