---
title: Instructor Teaching Activity - COAR
date: last-modified
---

Instructor teaching activity for COAR.

# Overview

This report slices and dices instructor teaching activity several ways:

* Recent academic years - a listing of instructor activity 
for a recent academic year for instructors teaching during that academic year.

* All instructors - a listing of instructor activity over time
for all instructors in [the sample](/10_download.html).

The page navigation on the right side of the display can help
as you explore the data.

**Issues and Errors**

Banner doesn’t always reflect reality. Contact John Leonard if you find inconsistences and we'll
incorporate them into the next iteration of the report.  See [this section](/20_clean.html#fix-known-errors) to learn more.


# AY25-26

This section list instructor activity for the academic year AY25-26 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## Jason Bennett

<style type="text/css">
#T_fa6a5_row0_col0, #T_fa6a5_row0_col1, #T_fa6a5_row0_col2, #T_fa6a5_row0_col3, #T_fa6a5_row0_col4, #T_fa6a5_row0_col5, #T_fa6a5_row0_col6 {
  background-color: #f0f0f0;
  border-bottom: 1px solid #ccc;
}
</style>
<table id="T_fa6a5">
  <thead>
    <tr>
      <th id="T_fa6a5_level0_col0" class="col_heading level0 col0" >Term</th>
      <th id="T_fa6a5_level0_col1" class="col_heading level0 col1" >Crse</th>
      <th id="T_fa6a5_level0_col2" class="col_heading level0 col2" >Sect</th>
      <th id="T_fa6a5_level0_col3" class="col_heading level0 col3" >Crse Title</th>
      <th id="T_fa6a5_level0_col4" class="col_heading level0 col4" >W.Type</th>
      <th id="T_fa6a5_level0_col5" class="col_heading level0 col5" >Stdnts</th>
      <th id="T_fa6a5_level0_col6" class="col_heading level0 col6" >Hours</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_fa6a5_row0_col0" class="data row0 col0" >Fall 2025</td>
      <td id="T_fa6a5_row0_col1" class="data row0 col1" >CMSC445</td>
      <td id="T_fa6a5_row0_col2" class="data row0 col2" >001</td>
      <td id="T_fa6a5_row0_col3" class="data row0 col3" >INTRO TO GAME DEVELOPMENT</td>
      <td id="T_fa6a5_row0_col4" class="data row0 col4" >LEC</td>
      <td id="T_fa6a5_row0_col5" class="data row0 col5" >14</td>
      <td id="T_fa6a5_row0_col6" class="data row0 col6" >44</td>
    </tr>
  </tbody>
</table>



# AY24-25

This section list instructor activity for the academic year AY24-25 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## Jason Bennett

<style type="text/css">
#T_e3e60_row0_col0, #T_e3e60_row0_col1, #T_e3e60_row0_col2, #T_e3e60_row0_col3, #T_e3e60_row0_col4, #T_e3e60_row0_col5, #T_e3e60_row0_col6 {
  background-color: #f0f0f0;
  border-bottom: 1px solid #ccc;
}
</style>
<table id="T_e3e60">
  <thead>
    <tr>
      <th id="T_e3e60_level0_col0" class="col_heading level0 col0" >Term</th>
      <th id="T_e3e60_level0_col1" class="col_heading level0 col1" >Crse</th>
      <th id="T_e3e60_level0_col2" class="col_heading level0 col2" >Sect</th>
      <th id="T_e3e60_level0_col3" class="col_heading level0 col3" >Crse Title</th>
      <th id="T_e3e60_level0_col4" class="col_heading level0 col4" >W.Type</th>
      <th id="T_e3e60_level0_col5" class="col_heading level0 col5" >Stdnts</th>
      <th id="T_e3e60_level0_col6" class="col_heading level0 col6" >Hours</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_e3e60_row0_col0" class="data row0 col0" >Fall 2024</td>
      <td id="T_e3e60_row0_col1" class="data row0 col1" >CMSC445</td>
      <td id="T_e3e60_row0_col2" class="data row0 col2" >001</td>
      <td id="T_e3e60_row0_col3" class="data row0 col3" >INTRO TO GAME DEVELOPMENT</td>
      <td id="T_e3e60_row0_col4" class="data row0 col4" >LEC</td>
      <td id="T_e3e60_row0_col5" class="data row0 col5" >8</td>
      <td id="T_e3e60_row0_col6" class="data row0 col6" >26</td>
    </tr>
  </tbody>
</table>



# AY23-24

This section list instructor activity for the academic year AY23-24 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## Jason Bennett

<style type="text/css">
#T_7cf1d_row0_col0, #T_7cf1d_row0_col1, #T_7cf1d_row0_col2, #T_7cf1d_row0_col3, #T_7cf1d_row0_col4, #T_7cf1d_row0_col5, #T_7cf1d_row0_col6 {
  background-color: #f0f0f0;
  border-bottom: 1px solid #ccc;
}
</style>
<table id="T_7cf1d">
  <thead>
    <tr>
      <th id="T_7cf1d_level0_col0" class="col_heading level0 col0" >Term</th>
      <th id="T_7cf1d_level0_col1" class="col_heading level0 col1" >Crse</th>
      <th id="T_7cf1d_level0_col2" class="col_heading level0 col2" >Sect</th>
      <th id="T_7cf1d_level0_col3" class="col_heading level0 col3" >Crse Title</th>
      <th id="T_7cf1d_level0_col4" class="col_heading level0 col4" >W.Type</th>
      <th id="T_7cf1d_level0_col5" class="col_heading level0 col5" >Stdnts</th>
      <th id="T_7cf1d_level0_col6" class="col_heading level0 col6" >Hours</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_7cf1d_row0_col0" class="data row0 col0" >Fall 2023</td>
      <td id="T_7cf1d_row0_col1" class="data row0 col1" >CMSC391</td>
      <td id="T_7cf1d_row0_col2" class="data row0 col2" >001</td>
      <td id="T_7cf1d_row0_col3" class="data row0 col3" >TOP:INTRO TO GAME DEVELOPMENT</td>
      <td id="T_7cf1d_row0_col4" class="data row0 col4" >LEC</td>
      <td id="T_7cf1d_row0_col5" class="data row0 col5" >10</td>
      <td id="T_7cf1d_row0_col6" class="data row0 col6" >30</td>
    </tr>
  </tbody>
</table>



# AY22-23

This section list instructor activity for the academic year AY22-23 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## Jason Bennett

<style type="text/css">
#T_45eae_row0_col0, #T_45eae_row0_col1, #T_45eae_row0_col2, #T_45eae_row0_col3, #T_45eae_row0_col4, #T_45eae_row0_col5, #T_45eae_row0_col6 {
  background-color: #f0f0f0;
  border-bottom: 1px solid #ccc;
}
</style>
<table id="T_45eae">
  <thead>
    <tr>
      <th id="T_45eae_level0_col0" class="col_heading level0 col0" >Term</th>
      <th id="T_45eae_level0_col1" class="col_heading level0 col1" >Crse</th>
      <th id="T_45eae_level0_col2" class="col_heading level0 col2" >Sect</th>
      <th id="T_45eae_level0_col3" class="col_heading level0 col3" >Crse Title</th>
      <th id="T_45eae_level0_col4" class="col_heading level0 col4" >W.Type</th>
      <th id="T_45eae_level0_col5" class="col_heading level0 col5" >Stdnts</th>
      <th id="T_45eae_level0_col6" class="col_heading level0 col6" >Hours</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_45eae_row0_col0" class="data row0 col0" >Fall 2022</td>
      <td id="T_45eae_row0_col1" class="data row0 col1" >CMSC391</td>
      <td id="T_45eae_row0_col2" class="data row0 col2" >001</td>
      <td id="T_45eae_row0_col3" class="data row0 col3" >TOP: INTRO TO GAME DEVELOPMENT</td>
      <td id="T_45eae_row0_col4" class="data row0 col4" >LEC</td>
      <td id="T_45eae_row0_col5" class="data row0 col5" >6</td>
      <td id="T_45eae_row0_col6" class="data row0 col6" >16</td>
    </tr>
  </tbody>
</table>



# AY21-22

This section list instructor activity for the academic year AY21-22 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


# AY20-21

This section list instructor activity for the academic year AY20-21 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


# All Instructors


## Jason Bennett

<style type="text/css">
#T_ddb53_row0_col0, #T_ddb53_row0_col1, #T_ddb53_row0_col2, #T_ddb53_row0_col3, #T_ddb53_row0_col4, #T_ddb53_row0_col5, #T_ddb53_row0_col6, #T_ddb53_row2_col0, #T_ddb53_row2_col1, #T_ddb53_row2_col2, #T_ddb53_row2_col3, #T_ddb53_row2_col4, #T_ddb53_row2_col5, #T_ddb53_row2_col6 {
  background-color: #f0f0f0;
  border-bottom: 1px solid #ccc;
}
#T_ddb53_row1_col0, #T_ddb53_row1_col1, #T_ddb53_row1_col2, #T_ddb53_row1_col3, #T_ddb53_row1_col4, #T_ddb53_row1_col5, #T_ddb53_row1_col6, #T_ddb53_row3_col0, #T_ddb53_row3_col1, #T_ddb53_row3_col2, #T_ddb53_row3_col3, #T_ddb53_row3_col4, #T_ddb53_row3_col5, #T_ddb53_row3_col6 {
  background-color: #ffffff;
  border-bottom: 1px solid #ccc;
}
</style>
<table id="T_ddb53">
  <thead>
    <tr>
      <th id="T_ddb53_level0_col0" class="col_heading level0 col0" >Term</th>
      <th id="T_ddb53_level0_col1" class="col_heading level0 col1" >Crse</th>
      <th id="T_ddb53_level0_col2" class="col_heading level0 col2" >Sect</th>
      <th id="T_ddb53_level0_col3" class="col_heading level0 col3" >Crse Title</th>
      <th id="T_ddb53_level0_col4" class="col_heading level0 col4" >W.Type</th>
      <th id="T_ddb53_level0_col5" class="col_heading level0 col5" >Stdnts</th>
      <th id="T_ddb53_level0_col6" class="col_heading level0 col6" >Hours</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_ddb53_row0_col0" class="data row0 col0" >Fall 2022</td>
      <td id="T_ddb53_row0_col1" class="data row0 col1" >CMSC391</td>
      <td id="T_ddb53_row0_col2" class="data row0 col2" >001</td>
      <td id="T_ddb53_row0_col3" class="data row0 col3" >TOP: INTRO TO GAME DEVELOPMENT</td>
      <td id="T_ddb53_row0_col4" class="data row0 col4" >LEC</td>
      <td id="T_ddb53_row0_col5" class="data row0 col5" >6</td>
      <td id="T_ddb53_row0_col6" class="data row0 col6" >16</td>
    </tr>
    <tr>
      <td id="T_ddb53_row1_col0" class="data row1 col0" >Fall 2023</td>
      <td id="T_ddb53_row1_col1" class="data row1 col1" >CMSC391</td>
      <td id="T_ddb53_row1_col2" class="data row1 col2" >001</td>
      <td id="T_ddb53_row1_col3" class="data row1 col3" >TOP:INTRO TO GAME DEVELOPMENT</td>
      <td id="T_ddb53_row1_col4" class="data row1 col4" >LEC</td>
      <td id="T_ddb53_row1_col5" class="data row1 col5" >10</td>
      <td id="T_ddb53_row1_col6" class="data row1 col6" >30</td>
    </tr>
    <tr>
      <td id="T_ddb53_row2_col0" class="data row2 col0" >Fall 2024</td>
      <td id="T_ddb53_row2_col1" class="data row2 col1" >CMSC445</td>
      <td id="T_ddb53_row2_col2" class="data row2 col2" >001</td>
      <td id="T_ddb53_row2_col3" class="data row2 col3" >INTRO TO GAME DEVELOPMENT</td>
      <td id="T_ddb53_row2_col4" class="data row2 col4" >LEC</td>
      <td id="T_ddb53_row2_col5" class="data row2 col5" >8</td>
      <td id="T_ddb53_row2_col6" class="data row2 col6" >26</td>
    </tr>
    <tr>
      <td id="T_ddb53_row3_col0" class="data row3 col0" >Fall 2025</td>
      <td id="T_ddb53_row3_col1" class="data row3 col1" >CMSC445</td>
      <td id="T_ddb53_row3_col2" class="data row3 col2" >001</td>
      <td id="T_ddb53_row3_col3" class="data row3 col3" >INTRO TO GAME DEVELOPMENT</td>
      <td id="T_ddb53_row3_col4" class="data row3 col4" >LEC</td>
      <td id="T_ddb53_row3_col5" class="data row3 col5" >14</td>
      <td id="T_ddb53_row3_col6" class="data row3 col6" >44</td>
    </tr>
  </tbody>
</table>


