---
title: Instructor Teaching Activity - EBRC
date: last-modified
---

Instructor teaching activity for EBRC.

# Overview

This report slices and dices instructor teaching activity several ways:

* Recent academic years - a listing of instructor activity 
for a recent academic year for instructors teaching during that academic year.

* All instructors - a listing of instructor activity over time
for all instructors in [the sample](/10_download.html).

The page navigation on the right side of the display can help
as you explore the data.

**Issues and Errors**

Banner doesn’t always reflect reality. Contact John Leonard if you find inconsistences and we'll
incorporate them into the next iteration of the report.  See [this section](/20_clean.html#fix-known-errors) to learn more.


# AY25-26

This section list instructor activity for the academic year AY25-26 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## Stephen Fong

<style type="text/css">
#T_852b8_row0_col0, #T_852b8_row0_col1, #T_852b8_row0_col2, #T_852b8_row0_col3, #T_852b8_row0_col4, #T_852b8_row0_col5, #T_852b8_row0_col6 {
  background-color: #f0f0f0;
  border-bottom: 1px solid #ccc;
}
</style>
<table id="T_852b8">
  <thead>
    <tr>
      <th id="T_852b8_level0_col0" class="col_heading level0 col0" >Term</th>
      <th id="T_852b8_level0_col1" class="col_heading level0 col1" >Crse</th>
      <th id="T_852b8_level0_col2" class="col_heading level0 col2" >Sect</th>
      <th id="T_852b8_level0_col3" class="col_heading level0 col3" >Crse Title</th>
      <th id="T_852b8_level0_col4" class="col_heading level0 col4" >W.Type</th>
      <th id="T_852b8_level0_col5" class="col_heading level0 col5" >Stdnts</th>
      <th id="T_852b8_level0_col6" class="col_heading level0 col6" >Hours</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_852b8_row0_col0" class="data row0 col0" >Fall 2025</td>
      <td id="T_852b8_row0_col1" class="data row0 col1" >ENGR492</td>
      <td id="T_852b8_row0_col2" class="data row0 col2" >010</td>
      <td id="T_852b8_row0_col3" class="data row0 col3" >INDEPENDENT STUDY IN ENGINRNG</td>
      <td id="T_852b8_row0_col4" class="data row0 col4" >IND</td>
      <td id="T_852b8_row0_col5" class="data row0 col5" >1</td>
      <td id="T_852b8_row0_col6" class="data row0 col6" >3</td>
    </tr>
  </tbody>
</table>



# AY24-25

This section list instructor activity for the academic year AY24-25 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## Stephen Fong

<style type="text/css">
#T_60bd6_row0_col0, #T_60bd6_row0_col1, #T_60bd6_row0_col2, #T_60bd6_row0_col3, #T_60bd6_row0_col4, #T_60bd6_row0_col5, #T_60bd6_row0_col6, #T_60bd6_row3_col0, #T_60bd6_row3_col1, #T_60bd6_row3_col2, #T_60bd6_row3_col3, #T_60bd6_row3_col4, #T_60bd6_row3_col5, #T_60bd6_row3_col6 {
  background-color: #f0f0f0;
  border-bottom: 1px solid #ccc;
}
#T_60bd6_row1_col0, #T_60bd6_row1_col1, #T_60bd6_row1_col2, #T_60bd6_row1_col3, #T_60bd6_row1_col4, #T_60bd6_row1_col5, #T_60bd6_row1_col6 {
  background-color: #ffffff;
  border-bottom: 1px solid #ccc;
}
#T_60bd6_row2_col0, #T_60bd6_row2_col1, #T_60bd6_row2_col2, #T_60bd6_row2_col3, #T_60bd6_row2_col4, #T_60bd6_row2_col5, #T_60bd6_row2_col6 {
  background-color: #f0f0f0;
  border-bottom: none;
}
</style>
<table id="T_60bd6">
  <thead>
    <tr>
      <th id="T_60bd6_level0_col0" class="col_heading level0 col0" >Term</th>
      <th id="T_60bd6_level0_col1" class="col_heading level0 col1" >Crse</th>
      <th id="T_60bd6_level0_col2" class="col_heading level0 col2" >Sect</th>
      <th id="T_60bd6_level0_col3" class="col_heading level0 col3" >Crse Title</th>
      <th id="T_60bd6_level0_col4" class="col_heading level0 col4" >W.Type</th>
      <th id="T_60bd6_level0_col5" class="col_heading level0 col5" >Stdnts</th>
      <th id="T_60bd6_level0_col6" class="col_heading level0 col6" >Hours</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_60bd6_row0_col0" class="data row0 col0" >Spring 2025</td>
      <td id="T_60bd6_row0_col1" class="data row0 col1" >CLSE312</td>
      <td id="T_60bd6_row0_col2" class="data row0 col2" >001</td>
      <td id="T_60bd6_row0_col3" class="data row0 col3" >CHEMICAL REACTION ENGINEERING</td>
      <td id="T_60bd6_row0_col4" class="data row0 col4" >LEC</td>
      <td id="T_60bd6_row0_col5" class="data row0 col5" >31</td>
      <td id="T_60bd6_row0_col6" class="data row0 col6" >93</td>
    </tr>
    <tr>
      <td id="T_60bd6_row1_col0" class="data row1 col0" >Fall 2024</td>
      <td id="T_60bd6_row1_col1" class="data row1 col1" >ENGR492</td>
      <td id="T_60bd6_row1_col2" class="data row1 col2" >010</td>
      <td id="T_60bd6_row1_col3" class="data row1 col3" >INDEPENDENT STUDY IN ENGINRNG</td>
      <td id="T_60bd6_row1_col4" class="data row1 col4" >IND</td>
      <td id="T_60bd6_row1_col5" class="data row1 col5" >4</td>
      <td id="T_60bd6_row1_col6" class="data row1 col6" >12</td>
    </tr>
    <tr>
      <td id="T_60bd6_row2_col0" class="data row2 col0" >Spring 2025</td>
      <td id="T_60bd6_row2_col1" class="data row2 col1" >ENGR492</td>
      <td id="T_60bd6_row2_col2" class="data row2 col2" >011</td>
      <td id="T_60bd6_row2_col3" class="data row2 col3" >INDEPENDENT STUDY IN ENGINRNG</td>
      <td id="T_60bd6_row2_col4" class="data row2 col4" >IND</td>
      <td id="T_60bd6_row2_col5" class="data row2 col5" >2</td>
      <td id="T_60bd6_row2_col6" class="data row2 col6" >6</td>
    </tr>
    <tr>
      <td id="T_60bd6_row3_col0" class="data row3 col0" >Spring 2025</td>
      <td id="T_60bd6_row3_col1" class="data row3 col1" >ENGR591</td>
      <td id="T_60bd6_row3_col2" class="data row3 col2" >004</td>
      <td id="T_60bd6_row3_col3" class="data row3 col3" >ST: ENVIRONMENTAL NASA</td>
      <td id="T_60bd6_row3_col4" class="data row3 col4" >LEC</td>
      <td id="T_60bd6_row3_col5" class="data row3 col5" >3</td>
      <td id="T_60bd6_row3_col6" class="data row3 col6" >9</td>
    </tr>
  </tbody>
</table>



# AY23-24

This section list instructor activity for the academic year AY23-24 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## Stephen Fong

<style type="text/css">
#T_8d0e0_row0_col0, #T_8d0e0_row0_col1, #T_8d0e0_row0_col2, #T_8d0e0_row0_col3, #T_8d0e0_row0_col4, #T_8d0e0_row0_col5, #T_8d0e0_row0_col6, #T_8d0e0_row4_col0, #T_8d0e0_row4_col1, #T_8d0e0_row4_col2, #T_8d0e0_row4_col3, #T_8d0e0_row4_col4, #T_8d0e0_row4_col5, #T_8d0e0_row4_col6, #T_8d0e0_row5_col0, #T_8d0e0_row5_col1, #T_8d0e0_row5_col2, #T_8d0e0_row5_col3, #T_8d0e0_row5_col4, #T_8d0e0_row5_col5, #T_8d0e0_row5_col6 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_8d0e0_row1_col0, #T_8d0e0_row1_col1, #T_8d0e0_row1_col2, #T_8d0e0_row1_col3, #T_8d0e0_row1_col4, #T_8d0e0_row1_col5, #T_8d0e0_row1_col6, #T_8d0e0_row6_col0, #T_8d0e0_row6_col1, #T_8d0e0_row6_col2, #T_8d0e0_row6_col3, #T_8d0e0_row6_col4, #T_8d0e0_row6_col5, #T_8d0e0_row6_col6 {
  background-color: #f0f0f0;
  border-bottom: 1px solid #ccc;
}
#T_8d0e0_row2_col0, #T_8d0e0_row2_col1, #T_8d0e0_row2_col2, #T_8d0e0_row2_col3, #T_8d0e0_row2_col4, #T_8d0e0_row2_col5, #T_8d0e0_row2_col6 {
  background-color: #ffffff;
  border-bottom: none;
}
#T_8d0e0_row3_col0, #T_8d0e0_row3_col1, #T_8d0e0_row3_col2, #T_8d0e0_row3_col3, #T_8d0e0_row3_col4, #T_8d0e0_row3_col5, #T_8d0e0_row3_col6 {
  background-color: #ffffff;
  border-bottom: 1px solid #ccc;
}
</style>
<table id="T_8d0e0">
  <thead>
    <tr>
      <th id="T_8d0e0_level0_col0" class="col_heading level0 col0" >Term</th>
      <th id="T_8d0e0_level0_col1" class="col_heading level0 col1" >Crse</th>
      <th id="T_8d0e0_level0_col2" class="col_heading level0 col2" >Sect</th>
      <th id="T_8d0e0_level0_col3" class="col_heading level0 col3" >Crse Title</th>
      <th id="T_8d0e0_level0_col4" class="col_heading level0 col4" >W.Type</th>
      <th id="T_8d0e0_level0_col5" class="col_heading level0 col5" >Stdnts</th>
      <th id="T_8d0e0_level0_col6" class="col_heading level0 col6" >Hours</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_8d0e0_row0_col0" class="data row0 col0" >Spring 2024</td>
      <td id="T_8d0e0_row0_col1" class="data row0 col1" >CLSE312</td>
      <td id="T_8d0e0_row0_col2" class="data row0 col2" >001</td>
      <td id="T_8d0e0_row0_col3" class="data row0 col3" >CHEMICAL REACTION ENGINEERING</td>
      <td id="T_8d0e0_row0_col4" class="data row0 col4" >LEC</td>
      <td id="T_8d0e0_row0_col5" class="data row0 col5" >36</td>
      <td id="T_8d0e0_row0_col6" class="data row0 col6" >108</td>
    </tr>
    <tr>
      <td id="T_8d0e0_row1_col0" class="data row1 col0" >Spring 2024</td>
      <td id="T_8d0e0_row1_col1" class="data row1 col1" >CLSE403</td>
      <td id="T_8d0e0_row1_col2" class="data row1 col2" >L03</td>
      <td id="T_8d0e0_row1_col3" class="data row1 col3" >SENIOR DESIGN STUDIO</td>
      <td id="T_8d0e0_row1_col4" class="data row1 col4" >LAB</td>
      <td id="T_8d0e0_row1_col5" class="data row1 col5" >4</td>
      <td id="T_8d0e0_row1_col6" class="data row1 col6" >8</td>
    </tr>
    <tr>
      <td id="T_8d0e0_row2_col0" class="data row2 col0" >Fall 2023</td>
      <td id="T_8d0e0_row2_col1" class="data row2 col1" >ENGR497</td>
      <td id="T_8d0e0_row2_col2" class="data row2 col2" >L15</td>
      <td id="T_8d0e0_row2_col3" class="data row2 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_8d0e0_row2_col4" class="data row2 col4" >VIP</td>
      <td id="T_8d0e0_row2_col5" class="data row2 col5" >2</td>
      <td id="T_8d0e0_row2_col6" class="data row2 col6" >4</td>
    </tr>
    <tr>
      <td id="T_8d0e0_row3_col0" class="data row3 col0" >Fall 2023</td>
      <td id="T_8d0e0_row3_col1" class="data row3 col1" >ENGR497</td>
      <td id="T_8d0e0_row3_col2" class="data row3 col2" >L16</td>
      <td id="T_8d0e0_row3_col3" class="data row3 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_8d0e0_row3_col4" class="data row3 col4" >VIP</td>
      <td id="T_8d0e0_row3_col5" class="data row3 col5" >3</td>
      <td id="T_8d0e0_row3_col6" class="data row3 col6" >3</td>
    </tr>
    <tr>
      <td id="T_8d0e0_row4_col0" class="data row4 col0" >Spring 2024</td>
      <td id="T_8d0e0_row4_col1" class="data row4 col1" >ENGR492</td>
      <td id="T_8d0e0_row4_col2" class="data row4 col2" >004</td>
      <td id="T_8d0e0_row4_col3" class="data row4 col3" >INDEPENDENT STUDY IN ENGINRNG</td>
      <td id="T_8d0e0_row4_col4" class="data row4 col4" >IND</td>
      <td id="T_8d0e0_row4_col5" class="data row4 col5" >1</td>
      <td id="T_8d0e0_row4_col6" class="data row4 col6" >3</td>
    </tr>
    <tr>
      <td id="T_8d0e0_row5_col0" class="data row5 col0" >Spring 2024</td>
      <td id="T_8d0e0_row5_col1" class="data row5 col1" >ENGR497</td>
      <td id="T_8d0e0_row5_col2" class="data row5 col2" >L15</td>
      <td id="T_8d0e0_row5_col3" class="data row5 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_8d0e0_row5_col4" class="data row5 col4" >VIP</td>
      <td id="T_8d0e0_row5_col5" class="data row5 col5" >2</td>
      <td id="T_8d0e0_row5_col6" class="data row5 col6" >2</td>
    </tr>
    <tr>
      <td id="T_8d0e0_row6_col0" class="data row6 col0" >Spring 2024</td>
      <td id="T_8d0e0_row6_col1" class="data row6 col1" >ENGR497</td>
      <td id="T_8d0e0_row6_col2" class="data row6 col2" >L16</td>
      <td id="T_8d0e0_row6_col3" class="data row6 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_8d0e0_row6_col4" class="data row6 col4" >VIP</td>
      <td id="T_8d0e0_row6_col5" class="data row6 col5" >2</td>
      <td id="T_8d0e0_row6_col6" class="data row6 col6" >4</td>
    </tr>
  </tbody>
</table>



# AY22-23

This section list instructor activity for the academic year AY22-23 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## Stephen Fong

<style type="text/css">
#T_3e55c_row0_col0, #T_3e55c_row0_col1, #T_3e55c_row0_col2, #T_3e55c_row0_col3, #T_3e55c_row0_col4, #T_3e55c_row0_col5, #T_3e55c_row0_col6, #T_3e55c_row3_col0, #T_3e55c_row3_col1, #T_3e55c_row3_col2, #T_3e55c_row3_col3, #T_3e55c_row3_col4, #T_3e55c_row3_col5, #T_3e55c_row3_col6 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_3e55c_row1_col0, #T_3e55c_row1_col1, #T_3e55c_row1_col2, #T_3e55c_row1_col3, #T_3e55c_row1_col4, #T_3e55c_row1_col5, #T_3e55c_row1_col6, #T_3e55c_row4_col0, #T_3e55c_row4_col1, #T_3e55c_row4_col2, #T_3e55c_row4_col3, #T_3e55c_row4_col4, #T_3e55c_row4_col5, #T_3e55c_row4_col6 {
  background-color: #f0f0f0;
  border-bottom: 1px solid #ccc;
}
#T_3e55c_row2_col0, #T_3e55c_row2_col1, #T_3e55c_row2_col2, #T_3e55c_row2_col3, #T_3e55c_row2_col4, #T_3e55c_row2_col5, #T_3e55c_row2_col6 {
  background-color: #ffffff;
  border-bottom: 1px solid #ccc;
}
</style>
<table id="T_3e55c">
  <thead>
    <tr>
      <th id="T_3e55c_level0_col0" class="col_heading level0 col0" >Term</th>
      <th id="T_3e55c_level0_col1" class="col_heading level0 col1" >Crse</th>
      <th id="T_3e55c_level0_col2" class="col_heading level0 col2" >Sect</th>
      <th id="T_3e55c_level0_col3" class="col_heading level0 col3" >Crse Title</th>
      <th id="T_3e55c_level0_col4" class="col_heading level0 col4" >W.Type</th>
      <th id="T_3e55c_level0_col5" class="col_heading level0 col5" >Stdnts</th>
      <th id="T_3e55c_level0_col6" class="col_heading level0 col6" >Hours</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_3e55c_row0_col0" class="data row0 col0" >Spring 2023</td>
      <td id="T_3e55c_row0_col1" class="data row0 col1" >CLSE312</td>
      <td id="T_3e55c_row0_col2" class="data row0 col2" >001</td>
      <td id="T_3e55c_row0_col3" class="data row0 col3" >CHEMICAL REACTION ENGINEERING</td>
      <td id="T_3e55c_row0_col4" class="data row0 col4" >LEC</td>
      <td id="T_3e55c_row0_col5" class="data row0 col5" >31</td>
      <td id="T_3e55c_row0_col6" class="data row0 col6" >93</td>
    </tr>
    <tr>
      <td id="T_3e55c_row1_col0" class="data row1 col0" >Spring 2023</td>
      <td id="T_3e55c_row1_col1" class="data row1 col1" >CLSE450</td>
      <td id="T_3e55c_row1_col2" class="data row1 col2" >043</td>
      <td id="T_3e55c_row1_col3" class="data row1 col3" >UG RSRCH IN CHEM/LFSC ENGRNG</td>
      <td id="T_3e55c_row1_col4" class="data row1 col4" >LAB</td>
      <td id="T_3e55c_row1_col5" class="data row1 col5" >1</td>
      <td id="T_3e55c_row1_col6" class="data row1 col6" >3</td>
    </tr>
    <tr>
      <td id="T_3e55c_row2_col0" class="data row2 col0" >Fall 2022</td>
      <td id="T_3e55c_row2_col1" class="data row2 col1" >ENGR497</td>
      <td id="T_3e55c_row2_col2" class="data row2 col2" >L15</td>
      <td id="T_3e55c_row2_col3" class="data row2 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_3e55c_row2_col4" class="data row2 col4" >VIP</td>
      <td id="T_3e55c_row2_col5" class="data row2 col5" >4</td>
      <td id="T_3e55c_row2_col6" class="data row2 col6" >8</td>
    </tr>
    <tr>
      <td id="T_3e55c_row3_col0" class="data row3 col0" >Spring 2023</td>
      <td id="T_3e55c_row3_col1" class="data row3 col1" >ENGR497</td>
      <td id="T_3e55c_row3_col2" class="data row3 col2" >L15</td>
      <td id="T_3e55c_row3_col3" class="data row3 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_3e55c_row3_col4" class="data row3 col4" >VIP</td>
      <td id="T_3e55c_row3_col5" class="data row3 col5" >2</td>
      <td id="T_3e55c_row3_col6" class="data row3 col6" >2</td>
    </tr>
    <tr>
      <td id="T_3e55c_row4_col0" class="data row4 col0" >Spring 2023</td>
      <td id="T_3e55c_row4_col1" class="data row4 col1" >ENGR497</td>
      <td id="T_3e55c_row4_col2" class="data row4 col2" >L16</td>
      <td id="T_3e55c_row4_col3" class="data row4 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_3e55c_row4_col4" class="data row4 col4" >VIP</td>
      <td id="T_3e55c_row4_col5" class="data row4 col5" >3</td>
      <td id="T_3e55c_row4_col6" class="data row4 col6" >6</td>
    </tr>
  </tbody>
</table>



# AY21-22

This section list instructor activity for the academic year AY21-22 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## Stephen Fong

<style type="text/css">
#T_ae62d_row0_col0, #T_ae62d_row0_col1, #T_ae62d_row0_col2, #T_ae62d_row0_col3, #T_ae62d_row0_col4, #T_ae62d_row0_col5, #T_ae62d_row0_col6, #T_ae62d_row4_col0, #T_ae62d_row4_col1, #T_ae62d_row4_col2, #T_ae62d_row4_col3, #T_ae62d_row4_col4, #T_ae62d_row4_col5, #T_ae62d_row4_col6 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_ae62d_row1_col0, #T_ae62d_row1_col1, #T_ae62d_row1_col2, #T_ae62d_row1_col3, #T_ae62d_row1_col4, #T_ae62d_row1_col5, #T_ae62d_row1_col6, #T_ae62d_row5_col0, #T_ae62d_row5_col1, #T_ae62d_row5_col2, #T_ae62d_row5_col3, #T_ae62d_row5_col4, #T_ae62d_row5_col5, #T_ae62d_row5_col6 {
  background-color: #f0f0f0;
  border-bottom: 1px solid #ccc;
}
#T_ae62d_row2_col0, #T_ae62d_row2_col1, #T_ae62d_row2_col2, #T_ae62d_row2_col3, #T_ae62d_row2_col4, #T_ae62d_row2_col5, #T_ae62d_row2_col6 {
  background-color: #ffffff;
  border-bottom: none;
}
#T_ae62d_row3_col0, #T_ae62d_row3_col1, #T_ae62d_row3_col2, #T_ae62d_row3_col3, #T_ae62d_row3_col4, #T_ae62d_row3_col5, #T_ae62d_row3_col6 {
  background-color: #ffffff;
  border-bottom: 1px solid #ccc;
}
</style>
<table id="T_ae62d">
  <thead>
    <tr>
      <th id="T_ae62d_level0_col0" class="col_heading level0 col0" >Term</th>
      <th id="T_ae62d_level0_col1" class="col_heading level0 col1" >Crse</th>
      <th id="T_ae62d_level0_col2" class="col_heading level0 col2" >Sect</th>
      <th id="T_ae62d_level0_col3" class="col_heading level0 col3" >Crse Title</th>
      <th id="T_ae62d_level0_col4" class="col_heading level0 col4" >W.Type</th>
      <th id="T_ae62d_level0_col5" class="col_heading level0 col5" >Stdnts</th>
      <th id="T_ae62d_level0_col6" class="col_heading level0 col6" >Hours</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_ae62d_row0_col0" class="data row0 col0" >Spring 2022</td>
      <td id="T_ae62d_row0_col1" class="data row0 col1" >CLSE312</td>
      <td id="T_ae62d_row0_col2" class="data row0 col2" >001</td>
      <td id="T_ae62d_row0_col3" class="data row0 col3" >CHEMICAL REACTION ENGINEERING</td>
      <td id="T_ae62d_row0_col4" class="data row0 col4" >LEC</td>
      <td id="T_ae62d_row0_col5" class="data row0 col5" >48</td>
      <td id="T_ae62d_row0_col6" class="data row0 col6" >144</td>
    </tr>
    <tr>
      <td id="T_ae62d_row1_col0" class="data row1 col0" >Spring 2022</td>
      <td id="T_ae62d_row1_col1" class="data row1 col1" >CLSE403</td>
      <td id="T_ae62d_row1_col2" class="data row1 col2" >L21</td>
      <td id="T_ae62d_row1_col3" class="data row1 col3" >SENIOR DESIGN STUDIO</td>
      <td id="T_ae62d_row1_col4" class="data row1 col4" >LAB</td>
      <td id="T_ae62d_row1_col5" class="data row1 col5" >6</td>
      <td id="T_ae62d_row1_col6" class="data row1 col6" >12</td>
    </tr>
    <tr>
      <td id="T_ae62d_row2_col0" class="data row2 col0" >Fall 2021</td>
      <td id="T_ae62d_row2_col1" class="data row2 col1" >ENGR497</td>
      <td id="T_ae62d_row2_col2" class="data row2 col2" >L15</td>
      <td id="T_ae62d_row2_col3" class="data row2 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_ae62d_row2_col4" class="data row2 col4" >VIP</td>
      <td id="T_ae62d_row2_col5" class="data row2 col5" >12</td>
      <td id="T_ae62d_row2_col6" class="data row2 col6" >24</td>
    </tr>
    <tr>
      <td id="T_ae62d_row3_col0" class="data row3 col0" >Fall 2021</td>
      <td id="T_ae62d_row3_col1" class="data row3 col1" >ENGR497</td>
      <td id="T_ae62d_row3_col2" class="data row3 col2" >L16</td>
      <td id="T_ae62d_row3_col3" class="data row3 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_ae62d_row3_col4" class="data row3 col4" >VIP</td>
      <td id="T_ae62d_row3_col5" class="data row3 col5" >1</td>
      <td id="T_ae62d_row3_col6" class="data row3 col6" >1</td>
    </tr>
    <tr>
      <td id="T_ae62d_row4_col0" class="data row4 col0" >Spring 2022</td>
      <td id="T_ae62d_row4_col1" class="data row4 col1" >ENGR497</td>
      <td id="T_ae62d_row4_col2" class="data row4 col2" >L15</td>
      <td id="T_ae62d_row4_col3" class="data row4 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_ae62d_row4_col4" class="data row4 col4" >VIP</td>
      <td id="T_ae62d_row4_col5" class="data row4 col5" >3</td>
      <td id="T_ae62d_row4_col6" class="data row4 col6" >3</td>
    </tr>
    <tr>
      <td id="T_ae62d_row5_col0" class="data row5 col0" >Spring 2022</td>
      <td id="T_ae62d_row5_col1" class="data row5 col1" >ENGR497</td>
      <td id="T_ae62d_row5_col2" class="data row5 col2" >L16</td>
      <td id="T_ae62d_row5_col3" class="data row5 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_ae62d_row5_col4" class="data row5 col4" >VIP</td>
      <td id="T_ae62d_row5_col5" class="data row5 col5" >8</td>
      <td id="T_ae62d_row5_col6" class="data row5 col6" >16</td>
    </tr>
  </tbody>
</table>



# AY20-21

This section list instructor activity for the academic year AY20-21 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## Stephen Fong

<style type="text/css">
#T_75b66_row0_col0, #T_75b66_row0_col1, #T_75b66_row0_col2, #T_75b66_row0_col3, #T_75b66_row0_col4, #T_75b66_row0_col5, #T_75b66_row0_col6, #T_75b66_row4_col0, #T_75b66_row4_col1, #T_75b66_row4_col2, #T_75b66_row4_col3, #T_75b66_row4_col4, #T_75b66_row4_col5, #T_75b66_row4_col6 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_75b66_row1_col0, #T_75b66_row1_col1, #T_75b66_row1_col2, #T_75b66_row1_col3, #T_75b66_row1_col4, #T_75b66_row1_col5, #T_75b66_row1_col6, #T_75b66_row5_col0, #T_75b66_row5_col1, #T_75b66_row5_col2, #T_75b66_row5_col3, #T_75b66_row5_col4, #T_75b66_row5_col5, #T_75b66_row5_col6 {
  background-color: #f0f0f0;
  border-bottom: 1px solid #ccc;
}
#T_75b66_row2_col0, #T_75b66_row2_col1, #T_75b66_row2_col2, #T_75b66_row2_col3, #T_75b66_row2_col4, #T_75b66_row2_col5, #T_75b66_row2_col6 {
  background-color: #ffffff;
  border-bottom: none;
}
#T_75b66_row3_col0, #T_75b66_row3_col1, #T_75b66_row3_col2, #T_75b66_row3_col3, #T_75b66_row3_col4, #T_75b66_row3_col5, #T_75b66_row3_col6 {
  background-color: #ffffff;
  border-bottom: 1px solid #ccc;
}
</style>
<table id="T_75b66">
  <thead>
    <tr>
      <th id="T_75b66_level0_col0" class="col_heading level0 col0" >Term</th>
      <th id="T_75b66_level0_col1" class="col_heading level0 col1" >Crse</th>
      <th id="T_75b66_level0_col2" class="col_heading level0 col2" >Sect</th>
      <th id="T_75b66_level0_col3" class="col_heading level0 col3" >Crse Title</th>
      <th id="T_75b66_level0_col4" class="col_heading level0 col4" >W.Type</th>
      <th id="T_75b66_level0_col5" class="col_heading level0 col5" >Stdnts</th>
      <th id="T_75b66_level0_col6" class="col_heading level0 col6" >Hours</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_75b66_row0_col0" class="data row0 col0" >Spring 2021</td>
      <td id="T_75b66_row0_col1" class="data row0 col1" >CLSE312</td>
      <td id="T_75b66_row0_col2" class="data row0 col2" >001</td>
      <td id="T_75b66_row0_col3" class="data row0 col3" >CHEMICAL REACTION ENGINEERING</td>
      <td id="T_75b66_row0_col4" class="data row0 col4" >LEC</td>
      <td id="T_75b66_row0_col5" class="data row0 col5" >16</td>
      <td id="T_75b66_row0_col6" class="data row0 col6" >48</td>
    </tr>
    <tr>
      <td id="T_75b66_row1_col0" class="data row1 col0" >Spring 2021</td>
      <td id="T_75b66_row1_col1" class="data row1 col1" >CLSE312</td>
      <td id="T_75b66_row1_col2" class="data row1 col2" >002</td>
      <td id="T_75b66_row1_col3" class="data row1 col3" >CHEMICAL REACTION ENGINEERING</td>
      <td id="T_75b66_row1_col4" class="data row1 col4" >LEC</td>
      <td id="T_75b66_row1_col5" class="data row1 col5" >41</td>
      <td id="T_75b66_row1_col6" class="data row1 col6" >123</td>
    </tr>
    <tr>
      <td id="T_75b66_row2_col0" class="data row2 col0" >Fall 2020</td>
      <td id="T_75b66_row2_col1" class="data row2 col1" >ENGR497</td>
      <td id="T_75b66_row2_col2" class="data row2 col2" >L15</td>
      <td id="T_75b66_row2_col3" class="data row2 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_75b66_row2_col4" class="data row2 col4" >VIP</td>
      <td id="T_75b66_row2_col5" class="data row2 col5" >4</td>
      <td id="T_75b66_row2_col6" class="data row2 col6" >8</td>
    </tr>
    <tr>
      <td id="T_75b66_row3_col0" class="data row3 col0" >Fall 2020</td>
      <td id="T_75b66_row3_col1" class="data row3 col1" >ENGR497</td>
      <td id="T_75b66_row3_col2" class="data row3 col2" >L16</td>
      <td id="T_75b66_row3_col3" class="data row3 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_75b66_row3_col4" class="data row3 col4" >VIP</td>
      <td id="T_75b66_row3_col5" class="data row3 col5" >2</td>
      <td id="T_75b66_row3_col6" class="data row3 col6" >2</td>
    </tr>
    <tr>
      <td id="T_75b66_row4_col0" class="data row4 col0" >Spring 2021</td>
      <td id="T_75b66_row4_col1" class="data row4 col1" >ENGR497</td>
      <td id="T_75b66_row4_col2" class="data row4 col2" >L15</td>
      <td id="T_75b66_row4_col3" class="data row4 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_75b66_row4_col4" class="data row4 col4" >VIP</td>
      <td id="T_75b66_row4_col5" class="data row4 col5" >3</td>
      <td id="T_75b66_row4_col6" class="data row4 col6" >3</td>
    </tr>
    <tr>
      <td id="T_75b66_row5_col0" class="data row5 col0" >Spring 2021</td>
      <td id="T_75b66_row5_col1" class="data row5 col1" >ENGR497</td>
      <td id="T_75b66_row5_col2" class="data row5 col2" >L16</td>
      <td id="T_75b66_row5_col3" class="data row5 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_75b66_row5_col4" class="data row5 col4" >VIP</td>
      <td id="T_75b66_row5_col5" class="data row5 col5" >6</td>
      <td id="T_75b66_row5_col6" class="data row5 col6" >12</td>
    </tr>
  </tbody>
</table>



# All Instructors


## Stephen Fong

<style type="text/css">
#T_d8ef4_row0_col0, #T_d8ef4_row0_col1, #T_d8ef4_row0_col2, #T_d8ef4_row0_col3, #T_d8ef4_row0_col4, #T_d8ef4_row0_col5, #T_d8ef4_row0_col6, #T_d8ef4_row4_col0, #T_d8ef4_row4_col1, #T_d8ef4_row4_col2, #T_d8ef4_row4_col3, #T_d8ef4_row4_col4, #T_d8ef4_row4_col5, #T_d8ef4_row4_col6, #T_d8ef4_row11_col0, #T_d8ef4_row11_col1, #T_d8ef4_row11_col2, #T_d8ef4_row11_col3, #T_d8ef4_row11_col4, #T_d8ef4_row11_col5, #T_d8ef4_row11_col6, #T_d8ef4_row13_col0, #T_d8ef4_row13_col1, #T_d8ef4_row13_col2, #T_d8ef4_row13_col3, #T_d8ef4_row13_col4, #T_d8ef4_row13_col5, #T_d8ef4_row13_col6, #T_d8ef4_row18_col0, #T_d8ef4_row18_col1, #T_d8ef4_row18_col2, #T_d8ef4_row18_col3, #T_d8ef4_row18_col4, #T_d8ef4_row18_col5, #T_d8ef4_row18_col6, #T_d8ef4_row20_col0, #T_d8ef4_row20_col1, #T_d8ef4_row20_col2, #T_d8ef4_row20_col3, #T_d8ef4_row20_col4, #T_d8ef4_row20_col5, #T_d8ef4_row20_col6, #T_d8ef4_row26_col0, #T_d8ef4_row26_col1, #T_d8ef4_row26_col2, #T_d8ef4_row26_col3, #T_d8ef4_row26_col4, #T_d8ef4_row26_col5, #T_d8ef4_row26_col6 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_d8ef4_row1_col0, #T_d8ef4_row1_col1, #T_d8ef4_row1_col2, #T_d8ef4_row1_col3, #T_d8ef4_row1_col4, #T_d8ef4_row1_col5, #T_d8ef4_row1_col6, #T_d8ef4_row5_col0, #T_d8ef4_row5_col1, #T_d8ef4_row5_col2, #T_d8ef4_row5_col3, #T_d8ef4_row5_col4, #T_d8ef4_row5_col5, #T_d8ef4_row5_col6, #T_d8ef4_row8_col0, #T_d8ef4_row8_col1, #T_d8ef4_row8_col2, #T_d8ef4_row8_col3, #T_d8ef4_row8_col4, #T_d8ef4_row8_col5, #T_d8ef4_row8_col6, #T_d8ef4_row12_col0, #T_d8ef4_row12_col1, #T_d8ef4_row12_col2, #T_d8ef4_row12_col3, #T_d8ef4_row12_col4, #T_d8ef4_row12_col5, #T_d8ef4_row12_col6, #T_d8ef4_row14_col0, #T_d8ef4_row14_col1, #T_d8ef4_row14_col2, #T_d8ef4_row14_col3, #T_d8ef4_row14_col4, #T_d8ef4_row14_col5, #T_d8ef4_row14_col6, #T_d8ef4_row19_col0, #T_d8ef4_row19_col1, #T_d8ef4_row19_col2, #T_d8ef4_row19_col3, #T_d8ef4_row19_col4, #T_d8ef4_row19_col5, #T_d8ef4_row19_col6, #T_d8ef4_row21_col0, #T_d8ef4_row21_col1, #T_d8ef4_row21_col2, #T_d8ef4_row21_col3, #T_d8ef4_row21_col4, #T_d8ef4_row21_col5, #T_d8ef4_row21_col6, #T_d8ef4_row27_col0, #T_d8ef4_row27_col1, #T_d8ef4_row27_col2, #T_d8ef4_row27_col3, #T_d8ef4_row27_col4, #T_d8ef4_row27_col5, #T_d8ef4_row27_col6, #T_d8ef4_row28_col0, #T_d8ef4_row28_col1, #T_d8ef4_row28_col2, #T_d8ef4_row28_col3, #T_d8ef4_row28_col4, #T_d8ef4_row28_col5, #T_d8ef4_row28_col6 {
  background-color: #f0f0f0;
  border-bottom: 1px solid #ccc;
}
#T_d8ef4_row2_col0, #T_d8ef4_row2_col1, #T_d8ef4_row2_col2, #T_d8ef4_row2_col3, #T_d8ef4_row2_col4, #T_d8ef4_row2_col5, #T_d8ef4_row2_col6, #T_d8ef4_row6_col0, #T_d8ef4_row6_col1, #T_d8ef4_row6_col2, #T_d8ef4_row6_col3, #T_d8ef4_row6_col4, #T_d8ef4_row6_col5, #T_d8ef4_row6_col6, #T_d8ef4_row9_col0, #T_d8ef4_row9_col1, #T_d8ef4_row9_col2, #T_d8ef4_row9_col3, #T_d8ef4_row9_col4, #T_d8ef4_row9_col5, #T_d8ef4_row9_col6, #T_d8ef4_row15_col0, #T_d8ef4_row15_col1, #T_d8ef4_row15_col2, #T_d8ef4_row15_col3, #T_d8ef4_row15_col4, #T_d8ef4_row15_col5, #T_d8ef4_row15_col6, #T_d8ef4_row22_col0, #T_d8ef4_row22_col1, #T_d8ef4_row22_col2, #T_d8ef4_row22_col3, #T_d8ef4_row22_col4, #T_d8ef4_row22_col5, #T_d8ef4_row22_col6, #T_d8ef4_row23_col0, #T_d8ef4_row23_col1, #T_d8ef4_row23_col2, #T_d8ef4_row23_col3, #T_d8ef4_row23_col4, #T_d8ef4_row23_col5, #T_d8ef4_row23_col6 {
  background-color: #ffffff;
  border-bottom: none;
}
#T_d8ef4_row3_col0, #T_d8ef4_row3_col1, #T_d8ef4_row3_col2, #T_d8ef4_row3_col3, #T_d8ef4_row3_col4, #T_d8ef4_row3_col5, #T_d8ef4_row3_col6, #T_d8ef4_row7_col0, #T_d8ef4_row7_col1, #T_d8ef4_row7_col2, #T_d8ef4_row7_col3, #T_d8ef4_row7_col4, #T_d8ef4_row7_col5, #T_d8ef4_row7_col6, #T_d8ef4_row10_col0, #T_d8ef4_row10_col1, #T_d8ef4_row10_col2, #T_d8ef4_row10_col3, #T_d8ef4_row10_col4, #T_d8ef4_row10_col5, #T_d8ef4_row10_col6, #T_d8ef4_row16_col0, #T_d8ef4_row16_col1, #T_d8ef4_row16_col2, #T_d8ef4_row16_col3, #T_d8ef4_row16_col4, #T_d8ef4_row16_col5, #T_d8ef4_row16_col6, #T_d8ef4_row17_col0, #T_d8ef4_row17_col1, #T_d8ef4_row17_col2, #T_d8ef4_row17_col3, #T_d8ef4_row17_col4, #T_d8ef4_row17_col5, #T_d8ef4_row17_col6, #T_d8ef4_row24_col0, #T_d8ef4_row24_col1, #T_d8ef4_row24_col2, #T_d8ef4_row24_col3, #T_d8ef4_row24_col4, #T_d8ef4_row24_col5, #T_d8ef4_row24_col6, #T_d8ef4_row25_col0, #T_d8ef4_row25_col1, #T_d8ef4_row25_col2, #T_d8ef4_row25_col3, #T_d8ef4_row25_col4, #T_d8ef4_row25_col5, #T_d8ef4_row25_col6 {
  background-color: #ffffff;
  border-bottom: 1px solid #ccc;
}
</style>
<table id="T_d8ef4">
  <thead>
    <tr>
      <th id="T_d8ef4_level0_col0" class="col_heading level0 col0" >Term</th>
      <th id="T_d8ef4_level0_col1" class="col_heading level0 col1" >Crse</th>
      <th id="T_d8ef4_level0_col2" class="col_heading level0 col2" >Sect</th>
      <th id="T_d8ef4_level0_col3" class="col_heading level0 col3" >Crse Title</th>
      <th id="T_d8ef4_level0_col4" class="col_heading level0 col4" >W.Type</th>
      <th id="T_d8ef4_level0_col5" class="col_heading level0 col5" >Stdnts</th>
      <th id="T_d8ef4_level0_col6" class="col_heading level0 col6" >Hours</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_d8ef4_row0_col0" class="data row0 col0" >Spring 2021</td>
      <td id="T_d8ef4_row0_col1" class="data row0 col1" >CLSE312</td>
      <td id="T_d8ef4_row0_col2" class="data row0 col2" >001</td>
      <td id="T_d8ef4_row0_col3" class="data row0 col3" >CHEMICAL REACTION ENGINEERING</td>
      <td id="T_d8ef4_row0_col4" class="data row0 col4" >LEC</td>
      <td id="T_d8ef4_row0_col5" class="data row0 col5" >16</td>
      <td id="T_d8ef4_row0_col6" class="data row0 col6" >48</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row1_col0" class="data row1 col0" >Spring 2021</td>
      <td id="T_d8ef4_row1_col1" class="data row1 col1" >CLSE312</td>
      <td id="T_d8ef4_row1_col2" class="data row1 col2" >002</td>
      <td id="T_d8ef4_row1_col3" class="data row1 col3" >CHEMICAL REACTION ENGINEERING</td>
      <td id="T_d8ef4_row1_col4" class="data row1 col4" >LEC</td>
      <td id="T_d8ef4_row1_col5" class="data row1 col5" >41</td>
      <td id="T_d8ef4_row1_col6" class="data row1 col6" >123</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row2_col0" class="data row2 col0" >Spring 2022</td>
      <td id="T_d8ef4_row2_col1" class="data row2 col1" >CLSE312</td>
      <td id="T_d8ef4_row2_col2" class="data row2 col2" >001</td>
      <td id="T_d8ef4_row2_col3" class="data row2 col3" >CHEMICAL REACTION ENGINEERING</td>
      <td id="T_d8ef4_row2_col4" class="data row2 col4" >LEC</td>
      <td id="T_d8ef4_row2_col5" class="data row2 col5" >48</td>
      <td id="T_d8ef4_row2_col6" class="data row2 col6" >144</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row3_col0" class="data row3 col0" >Spring 2022</td>
      <td id="T_d8ef4_row3_col1" class="data row3 col1" >CLSE403</td>
      <td id="T_d8ef4_row3_col2" class="data row3 col2" >L21</td>
      <td id="T_d8ef4_row3_col3" class="data row3 col3" >SENIOR DESIGN STUDIO</td>
      <td id="T_d8ef4_row3_col4" class="data row3 col4" >LAB</td>
      <td id="T_d8ef4_row3_col5" class="data row3 col5" >6</td>
      <td id="T_d8ef4_row3_col6" class="data row3 col6" >12</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row4_col0" class="data row4 col0" >Spring 2023</td>
      <td id="T_d8ef4_row4_col1" class="data row4 col1" >CLSE312</td>
      <td id="T_d8ef4_row4_col2" class="data row4 col2" >001</td>
      <td id="T_d8ef4_row4_col3" class="data row4 col3" >CHEMICAL REACTION ENGINEERING</td>
      <td id="T_d8ef4_row4_col4" class="data row4 col4" >LEC</td>
      <td id="T_d8ef4_row4_col5" class="data row4 col5" >31</td>
      <td id="T_d8ef4_row4_col6" class="data row4 col6" >93</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row5_col0" class="data row5 col0" >Spring 2023</td>
      <td id="T_d8ef4_row5_col1" class="data row5 col1" >CLSE450</td>
      <td id="T_d8ef4_row5_col2" class="data row5 col2" >043</td>
      <td id="T_d8ef4_row5_col3" class="data row5 col3" >UG RSRCH IN CHEM/LFSC ENGRNG</td>
      <td id="T_d8ef4_row5_col4" class="data row5 col4" >LAB</td>
      <td id="T_d8ef4_row5_col5" class="data row5 col5" >1</td>
      <td id="T_d8ef4_row5_col6" class="data row5 col6" >3</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row6_col0" class="data row6 col0" >Spring 2024</td>
      <td id="T_d8ef4_row6_col1" class="data row6 col1" >CLSE312</td>
      <td id="T_d8ef4_row6_col2" class="data row6 col2" >001</td>
      <td id="T_d8ef4_row6_col3" class="data row6 col3" >CHEMICAL REACTION ENGINEERING</td>
      <td id="T_d8ef4_row6_col4" class="data row6 col4" >LEC</td>
      <td id="T_d8ef4_row6_col5" class="data row6 col5" >36</td>
      <td id="T_d8ef4_row6_col6" class="data row6 col6" >108</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row7_col0" class="data row7 col0" >Spring 2024</td>
      <td id="T_d8ef4_row7_col1" class="data row7 col1" >CLSE403</td>
      <td id="T_d8ef4_row7_col2" class="data row7 col2" >L03</td>
      <td id="T_d8ef4_row7_col3" class="data row7 col3" >SENIOR DESIGN STUDIO</td>
      <td id="T_d8ef4_row7_col4" class="data row7 col4" >LAB</td>
      <td id="T_d8ef4_row7_col5" class="data row7 col5" >4</td>
      <td id="T_d8ef4_row7_col6" class="data row7 col6" >8</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row8_col0" class="data row8 col0" >Spring 2025</td>
      <td id="T_d8ef4_row8_col1" class="data row8 col1" >CLSE312</td>
      <td id="T_d8ef4_row8_col2" class="data row8 col2" >001</td>
      <td id="T_d8ef4_row8_col3" class="data row8 col3" >CHEMICAL REACTION ENGINEERING</td>
      <td id="T_d8ef4_row8_col4" class="data row8 col4" >LEC</td>
      <td id="T_d8ef4_row8_col5" class="data row8 col5" >31</td>
      <td id="T_d8ef4_row8_col6" class="data row8 col6" >93</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row9_col0" class="data row9 col0" >Fall 2020</td>
      <td id="T_d8ef4_row9_col1" class="data row9 col1" >ENGR497</td>
      <td id="T_d8ef4_row9_col2" class="data row9 col2" >L15</td>
      <td id="T_d8ef4_row9_col3" class="data row9 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_d8ef4_row9_col4" class="data row9 col4" >VIP</td>
      <td id="T_d8ef4_row9_col5" class="data row9 col5" >4</td>
      <td id="T_d8ef4_row9_col6" class="data row9 col6" >8</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row10_col0" class="data row10 col0" >Fall 2020</td>
      <td id="T_d8ef4_row10_col1" class="data row10 col1" >ENGR497</td>
      <td id="T_d8ef4_row10_col2" class="data row10 col2" >L16</td>
      <td id="T_d8ef4_row10_col3" class="data row10 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_d8ef4_row10_col4" class="data row10 col4" >VIP</td>
      <td id="T_d8ef4_row10_col5" class="data row10 col5" >2</td>
      <td id="T_d8ef4_row10_col6" class="data row10 col6" >2</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row11_col0" class="data row11 col0" >Spring 2021</td>
      <td id="T_d8ef4_row11_col1" class="data row11 col1" >ENGR497</td>
      <td id="T_d8ef4_row11_col2" class="data row11 col2" >L15</td>
      <td id="T_d8ef4_row11_col3" class="data row11 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_d8ef4_row11_col4" class="data row11 col4" >VIP</td>
      <td id="T_d8ef4_row11_col5" class="data row11 col5" >3</td>
      <td id="T_d8ef4_row11_col6" class="data row11 col6" >3</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row12_col0" class="data row12 col0" >Spring 2021</td>
      <td id="T_d8ef4_row12_col1" class="data row12 col1" >ENGR497</td>
      <td id="T_d8ef4_row12_col2" class="data row12 col2" >L16</td>
      <td id="T_d8ef4_row12_col3" class="data row12 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_d8ef4_row12_col4" class="data row12 col4" >VIP</td>
      <td id="T_d8ef4_row12_col5" class="data row12 col5" >6</td>
      <td id="T_d8ef4_row12_col6" class="data row12 col6" >12</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row13_col0" class="data row13 col0" >Fall 2021</td>
      <td id="T_d8ef4_row13_col1" class="data row13 col1" >ENGR497</td>
      <td id="T_d8ef4_row13_col2" class="data row13 col2" >L15</td>
      <td id="T_d8ef4_row13_col3" class="data row13 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_d8ef4_row13_col4" class="data row13 col4" >VIP</td>
      <td id="T_d8ef4_row13_col5" class="data row13 col5" >12</td>
      <td id="T_d8ef4_row13_col6" class="data row13 col6" >24</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row14_col0" class="data row14 col0" >Fall 2021</td>
      <td id="T_d8ef4_row14_col1" class="data row14 col1" >ENGR497</td>
      <td id="T_d8ef4_row14_col2" class="data row14 col2" >L16</td>
      <td id="T_d8ef4_row14_col3" class="data row14 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_d8ef4_row14_col4" class="data row14 col4" >VIP</td>
      <td id="T_d8ef4_row14_col5" class="data row14 col5" >1</td>
      <td id="T_d8ef4_row14_col6" class="data row14 col6" >1</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row15_col0" class="data row15 col0" >Spring 2022</td>
      <td id="T_d8ef4_row15_col1" class="data row15 col1" >ENGR497</td>
      <td id="T_d8ef4_row15_col2" class="data row15 col2" >L15</td>
      <td id="T_d8ef4_row15_col3" class="data row15 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_d8ef4_row15_col4" class="data row15 col4" >VIP</td>
      <td id="T_d8ef4_row15_col5" class="data row15 col5" >3</td>
      <td id="T_d8ef4_row15_col6" class="data row15 col6" >3</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row16_col0" class="data row16 col0" >Spring 2022</td>
      <td id="T_d8ef4_row16_col1" class="data row16 col1" >ENGR497</td>
      <td id="T_d8ef4_row16_col2" class="data row16 col2" >L16</td>
      <td id="T_d8ef4_row16_col3" class="data row16 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_d8ef4_row16_col4" class="data row16 col4" >VIP</td>
      <td id="T_d8ef4_row16_col5" class="data row16 col5" >8</td>
      <td id="T_d8ef4_row16_col6" class="data row16 col6" >16</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row17_col0" class="data row17 col0" >Fall 2022</td>
      <td id="T_d8ef4_row17_col1" class="data row17 col1" >ENGR497</td>
      <td id="T_d8ef4_row17_col2" class="data row17 col2" >L15</td>
      <td id="T_d8ef4_row17_col3" class="data row17 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_d8ef4_row17_col4" class="data row17 col4" >VIP</td>
      <td id="T_d8ef4_row17_col5" class="data row17 col5" >4</td>
      <td id="T_d8ef4_row17_col6" class="data row17 col6" >8</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row18_col0" class="data row18 col0" >Spring 2023</td>
      <td id="T_d8ef4_row18_col1" class="data row18 col1" >ENGR497</td>
      <td id="T_d8ef4_row18_col2" class="data row18 col2" >L15</td>
      <td id="T_d8ef4_row18_col3" class="data row18 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_d8ef4_row18_col4" class="data row18 col4" >VIP</td>
      <td id="T_d8ef4_row18_col5" class="data row18 col5" >2</td>
      <td id="T_d8ef4_row18_col6" class="data row18 col6" >2</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row19_col0" class="data row19 col0" >Spring 2023</td>
      <td id="T_d8ef4_row19_col1" class="data row19 col1" >ENGR497</td>
      <td id="T_d8ef4_row19_col2" class="data row19 col2" >L16</td>
      <td id="T_d8ef4_row19_col3" class="data row19 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_d8ef4_row19_col4" class="data row19 col4" >VIP</td>
      <td id="T_d8ef4_row19_col5" class="data row19 col5" >3</td>
      <td id="T_d8ef4_row19_col6" class="data row19 col6" >6</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row20_col0" class="data row20 col0" >Fall 2023</td>
      <td id="T_d8ef4_row20_col1" class="data row20 col1" >ENGR497</td>
      <td id="T_d8ef4_row20_col2" class="data row20 col2" >L15</td>
      <td id="T_d8ef4_row20_col3" class="data row20 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_d8ef4_row20_col4" class="data row20 col4" >VIP</td>
      <td id="T_d8ef4_row20_col5" class="data row20 col5" >2</td>
      <td id="T_d8ef4_row20_col6" class="data row20 col6" >4</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row21_col0" class="data row21 col0" >Fall 2023</td>
      <td id="T_d8ef4_row21_col1" class="data row21 col1" >ENGR497</td>
      <td id="T_d8ef4_row21_col2" class="data row21 col2" >L16</td>
      <td id="T_d8ef4_row21_col3" class="data row21 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_d8ef4_row21_col4" class="data row21 col4" >VIP</td>
      <td id="T_d8ef4_row21_col5" class="data row21 col5" >3</td>
      <td id="T_d8ef4_row21_col6" class="data row21 col6" >3</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row22_col0" class="data row22 col0" >Spring 2024</td>
      <td id="T_d8ef4_row22_col1" class="data row22 col1" >ENGR492</td>
      <td id="T_d8ef4_row22_col2" class="data row22 col2" >004</td>
      <td id="T_d8ef4_row22_col3" class="data row22 col3" >INDEPENDENT STUDY IN ENGINRNG</td>
      <td id="T_d8ef4_row22_col4" class="data row22 col4" >IND</td>
      <td id="T_d8ef4_row22_col5" class="data row22 col5" >1</td>
      <td id="T_d8ef4_row22_col6" class="data row22 col6" >3</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row23_col0" class="data row23 col0" >Spring 2024</td>
      <td id="T_d8ef4_row23_col1" class="data row23 col1" >ENGR497</td>
      <td id="T_d8ef4_row23_col2" class="data row23 col2" >L15</td>
      <td id="T_d8ef4_row23_col3" class="data row23 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_d8ef4_row23_col4" class="data row23 col4" >VIP</td>
      <td id="T_d8ef4_row23_col5" class="data row23 col5" >2</td>
      <td id="T_d8ef4_row23_col6" class="data row23 col6" >2</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row24_col0" class="data row24 col0" >Spring 2024</td>
      <td id="T_d8ef4_row24_col1" class="data row24 col1" >ENGR497</td>
      <td id="T_d8ef4_row24_col2" class="data row24 col2" >L16</td>
      <td id="T_d8ef4_row24_col3" class="data row24 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_d8ef4_row24_col4" class="data row24 col4" >VIP</td>
      <td id="T_d8ef4_row24_col5" class="data row24 col5" >2</td>
      <td id="T_d8ef4_row24_col6" class="data row24 col6" >4</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row25_col0" class="data row25 col0" >Fall 2024</td>
      <td id="T_d8ef4_row25_col1" class="data row25 col1" >ENGR492</td>
      <td id="T_d8ef4_row25_col2" class="data row25 col2" >010</td>
      <td id="T_d8ef4_row25_col3" class="data row25 col3" >INDEPENDENT STUDY IN ENGINRNG</td>
      <td id="T_d8ef4_row25_col4" class="data row25 col4" >IND</td>
      <td id="T_d8ef4_row25_col5" class="data row25 col5" >4</td>
      <td id="T_d8ef4_row25_col6" class="data row25 col6" >12</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row26_col0" class="data row26 col0" >Spring 2025</td>
      <td id="T_d8ef4_row26_col1" class="data row26 col1" >ENGR492</td>
      <td id="T_d8ef4_row26_col2" class="data row26 col2" >011</td>
      <td id="T_d8ef4_row26_col3" class="data row26 col3" >INDEPENDENT STUDY IN ENGINRNG</td>
      <td id="T_d8ef4_row26_col4" class="data row26 col4" >IND</td>
      <td id="T_d8ef4_row26_col5" class="data row26 col5" >2</td>
      <td id="T_d8ef4_row26_col6" class="data row26 col6" >6</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row27_col0" class="data row27 col0" >Spring 2025</td>
      <td id="T_d8ef4_row27_col1" class="data row27 col1" >ENGR591</td>
      <td id="T_d8ef4_row27_col2" class="data row27 col2" >004</td>
      <td id="T_d8ef4_row27_col3" class="data row27 col3" >ST: ENVIRONMENTAL NASA</td>
      <td id="T_d8ef4_row27_col4" class="data row27 col4" >LEC</td>
      <td id="T_d8ef4_row27_col5" class="data row27 col5" >3</td>
      <td id="T_d8ef4_row27_col6" class="data row27 col6" >9</td>
    </tr>
    <tr>
      <td id="T_d8ef4_row28_col0" class="data row28 col0" >Fall 2025</td>
      <td id="T_d8ef4_row28_col1" class="data row28 col1" >ENGR492</td>
      <td id="T_d8ef4_row28_col2" class="data row28 col2" >010</td>
      <td id="T_d8ef4_row28_col3" class="data row28 col3" >INDEPENDENT STUDY IN ENGINRNG</td>
      <td id="T_d8ef4_row28_col4" class="data row28 col4" >IND</td>
      <td id="T_d8ef4_row28_col5" class="data row28 col5" >1</td>
      <td id="T_d8ef4_row28_col6" class="data row28 col6" >3</td>
    </tr>
  </tbody>
</table>


