---
title: Department Teaching Activity - Chem & Life Science
date: last-modified
---


# AY24-25

This section list instructor activity for the academic year AY24-25 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## Fall 2024

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_8f923 table {
  width: 100%;
  border-collapse: collapse;
}
#T_8f923 th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_8f923 th {
  border: 0;
}
#T_8f923 thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_8f923 tbody td:nth-child(1) {
  display: none;
}
#T_8f923 thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_8f923 tbody td:nth-child(2) {
  display: none;
}
#T_8f923 thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_8f923 tbody td:nth-child(8) {
  display: none;
}
#T_8f923 td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_8f923 td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_8f923 td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_8f923 td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_8f923 td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_8f923 td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_8f923_row0_col0, #T_8f923_row0_col1, #T_8f923_row0_col2, #T_8f923_row0_col3, #T_8f923_row0_col4, #T_8f923_row0_col5, #T_8f923_row0_col6, #T_8f923_row0_col7, #T_8f923_row0_col8, #T_8f923_row2_col0, #T_8f923_row2_col1, #T_8f923_row2_col2, #T_8f923_row2_col3, #T_8f923_row2_col4, #T_8f923_row2_col5, #T_8f923_row2_col6, #T_8f923_row2_col7, #T_8f923_row2_col8, #T_8f923_row3_col0, #T_8f923_row3_col1, #T_8f923_row3_col2, #T_8f923_row3_col3, #T_8f923_row3_col4, #T_8f923_row3_col5, #T_8f923_row3_col6, #T_8f923_row3_col7, #T_8f923_row3_col8, #T_8f923_row5_col0, #T_8f923_row5_col1, #T_8f923_row5_col2, #T_8f923_row5_col3, #T_8f923_row5_col4, #T_8f923_row5_col5, #T_8f923_row5_col6, #T_8f923_row5_col7, #T_8f923_row5_col8, #T_8f923_row13_col0, #T_8f923_row13_col1, #T_8f923_row13_col2, #T_8f923_row13_col3, #T_8f923_row13_col4, #T_8f923_row13_col5, #T_8f923_row13_col6, #T_8f923_row13_col7, #T_8f923_row13_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_8f923_row1_col0, #T_8f923_row1_col1, #T_8f923_row1_col2, #T_8f923_row1_col3, #T_8f923_row1_col4, #T_8f923_row1_col5, #T_8f923_row1_col6, #T_8f923_row1_col7, #T_8f923_row1_col8, #T_8f923_row4_col0, #T_8f923_row4_col1, #T_8f923_row4_col2, #T_8f923_row4_col3, #T_8f923_row4_col4, #T_8f923_row4_col5, #T_8f923_row4_col6, #T_8f923_row4_col7, #T_8f923_row4_col8, #T_8f923_row6_col0, #T_8f923_row6_col1, #T_8f923_row6_col2, #T_8f923_row6_col3, #T_8f923_row6_col4, #T_8f923_row6_col5, #T_8f923_row6_col6, #T_8f923_row6_col7, #T_8f923_row6_col8, #T_8f923_row7_col0, #T_8f923_row7_col1, #T_8f923_row7_col2, #T_8f923_row7_col3, #T_8f923_row7_col4, #T_8f923_row7_col5, #T_8f923_row7_col6, #T_8f923_row7_col7, #T_8f923_row7_col8, #T_8f923_row8_col0, #T_8f923_row8_col1, #T_8f923_row8_col2, #T_8f923_row8_col3, #T_8f923_row8_col4, #T_8f923_row8_col5, #T_8f923_row8_col6, #T_8f923_row8_col7, #T_8f923_row8_col8, #T_8f923_row9_col0, #T_8f923_row9_col1, #T_8f923_row9_col2, #T_8f923_row9_col3, #T_8f923_row9_col4, #T_8f923_row9_col5, #T_8f923_row9_col6, #T_8f923_row9_col7, #T_8f923_row9_col8, #T_8f923_row10_col0, #T_8f923_row10_col1, #T_8f923_row10_col2, #T_8f923_row10_col3, #T_8f923_row10_col4, #T_8f923_row10_col5, #T_8f923_row10_col6, #T_8f923_row10_col7, #T_8f923_row10_col8, #T_8f923_row11_col0, #T_8f923_row11_col1, #T_8f923_row11_col2, #T_8f923_row11_col3, #T_8f923_row11_col4, #T_8f923_row11_col5, #T_8f923_row11_col6, #T_8f923_row11_col7, #T_8f923_row11_col8, #T_8f923_row12_col0, #T_8f923_row12_col1, #T_8f923_row12_col2, #T_8f923_row12_col3, #T_8f923_row12_col4, #T_8f923_row12_col5, #T_8f923_row12_col6, #T_8f923_row12_col7, #T_8f923_row12_col8, #T_8f923_row14_col0, #T_8f923_row14_col1, #T_8f923_row14_col2, #T_8f923_row14_col3, #T_8f923_row14_col4, #T_8f923_row14_col5, #T_8f923_row14_col6, #T_8f923_row14_col7, #T_8f923_row14_col8, #T_8f923_row15_col0, #T_8f923_row15_col1, #T_8f923_row15_col2, #T_8f923_row15_col3, #T_8f923_row15_col4, #T_8f923_row15_col5, #T_8f923_row15_col6, #T_8f923_row15_col7, #T_8f923_row15_col8, #T_8f923_row16_col0, #T_8f923_row16_col1, #T_8f923_row16_col2, #T_8f923_row16_col3, #T_8f923_row16_col4, #T_8f923_row16_col5, #T_8f923_row16_col6, #T_8f923_row16_col7, #T_8f923_row16_col8, #T_8f923_row17_col0, #T_8f923_row17_col1, #T_8f923_row17_col2, #T_8f923_row17_col3, #T_8f923_row17_col4, #T_8f923_row17_col5, #T_8f923_row17_col6, #T_8f923_row17_col7, #T_8f923_row17_col8, #T_8f923_row18_col0, #T_8f923_row18_col1, #T_8f923_row18_col2, #T_8f923_row18_col3, #T_8f923_row18_col4, #T_8f923_row18_col5, #T_8f923_row18_col6, #T_8f923_row18_col7, #T_8f923_row18_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_8f923">
  <thead>
    <tr>
      <th id="T_8f923_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_8f923_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_8f923_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_8f923_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_8f923_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_8f923_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_8f923_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_8f923_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_8f923_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_8f923_row0_col0" class="data row0 col0" >101</td>
      <td id="T_8f923_row0_col1" class="data row0 col1" >Fall 2024</td>
      <td id="T_8f923_row0_col2" class="data row0 col2" >CLSE101</td>
      <td id="T_8f923_row0_col3" class="data row0 col3" >001</td>
      <td id="T_8f923_row0_col4" class="data row0 col4" >INTRO TO ENGINEERING</td>
      <td id="T_8f923_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_8f923_row0_col6" class="data row0 col6" >30</td>
      <td id="T_8f923_row0_col7" class="data row0 col7" >90</td>
      <td id="T_8f923_row0_col8" class="data row0 col8" >Spangler</td>
    </tr>
    <tr>
      <td id="T_8f923_row1_col0" class="data row1 col0" >201</td>
      <td id="T_8f923_row1_col1" class="data row1 col1" >Fall 2024</td>
      <td id="T_8f923_row1_col2" class="data row1 col2" >CLSE201</td>
      <td id="T_8f923_row1_col3" class="data row1 col3" >901</td>
      <td id="T_8f923_row1_col4" class="data row1 col4" >CHEMICAL EGR FUNDAMENTALS I</td>
      <td id="T_8f923_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_8f923_row1_col6" class="data row1 col6" >36</td>
      <td id="T_8f923_row1_col7" class="data row1 col7" >72</td>
      <td id="T_8f923_row1_col8" class="data row1 col8" >Tang</td>
    </tr>
    <tr>
      <td id="T_8f923_row2_col0" class="data row2 col0" >301</td>
      <td id="T_8f923_row2_col1" class="data row2 col1" >Fall 2024</td>
      <td id="T_8f923_row2_col2" class="data row2 col2" >CLSE301</td>
      <td id="T_8f923_row2_col3" class="data row2 col3" >001</td>
      <td id="T_8f923_row2_col4" class="data row2 col4" >TRANSPORT PHENOMENA I</td>
      <td id="T_8f923_row2_col5" class="data row2 col5" >LEC</td>
      <td id="T_8f923_row2_col6" class="data row2 col6" >35</td>
      <td id="T_8f923_row2_col7" class="data row2 col7" >105</td>
      <td id="T_8f923_row2_col8" class="data row2 col8" >Wen</td>
    </tr>
    <tr>
      <td id="T_8f923_row3_col0" class="data row3 col0" >305</td>
      <td id="T_8f923_row3_col1" class="data row3 col1" >Fall 2024</td>
      <td id="T_8f923_row3_col2" class="data row3 col2" >CLSE305</td>
      <td id="T_8f923_row3_col3" class="data row3 col3" >001</td>
      <td id="T_8f923_row3_col4" class="data row3 col4" >THERMODYNAMICS OF PHASE EQUIL</td>
      <td id="T_8f923_row3_col5" class="data row3 col5" >LEC</td>
      <td id="T_8f923_row3_col6" class="data row3 col6" >34</td>
      <td id="T_8f923_row3_col7" class="data row3 col7" >102</td>
      <td id="T_8f923_row3_col8" class="data row3 col8" >Gupta</td>
    </tr>
    <tr>
      <td id="T_8f923_row4_col0" class="data row4 col0" >409</td>
      <td id="T_8f923_row4_col1" class="data row4 col1" >Fall 2024</td>
      <td id="T_8f923_row4_col2" class="data row4 col2" >CLSE409</td>
      <td id="T_8f923_row4_col3" class="data row4 col3" >001</td>
      <td id="T_8f923_row4_col4" class="data row4 col4" >PROCESS CNTRL CHEM/LFSC ENGRNG</td>
      <td id="T_8f923_row4_col5" class="data row4 col5" >LEC</td>
      <td id="T_8f923_row4_col6" class="data row4 col6" >31</td>
      <td id="T_8f923_row4_col7" class="data row4 col7" >93</td>
      <td id="T_8f923_row4_col8" class="data row4 col8" >Jiang</td>
    </tr>
    <tr>
      <td id="T_8f923_row5_col0" class="data row5 col0" >572</td>
      <td id="T_8f923_row5_col1" class="data row5 col1" >Fall 2024</td>
      <td id="T_8f923_row5_col2" class="data row5 col2" >CLSE572</td>
      <td id="T_8f923_row5_col3" class="data row5 col3" >001</td>
      <td id="T_8f923_row5_col4" class="data row5 col4" >AI/ML IN CHEM & LS ENGINEERING</td>
      <td id="T_8f923_row5_col5" class="data row5 col5" >LEC</td>
      <td id="T_8f923_row5_col6" class="data row5 col6" >14</td>
      <td id="T_8f923_row5_col7" class="data row5 col7" >42</td>
      <td id="T_8f923_row5_col8" class="data row5 col8" >McGill</td>
    </tr>
    <tr>
      <td id="T_8f923_row6_col0" class="data row6 col0" >601</td>
      <td id="T_8f923_row6_col1" class="data row6 col1" >Fall 2024</td>
      <td id="T_8f923_row6_col2" class="data row6 col2" >CLSE601</td>
      <td id="T_8f923_row6_col3" class="data row6 col3" >901</td>
      <td id="T_8f923_row6_col4" class="data row6 col4" >ENGINEERING PROJECT MANAGEMENT</td>
      <td id="T_8f923_row6_col5" class="data row6 col5" >LEC</td>
      <td id="T_8f923_row6_col6" class="data row6 col6" >14</td>
      <td id="T_8f923_row6_col7" class="data row6 col7" >42</td>
      <td id="T_8f923_row6_col8" class="data row6 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_8f923_row7_col0" class="data row7 col0" >650</td>
      <td id="T_8f923_row7_col1" class="data row7 col1" >Fall 2024</td>
      <td id="T_8f923_row7_col2" class="data row7 col2" >CLSE650</td>
      <td id="T_8f923_row7_col3" class="data row7 col3" >001</td>
      <td id="T_8f923_row7_col4" class="data row7 col4" >QUANTITATIVE ANALYS IN CLSE</td>
      <td id="T_8f923_row7_col5" class="data row7 col5" >LEC</td>
      <td id="T_8f923_row7_col6" class="data row7 col6" >3</td>
      <td id="T_8f923_row7_col7" class="data row7 col7" >9</td>
      <td id="T_8f923_row7_col8" class="data row7 col8" >Jiang</td>
    </tr>
    <tr>
      <td id="T_8f923_row8_col0" class="data row8 col0" >650</td>
      <td id="T_8f923_row8_col1" class="data row8 col1" >Fall 2024</td>
      <td id="T_8f923_row8_col2" class="data row8 col2" >CLSE650</td>
      <td id="T_8f923_row8_col3" class="data row8 col3" >001</td>
      <td id="T_8f923_row8_col4" class="data row8 col4" >QUANTITATIVE ANALYS IN CLSE</td>
      <td id="T_8f923_row8_col5" class="data row8 col5" >LEC</td>
      <td id="T_8f923_row8_col6" class="data row8 col6" >3</td>
      <td id="T_8f923_row8_col7" class="data row8 col7" >9</td>
      <td id="T_8f923_row8_col8" class="data row8 col8" >McGill</td>
    </tr>
    <tr>
      <td id="T_8f923_row9_col0" class="data row9 col0" >654</td>
      <td id="T_8f923_row9_col1" class="data row9 col1" >Fall 2024</td>
      <td id="T_8f923_row9_col2" class="data row9 col2" >CLSE654</td>
      <td id="T_8f923_row9_col3" class="data row9 col3" >001</td>
      <td id="T_8f923_row9_col4" class="data row9 col4" >EQUILIBRIUM ANALYSIS</td>
      <td id="T_8f923_row9_col5" class="data row9 col5" >LEC</td>
      <td id="T_8f923_row9_col6" class="data row9 col6" >8</td>
      <td id="T_8f923_row9_col7" class="data row9 col7" >24</td>
      <td id="T_8f923_row9_col8" class="data row9 col8" >Peters</td>
    </tr>
    <tr>
      <td id="T_8f923_row10_col0" class="data row10 col0" >690</td>
      <td id="T_8f923_row10_col1" class="data row10 col1" >Fall 2024</td>
      <td id="T_8f923_row10_col2" class="data row10 col2" >CLSE690</td>
      <td id="T_8f923_row10_col3" class="data row10 col3" >001</td>
      <td id="T_8f923_row10_col4" class="data row10 col4" >RESEARCH SEMINAR</td>
      <td id="T_8f923_row10_col5" class="data row10 col5" >SEM</td>
      <td id="T_8f923_row10_col6" class="data row10 col6" >30</td>
      <td id="T_8f923_row10_col7" class="data row10 col7" >15</td>
      <td id="T_8f923_row10_col8" class="data row10 col8" >Jiang</td>
    </tr>
    <tr>
      <td id="T_8f923_row11_col0" class="data row11 col0" >691</td>
      <td id="T_8f923_row11_col1" class="data row11 col1" >Fall 2024</td>
      <td id="T_8f923_row11_col2" class="data row11 col2" >CLSE691</td>
      <td id="T_8f923_row11_col3" class="data row11 col3" >001</td>
      <td id="T_8f923_row11_col4" class="data row11 col4" >ST: TECHNICAL COMMUNICATION</td>
      <td id="T_8f923_row11_col5" class="data row11 col5" >LEC</td>
      <td id="T_8f923_row11_col6" class="data row11 col6" >6</td>
      <td id="T_8f923_row11_col7" class="data row11 col7" >11</td>
      <td id="T_8f923_row11_col8" class="data row11 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_8f923_row12_col0" class="data row12 col0" >691</td>
      <td id="T_8f923_row12_col1" class="data row12 col1" >Fall 2024</td>
      <td id="T_8f923_row12_col2" class="data row12 col2" >CLSE691</td>
      <td id="T_8f923_row12_col3" class="data row12 col3" >001</td>
      <td id="T_8f923_row12_col4" class="data row12 col4" >ST: TECHNICAL COMMUNICATION</td>
      <td id="T_8f923_row12_col5" class="data row12 col5" >LEC</td>
      <td id="T_8f923_row12_col6" class="data row12 col6" >6</td>
      <td id="T_8f923_row12_col7" class="data row12 col7" >11</td>
      <td id="T_8f923_row12_col8" class="data row12 col8" >Spangler</td>
    </tr>
    <tr>
      <td id="T_8f923_row13_col0" class="data row13 col0" >101</td>
      <td id="T_8f923_row13_col1" class="data row13 col1" >Fall 2024</td>
      <td id="T_8f923_row13_col2" class="data row13 col2" >ENGR101</td>
      <td id="T_8f923_row13_col3" class="data row13 col3" >C01</td>
      <td id="T_8f923_row13_col4" class="data row13 col4" >INTRODUCTION TO ENGINEERING</td>
      <td id="T_8f923_row13_col5" class="data row13 col5" >LEC</td>
      <td id="T_8f923_row13_col6" class="data row13 col6" >10</td>
      <td id="T_8f923_row13_col7" class="data row13 col7" >40</td>
      <td id="T_8f923_row13_col8" class="data row13 col8" >Ferri</td>
    </tr>
    <tr>
      <td id="T_8f923_row14_col0" class="data row14 col0" >402</td>
      <td id="T_8f923_row14_col1" class="data row14 col1" >Fall 2024</td>
      <td id="T_8f923_row14_col2" class="data row14 col2" >ENGR402</td>
      <td id="T_8f923_row14_col3" class="data row14 col3" >003</td>
      <td id="T_8f923_row14_col4" class="data row14 col4" >SENIOR DESIGN STUDIO</td>
      <td id="T_8f923_row14_col5" class="data row14 col5" >LEC</td>
      <td id="T_8f923_row14_col6" class="data row14 col6" >33</td>
      <td id="T_8f923_row14_col7" class="data row14 col7" >33</td>
      <td id="T_8f923_row14_col8" class="data row14 col8" >Kuhn</td>
    </tr>
    <tr>
      <td id="T_8f923_row15_col0" class="data row15 col0" >497</td>
      <td id="T_8f923_row15_col1" class="data row15 col1" >Fall 2024</td>
      <td id="T_8f923_row15_col2" class="data row15 col2" >ENGR497</td>
      <td id="T_8f923_row15_col3" class="data row15 col3" >L11</td>
      <td id="T_8f923_row15_col4" class="data row15 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_8f923_row15_col5" class="data row15 col5" >VIP</td>
      <td id="T_8f923_row15_col6" class="data row15 col6" >2</td>
      <td id="T_8f923_row15_col7" class="data row15 col7" >2</td>
      <td id="T_8f923_row15_col8" class="data row15 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_8f923_row16_col0" class="data row16 col0" >497</td>
      <td id="T_8f923_row16_col1" class="data row16 col1" >Fall 2024</td>
      <td id="T_8f923_row16_col2" class="data row16 col2" >ENGR497</td>
      <td id="T_8f923_row16_col3" class="data row16 col3" >L13</td>
      <td id="T_8f923_row16_col4" class="data row16 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_8f923_row16_col5" class="data row16 col5" >VIP</td>
      <td id="T_8f923_row16_col6" class="data row16 col6" >1</td>
      <td id="T_8f923_row16_col7" class="data row16 col7" >2</td>
      <td id="T_8f923_row16_col8" class="data row16 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_8f923_row17_col0" class="data row17 col0" >497</td>
      <td id="T_8f923_row17_col1" class="data row17 col1" >Fall 2024</td>
      <td id="T_8f923_row17_col2" class="data row17 col2" >ENGR497</td>
      <td id="T_8f923_row17_col3" class="data row17 col3" >L35</td>
      <td id="T_8f923_row17_col4" class="data row17 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_8f923_row17_col5" class="data row17 col5" >VIP</td>
      <td id="T_8f923_row17_col6" class="data row17 col6" >1</td>
      <td id="T_8f923_row17_col7" class="data row17 col7" >1</td>
      <td id="T_8f923_row17_col8" class="data row17 col8" >Tang</td>
    </tr>
    <tr>
      <td id="T_8f923_row18_col0" class="data row18 col0" >497</td>
      <td id="T_8f923_row18_col1" class="data row18 col1" >Fall 2024</td>
      <td id="T_8f923_row18_col2" class="data row18 col2" >ENGR497</td>
      <td id="T_8f923_row18_col3" class="data row18 col3" >L36</td>
      <td id="T_8f923_row18_col4" class="data row18 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_8f923_row18_col5" class="data row18 col5" >VIP</td>
      <td id="T_8f923_row18_col6" class="data row18 col6" >1</td>
      <td id="T_8f923_row18_col7" class="data row18 col7" >2</td>
      <td id="T_8f923_row18_col8" class="data row18 col8" >Tang</td>
    </tr>
  </tbody>
</table>

:::

# AY23-24

This section list instructor activity for the academic year AY23-24 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## Fall 2023

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_919e7 table {
  width: 100%;
  border-collapse: collapse;
}
#T_919e7 th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_919e7 th {
  border: 0;
}
#T_919e7 thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_919e7 tbody td:nth-child(1) {
  display: none;
}
#T_919e7 thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_919e7 tbody td:nth-child(2) {
  display: none;
}
#T_919e7 thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_919e7 tbody td:nth-child(8) {
  display: none;
}
#T_919e7 td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_919e7 td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_919e7 td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_919e7 td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_919e7 td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_919e7 td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_919e7_row0_col0, #T_919e7_row0_col1, #T_919e7_row0_col2, #T_919e7_row0_col3, #T_919e7_row0_col4, #T_919e7_row0_col5, #T_919e7_row0_col6, #T_919e7_row0_col7, #T_919e7_row0_col8, #T_919e7_row2_col0, #T_919e7_row2_col1, #T_919e7_row2_col2, #T_919e7_row2_col3, #T_919e7_row2_col4, #T_919e7_row2_col5, #T_919e7_row2_col6, #T_919e7_row2_col7, #T_919e7_row2_col8, #T_919e7_row3_col0, #T_919e7_row3_col1, #T_919e7_row3_col2, #T_919e7_row3_col3, #T_919e7_row3_col4, #T_919e7_row3_col5, #T_919e7_row3_col6, #T_919e7_row3_col7, #T_919e7_row3_col8, #T_919e7_row14_col0, #T_919e7_row14_col1, #T_919e7_row14_col2, #T_919e7_row14_col3, #T_919e7_row14_col4, #T_919e7_row14_col5, #T_919e7_row14_col6, #T_919e7_row14_col7, #T_919e7_row14_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_919e7_row1_col0, #T_919e7_row1_col1, #T_919e7_row1_col2, #T_919e7_row1_col3, #T_919e7_row1_col4, #T_919e7_row1_col5, #T_919e7_row1_col6, #T_919e7_row1_col7, #T_919e7_row1_col8, #T_919e7_row4_col0, #T_919e7_row4_col1, #T_919e7_row4_col2, #T_919e7_row4_col3, #T_919e7_row4_col4, #T_919e7_row4_col5, #T_919e7_row4_col6, #T_919e7_row4_col7, #T_919e7_row4_col8, #T_919e7_row5_col0, #T_919e7_row5_col1, #T_919e7_row5_col2, #T_919e7_row5_col3, #T_919e7_row5_col4, #T_919e7_row5_col5, #T_919e7_row5_col6, #T_919e7_row5_col7, #T_919e7_row5_col8, #T_919e7_row6_col0, #T_919e7_row6_col1, #T_919e7_row6_col2, #T_919e7_row6_col3, #T_919e7_row6_col4, #T_919e7_row6_col5, #T_919e7_row6_col6, #T_919e7_row6_col7, #T_919e7_row6_col8, #T_919e7_row7_col0, #T_919e7_row7_col1, #T_919e7_row7_col2, #T_919e7_row7_col3, #T_919e7_row7_col4, #T_919e7_row7_col5, #T_919e7_row7_col6, #T_919e7_row7_col7, #T_919e7_row7_col8, #T_919e7_row8_col0, #T_919e7_row8_col1, #T_919e7_row8_col2, #T_919e7_row8_col3, #T_919e7_row8_col4, #T_919e7_row8_col5, #T_919e7_row8_col6, #T_919e7_row8_col7, #T_919e7_row8_col8, #T_919e7_row9_col0, #T_919e7_row9_col1, #T_919e7_row9_col2, #T_919e7_row9_col3, #T_919e7_row9_col4, #T_919e7_row9_col5, #T_919e7_row9_col6, #T_919e7_row9_col7, #T_919e7_row9_col8, #T_919e7_row10_col0, #T_919e7_row10_col1, #T_919e7_row10_col2, #T_919e7_row10_col3, #T_919e7_row10_col4, #T_919e7_row10_col5, #T_919e7_row10_col6, #T_919e7_row10_col7, #T_919e7_row10_col8, #T_919e7_row11_col0, #T_919e7_row11_col1, #T_919e7_row11_col2, #T_919e7_row11_col3, #T_919e7_row11_col4, #T_919e7_row11_col5, #T_919e7_row11_col6, #T_919e7_row11_col7, #T_919e7_row11_col8, #T_919e7_row12_col0, #T_919e7_row12_col1, #T_919e7_row12_col2, #T_919e7_row12_col3, #T_919e7_row12_col4, #T_919e7_row12_col5, #T_919e7_row12_col6, #T_919e7_row12_col7, #T_919e7_row12_col8, #T_919e7_row13_col0, #T_919e7_row13_col1, #T_919e7_row13_col2, #T_919e7_row13_col3, #T_919e7_row13_col4, #T_919e7_row13_col5, #T_919e7_row13_col6, #T_919e7_row13_col7, #T_919e7_row13_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_919e7">
  <thead>
    <tr>
      <th id="T_919e7_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_919e7_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_919e7_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_919e7_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_919e7_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_919e7_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_919e7_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_919e7_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_919e7_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_919e7_row0_col0" class="data row0 col0" >101</td>
      <td id="T_919e7_row0_col1" class="data row0 col1" >Fall 2023</td>
      <td id="T_919e7_row0_col2" class="data row0 col2" >CLSE101</td>
      <td id="T_919e7_row0_col3" class="data row0 col3" >001</td>
      <td id="T_919e7_row0_col4" class="data row0 col4" >INTRO TO ENGINEERING</td>
      <td id="T_919e7_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_919e7_row0_col6" class="data row0 col6" >46</td>
      <td id="T_919e7_row0_col7" class="data row0 col7" >138</td>
      <td id="T_919e7_row0_col8" class="data row0 col8" >Spangler</td>
    </tr>
    <tr>
      <td id="T_919e7_row1_col0" class="data row1 col0" >201</td>
      <td id="T_919e7_row1_col1" class="data row1 col1" >Fall 2023</td>
      <td id="T_919e7_row1_col2" class="data row1 col2" >CLSE201</td>
      <td id="T_919e7_row1_col3" class="data row1 col3" >901</td>
      <td id="T_919e7_row1_col4" class="data row1 col4" >CHEMICAL EGR FUNDAMENTALS I</td>
      <td id="T_919e7_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_919e7_row1_col6" class="data row1 col6" >37</td>
      <td id="T_919e7_row1_col7" class="data row1 col7" >74</td>
      <td id="T_919e7_row1_col8" class="data row1 col8" >Tang</td>
    </tr>
    <tr>
      <td id="T_919e7_row2_col0" class="data row2 col0" >301</td>
      <td id="T_919e7_row2_col1" class="data row2 col1" >Fall 2023</td>
      <td id="T_919e7_row2_col2" class="data row2 col2" >CLSE301</td>
      <td id="T_919e7_row2_col3" class="data row2 col3" >001</td>
      <td id="T_919e7_row2_col4" class="data row2 col4" >TRANSPORT PHENOMENA I</td>
      <td id="T_919e7_row2_col5" class="data row2 col5" >LEC</td>
      <td id="T_919e7_row2_col6" class="data row2 col6" >38</td>
      <td id="T_919e7_row2_col7" class="data row2 col7" >114</td>
      <td id="T_919e7_row2_col8" class="data row2 col8" >Ferri</td>
    </tr>
    <tr>
      <td id="T_919e7_row3_col0" class="data row3 col0" >305</td>
      <td id="T_919e7_row3_col1" class="data row3 col1" >Fall 2023</td>
      <td id="T_919e7_row3_col2" class="data row3 col2" >CLSE305</td>
      <td id="T_919e7_row3_col3" class="data row3 col3" >001</td>
      <td id="T_919e7_row3_col4" class="data row3 col4" >THERMODYNAMICS OF PHASE EQUIL</td>
      <td id="T_919e7_row3_col5" class="data row3 col5" >LEC</td>
      <td id="T_919e7_row3_col6" class="data row3 col6" >37</td>
      <td id="T_919e7_row3_col7" class="data row3 col7" >111</td>
      <td id="T_919e7_row3_col8" class="data row3 col8" >Yadavalli</td>
    </tr>
    <tr>
      <td id="T_919e7_row4_col0" class="data row4 col0" >409</td>
      <td id="T_919e7_row4_col1" class="data row4 col1" >Fall 2023</td>
      <td id="T_919e7_row4_col2" class="data row4 col2" >CLSE409</td>
      <td id="T_919e7_row4_col3" class="data row4 col3" >001</td>
      <td id="T_919e7_row4_col4" class="data row4 col4" >PROCESS CNTRL CHEM/LFSC ENGRNG</td>
      <td id="T_919e7_row4_col5" class="data row4 col5" >LEC</td>
      <td id="T_919e7_row4_col6" class="data row4 col6" >34</td>
      <td id="T_919e7_row4_col7" class="data row4 col7" >102</td>
      <td id="T_919e7_row4_col8" class="data row4 col8" >Jiang</td>
    </tr>
    <tr>
      <td id="T_919e7_row5_col0" class="data row5 col0" >650</td>
      <td id="T_919e7_row5_col1" class="data row5 col1" >Fall 2023</td>
      <td id="T_919e7_row5_col2" class="data row5 col2" >CLSE650</td>
      <td id="T_919e7_row5_col3" class="data row5 col3" >901</td>
      <td id="T_919e7_row5_col4" class="data row5 col4" >QUANTITATIVE ANALYS IN CLSE</td>
      <td id="T_919e7_row5_col5" class="data row5 col5" >LEC</td>
      <td id="T_919e7_row5_col6" class="data row5 col6" >7</td>
      <td id="T_919e7_row5_col7" class="data row5 col7" >21</td>
      <td id="T_919e7_row5_col8" class="data row5 col8" >McGill</td>
    </tr>
    <tr>
      <td id="T_919e7_row6_col0" class="data row6 col0" >654</td>
      <td id="T_919e7_row6_col1" class="data row6 col1" >Fall 2023</td>
      <td id="T_919e7_row6_col2" class="data row6 col2" >CLSE654</td>
      <td id="T_919e7_row6_col3" class="data row6 col3" >001</td>
      <td id="T_919e7_row6_col4" class="data row6 col4" >EQUILIBRIUM ANALYSIS</td>
      <td id="T_919e7_row6_col5" class="data row6 col5" >LEC</td>
      <td id="T_919e7_row6_col6" class="data row6 col6" >7</td>
      <td id="T_919e7_row6_col7" class="data row6 col7" >21</td>
      <td id="T_919e7_row6_col8" class="data row6 col8" >Peters</td>
    </tr>
    <tr>
      <td id="T_919e7_row7_col0" class="data row7 col0" >675</td>
      <td id="T_919e7_row7_col1" class="data row7 col1" >Fall 2023</td>
      <td id="T_919e7_row7_col2" class="data row7 col2" >CLSE675</td>
      <td id="T_919e7_row7_col3" class="data row7 col3" >001</td>
      <td id="T_919e7_row7_col4" class="data row7 col4" >POLYMERS IN MEDICINE</td>
      <td id="T_919e7_row7_col5" class="data row7 col5" >LEC</td>
      <td id="T_919e7_row7_col6" class="data row7 col6" >6</td>
      <td id="T_919e7_row7_col7" class="data row7 col7" >18</td>
      <td id="T_919e7_row7_col8" class="data row7 col8" >Wen</td>
    </tr>
    <tr>
      <td id="T_919e7_row8_col0" class="data row8 col0" >690</td>
      <td id="T_919e7_row8_col1" class="data row8 col1" >Fall 2023</td>
      <td id="T_919e7_row8_col2" class="data row8 col2" >CLSE690</td>
      <td id="T_919e7_row8_col3" class="data row8 col3" >001</td>
      <td id="T_919e7_row8_col4" class="data row8 col4" >RESEARCH SEMINAR</td>
      <td id="T_919e7_row8_col5" class="data row8 col5" >SEM</td>
      <td id="T_919e7_row8_col6" class="data row8 col6" >38</td>
      <td id="T_919e7_row8_col7" class="data row8 col7" >19</td>
      <td id="T_919e7_row8_col8" class="data row8 col8" >Jiang</td>
    </tr>
    <tr>
      <td id="T_919e7_row9_col0" class="data row9 col0" >691</td>
      <td id="T_919e7_row9_col1" class="data row9 col1" >Fall 2023</td>
      <td id="T_919e7_row9_col2" class="data row9 col2" >CLSE691</td>
      <td id="T_919e7_row9_col3" class="data row9 col3" >001</td>
      <td id="T_919e7_row9_col4" class="data row9 col4" >ST: TECHNICAL COMMUNICATION</td>
      <td id="T_919e7_row9_col5" class="data row9 col5" >LEC</td>
      <td id="T_919e7_row9_col6" class="data row9 col6" >4</td>
      <td id="T_919e7_row9_col7" class="data row9 col7" >9</td>
      <td id="T_919e7_row9_col8" class="data row9 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_919e7_row10_col0" class="data row10 col0" >691</td>
      <td id="T_919e7_row10_col1" class="data row10 col1" >Fall 2023</td>
      <td id="T_919e7_row10_col2" class="data row10 col2" >CLSE691</td>
      <td id="T_919e7_row10_col3" class="data row10 col3" >001</td>
      <td id="T_919e7_row10_col4" class="data row10 col4" >ST: TECHNICAL COMMUNICATION</td>
      <td id="T_919e7_row10_col5" class="data row10 col5" >LEC</td>
      <td id="T_919e7_row10_col6" class="data row10 col6" >4</td>
      <td id="T_919e7_row10_col7" class="data row10 col7" >9</td>
      <td id="T_919e7_row10_col8" class="data row10 col8" >Spangler</td>
    </tr>
    <tr>
      <td id="T_919e7_row11_col0" class="data row11 col0" >402</td>
      <td id="T_919e7_row11_col1" class="data row11 col1" >Fall 2023</td>
      <td id="T_919e7_row11_col2" class="data row11 col2" >ENGR402</td>
      <td id="T_919e7_row11_col3" class="data row11 col3" >003</td>
      <td id="T_919e7_row11_col4" class="data row11 col4" >SENIOR DESIGN STUDIO</td>
      <td id="T_919e7_row11_col5" class="data row11 col5" >LEC</td>
      <td id="T_919e7_row11_col6" class="data row11 col6" >34</td>
      <td id="T_919e7_row11_col7" class="data row11 col7" >34</td>
      <td id="T_919e7_row11_col8" class="data row11 col8" >Kuhn</td>
    </tr>
    <tr>
      <td id="T_919e7_row12_col0" class="data row12 col0" >497</td>
      <td id="T_919e7_row12_col1" class="data row12 col1" >Fall 2023</td>
      <td id="T_919e7_row12_col2" class="data row12 col2" >ENGR497</td>
      <td id="T_919e7_row12_col3" class="data row12 col3" >L11</td>
      <td id="T_919e7_row12_col4" class="data row12 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_919e7_row12_col5" class="data row12 col5" >VIP</td>
      <td id="T_919e7_row12_col6" class="data row12 col6" >2</td>
      <td id="T_919e7_row12_col7" class="data row12 col7" >2</td>
      <td id="T_919e7_row12_col8" class="data row12 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_919e7_row13_col0" class="data row13 col0" >497</td>
      <td id="T_919e7_row13_col1" class="data row13 col1" >Fall 2023</td>
      <td id="T_919e7_row13_col2" class="data row13 col2" >ENGR497</td>
      <td id="T_919e7_row13_col3" class="data row13 col3" >L35</td>
      <td id="T_919e7_row13_col4" class="data row13 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_919e7_row13_col5" class="data row13 col5" >VIP</td>
      <td id="T_919e7_row13_col6" class="data row13 col6" >2</td>
      <td id="T_919e7_row13_col7" class="data row13 col7" >2</td>
      <td id="T_919e7_row13_col8" class="data row13 col8" >Tang</td>
    </tr>
    <tr>
      <td id="T_919e7_row14_col0" class="data row14 col0" >591</td>
      <td id="T_919e7_row14_col1" class="data row14 col1" >Fall 2023</td>
      <td id="T_919e7_row14_col2" class="data row14 col2" >ENGR591</td>
      <td id="T_919e7_row14_col3" class="data row14 col3" >065</td>
      <td id="T_919e7_row14_col4" class="data row14 col4" >SPECIAL TOPICS (ADV TRAN PRAC)</td>
      <td id="T_919e7_row14_col5" class="data row14 col5" >LEC</td>
      <td id="T_919e7_row14_col6" class="data row14 col6" >1</td>
      <td id="T_919e7_row14_col7" class="data row14 col7" >1</td>
      <td id="T_919e7_row14_col8" class="data row14 col8" >Ferri</td>
    </tr>
  </tbody>
</table>

:::

## Spring 2024

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_d42e7 table {
  width: 100%;
  border-collapse: collapse;
}
#T_d42e7 th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_d42e7 th {
  border: 0;
}
#T_d42e7 thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_d42e7 tbody td:nth-child(1) {
  display: none;
}
#T_d42e7 thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_d42e7 tbody td:nth-child(2) {
  display: none;
}
#T_d42e7 thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_d42e7 tbody td:nth-child(8) {
  display: none;
}
#T_d42e7 td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_d42e7 td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_d42e7 td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_d42e7 td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_d42e7 td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_d42e7 td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_d42e7_row0_col0, #T_d42e7_row0_col1, #T_d42e7_row0_col2, #T_d42e7_row0_col3, #T_d42e7_row0_col4, #T_d42e7_row0_col5, #T_d42e7_row0_col6, #T_d42e7_row0_col7, #T_d42e7_row0_col8, #T_d42e7_row2_col0, #T_d42e7_row2_col1, #T_d42e7_row2_col2, #T_d42e7_row2_col3, #T_d42e7_row2_col4, #T_d42e7_row2_col5, #T_d42e7_row2_col6, #T_d42e7_row2_col7, #T_d42e7_row2_col8, #T_d42e7_row3_col0, #T_d42e7_row3_col1, #T_d42e7_row3_col2, #T_d42e7_row3_col3, #T_d42e7_row3_col4, #T_d42e7_row3_col5, #T_d42e7_row3_col6, #T_d42e7_row3_col7, #T_d42e7_row3_col8, #T_d42e7_row4_col0, #T_d42e7_row4_col1, #T_d42e7_row4_col2, #T_d42e7_row4_col3, #T_d42e7_row4_col4, #T_d42e7_row4_col5, #T_d42e7_row4_col6, #T_d42e7_row4_col7, #T_d42e7_row4_col8, #T_d42e7_row12_col0, #T_d42e7_row12_col1, #T_d42e7_row12_col2, #T_d42e7_row12_col3, #T_d42e7_row12_col4, #T_d42e7_row12_col5, #T_d42e7_row12_col6, #T_d42e7_row12_col7, #T_d42e7_row12_col8, #T_d42e7_row13_col0, #T_d42e7_row13_col1, #T_d42e7_row13_col2, #T_d42e7_row13_col3, #T_d42e7_row13_col4, #T_d42e7_row13_col5, #T_d42e7_row13_col6, #T_d42e7_row13_col7, #T_d42e7_row13_col8, #T_d42e7_row14_col0, #T_d42e7_row14_col1, #T_d42e7_row14_col2, #T_d42e7_row14_col3, #T_d42e7_row14_col4, #T_d42e7_row14_col5, #T_d42e7_row14_col6, #T_d42e7_row14_col7, #T_d42e7_row14_col8, #T_d42e7_row15_col0, #T_d42e7_row15_col1, #T_d42e7_row15_col2, #T_d42e7_row15_col3, #T_d42e7_row15_col4, #T_d42e7_row15_col5, #T_d42e7_row15_col6, #T_d42e7_row15_col7, #T_d42e7_row15_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_d42e7_row1_col0, #T_d42e7_row1_col1, #T_d42e7_row1_col2, #T_d42e7_row1_col3, #T_d42e7_row1_col4, #T_d42e7_row1_col5, #T_d42e7_row1_col6, #T_d42e7_row1_col7, #T_d42e7_row1_col8, #T_d42e7_row5_col0, #T_d42e7_row5_col1, #T_d42e7_row5_col2, #T_d42e7_row5_col3, #T_d42e7_row5_col4, #T_d42e7_row5_col5, #T_d42e7_row5_col6, #T_d42e7_row5_col7, #T_d42e7_row5_col8, #T_d42e7_row6_col0, #T_d42e7_row6_col1, #T_d42e7_row6_col2, #T_d42e7_row6_col3, #T_d42e7_row6_col4, #T_d42e7_row6_col5, #T_d42e7_row6_col6, #T_d42e7_row6_col7, #T_d42e7_row6_col8, #T_d42e7_row7_col0, #T_d42e7_row7_col1, #T_d42e7_row7_col2, #T_d42e7_row7_col3, #T_d42e7_row7_col4, #T_d42e7_row7_col5, #T_d42e7_row7_col6, #T_d42e7_row7_col7, #T_d42e7_row7_col8, #T_d42e7_row8_col0, #T_d42e7_row8_col1, #T_d42e7_row8_col2, #T_d42e7_row8_col3, #T_d42e7_row8_col4, #T_d42e7_row8_col5, #T_d42e7_row8_col6, #T_d42e7_row8_col7, #T_d42e7_row8_col8, #T_d42e7_row9_col0, #T_d42e7_row9_col1, #T_d42e7_row9_col2, #T_d42e7_row9_col3, #T_d42e7_row9_col4, #T_d42e7_row9_col5, #T_d42e7_row9_col6, #T_d42e7_row9_col7, #T_d42e7_row9_col8, #T_d42e7_row10_col0, #T_d42e7_row10_col1, #T_d42e7_row10_col2, #T_d42e7_row10_col3, #T_d42e7_row10_col4, #T_d42e7_row10_col5, #T_d42e7_row10_col6, #T_d42e7_row10_col7, #T_d42e7_row10_col8, #T_d42e7_row11_col0, #T_d42e7_row11_col1, #T_d42e7_row11_col2, #T_d42e7_row11_col3, #T_d42e7_row11_col4, #T_d42e7_row11_col5, #T_d42e7_row11_col6, #T_d42e7_row11_col7, #T_d42e7_row11_col8, #T_d42e7_row16_col0, #T_d42e7_row16_col1, #T_d42e7_row16_col2, #T_d42e7_row16_col3, #T_d42e7_row16_col4, #T_d42e7_row16_col5, #T_d42e7_row16_col6, #T_d42e7_row16_col7, #T_d42e7_row16_col8, #T_d42e7_row17_col0, #T_d42e7_row17_col1, #T_d42e7_row17_col2, #T_d42e7_row17_col3, #T_d42e7_row17_col4, #T_d42e7_row17_col5, #T_d42e7_row17_col6, #T_d42e7_row17_col7, #T_d42e7_row17_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_d42e7">
  <thead>
    <tr>
      <th id="T_d42e7_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_d42e7_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_d42e7_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_d42e7_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_d42e7_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_d42e7_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_d42e7_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_d42e7_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_d42e7_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_d42e7_row0_col0" class="data row0 col0" >115</td>
      <td id="T_d42e7_row0_col1" class="data row0 col1" >Spring 2024</td>
      <td id="T_d42e7_row0_col2" class="data row0 col2" >CLSE115</td>
      <td id="T_d42e7_row0_col3" class="data row0 col3" >001</td>
      <td id="T_d42e7_row0_col4" class="data row0 col4" >INTRO TO PROGRAMMING</td>
      <td id="T_d42e7_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_d42e7_row0_col6" class="data row0 col6" >38</td>
      <td id="T_d42e7_row0_col7" class="data row0 col7" >76</td>
      <td id="T_d42e7_row0_col8" class="data row0 col8" >McGill</td>
    </tr>
    <tr>
      <td id="T_d42e7_row1_col0" class="data row1 col0" >202</td>
      <td id="T_d42e7_row1_col1" class="data row1 col1" >Spring 2024</td>
      <td id="T_d42e7_row1_col2" class="data row1 col2" >CLSE202</td>
      <td id="T_d42e7_row1_col3" class="data row1 col3" >001</td>
      <td id="T_d42e7_row1_col4" class="data row1 col4" >CHEMICAL ENGINEERING FUND II</td>
      <td id="T_d42e7_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_d42e7_row1_col6" class="data row1 col6" >29</td>
      <td id="T_d42e7_row1_col7" class="data row1 col7" >58</td>
      <td id="T_d42e7_row1_col8" class="data row1 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_d42e7_row2_col0" class="data row2 col0" >302</td>
      <td id="T_d42e7_row2_col1" class="data row2 col1" >Spring 2024</td>
      <td id="T_d42e7_row2_col2" class="data row2 col2" >CLSE302</td>
      <td id="T_d42e7_row2_col3" class="data row2 col3" >001</td>
      <td id="T_d42e7_row2_col4" class="data row2 col4" >TRANSPORT PHENOMENA II</td>
      <td id="T_d42e7_row2_col5" class="data row2 col5" >LEC</td>
      <td id="T_d42e7_row2_col6" class="data row2 col6" >36</td>
      <td id="T_d42e7_row2_col7" class="data row2 col7" >72</td>
      <td id="T_d42e7_row2_col8" class="data row2 col8" >Peters</td>
    </tr>
    <tr>
      <td id="T_d42e7_row3_col0" class="data row3 col0" >560</td>
      <td id="T_d42e7_row3_col1" class="data row3 col1" >Spring 2024</td>
      <td id="T_d42e7_row3_col2" class="data row3 col2" >CLSE560</td>
      <td id="T_d42e7_row3_col3" class="data row3 col3" >901</td>
      <td id="T_d42e7_row3_col4" class="data row3 col4" >PROTEIN ENGINEERING</td>
      <td id="T_d42e7_row3_col5" class="data row3 col5" >LEC</td>
      <td id="T_d42e7_row3_col6" class="data row3 col6" >14</td>
      <td id="T_d42e7_row3_col7" class="data row3 col7" >42</td>
      <td id="T_d42e7_row3_col8" class="data row3 col8" >Spangler</td>
    </tr>
    <tr>
      <td id="T_d42e7_row4_col0" class="data row4 col0" >580</td>
      <td id="T_d42e7_row4_col1" class="data row4 col1" >Spring 2024</td>
      <td id="T_d42e7_row4_col2" class="data row4 col2" >CLSE580</td>
      <td id="T_d42e7_row4_col3" class="data row4 col3" >901</td>
      <td id="T_d42e7_row4_col4" class="data row4 col4" >SUSTAINABLE CHEMICAL ENGR</td>
      <td id="T_d42e7_row4_col5" class="data row4 col5" >LEC</td>
      <td id="T_d42e7_row4_col6" class="data row4 col6" >2</td>
      <td id="T_d42e7_row4_col7" class="data row4 col7" >6</td>
      <td id="T_d42e7_row4_col8" class="data row4 col8" >Tang</td>
    </tr>
    <tr>
      <td id="T_d42e7_row5_col0" class="data row5 col0" >655</td>
      <td id="T_d42e7_row5_col1" class="data row5 col1" >Spring 2024</td>
      <td id="T_d42e7_row5_col2" class="data row5 col2" >CLSE655</td>
      <td id="T_d42e7_row5_col3" class="data row5 col3" >001</td>
      <td id="T_d42e7_row5_col4" class="data row5 col4" >NONEQUILIBRIUM ANALYSIS</td>
      <td id="T_d42e7_row5_col5" class="data row5 col5" >LEC</td>
      <td id="T_d42e7_row5_col6" class="data row5 col6" >7</td>
      <td id="T_d42e7_row5_col7" class="data row5 col7" >21</td>
      <td id="T_d42e7_row5_col8" class="data row5 col8" >Wen</td>
    </tr>
    <tr>
      <td id="T_d42e7_row6_col0" class="data row6 col0" >656</td>
      <td id="T_d42e7_row6_col1" class="data row6 col1" >Spring 2024</td>
      <td id="T_d42e7_row6_col2" class="data row6 col2" >CLSE656</td>
      <td id="T_d42e7_row6_col3" class="data row6 col3" >901</td>
      <td id="T_d42e7_row6_col4" class="data row6 col4" >ADV CHEMICAL REACTION ENGR</td>
      <td id="T_d42e7_row6_col5" class="data row6 col5" >LEC</td>
      <td id="T_d42e7_row6_col6" class="data row6 col6" >5</td>
      <td id="T_d42e7_row6_col7" class="data row6 col7" >15</td>
      <td id="T_d42e7_row6_col8" class="data row6 col8" >Wen</td>
    </tr>
    <tr>
      <td id="T_d42e7_row7_col0" class="data row7 col0" >690</td>
      <td id="T_d42e7_row7_col1" class="data row7 col1" >Spring 2024</td>
      <td id="T_d42e7_row7_col2" class="data row7 col2" >CLSE690</td>
      <td id="T_d42e7_row7_col3" class="data row7 col3" >001</td>
      <td id="T_d42e7_row7_col4" class="data row7 col4" >RESEARCH SEMINAR</td>
      <td id="T_d42e7_row7_col5" class="data row7 col5" >SEM</td>
      <td id="T_d42e7_row7_col6" class="data row7 col6" >14</td>
      <td id="T_d42e7_row7_col7" class="data row7 col7" >14</td>
      <td id="T_d42e7_row7_col8" class="data row7 col8" >Jiang</td>
    </tr>
    <tr>
      <td id="T_d42e7_row8_col0" class="data row8 col0" >403</td>
      <td id="T_d42e7_row8_col1" class="data row8 col1" >Spring 2024</td>
      <td id="T_d42e7_row8_col2" class="data row8 col2" >ENGR403</td>
      <td id="T_d42e7_row8_col3" class="data row8 col3" >003</td>
      <td id="T_d42e7_row8_col4" class="data row8 col4" >SENIOR DESIGN STUDIO</td>
      <td id="T_d42e7_row8_col5" class="data row8 col5" >LEC</td>
      <td id="T_d42e7_row8_col6" class="data row8 col6" >34</td>
      <td id="T_d42e7_row8_col7" class="data row8 col7" >34</td>
      <td id="T_d42e7_row8_col8" class="data row8 col8" >Kuhn</td>
    </tr>
    <tr>
      <td id="T_d42e7_row9_col0" class="data row9 col0" >497</td>
      <td id="T_d42e7_row9_col1" class="data row9 col1" >Spring 2024</td>
      <td id="T_d42e7_row9_col2" class="data row9 col2" >ENGR497</td>
      <td id="T_d42e7_row9_col3" class="data row9 col3" >L12</td>
      <td id="T_d42e7_row9_col4" class="data row9 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_d42e7_row9_col5" class="data row9 col5" >VIP</td>
      <td id="T_d42e7_row9_col6" class="data row9 col6" >2</td>
      <td id="T_d42e7_row9_col7" class="data row9 col7" >2</td>
      <td id="T_d42e7_row9_col8" class="data row9 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_d42e7_row10_col0" class="data row10 col0" >497</td>
      <td id="T_d42e7_row10_col1" class="data row10 col1" >Spring 2024</td>
      <td id="T_d42e7_row10_col2" class="data row10 col2" >ENGR497</td>
      <td id="T_d42e7_row10_col3" class="data row10 col3" >L13</td>
      <td id="T_d42e7_row10_col4" class="data row10 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_d42e7_row10_col5" class="data row10 col5" >VIP</td>
      <td id="T_d42e7_row10_col6" class="data row10 col6" >0</td>
      <td id="T_d42e7_row10_col7" class="data row10 col7" >1</td>
      <td id="T_d42e7_row10_col8" class="data row10 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_d42e7_row11_col0" class="data row11 col0" >497</td>
      <td id="T_d42e7_row11_col1" class="data row11 col1" >Spring 2024</td>
      <td id="T_d42e7_row11_col2" class="data row11 col2" >ENGR497</td>
      <td id="T_d42e7_row11_col3" class="data row11 col3" >L35</td>
      <td id="T_d42e7_row11_col4" class="data row11 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_d42e7_row11_col5" class="data row11 col5" >VIP</td>
      <td id="T_d42e7_row11_col6" class="data row11 col6" >1</td>
      <td id="T_d42e7_row11_col7" class="data row11 col7" >1</td>
      <td id="T_d42e7_row11_col8" class="data row11 col8" >Tang</td>
    </tr>
    <tr>
      <td id="T_d42e7_row12_col0" class="data row12 col0" >591</td>
      <td id="T_d42e7_row12_col1" class="data row12 col1" >Spring 2024</td>
      <td id="T_d42e7_row12_col2" class="data row12 col2" >ENGR591</td>
      <td id="T_d42e7_row12_col3" class="data row12 col3" >001</td>
      <td id="T_d42e7_row12_col4" class="data row12 col4" >TOP:PROCESS ANALYTIC TECHNOL</td>
      <td id="T_d42e7_row12_col5" class="data row12 col5" >LEC</td>
      <td id="T_d42e7_row12_col6" class="data row12 col6" >11</td>
      <td id="T_d42e7_row12_col7" class="data row12 col7" >33</td>
      <td id="T_d42e7_row12_col8" class="data row12 col8" >Jiang</td>
    </tr>
    <tr>
      <td id="T_d42e7_row13_col0" class="data row13 col0" >591</td>
      <td id="T_d42e7_row13_col1" class="data row13 col1" >Spring 2024</td>
      <td id="T_d42e7_row13_col2" class="data row13 col2" >ENGR591</td>
      <td id="T_d42e7_row13_col3" class="data row13 col3" >901</td>
      <td id="T_d42e7_row13_col4" class="data row13 col4" >UNIT OPS CHEM ENGR: MASS TRANS</td>
      <td id="T_d42e7_row13_col5" class="data row13 col5" >LEC</td>
      <td id="T_d42e7_row13_col6" class="data row13 col6" >13</td>
      <td id="T_d42e7_row13_col7" class="data row13 col7" >39</td>
      <td id="T_d42e7_row13_col8" class="data row13 col8" >Ferri</td>
    </tr>
    <tr>
      <td id="T_d42e7_row14_col0" class="data row14 col0" >591</td>
      <td id="T_d42e7_row14_col1" class="data row14 col1" >Spring 2024</td>
      <td id="T_d42e7_row14_col2" class="data row14 col2" >ENGR591</td>
      <td id="T_d42e7_row14_col3" class="data row14 col3" >906</td>
      <td id="T_d42e7_row14_col4" class="data row14 col4" >TOP: BIOPRINTING & NANOTOXICOL</td>
      <td id="T_d42e7_row14_col5" class="data row14 col5" >LEC</td>
      <td id="T_d42e7_row14_col6" class="data row14 col6" >5</td>
      <td id="T_d42e7_row14_col7" class="data row14 col7" >15</td>
      <td id="T_d42e7_row14_col8" class="data row14 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_d42e7_row15_col0" class="data row15 col0" >591</td>
      <td id="T_d42e7_row15_col1" class="data row15 col1" >Spring 2024</td>
      <td id="T_d42e7_row15_col2" class="data row15 col2" >ENGR591</td>
      <td id="T_d42e7_row15_col3" class="data row15 col3" >907</td>
      <td id="T_d42e7_row15_col4" class="data row15 col4" >ST: WATER ESSENTIALS</td>
      <td id="T_d42e7_row15_col5" class="data row15 col5" >LEC</td>
      <td id="T_d42e7_row15_col6" class="data row15 col6" >5</td>
      <td id="T_d42e7_row15_col7" class="data row15 col7" >15</td>
      <td id="T_d42e7_row15_col8" class="data row15 col8" >Ferri</td>
    </tr>
    <tr>
      <td id="T_d42e7_row16_col0" class="data row16 col0" >691</td>
      <td id="T_d42e7_row16_col1" class="data row16 col1" >Spring 2024</td>
      <td id="T_d42e7_row16_col2" class="data row16 col2" >ENGR691</td>
      <td id="T_d42e7_row16_col3" class="data row16 col3" >C07</td>
      <td id="T_d42e7_row16_col4" class="data row16 col4" >ADV TOP IN INTERFACIAL PHENOM</td>
      <td id="T_d42e7_row16_col5" class="data row16 col5" >LEC</td>
      <td id="T_d42e7_row16_col6" class="data row16 col6" >1</td>
      <td id="T_d42e7_row16_col7" class="data row16 col7" >3</td>
      <td id="T_d42e7_row16_col8" class="data row16 col8" >Ferri</td>
    </tr>
    <tr>
      <td id="T_d42e7_row17_col0" class="data row17 col0" >691</td>
      <td id="T_d42e7_row17_col1" class="data row17 col1" >Spring 2024</td>
      <td id="T_d42e7_row17_col2" class="data row17 col2" >ENGR691</td>
      <td id="T_d42e7_row17_col3" class="data row17 col3" >C08</td>
      <td id="T_d42e7_row17_col4" class="data row17 col4" >ADV TOP IN SEPARATION PROC</td>
      <td id="T_d42e7_row17_col5" class="data row17 col5" >LEC</td>
      <td id="T_d42e7_row17_col6" class="data row17 col6" >1</td>
      <td id="T_d42e7_row17_col7" class="data row17 col7" >2</td>
      <td id="T_d42e7_row17_col8" class="data row17 col8" >Ferri</td>
    </tr>
  </tbody>
</table>

:::

## Summer 2024

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_8a77f table {
  width: 100%;
  border-collapse: collapse;
}
#T_8a77f th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_8a77f th {
  border: 0;
}
#T_8a77f thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_8a77f tbody td:nth-child(1) {
  display: none;
}
#T_8a77f thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_8a77f tbody td:nth-child(2) {
  display: none;
}
#T_8a77f thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_8a77f tbody td:nth-child(8) {
  display: none;
}
#T_8a77f td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_8a77f td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_8a77f td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_8a77f td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_8a77f td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_8a77f td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_8a77f_row0_col0, #T_8a77f_row0_col1, #T_8a77f_row0_col2, #T_8a77f_row0_col3, #T_8a77f_row0_col4, #T_8a77f_row0_col5, #T_8a77f_row0_col6, #T_8a77f_row0_col7, #T_8a77f_row0_col8, #T_8a77f_row1_col0, #T_8a77f_row1_col1, #T_8a77f_row1_col2, #T_8a77f_row1_col3, #T_8a77f_row1_col4, #T_8a77f_row1_col5, #T_8a77f_row1_col6, #T_8a77f_row1_col7, #T_8a77f_row1_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_8a77f_row2_col0, #T_8a77f_row2_col1, #T_8a77f_row2_col2, #T_8a77f_row2_col3, #T_8a77f_row2_col4, #T_8a77f_row2_col5, #T_8a77f_row2_col6, #T_8a77f_row2_col7, #T_8a77f_row2_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_8a77f">
  <thead>
    <tr>
      <th id="T_8a77f_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_8a77f_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_8a77f_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_8a77f_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_8a77f_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_8a77f_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_8a77f_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_8a77f_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_8a77f_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_8a77f_row0_col0" class="data row0 col0" >201</td>
      <td id="T_8a77f_row0_col1" class="data row0 col1" >Summer 2024</td>
      <td id="T_8a77f_row0_col2" class="data row0 col2" >CLSE201</td>
      <td id="T_8a77f_row0_col3" class="data row0 col3" >001</td>
      <td id="T_8a77f_row0_col4" class="data row0 col4" >CHEMICAL EGR FUNDAMENTALS I</td>
      <td id="T_8a77f_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_8a77f_row0_col6" class="data row0 col6" >5</td>
      <td id="T_8a77f_row0_col7" class="data row0 col7" >20</td>
      <td id="T_8a77f_row0_col8" class="data row0 col8" >Peters</td>
    </tr>
    <tr>
      <td id="T_8a77f_row1_col0" class="data row1 col0" >202</td>
      <td id="T_8a77f_row1_col1" class="data row1 col1" >Summer 2024</td>
      <td id="T_8a77f_row1_col2" class="data row1 col2" >CLSE202</td>
      <td id="T_8a77f_row1_col3" class="data row1 col3" >001</td>
      <td id="T_8a77f_row1_col4" class="data row1 col4" >CHEMICAL ENGINEERING FUND II</td>
      <td id="T_8a77f_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_8a77f_row1_col6" class="data row1 col6" >6</td>
      <td id="T_8a77f_row1_col7" class="data row1 col7" >24</td>
      <td id="T_8a77f_row1_col8" class="data row1 col8" >Peters</td>
    </tr>
    <tr>
      <td id="T_8a77f_row2_col0" class="data row2 col0" >497</td>
      <td id="T_8a77f_row2_col1" class="data row2 col1" >Summer 2024</td>
      <td id="T_8a77f_row2_col2" class="data row2 col2" >ENGR497</td>
      <td id="T_8a77f_row2_col3" class="data row2 col3" >123</td>
      <td id="T_8a77f_row2_col4" class="data row2 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_8a77f_row2_col5" class="data row2 col5" >VIP</td>
      <td id="T_8a77f_row2_col6" class="data row2 col6" >1</td>
      <td id="T_8a77f_row2_col7" class="data row2 col7" >1</td>
      <td id="T_8a77f_row2_col8" class="data row2 col8" >Tang</td>
    </tr>
  </tbody>
</table>

:::

# AY22-23

This section list instructor activity for the academic year AY22-23 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## Fall 2022

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_c7eb7 table {
  width: 100%;
  border-collapse: collapse;
}
#T_c7eb7 th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_c7eb7 th {
  border: 0;
}
#T_c7eb7 thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_c7eb7 tbody td:nth-child(1) {
  display: none;
}
#T_c7eb7 thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_c7eb7 tbody td:nth-child(2) {
  display: none;
}
#T_c7eb7 thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_c7eb7 tbody td:nth-child(8) {
  display: none;
}
#T_c7eb7 td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_c7eb7 td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_c7eb7 td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_c7eb7 td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_c7eb7 td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_c7eb7 td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_c7eb7_row0_col0, #T_c7eb7_row0_col1, #T_c7eb7_row0_col2, #T_c7eb7_row0_col3, #T_c7eb7_row0_col4, #T_c7eb7_row0_col5, #T_c7eb7_row0_col6, #T_c7eb7_row0_col7, #T_c7eb7_row0_col8, #T_c7eb7_row2_col0, #T_c7eb7_row2_col1, #T_c7eb7_row2_col2, #T_c7eb7_row2_col3, #T_c7eb7_row2_col4, #T_c7eb7_row2_col5, #T_c7eb7_row2_col6, #T_c7eb7_row2_col7, #T_c7eb7_row2_col8, #T_c7eb7_row3_col0, #T_c7eb7_row3_col1, #T_c7eb7_row3_col2, #T_c7eb7_row3_col3, #T_c7eb7_row3_col4, #T_c7eb7_row3_col5, #T_c7eb7_row3_col6, #T_c7eb7_row3_col7, #T_c7eb7_row3_col8, #T_c7eb7_row5_col0, #T_c7eb7_row5_col1, #T_c7eb7_row5_col2, #T_c7eb7_row5_col3, #T_c7eb7_row5_col4, #T_c7eb7_row5_col5, #T_c7eb7_row5_col6, #T_c7eb7_row5_col7, #T_c7eb7_row5_col8, #T_c7eb7_row17_col0, #T_c7eb7_row17_col1, #T_c7eb7_row17_col2, #T_c7eb7_row17_col3, #T_c7eb7_row17_col4, #T_c7eb7_row17_col5, #T_c7eb7_row17_col6, #T_c7eb7_row17_col7, #T_c7eb7_row17_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_c7eb7_row1_col0, #T_c7eb7_row1_col1, #T_c7eb7_row1_col2, #T_c7eb7_row1_col3, #T_c7eb7_row1_col4, #T_c7eb7_row1_col5, #T_c7eb7_row1_col6, #T_c7eb7_row1_col7, #T_c7eb7_row1_col8, #T_c7eb7_row4_col0, #T_c7eb7_row4_col1, #T_c7eb7_row4_col2, #T_c7eb7_row4_col3, #T_c7eb7_row4_col4, #T_c7eb7_row4_col5, #T_c7eb7_row4_col6, #T_c7eb7_row4_col7, #T_c7eb7_row4_col8, #T_c7eb7_row6_col0, #T_c7eb7_row6_col1, #T_c7eb7_row6_col2, #T_c7eb7_row6_col3, #T_c7eb7_row6_col4, #T_c7eb7_row6_col5, #T_c7eb7_row6_col6, #T_c7eb7_row6_col7, #T_c7eb7_row6_col8, #T_c7eb7_row7_col0, #T_c7eb7_row7_col1, #T_c7eb7_row7_col2, #T_c7eb7_row7_col3, #T_c7eb7_row7_col4, #T_c7eb7_row7_col5, #T_c7eb7_row7_col6, #T_c7eb7_row7_col7, #T_c7eb7_row7_col8, #T_c7eb7_row8_col0, #T_c7eb7_row8_col1, #T_c7eb7_row8_col2, #T_c7eb7_row8_col3, #T_c7eb7_row8_col4, #T_c7eb7_row8_col5, #T_c7eb7_row8_col6, #T_c7eb7_row8_col7, #T_c7eb7_row8_col8, #T_c7eb7_row9_col0, #T_c7eb7_row9_col1, #T_c7eb7_row9_col2, #T_c7eb7_row9_col3, #T_c7eb7_row9_col4, #T_c7eb7_row9_col5, #T_c7eb7_row9_col6, #T_c7eb7_row9_col7, #T_c7eb7_row9_col8, #T_c7eb7_row10_col0, #T_c7eb7_row10_col1, #T_c7eb7_row10_col2, #T_c7eb7_row10_col3, #T_c7eb7_row10_col4, #T_c7eb7_row10_col5, #T_c7eb7_row10_col6, #T_c7eb7_row10_col7, #T_c7eb7_row10_col8, #T_c7eb7_row11_col0, #T_c7eb7_row11_col1, #T_c7eb7_row11_col2, #T_c7eb7_row11_col3, #T_c7eb7_row11_col4, #T_c7eb7_row11_col5, #T_c7eb7_row11_col6, #T_c7eb7_row11_col7, #T_c7eb7_row11_col8, #T_c7eb7_row12_col0, #T_c7eb7_row12_col1, #T_c7eb7_row12_col2, #T_c7eb7_row12_col3, #T_c7eb7_row12_col4, #T_c7eb7_row12_col5, #T_c7eb7_row12_col6, #T_c7eb7_row12_col7, #T_c7eb7_row12_col8, #T_c7eb7_row13_col0, #T_c7eb7_row13_col1, #T_c7eb7_row13_col2, #T_c7eb7_row13_col3, #T_c7eb7_row13_col4, #T_c7eb7_row13_col5, #T_c7eb7_row13_col6, #T_c7eb7_row13_col7, #T_c7eb7_row13_col8, #T_c7eb7_row14_col0, #T_c7eb7_row14_col1, #T_c7eb7_row14_col2, #T_c7eb7_row14_col3, #T_c7eb7_row14_col4, #T_c7eb7_row14_col5, #T_c7eb7_row14_col6, #T_c7eb7_row14_col7, #T_c7eb7_row14_col8, #T_c7eb7_row15_col0, #T_c7eb7_row15_col1, #T_c7eb7_row15_col2, #T_c7eb7_row15_col3, #T_c7eb7_row15_col4, #T_c7eb7_row15_col5, #T_c7eb7_row15_col6, #T_c7eb7_row15_col7, #T_c7eb7_row15_col8, #T_c7eb7_row16_col0, #T_c7eb7_row16_col1, #T_c7eb7_row16_col2, #T_c7eb7_row16_col3, #T_c7eb7_row16_col4, #T_c7eb7_row16_col5, #T_c7eb7_row16_col6, #T_c7eb7_row16_col7, #T_c7eb7_row16_col8, #T_c7eb7_row18_col0, #T_c7eb7_row18_col1, #T_c7eb7_row18_col2, #T_c7eb7_row18_col3, #T_c7eb7_row18_col4, #T_c7eb7_row18_col5, #T_c7eb7_row18_col6, #T_c7eb7_row18_col7, #T_c7eb7_row18_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_c7eb7">
  <thead>
    <tr>
      <th id="T_c7eb7_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_c7eb7_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_c7eb7_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_c7eb7_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_c7eb7_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_c7eb7_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_c7eb7_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_c7eb7_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_c7eb7_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_c7eb7_row0_col0" class="data row0 col0" >101</td>
      <td id="T_c7eb7_row0_col1" class="data row0 col1" >Fall 2022</td>
      <td id="T_c7eb7_row0_col2" class="data row0 col2" >CLSE101</td>
      <td id="T_c7eb7_row0_col3" class="data row0 col3" >001</td>
      <td id="T_c7eb7_row0_col4" class="data row0 col4" >INTRO TO ENGINEERING</td>
      <td id="T_c7eb7_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_c7eb7_row0_col6" class="data row0 col6" >41</td>
      <td id="T_c7eb7_row0_col7" class="data row0 col7" >123</td>
      <td id="T_c7eb7_row0_col8" class="data row0 col8" >Spangler</td>
    </tr>
    <tr>
      <td id="T_c7eb7_row1_col0" class="data row1 col0" >201</td>
      <td id="T_c7eb7_row1_col1" class="data row1 col1" >Fall 2022</td>
      <td id="T_c7eb7_row1_col2" class="data row1 col2" >CLSE201</td>
      <td id="T_c7eb7_row1_col3" class="data row1 col3" >001</td>
      <td id="T_c7eb7_row1_col4" class="data row1 col4" >CHEMICAL EGR FUNDAMENTALS I</td>
      <td id="T_c7eb7_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_c7eb7_row1_col6" class="data row1 col6" >33</td>
      <td id="T_c7eb7_row1_col7" class="data row1 col7" >66</td>
      <td id="T_c7eb7_row1_col8" class="data row1 col8" >Tang</td>
    </tr>
    <tr>
      <td id="T_c7eb7_row2_col0" class="data row2 col0" >301</td>
      <td id="T_c7eb7_row2_col1" class="data row2 col1" >Fall 2022</td>
      <td id="T_c7eb7_row2_col2" class="data row2 col2" >CLSE301</td>
      <td id="T_c7eb7_row2_col3" class="data row2 col3" >001</td>
      <td id="T_c7eb7_row2_col4" class="data row2 col4" >TRANSPORT PHENOMENA I</td>
      <td id="T_c7eb7_row2_col5" class="data row2 col5" >LEC</td>
      <td id="T_c7eb7_row2_col6" class="data row2 col6" >29</td>
      <td id="T_c7eb7_row2_col7" class="data row2 col7" >87</td>
      <td id="T_c7eb7_row2_col8" class="data row2 col8" >Ferri</td>
    </tr>
    <tr>
      <td id="T_c7eb7_row3_col0" class="data row3 col0" >305</td>
      <td id="T_c7eb7_row3_col1" class="data row3 col1" >Fall 2022</td>
      <td id="T_c7eb7_row3_col2" class="data row3 col2" >CLSE305</td>
      <td id="T_c7eb7_row3_col3" class="data row3 col3" >001</td>
      <td id="T_c7eb7_row3_col4" class="data row3 col4" >THERMODYNAMICS OF PHASE EQUIL</td>
      <td id="T_c7eb7_row3_col5" class="data row3 col5" >LEC</td>
      <td id="T_c7eb7_row3_col6" class="data row3 col6" >30</td>
      <td id="T_c7eb7_row3_col7" class="data row3 col7" >90</td>
      <td id="T_c7eb7_row3_col8" class="data row3 col8" >Yadavalli</td>
    </tr>
    <tr>
      <td id="T_c7eb7_row4_col0" class="data row4 col0" >409</td>
      <td id="T_c7eb7_row4_col1" class="data row4 col1" >Fall 2022</td>
      <td id="T_c7eb7_row4_col2" class="data row4 col2" >CLSE409</td>
      <td id="T_c7eb7_row4_col3" class="data row4 col3" >001</td>
      <td id="T_c7eb7_row4_col4" class="data row4 col4" >PROCESS CNTRL CHEM/LFSC ENGRNG</td>
      <td id="T_c7eb7_row4_col5" class="data row4 col5" >LEC</td>
      <td id="T_c7eb7_row4_col6" class="data row4 col6" >48</td>
      <td id="T_c7eb7_row4_col7" class="data row4 col7" >144</td>
      <td id="T_c7eb7_row4_col8" class="data row4 col8" >Jiang</td>
    </tr>
    <tr>
      <td id="T_c7eb7_row5_col0" class="data row5 col0" >585</td>
      <td id="T_c7eb7_row5_col1" class="data row5 col1" >Fall 2022</td>
      <td id="T_c7eb7_row5_col2" class="data row5 col2" >CLSE585</td>
      <td id="T_c7eb7_row5_col3" class="data row5 col3" >901</td>
      <td id="T_c7eb7_row5_col4" class="data row5 col4" >INTERFACIAL PHENOMENA</td>
      <td id="T_c7eb7_row5_col5" class="data row5 col5" >LEC</td>
      <td id="T_c7eb7_row5_col6" class="data row5 col6" >18</td>
      <td id="T_c7eb7_row5_col7" class="data row5 col7" >54</td>
      <td id="T_c7eb7_row5_col8" class="data row5 col8" >Ferri</td>
    </tr>
    <tr>
      <td id="T_c7eb7_row6_col0" class="data row6 col0" >650</td>
      <td id="T_c7eb7_row6_col1" class="data row6 col1" >Fall 2022</td>
      <td id="T_c7eb7_row6_col2" class="data row6 col2" >CLSE650</td>
      <td id="T_c7eb7_row6_col3" class="data row6 col3" >901</td>
      <td id="T_c7eb7_row6_col4" class="data row6 col4" >QUANTITATIVE ANALYS IN CLSE</td>
      <td id="T_c7eb7_row6_col5" class="data row6 col5" >LEC</td>
      <td id="T_c7eb7_row6_col6" class="data row6 col6" >6</td>
      <td id="T_c7eb7_row6_col7" class="data row6 col7" >18</td>
      <td id="T_c7eb7_row6_col8" class="data row6 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_c7eb7_row7_col0" class="data row7 col0" >650</td>
      <td id="T_c7eb7_row7_col1" class="data row7 col1" >Fall 2022</td>
      <td id="T_c7eb7_row7_col2" class="data row7 col2" >CLSE650</td>
      <td id="T_c7eb7_row7_col3" class="data row7 col3" >901</td>
      <td id="T_c7eb7_row7_col4" class="data row7 col4" >QUANTITATIVE ANALYS IN CLSE</td>
      <td id="T_c7eb7_row7_col5" class="data row7 col5" >LEC</td>
      <td id="T_c7eb7_row7_col6" class="data row7 col6" >6</td>
      <td id="T_c7eb7_row7_col7" class="data row7 col7" >18</td>
      <td id="T_c7eb7_row7_col8" class="data row7 col8" >McGill</td>
    </tr>
    <tr>
      <td id="T_c7eb7_row8_col0" class="data row8 col0" >654</td>
      <td id="T_c7eb7_row8_col1" class="data row8 col1" >Fall 2022</td>
      <td id="T_c7eb7_row8_col2" class="data row8 col2" >CLSE654</td>
      <td id="T_c7eb7_row8_col3" class="data row8 col3" >001</td>
      <td id="T_c7eb7_row8_col4" class="data row8 col4" >EQUILIBRIUM ANALYSIS</td>
      <td id="T_c7eb7_row8_col5" class="data row8 col5" >LEC</td>
      <td id="T_c7eb7_row8_col6" class="data row8 col6" >9</td>
      <td id="T_c7eb7_row8_col7" class="data row8 col7" >27</td>
      <td id="T_c7eb7_row8_col8" class="data row8 col8" >Peters</td>
    </tr>
    <tr>
      <td id="T_c7eb7_row9_col0" class="data row9 col0" >675</td>
      <td id="T_c7eb7_row9_col1" class="data row9 col1" >Fall 2022</td>
      <td id="T_c7eb7_row9_col2" class="data row9 col2" >CLSE675</td>
      <td id="T_c7eb7_row9_col3" class="data row9 col3" >001</td>
      <td id="T_c7eb7_row9_col4" class="data row9 col4" >POLYMERS IN MEDICINE</td>
      <td id="T_c7eb7_row9_col5" class="data row9 col5" >LEC</td>
      <td id="T_c7eb7_row9_col6" class="data row9 col6" >4</td>
      <td id="T_c7eb7_row9_col7" class="data row9 col7" >12</td>
      <td id="T_c7eb7_row9_col8" class="data row9 col8" >Wen</td>
    </tr>
    <tr>
      <td id="T_c7eb7_row10_col0" class="data row10 col0" >690</td>
      <td id="T_c7eb7_row10_col1" class="data row10 col1" >Fall 2022</td>
      <td id="T_c7eb7_row10_col2" class="data row10 col2" >CLSE690</td>
      <td id="T_c7eb7_row10_col3" class="data row10 col3" >001</td>
      <td id="T_c7eb7_row10_col4" class="data row10 col4" >RESEARCH SEMINAR</td>
      <td id="T_c7eb7_row10_col5" class="data row10 col5" >SEM</td>
      <td id="T_c7eb7_row10_col6" class="data row10 col6" >36</td>
      <td id="T_c7eb7_row10_col7" class="data row10 col7" >18</td>
      <td id="T_c7eb7_row10_col8" class="data row10 col8" >Jiang</td>
    </tr>
    <tr>
      <td id="T_c7eb7_row11_col0" class="data row11 col0" >691</td>
      <td id="T_c7eb7_row11_col1" class="data row11 col1" >Fall 2022</td>
      <td id="T_c7eb7_row11_col2" class="data row11 col2" >CLSE691</td>
      <td id="T_c7eb7_row11_col3" class="data row11 col3" >001</td>
      <td id="T_c7eb7_row11_col4" class="data row11 col4" >ST: TECHNICAL COMMUNICATION</td>
      <td id="T_c7eb7_row11_col5" class="data row11 col5" >LEC</td>
      <td id="T_c7eb7_row11_col6" class="data row11 col6" >4</td>
      <td id="T_c7eb7_row11_col7" class="data row11 col7" >4</td>
      <td id="T_c7eb7_row11_col8" class="data row11 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_c7eb7_row12_col0" class="data row12 col0" >691</td>
      <td id="T_c7eb7_row12_col1" class="data row12 col1" >Fall 2022</td>
      <td id="T_c7eb7_row12_col2" class="data row12 col2" >CLSE691</td>
      <td id="T_c7eb7_row12_col3" class="data row12 col3" >001</td>
      <td id="T_c7eb7_row12_col4" class="data row12 col4" >ST: TECHNICAL COMMUNICATION</td>
      <td id="T_c7eb7_row12_col5" class="data row12 col5" >LEC</td>
      <td id="T_c7eb7_row12_col6" class="data row12 col6" >4</td>
      <td id="T_c7eb7_row12_col7" class="data row12 col7" >4</td>
      <td id="T_c7eb7_row12_col8" class="data row12 col8" >Spangler</td>
    </tr>
    <tr>
      <td id="T_c7eb7_row13_col0" class="data row13 col0" >402</td>
      <td id="T_c7eb7_row13_col1" class="data row13 col1" >Fall 2022</td>
      <td id="T_c7eb7_row13_col2" class="data row13 col2" >ENGR402</td>
      <td id="T_c7eb7_row13_col3" class="data row13 col3" >002</td>
      <td id="T_c7eb7_row13_col4" class="data row13 col4" >SENIOR DESIGN STUDIO</td>
      <td id="T_c7eb7_row13_col5" class="data row13 col5" >LEC</td>
      <td id="T_c7eb7_row13_col6" class="data row13 col6" >44</td>
      <td id="T_c7eb7_row13_col7" class="data row13 col7" >44</td>
      <td id="T_c7eb7_row13_col8" class="data row13 col8" >Kuhn</td>
    </tr>
    <tr>
      <td id="T_c7eb7_row14_col0" class="data row14 col0" >497</td>
      <td id="T_c7eb7_row14_col1" class="data row14 col1" >Fall 2022</td>
      <td id="T_c7eb7_row14_col2" class="data row14 col2" >ENGR497</td>
      <td id="T_c7eb7_row14_col3" class="data row14 col3" >L11</td>
      <td id="T_c7eb7_row14_col4" class="data row14 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_c7eb7_row14_col5" class="data row14 col5" >VIP</td>
      <td id="T_c7eb7_row14_col6" class="data row14 col6" >1</td>
      <td id="T_c7eb7_row14_col7" class="data row14 col7" >1</td>
      <td id="T_c7eb7_row14_col8" class="data row14 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_c7eb7_row15_col0" class="data row15 col0" >497</td>
      <td id="T_c7eb7_row15_col1" class="data row15 col1" >Fall 2022</td>
      <td id="T_c7eb7_row15_col2" class="data row15 col2" >ENGR497</td>
      <td id="T_c7eb7_row15_col3" class="data row15 col3" >L13</td>
      <td id="T_c7eb7_row15_col4" class="data row15 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_c7eb7_row15_col5" class="data row15 col5" >VIP</td>
      <td id="T_c7eb7_row15_col6" class="data row15 col6" >1</td>
      <td id="T_c7eb7_row15_col7" class="data row15 col7" >2</td>
      <td id="T_c7eb7_row15_col8" class="data row15 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_c7eb7_row16_col0" class="data row16 col0" >497</td>
      <td id="T_c7eb7_row16_col1" class="data row16 col1" >Fall 2022</td>
      <td id="T_c7eb7_row16_col2" class="data row16 col2" >ENGR497</td>
      <td id="T_c7eb7_row16_col3" class="data row16 col3" >L35</td>
      <td id="T_c7eb7_row16_col4" class="data row16 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_c7eb7_row16_col5" class="data row16 col5" >VIP</td>
      <td id="T_c7eb7_row16_col6" class="data row16 col6" >5</td>
      <td id="T_c7eb7_row16_col7" class="data row16 col7" >5</td>
      <td id="T_c7eb7_row16_col8" class="data row16 col8" >Tang</td>
    </tr>
    <tr>
      <td id="T_c7eb7_row17_col0" class="data row17 col0" >591</td>
      <td id="T_c7eb7_row17_col1" class="data row17 col1" >Fall 2022</td>
      <td id="T_c7eb7_row17_col2" class="data row17 col2" >ENGR591</td>
      <td id="T_c7eb7_row17_col3" class="data row17 col3" >003</td>
      <td id="T_c7eb7_row17_col4" class="data row17 col4" >TOP: SYSTEMS ENGINEERING I</td>
      <td id="T_c7eb7_row17_col5" class="data row17 col5" >LEC</td>
      <td id="T_c7eb7_row17_col6" class="data row17 col6" >2</td>
      <td id="T_c7eb7_row17_col7" class="data row17 col7" >6</td>
      <td id="T_c7eb7_row17_col8" class="data row17 col8" >Ferri</td>
    </tr>
    <tr>
      <td id="T_c7eb7_row18_col0" class="data row18 col0" >691</td>
      <td id="T_c7eb7_row18_col1" class="data row18 col1" >Fall 2022</td>
      <td id="T_c7eb7_row18_col2" class="data row18 col2" >ENGR691</td>
      <td id="T_c7eb7_row18_col3" class="data row18 col3" >901</td>
      <td id="T_c7eb7_row18_col4" class="data row18 col4" >ST:ADV TOP IN INTERFACIAL PHEN</td>
      <td id="T_c7eb7_row18_col5" class="data row18 col5" >LEC</td>
      <td id="T_c7eb7_row18_col6" class="data row18 col6" >1</td>
      <td id="T_c7eb7_row18_col7" class="data row18 col7" >4</td>
      <td id="T_c7eb7_row18_col8" class="data row18 col8" >Ferri</td>
    </tr>
  </tbody>
</table>

:::

## Spring 2023

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_8b17e table {
  width: 100%;
  border-collapse: collapse;
}
#T_8b17e th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_8b17e th {
  border: 0;
}
#T_8b17e thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_8b17e tbody td:nth-child(1) {
  display: none;
}
#T_8b17e thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_8b17e tbody td:nth-child(2) {
  display: none;
}
#T_8b17e thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_8b17e tbody td:nth-child(8) {
  display: none;
}
#T_8b17e td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_8b17e td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_8b17e td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_8b17e td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_8b17e td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_8b17e td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_8b17e_row0_col0, #T_8b17e_row0_col1, #T_8b17e_row0_col2, #T_8b17e_row0_col3, #T_8b17e_row0_col4, #T_8b17e_row0_col5, #T_8b17e_row0_col6, #T_8b17e_row0_col7, #T_8b17e_row0_col8, #T_8b17e_row2_col0, #T_8b17e_row2_col1, #T_8b17e_row2_col2, #T_8b17e_row2_col3, #T_8b17e_row2_col4, #T_8b17e_row2_col5, #T_8b17e_row2_col6, #T_8b17e_row2_col7, #T_8b17e_row2_col8, #T_8b17e_row3_col0, #T_8b17e_row3_col1, #T_8b17e_row3_col2, #T_8b17e_row3_col3, #T_8b17e_row3_col4, #T_8b17e_row3_col5, #T_8b17e_row3_col6, #T_8b17e_row3_col7, #T_8b17e_row3_col8, #T_8b17e_row12_col0, #T_8b17e_row12_col1, #T_8b17e_row12_col2, #T_8b17e_row12_col3, #T_8b17e_row12_col4, #T_8b17e_row12_col5, #T_8b17e_row12_col6, #T_8b17e_row12_col7, #T_8b17e_row12_col8, #T_8b17e_row13_col0, #T_8b17e_row13_col1, #T_8b17e_row13_col2, #T_8b17e_row13_col3, #T_8b17e_row13_col4, #T_8b17e_row13_col5, #T_8b17e_row13_col6, #T_8b17e_row13_col7, #T_8b17e_row13_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_8b17e_row1_col0, #T_8b17e_row1_col1, #T_8b17e_row1_col2, #T_8b17e_row1_col3, #T_8b17e_row1_col4, #T_8b17e_row1_col5, #T_8b17e_row1_col6, #T_8b17e_row1_col7, #T_8b17e_row1_col8, #T_8b17e_row4_col0, #T_8b17e_row4_col1, #T_8b17e_row4_col2, #T_8b17e_row4_col3, #T_8b17e_row4_col4, #T_8b17e_row4_col5, #T_8b17e_row4_col6, #T_8b17e_row4_col7, #T_8b17e_row4_col8, #T_8b17e_row5_col0, #T_8b17e_row5_col1, #T_8b17e_row5_col2, #T_8b17e_row5_col3, #T_8b17e_row5_col4, #T_8b17e_row5_col5, #T_8b17e_row5_col6, #T_8b17e_row5_col7, #T_8b17e_row5_col8, #T_8b17e_row6_col0, #T_8b17e_row6_col1, #T_8b17e_row6_col2, #T_8b17e_row6_col3, #T_8b17e_row6_col4, #T_8b17e_row6_col5, #T_8b17e_row6_col6, #T_8b17e_row6_col7, #T_8b17e_row6_col8, #T_8b17e_row7_col0, #T_8b17e_row7_col1, #T_8b17e_row7_col2, #T_8b17e_row7_col3, #T_8b17e_row7_col4, #T_8b17e_row7_col5, #T_8b17e_row7_col6, #T_8b17e_row7_col7, #T_8b17e_row7_col8, #T_8b17e_row8_col0, #T_8b17e_row8_col1, #T_8b17e_row8_col2, #T_8b17e_row8_col3, #T_8b17e_row8_col4, #T_8b17e_row8_col5, #T_8b17e_row8_col6, #T_8b17e_row8_col7, #T_8b17e_row8_col8, #T_8b17e_row9_col0, #T_8b17e_row9_col1, #T_8b17e_row9_col2, #T_8b17e_row9_col3, #T_8b17e_row9_col4, #T_8b17e_row9_col5, #T_8b17e_row9_col6, #T_8b17e_row9_col7, #T_8b17e_row9_col8, #T_8b17e_row10_col0, #T_8b17e_row10_col1, #T_8b17e_row10_col2, #T_8b17e_row10_col3, #T_8b17e_row10_col4, #T_8b17e_row10_col5, #T_8b17e_row10_col6, #T_8b17e_row10_col7, #T_8b17e_row10_col8, #T_8b17e_row11_col0, #T_8b17e_row11_col1, #T_8b17e_row11_col2, #T_8b17e_row11_col3, #T_8b17e_row11_col4, #T_8b17e_row11_col5, #T_8b17e_row11_col6, #T_8b17e_row11_col7, #T_8b17e_row11_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_8b17e">
  <thead>
    <tr>
      <th id="T_8b17e_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_8b17e_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_8b17e_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_8b17e_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_8b17e_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_8b17e_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_8b17e_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_8b17e_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_8b17e_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_8b17e_row0_col0" class="data row0 col0" >115</td>
      <td id="T_8b17e_row0_col1" class="data row0 col1" >Spring 2023</td>
      <td id="T_8b17e_row0_col2" class="data row0 col2" >CLSE115</td>
      <td id="T_8b17e_row0_col3" class="data row0 col3" >001</td>
      <td id="T_8b17e_row0_col4" class="data row0 col4" >INTRO TO PROGRAMMING</td>
      <td id="T_8b17e_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_8b17e_row0_col6" class="data row0 col6" >41</td>
      <td id="T_8b17e_row0_col7" class="data row0 col7" >82</td>
      <td id="T_8b17e_row0_col8" class="data row0 col8" >McGill</td>
    </tr>
    <tr>
      <td id="T_8b17e_row1_col0" class="data row1 col0" >202</td>
      <td id="T_8b17e_row1_col1" class="data row1 col1" >Spring 2023</td>
      <td id="T_8b17e_row1_col2" class="data row1 col2" >CLSE202</td>
      <td id="T_8b17e_row1_col3" class="data row1 col3" >001</td>
      <td id="T_8b17e_row1_col4" class="data row1 col4" >CHEMICAL ENGINEERING FUND II</td>
      <td id="T_8b17e_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_8b17e_row1_col6" class="data row1 col6" >21</td>
      <td id="T_8b17e_row1_col7" class="data row1 col7" >42</td>
      <td id="T_8b17e_row1_col8" class="data row1 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_8b17e_row2_col0" class="data row2 col0" >302</td>
      <td id="T_8b17e_row2_col1" class="data row2 col1" >Spring 2023</td>
      <td id="T_8b17e_row2_col2" class="data row2 col2" >CLSE302</td>
      <td id="T_8b17e_row2_col3" class="data row2 col3" >001</td>
      <td id="T_8b17e_row2_col4" class="data row2 col4" >TRANSPORT PHENOMENA II</td>
      <td id="T_8b17e_row2_col5" class="data row2 col5" >LEC</td>
      <td id="T_8b17e_row2_col6" class="data row2 col6" >33</td>
      <td id="T_8b17e_row2_col7" class="data row2 col7" >66</td>
      <td id="T_8b17e_row2_col8" class="data row2 col8" >Peters</td>
    </tr>
    <tr>
      <td id="T_8b17e_row3_col0" class="data row3 col0" >580</td>
      <td id="T_8b17e_row3_col1" class="data row3 col1" >Spring 2023</td>
      <td id="T_8b17e_row3_col2" class="data row3 col2" >CLSE580</td>
      <td id="T_8b17e_row3_col3" class="data row3 col3" >901</td>
      <td id="T_8b17e_row3_col4" class="data row3 col4" >SUSTAINABLE CHEMICAL ENGR</td>
      <td id="T_8b17e_row3_col5" class="data row3 col5" >LEC</td>
      <td id="T_8b17e_row3_col6" class="data row3 col6" >12</td>
      <td id="T_8b17e_row3_col7" class="data row3 col7" >36</td>
      <td id="T_8b17e_row3_col8" class="data row3 col8" >Tang</td>
    </tr>
    <tr>
      <td id="T_8b17e_row4_col0" class="data row4 col0" >655</td>
      <td id="T_8b17e_row4_col1" class="data row4 col1" >Spring 2023</td>
      <td id="T_8b17e_row4_col2" class="data row4 col2" >CLSE655</td>
      <td id="T_8b17e_row4_col3" class="data row4 col3" >001</td>
      <td id="T_8b17e_row4_col4" class="data row4 col4" >NONEQUILIBRIUM ANALYSIS</td>
      <td id="T_8b17e_row4_col5" class="data row4 col5" >LEC</td>
      <td id="T_8b17e_row4_col6" class="data row4 col6" >9</td>
      <td id="T_8b17e_row4_col7" class="data row4 col7" >27</td>
      <td id="T_8b17e_row4_col8" class="data row4 col8" >Yadavalli</td>
    </tr>
    <tr>
      <td id="T_8b17e_row5_col0" class="data row5 col0" >656</td>
      <td id="T_8b17e_row5_col1" class="data row5 col1" >Spring 2023</td>
      <td id="T_8b17e_row5_col2" class="data row5 col2" >CLSE656</td>
      <td id="T_8b17e_row5_col3" class="data row5 col3" >001</td>
      <td id="T_8b17e_row5_col4" class="data row5 col4" >ADV CHEMICAL REACTION ENGR</td>
      <td id="T_8b17e_row5_col5" class="data row5 col5" >LEC</td>
      <td id="T_8b17e_row5_col6" class="data row5 col6" >12</td>
      <td id="T_8b17e_row5_col7" class="data row5 col7" >36</td>
      <td id="T_8b17e_row5_col8" class="data row5 col8" >Wen</td>
    </tr>
    <tr>
      <td id="T_8b17e_row6_col0" class="data row6 col0" >690</td>
      <td id="T_8b17e_row6_col1" class="data row6 col1" >Spring 2023</td>
      <td id="T_8b17e_row6_col2" class="data row6 col2" >CLSE690</td>
      <td id="T_8b17e_row6_col3" class="data row6 col3" >001</td>
      <td id="T_8b17e_row6_col4" class="data row6 col4" >RESEARCH SEMINAR</td>
      <td id="T_8b17e_row6_col5" class="data row6 col5" >SEM</td>
      <td id="T_8b17e_row6_col6" class="data row6 col6" >18</td>
      <td id="T_8b17e_row6_col7" class="data row6 col7" >18</td>
      <td id="T_8b17e_row6_col8" class="data row6 col8" >Jiang</td>
    </tr>
    <tr>
      <td id="T_8b17e_row7_col0" class="data row7 col0" >691</td>
      <td id="T_8b17e_row7_col1" class="data row7 col1" >Spring 2023</td>
      <td id="T_8b17e_row7_col2" class="data row7 col2" >CLSE691</td>
      <td id="T_8b17e_row7_col3" class="data row7 col3" >001</td>
      <td id="T_8b17e_row7_col4" class="data row7 col4" >SP TP: STEM CELL ENGINEERING</td>
      <td id="T_8b17e_row7_col5" class="data row7 col5" >LEC</td>
      <td id="T_8b17e_row7_col6" class="data row7 col6" >6</td>
      <td id="T_8b17e_row7_col7" class="data row7 col7" >18</td>
      <td id="T_8b17e_row7_col8" class="data row7 col8" >Wen</td>
    </tr>
    <tr>
      <td id="T_8b17e_row8_col0" class="data row8 col0" >403</td>
      <td id="T_8b17e_row8_col1" class="data row8 col1" >Spring 2023</td>
      <td id="T_8b17e_row8_col2" class="data row8 col2" >ENGR403</td>
      <td id="T_8b17e_row8_col3" class="data row8 col3" >002</td>
      <td id="T_8b17e_row8_col4" class="data row8 col4" >SENIOR DESIGN STUDIO</td>
      <td id="T_8b17e_row8_col5" class="data row8 col5" >LEC</td>
      <td id="T_8b17e_row8_col6" class="data row8 col6" >44</td>
      <td id="T_8b17e_row8_col7" class="data row8 col7" >44</td>
      <td id="T_8b17e_row8_col8" class="data row8 col8" >Kuhn</td>
    </tr>
    <tr>
      <td id="T_8b17e_row9_col0" class="data row9 col0" >497</td>
      <td id="T_8b17e_row9_col1" class="data row9 col1" >Spring 2023</td>
      <td id="T_8b17e_row9_col2" class="data row9 col2" >ENGR497</td>
      <td id="T_8b17e_row9_col3" class="data row9 col3" >L12</td>
      <td id="T_8b17e_row9_col4" class="data row9 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_8b17e_row9_col5" class="data row9 col5" >VIP</td>
      <td id="T_8b17e_row9_col6" class="data row9 col6" >1</td>
      <td id="T_8b17e_row9_col7" class="data row9 col7" >1</td>
      <td id="T_8b17e_row9_col8" class="data row9 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_8b17e_row10_col0" class="data row10 col0" >497</td>
      <td id="T_8b17e_row10_col1" class="data row10 col1" >Spring 2023</td>
      <td id="T_8b17e_row10_col2" class="data row10 col2" >ENGR497</td>
      <td id="T_8b17e_row10_col3" class="data row10 col3" >L35</td>
      <td id="T_8b17e_row10_col4" class="data row10 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_8b17e_row10_col5" class="data row10 col5" >VIP</td>
      <td id="T_8b17e_row10_col6" class="data row10 col6" >3</td>
      <td id="T_8b17e_row10_col7" class="data row10 col7" >3</td>
      <td id="T_8b17e_row10_col8" class="data row10 col8" >Tang</td>
    </tr>
    <tr>
      <td id="T_8b17e_row11_col0" class="data row11 col0" >497</td>
      <td id="T_8b17e_row11_col1" class="data row11 col1" >Spring 2023</td>
      <td id="T_8b17e_row11_col2" class="data row11 col2" >ENGR497</td>
      <td id="T_8b17e_row11_col3" class="data row11 col3" >L36</td>
      <td id="T_8b17e_row11_col4" class="data row11 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_8b17e_row11_col5" class="data row11 col5" >VIP</td>
      <td id="T_8b17e_row11_col6" class="data row11 col6" >1</td>
      <td id="T_8b17e_row11_col7" class="data row11 col7" >2</td>
      <td id="T_8b17e_row11_col8" class="data row11 col8" >Tang</td>
    </tr>
    <tr>
      <td id="T_8b17e_row12_col0" class="data row12 col0" >591</td>
      <td id="T_8b17e_row12_col1" class="data row12 col1" >Spring 2023</td>
      <td id="T_8b17e_row12_col2" class="data row12 col2" >ENGR591</td>
      <td id="T_8b17e_row12_col3" class="data row12 col3" >001</td>
      <td id="T_8b17e_row12_col4" class="data row12 col4" >TOP:PROCESS ANALYTIC TECHNOL</td>
      <td id="T_8b17e_row12_col5" class="data row12 col5" >LEC</td>
      <td id="T_8b17e_row12_col6" class="data row12 col6" >14</td>
      <td id="T_8b17e_row12_col7" class="data row12 col7" >42</td>
      <td id="T_8b17e_row12_col8" class="data row12 col8" >Jiang</td>
    </tr>
    <tr>
      <td id="T_8b17e_row13_col0" class="data row13 col0" >591</td>
      <td id="T_8b17e_row13_col1" class="data row13 col1" >Spring 2023</td>
      <td id="T_8b17e_row13_col2" class="data row13 col2" >ENGR591</td>
      <td id="T_8b17e_row13_col3" class="data row13 col3" >906</td>
      <td id="T_8b17e_row13_col4" class="data row13 col4" >TOP: BIOPRINTING & NANOTOXICOL</td>
      <td id="T_8b17e_row13_col5" class="data row13 col5" >LEC</td>
      <td id="T_8b17e_row13_col6" class="data row13 col6" >2</td>
      <td id="T_8b17e_row13_col7" class="data row13 col7" >6</td>
      <td id="T_8b17e_row13_col8" class="data row13 col8" >Lewinski</td>
    </tr>
  </tbody>
</table>

:::

## Summer 2023

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_53b73 table {
  width: 100%;
  border-collapse: collapse;
}
#T_53b73 th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_53b73 th {
  border: 0;
}
#T_53b73 thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_53b73 tbody td:nth-child(1) {
  display: none;
}
#T_53b73 thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_53b73 tbody td:nth-child(2) {
  display: none;
}
#T_53b73 thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_53b73 tbody td:nth-child(8) {
  display: none;
}
#T_53b73 td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_53b73 td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_53b73 td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_53b73 td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_53b73 td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_53b73 td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_53b73_row0_col0, #T_53b73_row0_col1, #T_53b73_row0_col2, #T_53b73_row0_col3, #T_53b73_row0_col4, #T_53b73_row0_col5, #T_53b73_row0_col6, #T_53b73_row0_col7, #T_53b73_row0_col8, #T_53b73_row1_col0, #T_53b73_row1_col1, #T_53b73_row1_col2, #T_53b73_row1_col3, #T_53b73_row1_col4, #T_53b73_row1_col5, #T_53b73_row1_col6, #T_53b73_row1_col7, #T_53b73_row1_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
</style>
<table id="T_53b73">
  <thead>
    <tr>
      <th id="T_53b73_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_53b73_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_53b73_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_53b73_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_53b73_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_53b73_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_53b73_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_53b73_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_53b73_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_53b73_row0_col0" class="data row0 col0" >201</td>
      <td id="T_53b73_row0_col1" class="data row0 col1" >Summer 2023</td>
      <td id="T_53b73_row0_col2" class="data row0 col2" >CLSE201</td>
      <td id="T_53b73_row0_col3" class="data row0 col3" >001</td>
      <td id="T_53b73_row0_col4" class="data row0 col4" >CHEMICAL EGR FUNDAMENTALS I</td>
      <td id="T_53b73_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_53b73_row0_col6" class="data row0 col6" >12</td>
      <td id="T_53b73_row0_col7" class="data row0 col7" >48</td>
      <td id="T_53b73_row0_col8" class="data row0 col8" >Peters</td>
    </tr>
    <tr>
      <td id="T_53b73_row1_col0" class="data row1 col0" >202</td>
      <td id="T_53b73_row1_col1" class="data row1 col1" >Summer 2023</td>
      <td id="T_53b73_row1_col2" class="data row1 col2" >CLSE202</td>
      <td id="T_53b73_row1_col3" class="data row1 col3" >001</td>
      <td id="T_53b73_row1_col4" class="data row1 col4" >CHEMICAL ENGINEERING FUND II</td>
      <td id="T_53b73_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_53b73_row1_col6" class="data row1 col6" >16</td>
      <td id="T_53b73_row1_col7" class="data row1 col7" >64</td>
      <td id="T_53b73_row1_col8" class="data row1 col8" >Peters</td>
    </tr>
  </tbody>
</table>

:::

# AY21-22

This section list instructor activity for the academic year AY21-22 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## Fall 2021

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_201b1 table {
  width: 100%;
  border-collapse: collapse;
}
#T_201b1 th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_201b1 th {
  border: 0;
}
#T_201b1 thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_201b1 tbody td:nth-child(1) {
  display: none;
}
#T_201b1 thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_201b1 tbody td:nth-child(2) {
  display: none;
}
#T_201b1 thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_201b1 tbody td:nth-child(8) {
  display: none;
}
#T_201b1 td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_201b1 td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_201b1 td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_201b1 td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_201b1 td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_201b1 td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_201b1_row0_col0, #T_201b1_row0_col1, #T_201b1_row0_col2, #T_201b1_row0_col3, #T_201b1_row0_col4, #T_201b1_row0_col5, #T_201b1_row0_col6, #T_201b1_row0_col7, #T_201b1_row0_col8, #T_201b1_row5_col0, #T_201b1_row5_col1, #T_201b1_row5_col2, #T_201b1_row5_col3, #T_201b1_row5_col4, #T_201b1_row5_col5, #T_201b1_row5_col6, #T_201b1_row5_col7, #T_201b1_row5_col8, #T_201b1_row6_col0, #T_201b1_row6_col1, #T_201b1_row6_col2, #T_201b1_row6_col3, #T_201b1_row6_col4, #T_201b1_row6_col5, #T_201b1_row6_col6, #T_201b1_row6_col7, #T_201b1_row6_col8, #T_201b1_row7_col0, #T_201b1_row7_col1, #T_201b1_row7_col2, #T_201b1_row7_col3, #T_201b1_row7_col4, #T_201b1_row7_col5, #T_201b1_row7_col6, #T_201b1_row7_col7, #T_201b1_row7_col8, #T_201b1_row8_col0, #T_201b1_row8_col1, #T_201b1_row8_col2, #T_201b1_row8_col3, #T_201b1_row8_col4, #T_201b1_row8_col5, #T_201b1_row8_col6, #T_201b1_row8_col7, #T_201b1_row8_col8, #T_201b1_row9_col0, #T_201b1_row9_col1, #T_201b1_row9_col2, #T_201b1_row9_col3, #T_201b1_row9_col4, #T_201b1_row9_col5, #T_201b1_row9_col6, #T_201b1_row9_col7, #T_201b1_row9_col8, #T_201b1_row10_col0, #T_201b1_row10_col1, #T_201b1_row10_col2, #T_201b1_row10_col3, #T_201b1_row10_col4, #T_201b1_row10_col5, #T_201b1_row10_col6, #T_201b1_row10_col7, #T_201b1_row10_col8, #T_201b1_row11_col0, #T_201b1_row11_col1, #T_201b1_row11_col2, #T_201b1_row11_col3, #T_201b1_row11_col4, #T_201b1_row11_col5, #T_201b1_row11_col6, #T_201b1_row11_col7, #T_201b1_row11_col8, #T_201b1_row12_col0, #T_201b1_row12_col1, #T_201b1_row12_col2, #T_201b1_row12_col3, #T_201b1_row12_col4, #T_201b1_row12_col5, #T_201b1_row12_col6, #T_201b1_row12_col7, #T_201b1_row12_col8, #T_201b1_row13_col0, #T_201b1_row13_col1, #T_201b1_row13_col2, #T_201b1_row13_col3, #T_201b1_row13_col4, #T_201b1_row13_col5, #T_201b1_row13_col6, #T_201b1_row13_col7, #T_201b1_row13_col8, #T_201b1_row14_col0, #T_201b1_row14_col1, #T_201b1_row14_col2, #T_201b1_row14_col3, #T_201b1_row14_col4, #T_201b1_row14_col5, #T_201b1_row14_col6, #T_201b1_row14_col7, #T_201b1_row14_col8, #T_201b1_row16_col0, #T_201b1_row16_col1, #T_201b1_row16_col2, #T_201b1_row16_col3, #T_201b1_row16_col4, #T_201b1_row16_col5, #T_201b1_row16_col6, #T_201b1_row16_col7, #T_201b1_row16_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_201b1_row1_col0, #T_201b1_row1_col1, #T_201b1_row1_col2, #T_201b1_row1_col3, #T_201b1_row1_col4, #T_201b1_row1_col5, #T_201b1_row1_col6, #T_201b1_row1_col7, #T_201b1_row1_col8, #T_201b1_row2_col0, #T_201b1_row2_col1, #T_201b1_row2_col2, #T_201b1_row2_col3, #T_201b1_row2_col4, #T_201b1_row2_col5, #T_201b1_row2_col6, #T_201b1_row2_col7, #T_201b1_row2_col8, #T_201b1_row3_col0, #T_201b1_row3_col1, #T_201b1_row3_col2, #T_201b1_row3_col3, #T_201b1_row3_col4, #T_201b1_row3_col5, #T_201b1_row3_col6, #T_201b1_row3_col7, #T_201b1_row3_col8, #T_201b1_row4_col0, #T_201b1_row4_col1, #T_201b1_row4_col2, #T_201b1_row4_col3, #T_201b1_row4_col4, #T_201b1_row4_col5, #T_201b1_row4_col6, #T_201b1_row4_col7, #T_201b1_row4_col8, #T_201b1_row15_col0, #T_201b1_row15_col1, #T_201b1_row15_col2, #T_201b1_row15_col3, #T_201b1_row15_col4, #T_201b1_row15_col5, #T_201b1_row15_col6, #T_201b1_row15_col7, #T_201b1_row15_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_201b1">
  <thead>
    <tr>
      <th id="T_201b1_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_201b1_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_201b1_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_201b1_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_201b1_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_201b1_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_201b1_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_201b1_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_201b1_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_201b1_row0_col0" class="data row0 col0" >201</td>
      <td id="T_201b1_row0_col1" class="data row0 col1" >Fall 2021</td>
      <td id="T_201b1_row0_col2" class="data row0 col2" >CLSE201</td>
      <td id="T_201b1_row0_col3" class="data row0 col3" >001</td>
      <td id="T_201b1_row0_col4" class="data row0 col4" >CHEMICAL EGR FUNDAMENTALS I</td>
      <td id="T_201b1_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_201b1_row0_col6" class="data row0 col6" >20</td>
      <td id="T_201b1_row0_col7" class="data row0 col7" >40</td>
      <td id="T_201b1_row0_col8" class="data row0 col8" >Tang</td>
    </tr>
    <tr>
      <td id="T_201b1_row1_col0" class="data row1 col0" >301</td>
      <td id="T_201b1_row1_col1" class="data row1 col1" >Fall 2021</td>
      <td id="T_201b1_row1_col2" class="data row1 col2" >CLSE301</td>
      <td id="T_201b1_row1_col3" class="data row1 col3" >001</td>
      <td id="T_201b1_row1_col4" class="data row1 col4" >TRANSPORT PHENOMENA I</td>
      <td id="T_201b1_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_201b1_row1_col6" class="data row1 col6" >25</td>
      <td id="T_201b1_row1_col7" class="data row1 col7" >75</td>
      <td id="T_201b1_row1_col8" class="data row1 col8" >Ferri</td>
    </tr>
    <tr>
      <td id="T_201b1_row2_col0" class="data row2 col0" >301</td>
      <td id="T_201b1_row2_col1" class="data row2 col1" >Fall 2021</td>
      <td id="T_201b1_row2_col2" class="data row2 col2" >CLSE301</td>
      <td id="T_201b1_row2_col3" class="data row2 col3" >002</td>
      <td id="T_201b1_row2_col4" class="data row2 col4" >TRANSPORT PHENOMENA I</td>
      <td id="T_201b1_row2_col5" class="data row2 col5" >LEC</td>
      <td id="T_201b1_row2_col6" class="data row2 col6" >33</td>
      <td id="T_201b1_row2_col7" class="data row2 col7" >99</td>
      <td id="T_201b1_row2_col8" class="data row2 col8" >Ferri</td>
    </tr>
    <tr>
      <td id="T_201b1_row3_col0" class="data row3 col0" >305</td>
      <td id="T_201b1_row3_col1" class="data row3 col1" >Fall 2021</td>
      <td id="T_201b1_row3_col2" class="data row3 col2" >CLSE305</td>
      <td id="T_201b1_row3_col3" class="data row3 col3" >001</td>
      <td id="T_201b1_row3_col4" class="data row3 col4" >THERMODYNAMICS OF PHASE EQUIL</td>
      <td id="T_201b1_row3_col5" class="data row3 col5" >LEC</td>
      <td id="T_201b1_row3_col6" class="data row3 col6" >23</td>
      <td id="T_201b1_row3_col7" class="data row3 col7" >69</td>
      <td id="T_201b1_row3_col8" class="data row3 col8" >Yadavalli</td>
    </tr>
    <tr>
      <td id="T_201b1_row4_col0" class="data row4 col0" >305</td>
      <td id="T_201b1_row4_col1" class="data row4 col1" >Fall 2021</td>
      <td id="T_201b1_row4_col2" class="data row4 col2" >CLSE305</td>
      <td id="T_201b1_row4_col3" class="data row4 col3" >002</td>
      <td id="T_201b1_row4_col4" class="data row4 col4" >THERMODYNAMICS OF PHASE EQUIL</td>
      <td id="T_201b1_row4_col5" class="data row4 col5" >LEC</td>
      <td id="T_201b1_row4_col6" class="data row4 col6" >32</td>
      <td id="T_201b1_row4_col7" class="data row4 col7" >96</td>
      <td id="T_201b1_row4_col8" class="data row4 col8" >Yadavalli</td>
    </tr>
    <tr>
      <td id="T_201b1_row5_col0" class="data row5 col0" >409</td>
      <td id="T_201b1_row5_col1" class="data row5 col1" >Fall 2021</td>
      <td id="T_201b1_row5_col2" class="data row5 col2" >CLSE409</td>
      <td id="T_201b1_row5_col3" class="data row5 col3" >001</td>
      <td id="T_201b1_row5_col4" class="data row5 col4" >PROCESS CNTRL CHEM/LFSC ENGRNG</td>
      <td id="T_201b1_row5_col5" class="data row5 col5" >LEC</td>
      <td id="T_201b1_row5_col6" class="data row5 col6" >39</td>
      <td id="T_201b1_row5_col7" class="data row5 col7" >117</td>
      <td id="T_201b1_row5_col8" class="data row5 col8" >Jiang</td>
    </tr>
    <tr>
      <td id="T_201b1_row6_col0" class="data row6 col0" >409</td>
      <td id="T_201b1_row6_col1" class="data row6 col1" >Fall 2021</td>
      <td id="T_201b1_row6_col2" class="data row6 col2" >CLSE409</td>
      <td id="T_201b1_row6_col3" class="data row6 col3" >002</td>
      <td id="T_201b1_row6_col4" class="data row6 col4" >PROCESS CNTRL CHEM/LFSC ENGRNG</td>
      <td id="T_201b1_row6_col5" class="data row6 col5" >LEC</td>
      <td id="T_201b1_row6_col6" class="data row6 col6" >19</td>
      <td id="T_201b1_row6_col7" class="data row6 col7" >57</td>
      <td id="T_201b1_row6_col8" class="data row6 col8" >Jiang</td>
    </tr>
    <tr>
      <td id="T_201b1_row7_col0" class="data row7 col0" >650</td>
      <td id="T_201b1_row7_col1" class="data row7 col1" >Fall 2021</td>
      <td id="T_201b1_row7_col2" class="data row7 col2" >CLSE650</td>
      <td id="T_201b1_row7_col3" class="data row7 col3" >001</td>
      <td id="T_201b1_row7_col4" class="data row7 col4" >QUANTITATIVE ANALYS IN CLSE</td>
      <td id="T_201b1_row7_col5" class="data row7 col5" >LEC</td>
      <td id="T_201b1_row7_col6" class="data row7 col6" >8</td>
      <td id="T_201b1_row7_col7" class="data row7 col7" >12</td>
      <td id="T_201b1_row7_col8" class="data row7 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_201b1_row8_col0" class="data row8 col0" >654</td>
      <td id="T_201b1_row8_col1" class="data row8 col1" >Fall 2021</td>
      <td id="T_201b1_row8_col2" class="data row8 col2" >CLSE654</td>
      <td id="T_201b1_row8_col3" class="data row8 col3" >001</td>
      <td id="T_201b1_row8_col4" class="data row8 col4" >EQUILIBRIUM ANALYSIS</td>
      <td id="T_201b1_row8_col5" class="data row8 col5" >LEC</td>
      <td id="T_201b1_row8_col6" class="data row8 col6" >6</td>
      <td id="T_201b1_row8_col7" class="data row8 col7" >18</td>
      <td id="T_201b1_row8_col8" class="data row8 col8" >Peters</td>
    </tr>
    <tr>
      <td id="T_201b1_row9_col0" class="data row9 col0" >675</td>
      <td id="T_201b1_row9_col1" class="data row9 col1" >Fall 2021</td>
      <td id="T_201b1_row9_col2" class="data row9 col2" >CLSE675</td>
      <td id="T_201b1_row9_col3" class="data row9 col3" >001</td>
      <td id="T_201b1_row9_col4" class="data row9 col4" >POLYMERS IN MEDICINE</td>
      <td id="T_201b1_row9_col5" class="data row9 col5" >LEC</td>
      <td id="T_201b1_row9_col6" class="data row9 col6" >10</td>
      <td id="T_201b1_row9_col7" class="data row9 col7" >15</td>
      <td id="T_201b1_row9_col8" class="data row9 col8" >Wen</td>
    </tr>
    <tr>
      <td id="T_201b1_row10_col0" class="data row10 col0" >690</td>
      <td id="T_201b1_row10_col1" class="data row10 col1" >Fall 2021</td>
      <td id="T_201b1_row10_col2" class="data row10 col2" >CLSE690</td>
      <td id="T_201b1_row10_col3" class="data row10 col3" >001</td>
      <td id="T_201b1_row10_col4" class="data row10 col4" >RESEARCH SEMINAR</td>
      <td id="T_201b1_row10_col5" class="data row10 col5" >SEM</td>
      <td id="T_201b1_row10_col6" class="data row10 col6" >46</td>
      <td id="T_201b1_row10_col7" class="data row10 col7" >23</td>
      <td id="T_201b1_row10_col8" class="data row10 col8" >Jiang</td>
    </tr>
    <tr>
      <td id="T_201b1_row11_col0" class="data row11 col0" >402</td>
      <td id="T_201b1_row11_col1" class="data row11 col1" >Fall 2021</td>
      <td id="T_201b1_row11_col2" class="data row11 col2" >ENGR402</td>
      <td id="T_201b1_row11_col3" class="data row11 col3" >002</td>
      <td id="T_201b1_row11_col4" class="data row11 col4" >SENIOR DESIGN STUDIO</td>
      <td id="T_201b1_row11_col5" class="data row11 col5" >LEC</td>
      <td id="T_201b1_row11_col6" class="data row11 col6" >56</td>
      <td id="T_201b1_row11_col7" class="data row11 col7" >56</td>
      <td id="T_201b1_row11_col8" class="data row11 col8" >Ferri</td>
    </tr>
    <tr>
      <td id="T_201b1_row12_col0" class="data row12 col0" >497</td>
      <td id="T_201b1_row12_col1" class="data row12 col1" >Fall 2021</td>
      <td id="T_201b1_row12_col2" class="data row12 col2" >ENGR497</td>
      <td id="T_201b1_row12_col3" class="data row12 col3" >L11</td>
      <td id="T_201b1_row12_col4" class="data row12 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_201b1_row12_col5" class="data row12 col5" >VIP</td>
      <td id="T_201b1_row12_col6" class="data row12 col6" >2</td>
      <td id="T_201b1_row12_col7" class="data row12 col7" >2</td>
      <td id="T_201b1_row12_col8" class="data row12 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_201b1_row13_col0" class="data row13 col0" >497</td>
      <td id="T_201b1_row13_col1" class="data row13 col1" >Fall 2021</td>
      <td id="T_201b1_row13_col2" class="data row13 col2" >ENGR497</td>
      <td id="T_201b1_row13_col3" class="data row13 col3" >L13</td>
      <td id="T_201b1_row13_col4" class="data row13 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_201b1_row13_col5" class="data row13 col5" >VIP</td>
      <td id="T_201b1_row13_col6" class="data row13 col6" >1</td>
      <td id="T_201b1_row13_col7" class="data row13 col7" >2</td>
      <td id="T_201b1_row13_col8" class="data row13 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_201b1_row14_col0" class="data row14 col0" >497</td>
      <td id="T_201b1_row14_col1" class="data row14 col1" >Fall 2021</td>
      <td id="T_201b1_row14_col2" class="data row14 col2" >ENGR497</td>
      <td id="T_201b1_row14_col3" class="data row14 col3" >L35</td>
      <td id="T_201b1_row14_col4" class="data row14 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_201b1_row14_col5" class="data row14 col5" >VIP</td>
      <td id="T_201b1_row14_col6" class="data row14 col6" >7</td>
      <td id="T_201b1_row14_col7" class="data row14 col7" >7</td>
      <td id="T_201b1_row14_col8" class="data row14 col8" >Tang</td>
    </tr>
    <tr>
      <td id="T_201b1_row15_col0" class="data row15 col0" >591</td>
      <td id="T_201b1_row15_col1" class="data row15 col1" >Fall 2021</td>
      <td id="T_201b1_row15_col2" class="data row15 col2" >ENGR591</td>
      <td id="T_201b1_row15_col3" class="data row15 col3" >904</td>
      <td id="T_201b1_row15_col4" class="data row15 col4" >ST: INTERFACIAL PHENOMENA</td>
      <td id="T_201b1_row15_col5" class="data row15 col5" >LEC</td>
      <td id="T_201b1_row15_col6" class="data row15 col6" >13</td>
      <td id="T_201b1_row15_col7" class="data row15 col7" >39</td>
      <td id="T_201b1_row15_col8" class="data row15 col8" >Ferri</td>
    </tr>
    <tr>
      <td id="T_201b1_row16_col0" class="data row16 col0" >691</td>
      <td id="T_201b1_row16_col1" class="data row16 col1" >Fall 2021</td>
      <td id="T_201b1_row16_col2" class="data row16 col2" >ENGR691</td>
      <td id="T_201b1_row16_col3" class="data row16 col3" >005</td>
      <td id="T_201b1_row16_col4" class="data row16 col4" >ST: ADV TOP/COLLOID&INFACE SCI</td>
      <td id="T_201b1_row16_col5" class="data row16 col5" >LEC</td>
      <td id="T_201b1_row16_col6" class="data row16 col6" >4</td>
      <td id="T_201b1_row16_col7" class="data row16 col7" >12</td>
      <td id="T_201b1_row16_col8" class="data row16 col8" >Ferri</td>
    </tr>
  </tbody>
</table>

:::

## Spring 2022

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_d5cd4 table {
  width: 100%;
  border-collapse: collapse;
}
#T_d5cd4 th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_d5cd4 th {
  border: 0;
}
#T_d5cd4 thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_d5cd4 tbody td:nth-child(1) {
  display: none;
}
#T_d5cd4 thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_d5cd4 tbody td:nth-child(2) {
  display: none;
}
#T_d5cd4 thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_d5cd4 tbody td:nth-child(8) {
  display: none;
}
#T_d5cd4 td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_d5cd4 td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_d5cd4 td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_d5cd4 td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_d5cd4 td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_d5cd4 td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_d5cd4_row0_col0, #T_d5cd4_row0_col1, #T_d5cd4_row0_col2, #T_d5cd4_row0_col3, #T_d5cd4_row0_col4, #T_d5cd4_row0_col5, #T_d5cd4_row0_col6, #T_d5cd4_row0_col7, #T_d5cd4_row0_col8, #T_d5cd4_row2_col0, #T_d5cd4_row2_col1, #T_d5cd4_row2_col2, #T_d5cd4_row2_col3, #T_d5cd4_row2_col4, #T_d5cd4_row2_col5, #T_d5cd4_row2_col6, #T_d5cd4_row2_col7, #T_d5cd4_row2_col8, #T_d5cd4_row3_col0, #T_d5cd4_row3_col1, #T_d5cd4_row3_col2, #T_d5cd4_row3_col3, #T_d5cd4_row3_col4, #T_d5cd4_row3_col5, #T_d5cd4_row3_col6, #T_d5cd4_row3_col7, #T_d5cd4_row3_col8, #T_d5cd4_row12_col0, #T_d5cd4_row12_col1, #T_d5cd4_row12_col2, #T_d5cd4_row12_col3, #T_d5cd4_row12_col4, #T_d5cd4_row12_col5, #T_d5cd4_row12_col6, #T_d5cd4_row12_col7, #T_d5cd4_row12_col8, #T_d5cd4_row13_col0, #T_d5cd4_row13_col1, #T_d5cd4_row13_col2, #T_d5cd4_row13_col3, #T_d5cd4_row13_col4, #T_d5cd4_row13_col5, #T_d5cd4_row13_col6, #T_d5cd4_row13_col7, #T_d5cd4_row13_col8, #T_d5cd4_row14_col0, #T_d5cd4_row14_col1, #T_d5cd4_row14_col2, #T_d5cd4_row14_col3, #T_d5cd4_row14_col4, #T_d5cd4_row14_col5, #T_d5cd4_row14_col6, #T_d5cd4_row14_col7, #T_d5cd4_row14_col8, #T_d5cd4_row15_col0, #T_d5cd4_row15_col1, #T_d5cd4_row15_col2, #T_d5cd4_row15_col3, #T_d5cd4_row15_col4, #T_d5cd4_row15_col5, #T_d5cd4_row15_col6, #T_d5cd4_row15_col7, #T_d5cd4_row15_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_d5cd4_row1_col0, #T_d5cd4_row1_col1, #T_d5cd4_row1_col2, #T_d5cd4_row1_col3, #T_d5cd4_row1_col4, #T_d5cd4_row1_col5, #T_d5cd4_row1_col6, #T_d5cd4_row1_col7, #T_d5cd4_row1_col8, #T_d5cd4_row4_col0, #T_d5cd4_row4_col1, #T_d5cd4_row4_col2, #T_d5cd4_row4_col3, #T_d5cd4_row4_col4, #T_d5cd4_row4_col5, #T_d5cd4_row4_col6, #T_d5cd4_row4_col7, #T_d5cd4_row4_col8, #T_d5cd4_row5_col0, #T_d5cd4_row5_col1, #T_d5cd4_row5_col2, #T_d5cd4_row5_col3, #T_d5cd4_row5_col4, #T_d5cd4_row5_col5, #T_d5cd4_row5_col6, #T_d5cd4_row5_col7, #T_d5cd4_row5_col8, #T_d5cd4_row6_col0, #T_d5cd4_row6_col1, #T_d5cd4_row6_col2, #T_d5cd4_row6_col3, #T_d5cd4_row6_col4, #T_d5cd4_row6_col5, #T_d5cd4_row6_col6, #T_d5cd4_row6_col7, #T_d5cd4_row6_col8, #T_d5cd4_row7_col0, #T_d5cd4_row7_col1, #T_d5cd4_row7_col2, #T_d5cd4_row7_col3, #T_d5cd4_row7_col4, #T_d5cd4_row7_col5, #T_d5cd4_row7_col6, #T_d5cd4_row7_col7, #T_d5cd4_row7_col8, #T_d5cd4_row8_col0, #T_d5cd4_row8_col1, #T_d5cd4_row8_col2, #T_d5cd4_row8_col3, #T_d5cd4_row8_col4, #T_d5cd4_row8_col5, #T_d5cd4_row8_col6, #T_d5cd4_row8_col7, #T_d5cd4_row8_col8, #T_d5cd4_row9_col0, #T_d5cd4_row9_col1, #T_d5cd4_row9_col2, #T_d5cd4_row9_col3, #T_d5cd4_row9_col4, #T_d5cd4_row9_col5, #T_d5cd4_row9_col6, #T_d5cd4_row9_col7, #T_d5cd4_row9_col8, #T_d5cd4_row10_col0, #T_d5cd4_row10_col1, #T_d5cd4_row10_col2, #T_d5cd4_row10_col3, #T_d5cd4_row10_col4, #T_d5cd4_row10_col5, #T_d5cd4_row10_col6, #T_d5cd4_row10_col7, #T_d5cd4_row10_col8, #T_d5cd4_row11_col0, #T_d5cd4_row11_col1, #T_d5cd4_row11_col2, #T_d5cd4_row11_col3, #T_d5cd4_row11_col4, #T_d5cd4_row11_col5, #T_d5cd4_row11_col6, #T_d5cd4_row11_col7, #T_d5cd4_row11_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_d5cd4">
  <thead>
    <tr>
      <th id="T_d5cd4_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_d5cd4_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_d5cd4_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_d5cd4_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_d5cd4_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_d5cd4_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_d5cd4_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_d5cd4_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_d5cd4_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_d5cd4_row0_col0" class="data row0 col0" >115</td>
      <td id="T_d5cd4_row0_col1" class="data row0 col1" >Spring 2022</td>
      <td id="T_d5cd4_row0_col2" class="data row0 col2" >CLSE115</td>
      <td id="T_d5cd4_row0_col3" class="data row0 col3" >902</td>
      <td id="T_d5cd4_row0_col4" class="data row0 col4" >INTRO TO PROGRAMMING</td>
      <td id="T_d5cd4_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_d5cd4_row0_col6" class="data row0 col6" >50</td>
      <td id="T_d5cd4_row0_col7" class="data row0 col7" >100</td>
      <td id="T_d5cd4_row0_col8" class="data row0 col8" >Jensen</td>
    </tr>
    <tr>
      <td id="T_d5cd4_row1_col0" class="data row1 col0" >202</td>
      <td id="T_d5cd4_row1_col1" class="data row1 col1" >Spring 2022</td>
      <td id="T_d5cd4_row1_col2" class="data row1 col2" >CLSE202</td>
      <td id="T_d5cd4_row1_col3" class="data row1 col3" >001</td>
      <td id="T_d5cd4_row1_col4" class="data row1 col4" >CHEMICAL ENGINEERING FUND II</td>
      <td id="T_d5cd4_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_d5cd4_row1_col6" class="data row1 col6" >17</td>
      <td id="T_d5cd4_row1_col7" class="data row1 col7" >34</td>
      <td id="T_d5cd4_row1_col8" class="data row1 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_d5cd4_row2_col0" class="data row2 col0" >302</td>
      <td id="T_d5cd4_row2_col1" class="data row2 col1" >Spring 2022</td>
      <td id="T_d5cd4_row2_col2" class="data row2 col2" >CLSE302</td>
      <td id="T_d5cd4_row2_col3" class="data row2 col3" >001</td>
      <td id="T_d5cd4_row2_col4" class="data row2 col4" >TRANSPORT PHENOMENA II</td>
      <td id="T_d5cd4_row2_col5" class="data row2 col5" >LEC</td>
      <td id="T_d5cd4_row2_col6" class="data row2 col6" >49</td>
      <td id="T_d5cd4_row2_col7" class="data row2 col7" >98</td>
      <td id="T_d5cd4_row2_col8" class="data row2 col8" >Peters</td>
    </tr>
    <tr>
      <td id="T_d5cd4_row3_col0" class="data row3 col0" >580</td>
      <td id="T_d5cd4_row3_col1" class="data row3 col1" >Spring 2022</td>
      <td id="T_d5cd4_row3_col2" class="data row3 col2" >CLSE580</td>
      <td id="T_d5cd4_row3_col3" class="data row3 col3" >901</td>
      <td id="T_d5cd4_row3_col4" class="data row3 col4" >SUSTAINABLE CHEMICAL ENGR</td>
      <td id="T_d5cd4_row3_col5" class="data row3 col5" >LEC</td>
      <td id="T_d5cd4_row3_col6" class="data row3 col6" >12</td>
      <td id="T_d5cd4_row3_col7" class="data row3 col7" >36</td>
      <td id="T_d5cd4_row3_col8" class="data row3 col8" >Tang</td>
    </tr>
    <tr>
      <td id="T_d5cd4_row4_col0" class="data row4 col0" >655</td>
      <td id="T_d5cd4_row4_col1" class="data row4 col1" >Spring 2022</td>
      <td id="T_d5cd4_row4_col2" class="data row4 col2" >CLSE655</td>
      <td id="T_d5cd4_row4_col3" class="data row4 col3" >001</td>
      <td id="T_d5cd4_row4_col4" class="data row4 col4" >NONEQUILIBRIUM ANALYSIS</td>
      <td id="T_d5cd4_row4_col5" class="data row4 col5" >LEC</td>
      <td id="T_d5cd4_row4_col6" class="data row4 col6" >4</td>
      <td id="T_d5cd4_row4_col7" class="data row4 col7" >12</td>
      <td id="T_d5cd4_row4_col8" class="data row4 col8" >Yadavalli</td>
    </tr>
    <tr>
      <td id="T_d5cd4_row5_col0" class="data row5 col0" >656</td>
      <td id="T_d5cd4_row5_col1" class="data row5 col1" >Spring 2022</td>
      <td id="T_d5cd4_row5_col2" class="data row5 col2" >CLSE656</td>
      <td id="T_d5cd4_row5_col3" class="data row5 col3" >001</td>
      <td id="T_d5cd4_row5_col4" class="data row5 col4" >ADV CHEMICAL REACTION ENGR</td>
      <td id="T_d5cd4_row5_col5" class="data row5 col5" >LEC</td>
      <td id="T_d5cd4_row5_col6" class="data row5 col6" >2</td>
      <td id="T_d5cd4_row5_col7" class="data row5 col7" >6</td>
      <td id="T_d5cd4_row5_col8" class="data row5 col8" >Gupta</td>
    </tr>
    <tr>
      <td id="T_d5cd4_row6_col0" class="data row6 col0" >690</td>
      <td id="T_d5cd4_row6_col1" class="data row6 col1" >Spring 2022</td>
      <td id="T_d5cd4_row6_col2" class="data row6 col2" >CLSE690</td>
      <td id="T_d5cd4_row6_col3" class="data row6 col3" >001</td>
      <td id="T_d5cd4_row6_col4" class="data row6 col4" >RESEARCH SEMINAR</td>
      <td id="T_d5cd4_row6_col5" class="data row6 col5" >SEM</td>
      <td id="T_d5cd4_row6_col6" class="data row6 col6" >15</td>
      <td id="T_d5cd4_row6_col7" class="data row6 col7" >15</td>
      <td id="T_d5cd4_row6_col8" class="data row6 col8" >Jiang</td>
    </tr>
    <tr>
      <td id="T_d5cd4_row7_col0" class="data row7 col0" >691</td>
      <td id="T_d5cd4_row7_col1" class="data row7 col1" >Spring 2022</td>
      <td id="T_d5cd4_row7_col2" class="data row7 col2" >CLSE691</td>
      <td id="T_d5cd4_row7_col3" class="data row7 col3" >001</td>
      <td id="T_d5cd4_row7_col4" class="data row7 col4" >SP TP: STEM CELL ENGINEERING</td>
      <td id="T_d5cd4_row7_col5" class="data row7 col5" >LEC</td>
      <td id="T_d5cd4_row7_col6" class="data row7 col6" >1</td>
      <td id="T_d5cd4_row7_col7" class="data row7 col7" >3</td>
      <td id="T_d5cd4_row7_col8" class="data row7 col8" >Wen</td>
    </tr>
    <tr>
      <td id="T_d5cd4_row8_col0" class="data row8 col0" >403</td>
      <td id="T_d5cd4_row8_col1" class="data row8 col1" >Spring 2022</td>
      <td id="T_d5cd4_row8_col2" class="data row8 col2" >ENGR403</td>
      <td id="T_d5cd4_row8_col3" class="data row8 col3" >002</td>
      <td id="T_d5cd4_row8_col4" class="data row8 col4" >SENIOR DESIGN STUDIO</td>
      <td id="T_d5cd4_row8_col5" class="data row8 col5" >LEC</td>
      <td id="T_d5cd4_row8_col6" class="data row8 col6" >56</td>
      <td id="T_d5cd4_row8_col7" class="data row8 col7" >56</td>
      <td id="T_d5cd4_row8_col8" class="data row8 col8" >Ferri</td>
    </tr>
    <tr>
      <td id="T_d5cd4_row9_col0" class="data row9 col0" >497</td>
      <td id="T_d5cd4_row9_col1" class="data row9 col1" >Spring 2022</td>
      <td id="T_d5cd4_row9_col2" class="data row9 col2" >ENGR497</td>
      <td id="T_d5cd4_row9_col3" class="data row9 col3" >L12</td>
      <td id="T_d5cd4_row9_col4" class="data row9 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_d5cd4_row9_col5" class="data row9 col5" >VIP</td>
      <td id="T_d5cd4_row9_col6" class="data row9 col6" >1</td>
      <td id="T_d5cd4_row9_col7" class="data row9 col7" >1</td>
      <td id="T_d5cd4_row9_col8" class="data row9 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_d5cd4_row10_col0" class="data row10 col0" >497</td>
      <td id="T_d5cd4_row10_col1" class="data row10 col1" >Spring 2022</td>
      <td id="T_d5cd4_row10_col2" class="data row10 col2" >ENGR497</td>
      <td id="T_d5cd4_row10_col3" class="data row10 col3" >L13</td>
      <td id="T_d5cd4_row10_col4" class="data row10 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_d5cd4_row10_col5" class="data row10 col5" >VIP</td>
      <td id="T_d5cd4_row10_col6" class="data row10 col6" >1</td>
      <td id="T_d5cd4_row10_col7" class="data row10 col7" >2</td>
      <td id="T_d5cd4_row10_col8" class="data row10 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_d5cd4_row11_col0" class="data row11 col0" >497</td>
      <td id="T_d5cd4_row11_col1" class="data row11 col1" >Spring 2022</td>
      <td id="T_d5cd4_row11_col2" class="data row11 col2" >ENGR497</td>
      <td id="T_d5cd4_row11_col3" class="data row11 col3" >L35</td>
      <td id="T_d5cd4_row11_col4" class="data row11 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_d5cd4_row11_col5" class="data row11 col5" >VIP</td>
      <td id="T_d5cd4_row11_col6" class="data row11 col6" >6</td>
      <td id="T_d5cd4_row11_col7" class="data row11 col7" >6</td>
      <td id="T_d5cd4_row11_col8" class="data row11 col8" >Tang</td>
    </tr>
    <tr>
      <td id="T_d5cd4_row12_col0" class="data row12 col0" >591</td>
      <td id="T_d5cd4_row12_col1" class="data row12 col1" >Spring 2022</td>
      <td id="T_d5cd4_row12_col2" class="data row12 col2" >ENGR591</td>
      <td id="T_d5cd4_row12_col3" class="data row12 col3" >001</td>
      <td id="T_d5cd4_row12_col4" class="data row12 col4" >TOP:PROCESS ANALYTIC TECHNOL</td>
      <td id="T_d5cd4_row12_col5" class="data row12 col5" >LEC</td>
      <td id="T_d5cd4_row12_col6" class="data row12 col6" >9</td>
      <td id="T_d5cd4_row12_col7" class="data row12 col7" >27</td>
      <td id="T_d5cd4_row12_col8" class="data row12 col8" >Jiang</td>
    </tr>
    <tr>
      <td id="T_d5cd4_row13_col0" class="data row13 col0" >591</td>
      <td id="T_d5cd4_row13_col1" class="data row13 col1" >Spring 2022</td>
      <td id="T_d5cd4_row13_col2" class="data row13 col2" >ENGR591</td>
      <td id="T_d5cd4_row13_col3" class="data row13 col3" >902</td>
      <td id="T_d5cd4_row13_col4" class="data row13 col4" >SP:SEP PROCESS/FUND OF PHARM E</td>
      <td id="T_d5cd4_row13_col5" class="data row13 col5" >LEC</td>
      <td id="T_d5cd4_row13_col6" class="data row13 col6" >13</td>
      <td id="T_d5cd4_row13_col7" class="data row13 col7" >39</td>
      <td id="T_d5cd4_row13_col8" class="data row13 col8" >Ferri</td>
    </tr>
    <tr>
      <td id="T_d5cd4_row14_col0" class="data row14 col0" >591</td>
      <td id="T_d5cd4_row14_col1" class="data row14 col1" >Spring 2022</td>
      <td id="T_d5cd4_row14_col2" class="data row14 col2" >ENGR591</td>
      <td id="T_d5cd4_row14_col3" class="data row14 col3" >903</td>
      <td id="T_d5cd4_row14_col4" class="data row14 col4" >TOPICS: WATER ESSENTIALS</td>
      <td id="T_d5cd4_row14_col5" class="data row14 col5" >LEC</td>
      <td id="T_d5cd4_row14_col6" class="data row14 col6" >5</td>
      <td id="T_d5cd4_row14_col7" class="data row14 col7" >15</td>
      <td id="T_d5cd4_row14_col8" class="data row14 col8" >Ferri</td>
    </tr>
    <tr>
      <td id="T_d5cd4_row15_col0" class="data row15 col0" >591</td>
      <td id="T_d5cd4_row15_col1" class="data row15 col1" >Spring 2022</td>
      <td id="T_d5cd4_row15_col2" class="data row15 col2" >ENGR591</td>
      <td id="T_d5cd4_row15_col3" class="data row15 col3" >904</td>
      <td id="T_d5cd4_row15_col4" class="data row15 col4" >ST: SENSORS FOR CLINICAL APPS</td>
      <td id="T_d5cd4_row15_col5" class="data row15 col5" >LEC</td>
      <td id="T_d5cd4_row15_col6" class="data row15 col6" >1</td>
      <td id="T_d5cd4_row15_col7" class="data row15 col7" >3</td>
      <td id="T_d5cd4_row15_col8" class="data row15 col8" >Yadavalli</td>
    </tr>
  </tbody>
</table>

:::

## Summer 2022

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_133cc table {
  width: 100%;
  border-collapse: collapse;
}
#T_133cc th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_133cc th {
  border: 0;
}
#T_133cc thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_133cc tbody td:nth-child(1) {
  display: none;
}
#T_133cc thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_133cc tbody td:nth-child(2) {
  display: none;
}
#T_133cc thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_133cc tbody td:nth-child(8) {
  display: none;
}
#T_133cc td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_133cc td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_133cc td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_133cc td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_133cc td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_133cc td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_133cc_row0_col0, #T_133cc_row0_col1, #T_133cc_row0_col2, #T_133cc_row0_col3, #T_133cc_row0_col4, #T_133cc_row0_col5, #T_133cc_row0_col6, #T_133cc_row0_col7, #T_133cc_row0_col8, #T_133cc_row1_col0, #T_133cc_row1_col1, #T_133cc_row1_col2, #T_133cc_row1_col3, #T_133cc_row1_col4, #T_133cc_row1_col5, #T_133cc_row1_col6, #T_133cc_row1_col7, #T_133cc_row1_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
</style>
<table id="T_133cc">
  <thead>
    <tr>
      <th id="T_133cc_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_133cc_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_133cc_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_133cc_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_133cc_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_133cc_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_133cc_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_133cc_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_133cc_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_133cc_row0_col0" class="data row0 col0" >201</td>
      <td id="T_133cc_row0_col1" class="data row0 col1" >Summer 2022</td>
      <td id="T_133cc_row0_col2" class="data row0 col2" >CLSE201</td>
      <td id="T_133cc_row0_col3" class="data row0 col3" >001</td>
      <td id="T_133cc_row0_col4" class="data row0 col4" >CHEMICAL EGR FUNDAMENTALS I</td>
      <td id="T_133cc_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_133cc_row0_col6" class="data row0 col6" >13</td>
      <td id="T_133cc_row0_col7" class="data row0 col7" >52</td>
      <td id="T_133cc_row0_col8" class="data row0 col8" >Peters</td>
    </tr>
    <tr>
      <td id="T_133cc_row1_col0" class="data row1 col0" >202</td>
      <td id="T_133cc_row1_col1" class="data row1 col1" >Summer 2022</td>
      <td id="T_133cc_row1_col2" class="data row1 col2" >CLSE202</td>
      <td id="T_133cc_row1_col3" class="data row1 col3" >001</td>
      <td id="T_133cc_row1_col4" class="data row1 col4" >CHEMICAL ENGINEERING FUND II</td>
      <td id="T_133cc_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_133cc_row1_col6" class="data row1 col6" >15</td>
      <td id="T_133cc_row1_col7" class="data row1 col7" >60</td>
      <td id="T_133cc_row1_col8" class="data row1 col8" >Peters</td>
    </tr>
  </tbody>
</table>

:::

# AY20-21

This section list instructor activity for the academic year AY20-21 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## Fall 2020

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_c59fa table {
  width: 100%;
  border-collapse: collapse;
}
#T_c59fa th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_c59fa th {
  border: 0;
}
#T_c59fa thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_c59fa tbody td:nth-child(1) {
  display: none;
}
#T_c59fa thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_c59fa tbody td:nth-child(2) {
  display: none;
}
#T_c59fa thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_c59fa tbody td:nth-child(8) {
  display: none;
}
#T_c59fa td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_c59fa td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_c59fa td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_c59fa td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_c59fa td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_c59fa td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_c59fa_row0_col0, #T_c59fa_row0_col1, #T_c59fa_row0_col2, #T_c59fa_row0_col3, #T_c59fa_row0_col4, #T_c59fa_row0_col5, #T_c59fa_row0_col6, #T_c59fa_row0_col7, #T_c59fa_row0_col8, #T_c59fa_row1_col0, #T_c59fa_row1_col1, #T_c59fa_row1_col2, #T_c59fa_row1_col3, #T_c59fa_row1_col4, #T_c59fa_row1_col5, #T_c59fa_row1_col6, #T_c59fa_row1_col7, #T_c59fa_row1_col8, #T_c59fa_row2_col0, #T_c59fa_row2_col1, #T_c59fa_row2_col2, #T_c59fa_row2_col3, #T_c59fa_row2_col4, #T_c59fa_row2_col5, #T_c59fa_row2_col6, #T_c59fa_row2_col7, #T_c59fa_row2_col8, #T_c59fa_row9_col0, #T_c59fa_row9_col1, #T_c59fa_row9_col2, #T_c59fa_row9_col3, #T_c59fa_row9_col4, #T_c59fa_row9_col5, #T_c59fa_row9_col6, #T_c59fa_row9_col7, #T_c59fa_row9_col8, #T_c59fa_row11_col0, #T_c59fa_row11_col1, #T_c59fa_row11_col2, #T_c59fa_row11_col3, #T_c59fa_row11_col4, #T_c59fa_row11_col5, #T_c59fa_row11_col6, #T_c59fa_row11_col7, #T_c59fa_row11_col8, #T_c59fa_row12_col0, #T_c59fa_row12_col1, #T_c59fa_row12_col2, #T_c59fa_row12_col3, #T_c59fa_row12_col4, #T_c59fa_row12_col5, #T_c59fa_row12_col6, #T_c59fa_row12_col7, #T_c59fa_row12_col8, #T_c59fa_row13_col0, #T_c59fa_row13_col1, #T_c59fa_row13_col2, #T_c59fa_row13_col3, #T_c59fa_row13_col4, #T_c59fa_row13_col5, #T_c59fa_row13_col6, #T_c59fa_row13_col7, #T_c59fa_row13_col8, #T_c59fa_row14_col0, #T_c59fa_row14_col1, #T_c59fa_row14_col2, #T_c59fa_row14_col3, #T_c59fa_row14_col4, #T_c59fa_row14_col5, #T_c59fa_row14_col6, #T_c59fa_row14_col7, #T_c59fa_row14_col8, #T_c59fa_row15_col0, #T_c59fa_row15_col1, #T_c59fa_row15_col2, #T_c59fa_row15_col3, #T_c59fa_row15_col4, #T_c59fa_row15_col5, #T_c59fa_row15_col6, #T_c59fa_row15_col7, #T_c59fa_row15_col8, #T_c59fa_row16_col0, #T_c59fa_row16_col1, #T_c59fa_row16_col2, #T_c59fa_row16_col3, #T_c59fa_row16_col4, #T_c59fa_row16_col5, #T_c59fa_row16_col6, #T_c59fa_row16_col7, #T_c59fa_row16_col8, #T_c59fa_row17_col0, #T_c59fa_row17_col1, #T_c59fa_row17_col2, #T_c59fa_row17_col3, #T_c59fa_row17_col4, #T_c59fa_row17_col5, #T_c59fa_row17_col6, #T_c59fa_row17_col7, #T_c59fa_row17_col8, #T_c59fa_row18_col0, #T_c59fa_row18_col1, #T_c59fa_row18_col2, #T_c59fa_row18_col3, #T_c59fa_row18_col4, #T_c59fa_row18_col5, #T_c59fa_row18_col6, #T_c59fa_row18_col7, #T_c59fa_row18_col8, #T_c59fa_row21_col0, #T_c59fa_row21_col1, #T_c59fa_row21_col2, #T_c59fa_row21_col3, #T_c59fa_row21_col4, #T_c59fa_row21_col5, #T_c59fa_row21_col6, #T_c59fa_row21_col7, #T_c59fa_row21_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_c59fa_row3_col0, #T_c59fa_row3_col1, #T_c59fa_row3_col2, #T_c59fa_row3_col3, #T_c59fa_row3_col4, #T_c59fa_row3_col5, #T_c59fa_row3_col6, #T_c59fa_row3_col7, #T_c59fa_row3_col8, #T_c59fa_row4_col0, #T_c59fa_row4_col1, #T_c59fa_row4_col2, #T_c59fa_row4_col3, #T_c59fa_row4_col4, #T_c59fa_row4_col5, #T_c59fa_row4_col6, #T_c59fa_row4_col7, #T_c59fa_row4_col8, #T_c59fa_row5_col0, #T_c59fa_row5_col1, #T_c59fa_row5_col2, #T_c59fa_row5_col3, #T_c59fa_row5_col4, #T_c59fa_row5_col5, #T_c59fa_row5_col6, #T_c59fa_row5_col7, #T_c59fa_row5_col8, #T_c59fa_row6_col0, #T_c59fa_row6_col1, #T_c59fa_row6_col2, #T_c59fa_row6_col3, #T_c59fa_row6_col4, #T_c59fa_row6_col5, #T_c59fa_row6_col6, #T_c59fa_row6_col7, #T_c59fa_row6_col8, #T_c59fa_row7_col0, #T_c59fa_row7_col1, #T_c59fa_row7_col2, #T_c59fa_row7_col3, #T_c59fa_row7_col4, #T_c59fa_row7_col5, #T_c59fa_row7_col6, #T_c59fa_row7_col7, #T_c59fa_row7_col8, #T_c59fa_row8_col0, #T_c59fa_row8_col1, #T_c59fa_row8_col2, #T_c59fa_row8_col3, #T_c59fa_row8_col4, #T_c59fa_row8_col5, #T_c59fa_row8_col6, #T_c59fa_row8_col7, #T_c59fa_row8_col8, #T_c59fa_row10_col0, #T_c59fa_row10_col1, #T_c59fa_row10_col2, #T_c59fa_row10_col3, #T_c59fa_row10_col4, #T_c59fa_row10_col5, #T_c59fa_row10_col6, #T_c59fa_row10_col7, #T_c59fa_row10_col8, #T_c59fa_row19_col0, #T_c59fa_row19_col1, #T_c59fa_row19_col2, #T_c59fa_row19_col3, #T_c59fa_row19_col4, #T_c59fa_row19_col5, #T_c59fa_row19_col6, #T_c59fa_row19_col7, #T_c59fa_row19_col8, #T_c59fa_row20_col0, #T_c59fa_row20_col1, #T_c59fa_row20_col2, #T_c59fa_row20_col3, #T_c59fa_row20_col4, #T_c59fa_row20_col5, #T_c59fa_row20_col6, #T_c59fa_row20_col7, #T_c59fa_row20_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_c59fa">
  <thead>
    <tr>
      <th id="T_c59fa_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_c59fa_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_c59fa_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_c59fa_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_c59fa_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_c59fa_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_c59fa_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_c59fa_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_c59fa_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_c59fa_row0_col0" class="data row0 col0" >201</td>
      <td id="T_c59fa_row0_col1" class="data row0 col1" >Fall 2020</td>
      <td id="T_c59fa_row0_col2" class="data row0 col2" >CLSE201</td>
      <td id="T_c59fa_row0_col3" class="data row0 col3" >001</td>
      <td id="T_c59fa_row0_col4" class="data row0 col4" >CHEMICAL EGR FUNDAMENTALS I</td>
      <td id="T_c59fa_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_c59fa_row0_col6" class="data row0 col6" >16</td>
      <td id="T_c59fa_row0_col7" class="data row0 col7" >21</td>
      <td id="T_c59fa_row0_col8" class="data row0 col8" >Tang</td>
    </tr>
    <tr>
      <td id="T_c59fa_row1_col0" class="data row1 col0" >201</td>
      <td id="T_c59fa_row1_col1" class="data row1 col1" >Fall 2020</td>
      <td id="T_c59fa_row1_col2" class="data row1 col2" >CLSE201</td>
      <td id="T_c59fa_row1_col3" class="data row1 col3" >001</td>
      <td id="T_c59fa_row1_col4" class="data row1 col4" >CHEMICAL EGR FUNDAMENTALS I</td>
      <td id="T_c59fa_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_c59fa_row1_col6" class="data row1 col6" >16</td>
      <td id="T_c59fa_row1_col7" class="data row1 col7" >21</td>
      <td id="T_c59fa_row1_col8" class="data row1 col8" >Tang</td>
    </tr>
    <tr>
      <td id="T_c59fa_row2_col0" class="data row2 col0" >201</td>
      <td id="T_c59fa_row2_col1" class="data row2 col1" >Fall 2020</td>
      <td id="T_c59fa_row2_col2" class="data row2 col2" >CLSE201</td>
      <td id="T_c59fa_row2_col3" class="data row2 col3" >002</td>
      <td id="T_c59fa_row2_col4" class="data row2 col4" >CHEMICAL EGR FUNDAMENTALS I</td>
      <td id="T_c59fa_row2_col5" class="data row2 col5" >LEC</td>
      <td id="T_c59fa_row2_col6" class="data row2 col6" >8</td>
      <td id="T_c59fa_row2_col7" class="data row2 col7" >16</td>
      <td id="T_c59fa_row2_col8" class="data row2 col8" >Tang</td>
    </tr>
    <tr>
      <td id="T_c59fa_row3_col0" class="data row3 col0" >301</td>
      <td id="T_c59fa_row3_col1" class="data row3 col1" >Fall 2020</td>
      <td id="T_c59fa_row3_col2" class="data row3 col2" >CLSE301</td>
      <td id="T_c59fa_row3_col3" class="data row3 col3" >001</td>
      <td id="T_c59fa_row3_col4" class="data row3 col4" >TRANSPORT PHENOMENA I</td>
      <td id="T_c59fa_row3_col5" class="data row3 col5" >LEC</td>
      <td id="T_c59fa_row3_col6" class="data row3 col6" >33</td>
      <td id="T_c59fa_row3_col7" class="data row3 col7" >33</td>
      <td id="T_c59fa_row3_col8" class="data row3 col8" >Ferri</td>
    </tr>
    <tr>
      <td id="T_c59fa_row4_col0" class="data row4 col0" >301</td>
      <td id="T_c59fa_row4_col1" class="data row4 col1" >Fall 2020</td>
      <td id="T_c59fa_row4_col2" class="data row4 col2" >CLSE301</td>
      <td id="T_c59fa_row4_col3" class="data row4 col3" >001</td>
      <td id="T_c59fa_row4_col4" class="data row4 col4" >TRANSPORT PHENOMENA I</td>
      <td id="T_c59fa_row4_col5" class="data row4 col5" >LEC</td>
      <td id="T_c59fa_row4_col6" class="data row4 col6" >33</td>
      <td id="T_c59fa_row4_col7" class="data row4 col7" >33</td>
      <td id="T_c59fa_row4_col8" class="data row4 col8" >Ferri</td>
    </tr>
    <tr>
      <td id="T_c59fa_row5_col0" class="data row5 col0" >301</td>
      <td id="T_c59fa_row5_col1" class="data row5 col1" >Fall 2020</td>
      <td id="T_c59fa_row5_col2" class="data row5 col2" >CLSE301</td>
      <td id="T_c59fa_row5_col3" class="data row5 col3" >002</td>
      <td id="T_c59fa_row5_col4" class="data row5 col4" >TRANSPORT PHENOMENA I</td>
      <td id="T_c59fa_row5_col5" class="data row5 col5" >LEC</td>
      <td id="T_c59fa_row5_col6" class="data row5 col6" >26</td>
      <td id="T_c59fa_row5_col7" class="data row5 col7" >39</td>
      <td id="T_c59fa_row5_col8" class="data row5 col8" >Ferri</td>
    </tr>
    <tr>
      <td id="T_c59fa_row6_col0" class="data row6 col0" >305</td>
      <td id="T_c59fa_row6_col1" class="data row6 col1" >Fall 2020</td>
      <td id="T_c59fa_row6_col2" class="data row6 col2" >CLSE305</td>
      <td id="T_c59fa_row6_col3" class="data row6 col3" >001</td>
      <td id="T_c59fa_row6_col4" class="data row6 col4" >THERMODYNAMICS OF PHASE EQUIL</td>
      <td id="T_c59fa_row6_col5" class="data row6 col5" >LEC</td>
      <td id="T_c59fa_row6_col6" class="data row6 col6" >30</td>
      <td id="T_c59fa_row6_col7" class="data row6 col7" >30</td>
      <td id="T_c59fa_row6_col8" class="data row6 col8" >Yadavalli</td>
    </tr>
    <tr>
      <td id="T_c59fa_row7_col0" class="data row7 col0" >305</td>
      <td id="T_c59fa_row7_col1" class="data row7 col1" >Fall 2020</td>
      <td id="T_c59fa_row7_col2" class="data row7 col2" >CLSE305</td>
      <td id="T_c59fa_row7_col3" class="data row7 col3" >001</td>
      <td id="T_c59fa_row7_col4" class="data row7 col4" >THERMODYNAMICS OF PHASE EQUIL</td>
      <td id="T_c59fa_row7_col5" class="data row7 col5" >LEC</td>
      <td id="T_c59fa_row7_col6" class="data row7 col6" >30</td>
      <td id="T_c59fa_row7_col7" class="data row7 col7" >30</td>
      <td id="T_c59fa_row7_col8" class="data row7 col8" >Yadavalli</td>
    </tr>
    <tr>
      <td id="T_c59fa_row8_col0" class="data row8 col0" >305</td>
      <td id="T_c59fa_row8_col1" class="data row8 col1" >Fall 2020</td>
      <td id="T_c59fa_row8_col2" class="data row8 col2" >CLSE305</td>
      <td id="T_c59fa_row8_col3" class="data row8 col3" >002</td>
      <td id="T_c59fa_row8_col4" class="data row8 col4" >THERMODYNAMICS OF PHASE EQUIL</td>
      <td id="T_c59fa_row8_col5" class="data row8 col5" >LEC</td>
      <td id="T_c59fa_row8_col6" class="data row8 col6" >30</td>
      <td id="T_c59fa_row8_col7" class="data row8 col7" >45</td>
      <td id="T_c59fa_row8_col8" class="data row8 col8" >Yadavalli</td>
    </tr>
    <tr>
      <td id="T_c59fa_row9_col0" class="data row9 col0" >409</td>
      <td id="T_c59fa_row9_col1" class="data row9 col1" >Fall 2020</td>
      <td id="T_c59fa_row9_col2" class="data row9 col2" >CLSE409</td>
      <td id="T_c59fa_row9_col3" class="data row9 col3" >001</td>
      <td id="T_c59fa_row9_col4" class="data row9 col4" >PROCESS CNTRL CHEM/LFSC ENGRNG</td>
      <td id="T_c59fa_row9_col5" class="data row9 col5" >LEC</td>
      <td id="T_c59fa_row9_col6" class="data row9 col6" >46</td>
      <td id="T_c59fa_row9_col7" class="data row9 col7" >138</td>
      <td id="T_c59fa_row9_col8" class="data row9 col8" >Jiang</td>
    </tr>
    <tr>
      <td id="T_c59fa_row10_col0" class="data row10 col0" >575</td>
      <td id="T_c59fa_row10_col1" class="data row10 col1" >Fall 2020</td>
      <td id="T_c59fa_row10_col2" class="data row10 col2" >CLSE575</td>
      <td id="T_c59fa_row10_col3" class="data row10 col3" >001</td>
      <td id="T_c59fa_row10_col4" class="data row10 col4" >NANOTECH LIFE SCI AND ENGG</td>
      <td id="T_c59fa_row10_col5" class="data row10 col5" >LEC</td>
      <td id="T_c59fa_row10_col6" class="data row10 col6" >24</td>
      <td id="T_c59fa_row10_col7" class="data row10 col7" >36</td>
      <td id="T_c59fa_row10_col8" class="data row10 col8" >Yadavalli</td>
    </tr>
    <tr>
      <td id="T_c59fa_row11_col0" class="data row11 col0" >650</td>
      <td id="T_c59fa_row11_col1" class="data row11 col1" >Fall 2020</td>
      <td id="T_c59fa_row11_col2" class="data row11 col2" >CLSE650</td>
      <td id="T_c59fa_row11_col3" class="data row11 col3" >001</td>
      <td id="T_c59fa_row11_col4" class="data row11 col4" >QUANTITATIVE ANALYS IN CLSE</td>
      <td id="T_c59fa_row11_col5" class="data row11 col5" >LEC</td>
      <td id="T_c59fa_row11_col6" class="data row11 col6" >14</td>
      <td id="T_c59fa_row11_col7" class="data row11 col7" >21</td>
      <td id="T_c59fa_row11_col8" class="data row11 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_c59fa_row12_col0" class="data row12 col0" >654</td>
      <td id="T_c59fa_row12_col1" class="data row12 col1" >Fall 2020</td>
      <td id="T_c59fa_row12_col2" class="data row12 col2" >CLSE654</td>
      <td id="T_c59fa_row12_col3" class="data row12 col3" >001</td>
      <td id="T_c59fa_row12_col4" class="data row12 col4" >EQUILIBRIUM ANALYSIS</td>
      <td id="T_c59fa_row12_col5" class="data row12 col5" >LEC</td>
      <td id="T_c59fa_row12_col6" class="data row12 col6" >20</td>
      <td id="T_c59fa_row12_col7" class="data row12 col7" >30</td>
      <td id="T_c59fa_row12_col8" class="data row12 col8" >Peters</td>
    </tr>
    <tr>
      <td id="T_c59fa_row13_col0" class="data row13 col0" >675</td>
      <td id="T_c59fa_row13_col1" class="data row13 col1" >Fall 2020</td>
      <td id="T_c59fa_row13_col2" class="data row13 col2" >CLSE675</td>
      <td id="T_c59fa_row13_col3" class="data row13 col3" >001</td>
      <td id="T_c59fa_row13_col4" class="data row13 col4" >POLYMERS IN MEDICINE</td>
      <td id="T_c59fa_row13_col5" class="data row13 col5" >LEC</td>
      <td id="T_c59fa_row13_col6" class="data row13 col6" >4</td>
      <td id="T_c59fa_row13_col7" class="data row13 col7" >6</td>
      <td id="T_c59fa_row13_col8" class="data row13 col8" >Wen</td>
    </tr>
    <tr>
      <td id="T_c59fa_row14_col0" class="data row14 col0" >690</td>
      <td id="T_c59fa_row14_col1" class="data row14 col1" >Fall 2020</td>
      <td id="T_c59fa_row14_col2" class="data row14 col2" >CLSE690</td>
      <td id="T_c59fa_row14_col3" class="data row14 col3" >001</td>
      <td id="T_c59fa_row14_col4" class="data row14 col4" >RESEARCH SEMINAR</td>
      <td id="T_c59fa_row14_col5" class="data row14 col5" >SEM</td>
      <td id="T_c59fa_row14_col6" class="data row14 col6" >42</td>
      <td id="T_c59fa_row14_col7" class="data row14 col7" >21</td>
      <td id="T_c59fa_row14_col8" class="data row14 col8" >Jiang</td>
    </tr>
    <tr>
      <td id="T_c59fa_row15_col0" class="data row15 col0" >402</td>
      <td id="T_c59fa_row15_col1" class="data row15 col1" >Fall 2020</td>
      <td id="T_c59fa_row15_col2" class="data row15 col2" >ENGR402</td>
      <td id="T_c59fa_row15_col3" class="data row15 col3" >002</td>
      <td id="T_c59fa_row15_col4" class="data row15 col4" >SENIOR DESIGN STUDIO</td>
      <td id="T_c59fa_row15_col5" class="data row15 col5" >LEC</td>
      <td id="T_c59fa_row15_col6" class="data row15 col6" >117</td>
      <td id="T_c59fa_row15_col7" class="data row15 col7" >117</td>
      <td id="T_c59fa_row15_col8" class="data row15 col8" >Ward</td>
    </tr>
    <tr>
      <td id="T_c59fa_row16_col0" class="data row16 col0" >497</td>
      <td id="T_c59fa_row16_col1" class="data row16 col1" >Fall 2020</td>
      <td id="T_c59fa_row16_col2" class="data row16 col2" >ENGR497</td>
      <td id="T_c59fa_row16_col3" class="data row16 col3" >L11</td>
      <td id="T_c59fa_row16_col4" class="data row16 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_c59fa_row16_col5" class="data row16 col5" >VIP</td>
      <td id="T_c59fa_row16_col6" class="data row16 col6" >1</td>
      <td id="T_c59fa_row16_col7" class="data row16 col7" >1</td>
      <td id="T_c59fa_row16_col8" class="data row16 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_c59fa_row17_col0" class="data row17 col0" >497</td>
      <td id="T_c59fa_row17_col1" class="data row17 col1" >Fall 2020</td>
      <td id="T_c59fa_row17_col2" class="data row17 col2" >ENGR497</td>
      <td id="T_c59fa_row17_col3" class="data row17 col3" >L35</td>
      <td id="T_c59fa_row17_col4" class="data row17 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_c59fa_row17_col5" class="data row17 col5" >VIP</td>
      <td id="T_c59fa_row17_col6" class="data row17 col6" >5</td>
      <td id="T_c59fa_row17_col7" class="data row17 col7" >5</td>
      <td id="T_c59fa_row17_col8" class="data row17 col8" >Tang</td>
    </tr>
    <tr>
      <td id="T_c59fa_row18_col0" class="data row18 col0" >497</td>
      <td id="T_c59fa_row18_col1" class="data row18 col1" >Fall 2020</td>
      <td id="T_c59fa_row18_col2" class="data row18 col2" >ENGR497</td>
      <td id="T_c59fa_row18_col3" class="data row18 col3" >L36</td>
      <td id="T_c59fa_row18_col4" class="data row18 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_c59fa_row18_col5" class="data row18 col5" >VIP</td>
      <td id="T_c59fa_row18_col6" class="data row18 col6" >2</td>
      <td id="T_c59fa_row18_col7" class="data row18 col7" >4</td>
      <td id="T_c59fa_row18_col8" class="data row18 col8" >Tang</td>
    </tr>
    <tr>
      <td id="T_c59fa_row19_col0" class="data row19 col0" >591</td>
      <td id="T_c59fa_row19_col1" class="data row19 col1" >Fall 2020</td>
      <td id="T_c59fa_row19_col2" class="data row19 col2" >ENGR591</td>
      <td id="T_c59fa_row19_col3" class="data row19 col3" >902</td>
      <td id="T_c59fa_row19_col4" class="data row19 col4" >ST:BIOPRINTING &NANOTOXICOLOGY</td>
      <td id="T_c59fa_row19_col5" class="data row19 col5" >LEC</td>
      <td id="T_c59fa_row19_col6" class="data row19 col6" >11</td>
      <td id="T_c59fa_row19_col7" class="data row19 col7" >33</td>
      <td id="T_c59fa_row19_col8" class="data row19 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_c59fa_row20_col0" class="data row20 col0" >591</td>
      <td id="T_c59fa_row20_col1" class="data row20 col1" >Fall 2020</td>
      <td id="T_c59fa_row20_col2" class="data row20 col2" >ENGR591</td>
      <td id="T_c59fa_row20_col3" class="data row20 col3" >903</td>
      <td id="T_c59fa_row20_col4" class="data row20 col4" >ST: POLYMER ENGINEERING</td>
      <td id="T_c59fa_row20_col5" class="data row20 col5" >LEC</td>
      <td id="T_c59fa_row20_col6" class="data row20 col6" >7</td>
      <td id="T_c59fa_row20_col7" class="data row20 col7" >21</td>
      <td id="T_c59fa_row20_col8" class="data row20 col8" >Wynne</td>
    </tr>
    <tr>
      <td id="T_c59fa_row21_col0" class="data row21 col0" >691</td>
      <td id="T_c59fa_row21_col1" class="data row21 col1" >Fall 2020</td>
      <td id="T_c59fa_row21_col2" class="data row21 col2" >ENGR691</td>
      <td id="T_c59fa_row21_col3" class="data row21 col3" >902</td>
      <td id="T_c59fa_row21_col4" class="data row21 col4" >ST: POLYMER ENGINEERING</td>
      <td id="T_c59fa_row21_col5" class="data row21 col5" >LEC</td>
      <td id="T_c59fa_row21_col6" class="data row21 col6" >2</td>
      <td id="T_c59fa_row21_col7" class="data row21 col7" >6</td>
      <td id="T_c59fa_row21_col8" class="data row21 col8" >Wynne</td>
    </tr>
  </tbody>
</table>

:::

## Spring 2021

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_bd105 table {
  width: 100%;
  border-collapse: collapse;
}
#T_bd105 th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_bd105 th {
  border: 0;
}
#T_bd105 thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_bd105 tbody td:nth-child(1) {
  display: none;
}
#T_bd105 thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_bd105 tbody td:nth-child(2) {
  display: none;
}
#T_bd105 thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_bd105 tbody td:nth-child(8) {
  display: none;
}
#T_bd105 td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_bd105 td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_bd105 td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_bd105 td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_bd105 td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_bd105 td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_bd105_row0_col0, #T_bd105_row0_col1, #T_bd105_row0_col2, #T_bd105_row0_col3, #T_bd105_row0_col4, #T_bd105_row0_col5, #T_bd105_row0_col6, #T_bd105_row0_col7, #T_bd105_row0_col8, #T_bd105_row3_col0, #T_bd105_row3_col1, #T_bd105_row3_col2, #T_bd105_row3_col3, #T_bd105_row3_col4, #T_bd105_row3_col5, #T_bd105_row3_col6, #T_bd105_row3_col7, #T_bd105_row3_col8, #T_bd105_row4_col0, #T_bd105_row4_col1, #T_bd105_row4_col2, #T_bd105_row4_col3, #T_bd105_row4_col4, #T_bd105_row4_col5, #T_bd105_row4_col6, #T_bd105_row4_col7, #T_bd105_row4_col8, #T_bd105_row14_col0, #T_bd105_row14_col1, #T_bd105_row14_col2, #T_bd105_row14_col3, #T_bd105_row14_col4, #T_bd105_row14_col5, #T_bd105_row14_col6, #T_bd105_row14_col7, #T_bd105_row14_col8, #T_bd105_row15_col0, #T_bd105_row15_col1, #T_bd105_row15_col2, #T_bd105_row15_col3, #T_bd105_row15_col4, #T_bd105_row15_col5, #T_bd105_row15_col6, #T_bd105_row15_col7, #T_bd105_row15_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_bd105_row1_col0, #T_bd105_row1_col1, #T_bd105_row1_col2, #T_bd105_row1_col3, #T_bd105_row1_col4, #T_bd105_row1_col5, #T_bd105_row1_col6, #T_bd105_row1_col7, #T_bd105_row1_col8, #T_bd105_row2_col0, #T_bd105_row2_col1, #T_bd105_row2_col2, #T_bd105_row2_col3, #T_bd105_row2_col4, #T_bd105_row2_col5, #T_bd105_row2_col6, #T_bd105_row2_col7, #T_bd105_row2_col8, #T_bd105_row5_col0, #T_bd105_row5_col1, #T_bd105_row5_col2, #T_bd105_row5_col3, #T_bd105_row5_col4, #T_bd105_row5_col5, #T_bd105_row5_col6, #T_bd105_row5_col7, #T_bd105_row5_col8, #T_bd105_row6_col0, #T_bd105_row6_col1, #T_bd105_row6_col2, #T_bd105_row6_col3, #T_bd105_row6_col4, #T_bd105_row6_col5, #T_bd105_row6_col6, #T_bd105_row6_col7, #T_bd105_row6_col8, #T_bd105_row7_col0, #T_bd105_row7_col1, #T_bd105_row7_col2, #T_bd105_row7_col3, #T_bd105_row7_col4, #T_bd105_row7_col5, #T_bd105_row7_col6, #T_bd105_row7_col7, #T_bd105_row7_col8, #T_bd105_row8_col0, #T_bd105_row8_col1, #T_bd105_row8_col2, #T_bd105_row8_col3, #T_bd105_row8_col4, #T_bd105_row8_col5, #T_bd105_row8_col6, #T_bd105_row8_col7, #T_bd105_row8_col8, #T_bd105_row9_col0, #T_bd105_row9_col1, #T_bd105_row9_col2, #T_bd105_row9_col3, #T_bd105_row9_col4, #T_bd105_row9_col5, #T_bd105_row9_col6, #T_bd105_row9_col7, #T_bd105_row9_col8, #T_bd105_row10_col0, #T_bd105_row10_col1, #T_bd105_row10_col2, #T_bd105_row10_col3, #T_bd105_row10_col4, #T_bd105_row10_col5, #T_bd105_row10_col6, #T_bd105_row10_col7, #T_bd105_row10_col8, #T_bd105_row11_col0, #T_bd105_row11_col1, #T_bd105_row11_col2, #T_bd105_row11_col3, #T_bd105_row11_col4, #T_bd105_row11_col5, #T_bd105_row11_col6, #T_bd105_row11_col7, #T_bd105_row11_col8, #T_bd105_row12_col0, #T_bd105_row12_col1, #T_bd105_row12_col2, #T_bd105_row12_col3, #T_bd105_row12_col4, #T_bd105_row12_col5, #T_bd105_row12_col6, #T_bd105_row12_col7, #T_bd105_row12_col8, #T_bd105_row13_col0, #T_bd105_row13_col1, #T_bd105_row13_col2, #T_bd105_row13_col3, #T_bd105_row13_col4, #T_bd105_row13_col5, #T_bd105_row13_col6, #T_bd105_row13_col7, #T_bd105_row13_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_bd105">
  <thead>
    <tr>
      <th id="T_bd105_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_bd105_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_bd105_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_bd105_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_bd105_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_bd105_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_bd105_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_bd105_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_bd105_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_bd105_row0_col0" class="data row0 col0" >115</td>
      <td id="T_bd105_row0_col1" class="data row0 col1" >Spring 2021</td>
      <td id="T_bd105_row0_col2" class="data row0 col2" >CLSE115</td>
      <td id="T_bd105_row0_col3" class="data row0 col3" >902</td>
      <td id="T_bd105_row0_col4" class="data row0 col4" >INTRO TO PROGRAMMING</td>
      <td id="T_bd105_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_bd105_row0_col6" class="data row0 col6" >51</td>
      <td id="T_bd105_row0_col7" class="data row0 col7" >102</td>
      <td id="T_bd105_row0_col8" class="data row0 col8" >Reveles Ramirez</td>
    </tr>
    <tr>
      <td id="T_bd105_row1_col0" class="data row1 col0" >202</td>
      <td id="T_bd105_row1_col1" class="data row1 col1" >Spring 2021</td>
      <td id="T_bd105_row1_col2" class="data row1 col2" >CLSE202</td>
      <td id="T_bd105_row1_col3" class="data row1 col3" >001</td>
      <td id="T_bd105_row1_col4" class="data row1 col4" >CHEMICAL ENGINEERING FUND II</td>
      <td id="T_bd105_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_bd105_row1_col6" class="data row1 col6" >12</td>
      <td id="T_bd105_row1_col7" class="data row1 col7" >24</td>
      <td id="T_bd105_row1_col8" class="data row1 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_bd105_row2_col0" class="data row2 col0" >202</td>
      <td id="T_bd105_row2_col1" class="data row2 col1" >Spring 2021</td>
      <td id="T_bd105_row2_col2" class="data row2 col2" >CLSE202</td>
      <td id="T_bd105_row2_col3" class="data row2 col3" >002</td>
      <td id="T_bd105_row2_col4" class="data row2 col4" >CHEMICAL ENGINEERING FUND II</td>
      <td id="T_bd105_row2_col5" class="data row2 col5" >LEC</td>
      <td id="T_bd105_row2_col6" class="data row2 col6" >10</td>
      <td id="T_bd105_row2_col7" class="data row2 col7" >20</td>
      <td id="T_bd105_row2_col8" class="data row2 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_bd105_row3_col0" class="data row3 col0" >302</td>
      <td id="T_bd105_row3_col1" class="data row3 col1" >Spring 2021</td>
      <td id="T_bd105_row3_col2" class="data row3 col2" >CLSE302</td>
      <td id="T_bd105_row3_col3" class="data row3 col3" >001</td>
      <td id="T_bd105_row3_col4" class="data row3 col4" >TRANSPORT PHENOMENA II</td>
      <td id="T_bd105_row3_col5" class="data row3 col5" >LEC</td>
      <td id="T_bd105_row3_col6" class="data row3 col6" >17</td>
      <td id="T_bd105_row3_col7" class="data row3 col7" >34</td>
      <td id="T_bd105_row3_col8" class="data row3 col8" >Peters</td>
    </tr>
    <tr>
      <td id="T_bd105_row4_col0" class="data row4 col0" >302</td>
      <td id="T_bd105_row4_col1" class="data row4 col1" >Spring 2021</td>
      <td id="T_bd105_row4_col2" class="data row4 col2" >CLSE302</td>
      <td id="T_bd105_row4_col3" class="data row4 col3" >002</td>
      <td id="T_bd105_row4_col4" class="data row4 col4" >TRANSPORT PHENOMENA II</td>
      <td id="T_bd105_row4_col5" class="data row4 col5" >LEC</td>
      <td id="T_bd105_row4_col6" class="data row4 col6" >43</td>
      <td id="T_bd105_row4_col7" class="data row4 col7" >86</td>
      <td id="T_bd105_row4_col8" class="data row4 col8" >Peters</td>
    </tr>
    <tr>
      <td id="T_bd105_row5_col0" class="data row5 col0" >655</td>
      <td id="T_bd105_row5_col1" class="data row5 col1" >Spring 2021</td>
      <td id="T_bd105_row5_col2" class="data row5 col2" >CLSE655</td>
      <td id="T_bd105_row5_col3" class="data row5 col3" >001</td>
      <td id="T_bd105_row5_col4" class="data row5 col4" >NONEQUILIBRIUM ANALYSIS</td>
      <td id="T_bd105_row5_col5" class="data row5 col5" >LEC</td>
      <td id="T_bd105_row5_col6" class="data row5 col6" >8</td>
      <td id="T_bd105_row5_col7" class="data row5 col7" >24</td>
      <td id="T_bd105_row5_col8" class="data row5 col8" >Yadavalli</td>
    </tr>
    <tr>
      <td id="T_bd105_row6_col0" class="data row6 col0" >656</td>
      <td id="T_bd105_row6_col1" class="data row6 col1" >Spring 2021</td>
      <td id="T_bd105_row6_col2" class="data row6 col2" >CLSE656</td>
      <td id="T_bd105_row6_col3" class="data row6 col3" >001</td>
      <td id="T_bd105_row6_col4" class="data row6 col4" >ADV CHEMICAL REACTION ENGR</td>
      <td id="T_bd105_row6_col5" class="data row6 col5" >LEC</td>
      <td id="T_bd105_row6_col6" class="data row6 col6" >7</td>
      <td id="T_bd105_row6_col7" class="data row6 col7" >21</td>
      <td id="T_bd105_row6_col8" class="data row6 col8" >Gupta</td>
    </tr>
    <tr>
      <td id="T_bd105_row7_col0" class="data row7 col0" >690</td>
      <td id="T_bd105_row7_col1" class="data row7 col1" >Spring 2021</td>
      <td id="T_bd105_row7_col2" class="data row7 col2" >CLSE690</td>
      <td id="T_bd105_row7_col3" class="data row7 col3" >001</td>
      <td id="T_bd105_row7_col4" class="data row7 col4" >RESEARCH SEMINAR</td>
      <td id="T_bd105_row7_col5" class="data row7 col5" >SEM</td>
      <td id="T_bd105_row7_col6" class="data row7 col6" >23</td>
      <td id="T_bd105_row7_col7" class="data row7 col7" >23</td>
      <td id="T_bd105_row7_col8" class="data row7 col8" >Jiang</td>
    </tr>
    <tr>
      <td id="T_bd105_row8_col0" class="data row8 col0" >691</td>
      <td id="T_bd105_row8_col1" class="data row8 col1" >Spring 2021</td>
      <td id="T_bd105_row8_col2" class="data row8 col2" >CLSE691</td>
      <td id="T_bd105_row8_col3" class="data row8 col3" >001</td>
      <td id="T_bd105_row8_col4" class="data row8 col4" >SP TP: STEM CELL ENGINEERING</td>
      <td id="T_bd105_row8_col5" class="data row8 col5" >LEC</td>
      <td id="T_bd105_row8_col6" class="data row8 col6" >6</td>
      <td id="T_bd105_row8_col7" class="data row8 col7" >18</td>
      <td id="T_bd105_row8_col8" class="data row8 col8" >Wen</td>
    </tr>
    <tr>
      <td id="T_bd105_row9_col0" class="data row9 col0" >403</td>
      <td id="T_bd105_row9_col1" class="data row9 col1" >Spring 2021</td>
      <td id="T_bd105_row9_col2" class="data row9 col2" >ENGR403</td>
      <td id="T_bd105_row9_col3" class="data row9 col3" >002</td>
      <td id="T_bd105_row9_col4" class="data row9 col4" >SENIOR DESIGN STUDIO</td>
      <td id="T_bd105_row9_col5" class="data row9 col5" >LEC</td>
      <td id="T_bd105_row9_col6" class="data row9 col6" >117</td>
      <td id="T_bd105_row9_col7" class="data row9 col7" >117</td>
      <td id="T_bd105_row9_col8" class="data row9 col8" >Ward</td>
    </tr>
    <tr>
      <td id="T_bd105_row10_col0" class="data row10 col0" >497</td>
      <td id="T_bd105_row10_col1" class="data row10 col1" >Spring 2021</td>
      <td id="T_bd105_row10_col2" class="data row10 col2" >ENGR497</td>
      <td id="T_bd105_row10_col3" class="data row10 col3" >L12</td>
      <td id="T_bd105_row10_col4" class="data row10 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_bd105_row10_col5" class="data row10 col5" >VIP</td>
      <td id="T_bd105_row10_col6" class="data row10 col6" >2</td>
      <td id="T_bd105_row10_col7" class="data row10 col7" >2</td>
      <td id="T_bd105_row10_col8" class="data row10 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_bd105_row11_col0" class="data row11 col0" >497</td>
      <td id="T_bd105_row11_col1" class="data row11 col1" >Spring 2021</td>
      <td id="T_bd105_row11_col2" class="data row11 col2" >ENGR497</td>
      <td id="T_bd105_row11_col3" class="data row11 col3" >L13</td>
      <td id="T_bd105_row11_col4" class="data row11 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_bd105_row11_col5" class="data row11 col5" >VIP</td>
      <td id="T_bd105_row11_col6" class="data row11 col6" >0</td>
      <td id="T_bd105_row11_col7" class="data row11 col7" >1</td>
      <td id="T_bd105_row11_col8" class="data row11 col8" >Lewinski</td>
    </tr>
    <tr>
      <td id="T_bd105_row12_col0" class="data row12 col0" >497</td>
      <td id="T_bd105_row12_col1" class="data row12 col1" >Spring 2021</td>
      <td id="T_bd105_row12_col2" class="data row12 col2" >ENGR497</td>
      <td id="T_bd105_row12_col3" class="data row12 col3" >L35</td>
      <td id="T_bd105_row12_col4" class="data row12 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_bd105_row12_col5" class="data row12 col5" >VIP</td>
      <td id="T_bd105_row12_col6" class="data row12 col6" >6</td>
      <td id="T_bd105_row12_col7" class="data row12 col7" >6</td>
      <td id="T_bd105_row12_col8" class="data row12 col8" >Tang</td>
    </tr>
    <tr>
      <td id="T_bd105_row13_col0" class="data row13 col0" >497</td>
      <td id="T_bd105_row13_col1" class="data row13 col1" >Spring 2021</td>
      <td id="T_bd105_row13_col2" class="data row13 col2" >ENGR497</td>
      <td id="T_bd105_row13_col3" class="data row13 col3" >L36</td>
      <td id="T_bd105_row13_col4" class="data row13 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_bd105_row13_col5" class="data row13 col5" >VIP</td>
      <td id="T_bd105_row13_col6" class="data row13 col6" >1</td>
      <td id="T_bd105_row13_col7" class="data row13 col7" >2</td>
      <td id="T_bd105_row13_col8" class="data row13 col8" >Tang</td>
    </tr>
    <tr>
      <td id="T_bd105_row14_col0" class="data row14 col0" >591</td>
      <td id="T_bd105_row14_col1" class="data row14 col1" >Spring 2021</td>
      <td id="T_bd105_row14_col2" class="data row14 col2" >ENGR591</td>
      <td id="T_bd105_row14_col3" class="data row14 col3" >010</td>
      <td id="T_bd105_row14_col4" class="data row14 col4" >TOP:PROCESS ANALYTIC TECHNOL</td>
      <td id="T_bd105_row14_col5" class="data row14 col5" >LEC</td>
      <td id="T_bd105_row14_col6" class="data row14 col6" >6</td>
      <td id="T_bd105_row14_col7" class="data row14 col7" >18</td>
      <td id="T_bd105_row14_col8" class="data row14 col8" >Jiang</td>
    </tr>
    <tr>
      <td id="T_bd105_row15_col0" class="data row15 col0" >591</td>
      <td id="T_bd105_row15_col1" class="data row15 col1" >Spring 2021</td>
      <td id="T_bd105_row15_col2" class="data row15 col2" >ENGR591</td>
      <td id="T_bd105_row15_col3" class="data row15 col3" >905</td>
      <td id="T_bd105_row15_col4" class="data row15 col4" >TOP: SUSTAINABLE CHEM ENG</td>
      <td id="T_bd105_row15_col5" class="data row15 col5" >LEC</td>
      <td id="T_bd105_row15_col6" class="data row15 col6" >12</td>
      <td id="T_bd105_row15_col7" class="data row15 col7" >36</td>
      <td id="T_bd105_row15_col8" class="data row15 col8" >Tang</td>
    </tr>
  </tbody>
</table>

:::

## Summer 2021

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_16fec table {
  width: 100%;
  border-collapse: collapse;
}
#T_16fec th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_16fec th {
  border: 0;
}
#T_16fec thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_16fec tbody td:nth-child(1) {
  display: none;
}
#T_16fec thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_16fec tbody td:nth-child(2) {
  display: none;
}
#T_16fec thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_16fec tbody td:nth-child(8) {
  display: none;
}
#T_16fec td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_16fec td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_16fec td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_16fec td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_16fec td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_16fec td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_16fec_row0_col0, #T_16fec_row0_col1, #T_16fec_row0_col2, #T_16fec_row0_col3, #T_16fec_row0_col4, #T_16fec_row0_col5, #T_16fec_row0_col6, #T_16fec_row0_col7, #T_16fec_row0_col8, #T_16fec_row1_col0, #T_16fec_row1_col1, #T_16fec_row1_col2, #T_16fec_row1_col3, #T_16fec_row1_col4, #T_16fec_row1_col5, #T_16fec_row1_col6, #T_16fec_row1_col7, #T_16fec_row1_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_16fec_row2_col0, #T_16fec_row2_col1, #T_16fec_row2_col2, #T_16fec_row2_col3, #T_16fec_row2_col4, #T_16fec_row2_col5, #T_16fec_row2_col6, #T_16fec_row2_col7, #T_16fec_row2_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_16fec">
  <thead>
    <tr>
      <th id="T_16fec_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_16fec_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_16fec_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_16fec_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_16fec_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_16fec_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_16fec_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_16fec_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_16fec_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_16fec_row0_col0" class="data row0 col0" >201</td>
      <td id="T_16fec_row0_col1" class="data row0 col1" >Summer 2021</td>
      <td id="T_16fec_row0_col2" class="data row0 col2" >CLSE201</td>
      <td id="T_16fec_row0_col3" class="data row0 col3" >001</td>
      <td id="T_16fec_row0_col4" class="data row0 col4" >CHEMICAL EGR FUNDAMENTALS I</td>
      <td id="T_16fec_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_16fec_row0_col6" class="data row0 col6" >36</td>
      <td id="T_16fec_row0_col7" class="data row0 col7" >144</td>
      <td id="T_16fec_row0_col8" class="data row0 col8" >Peters</td>
    </tr>
    <tr>
      <td id="T_16fec_row1_col0" class="data row1 col0" >202</td>
      <td id="T_16fec_row1_col1" class="data row1 col1" >Summer 2021</td>
      <td id="T_16fec_row1_col2" class="data row1 col2" >CLSE202</td>
      <td id="T_16fec_row1_col3" class="data row1 col3" >001</td>
      <td id="T_16fec_row1_col4" class="data row1 col4" >CHEMICAL ENGINEERING FUND II</td>
      <td id="T_16fec_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_16fec_row1_col6" class="data row1 col6" >40</td>
      <td id="T_16fec_row1_col7" class="data row1 col7" >160</td>
      <td id="T_16fec_row1_col8" class="data row1 col8" >Peters</td>
    </tr>
    <tr>
      <td id="T_16fec_row2_col0" class="data row2 col0" >692</td>
      <td id="T_16fec_row2_col1" class="data row2 col1" >Summer 2021</td>
      <td id="T_16fec_row2_col2" class="data row2 col2" >CLSE692</td>
      <td id="T_16fec_row2_col3" class="data row2 col3" >004</td>
      <td id="T_16fec_row2_col4" class="data row2 col4" >INDEPENDENT STUDY</td>
      <td id="T_16fec_row2_col5" class="data row2 col5" >LEC</td>
      <td id="T_16fec_row2_col6" class="data row2 col6" >1</td>
      <td id="T_16fec_row2_col7" class="data row2 col7" >3</td>
      <td id="T_16fec_row2_col8" class="data row2 col8" >Gupton</td>
    </tr>
  </tbody>
</table>

:::
