---
title: Department Teaching Activity - ENGR
date: last-modified
---


# AY25-26

This section list instructor activity for the academic year AY25-26 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## Fall 2025

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_8f2c9 table {
  width: 100%;
  border-collapse: collapse;
}
#T_8f2c9 th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_8f2c9 th {
  border: 0;
}
#T_8f2c9 thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_8f2c9 tbody td:nth-child(1) {
  display: none;
}
#T_8f2c9 thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_8f2c9 tbody td:nth-child(2) {
  display: none;
}
#T_8f2c9 thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_8f2c9 tbody td:nth-child(8) {
  display: none;
}
#T_8f2c9 td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_8f2c9 td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_8f2c9 td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_8f2c9 td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_8f2c9 td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_8f2c9 td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_8f2c9_row0_col0, #T_8f2c9_row0_col1, #T_8f2c9_row0_col2, #T_8f2c9_row0_col3, #T_8f2c9_row0_col4, #T_8f2c9_row0_col5, #T_8f2c9_row0_col6, #T_8f2c9_row0_col7, #T_8f2c9_row0_col8, #T_8f2c9_row2_col0, #T_8f2c9_row2_col1, #T_8f2c9_row2_col2, #T_8f2c9_row2_col3, #T_8f2c9_row2_col4, #T_8f2c9_row2_col5, #T_8f2c9_row2_col6, #T_8f2c9_row2_col7, #T_8f2c9_row2_col8, #T_8f2c9_row3_col0, #T_8f2c9_row3_col1, #T_8f2c9_row3_col2, #T_8f2c9_row3_col3, #T_8f2c9_row3_col4, #T_8f2c9_row3_col5, #T_8f2c9_row3_col6, #T_8f2c9_row3_col7, #T_8f2c9_row3_col8, #T_8f2c9_row4_col0, #T_8f2c9_row4_col1, #T_8f2c9_row4_col2, #T_8f2c9_row4_col3, #T_8f2c9_row4_col4, #T_8f2c9_row4_col5, #T_8f2c9_row4_col6, #T_8f2c9_row4_col7, #T_8f2c9_row4_col8, #T_8f2c9_row5_col0, #T_8f2c9_row5_col1, #T_8f2c9_row5_col2, #T_8f2c9_row5_col3, #T_8f2c9_row5_col4, #T_8f2c9_row5_col5, #T_8f2c9_row5_col6, #T_8f2c9_row5_col7, #T_8f2c9_row5_col8, #T_8f2c9_row6_col0, #T_8f2c9_row6_col1, #T_8f2c9_row6_col2, #T_8f2c9_row6_col3, #T_8f2c9_row6_col4, #T_8f2c9_row6_col5, #T_8f2c9_row6_col6, #T_8f2c9_row6_col7, #T_8f2c9_row6_col8, #T_8f2c9_row7_col0, #T_8f2c9_row7_col1, #T_8f2c9_row7_col2, #T_8f2c9_row7_col3, #T_8f2c9_row7_col4, #T_8f2c9_row7_col5, #T_8f2c9_row7_col6, #T_8f2c9_row7_col7, #T_8f2c9_row7_col8, #T_8f2c9_row8_col0, #T_8f2c9_row8_col1, #T_8f2c9_row8_col2, #T_8f2c9_row8_col3, #T_8f2c9_row8_col4, #T_8f2c9_row8_col5, #T_8f2c9_row8_col6, #T_8f2c9_row8_col7, #T_8f2c9_row8_col8, #T_8f2c9_row12_col0, #T_8f2c9_row12_col1, #T_8f2c9_row12_col2, #T_8f2c9_row12_col3, #T_8f2c9_row12_col4, #T_8f2c9_row12_col5, #T_8f2c9_row12_col6, #T_8f2c9_row12_col7, #T_8f2c9_row12_col8, #T_8f2c9_row13_col0, #T_8f2c9_row13_col1, #T_8f2c9_row13_col2, #T_8f2c9_row13_col3, #T_8f2c9_row13_col4, #T_8f2c9_row13_col5, #T_8f2c9_row13_col6, #T_8f2c9_row13_col7, #T_8f2c9_row13_col8, #T_8f2c9_row14_col0, #T_8f2c9_row14_col1, #T_8f2c9_row14_col2, #T_8f2c9_row14_col3, #T_8f2c9_row14_col4, #T_8f2c9_row14_col5, #T_8f2c9_row14_col6, #T_8f2c9_row14_col7, #T_8f2c9_row14_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
#T_8f2c9_row1_col0, #T_8f2c9_row1_col1, #T_8f2c9_row1_col2, #T_8f2c9_row1_col3, #T_8f2c9_row1_col4, #T_8f2c9_row1_col5, #T_8f2c9_row1_col6, #T_8f2c9_row1_col7, #T_8f2c9_row1_col8, #T_8f2c9_row9_col0, #T_8f2c9_row9_col1, #T_8f2c9_row9_col2, #T_8f2c9_row9_col3, #T_8f2c9_row9_col4, #T_8f2c9_row9_col5, #T_8f2c9_row9_col6, #T_8f2c9_row9_col7, #T_8f2c9_row9_col8, #T_8f2c9_row10_col0, #T_8f2c9_row10_col1, #T_8f2c9_row10_col2, #T_8f2c9_row10_col3, #T_8f2c9_row10_col4, #T_8f2c9_row10_col5, #T_8f2c9_row10_col6, #T_8f2c9_row10_col7, #T_8f2c9_row10_col8, #T_8f2c9_row11_col0, #T_8f2c9_row11_col1, #T_8f2c9_row11_col2, #T_8f2c9_row11_col3, #T_8f2c9_row11_col4, #T_8f2c9_row11_col5, #T_8f2c9_row11_col6, #T_8f2c9_row11_col7, #T_8f2c9_row11_col8, #T_8f2c9_row15_col0, #T_8f2c9_row15_col1, #T_8f2c9_row15_col2, #T_8f2c9_row15_col3, #T_8f2c9_row15_col4, #T_8f2c9_row15_col5, #T_8f2c9_row15_col6, #T_8f2c9_row15_col7, #T_8f2c9_row15_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
</style>
<table id="T_8f2c9">
  <thead>
    <tr>
      <th id="T_8f2c9_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_8f2c9_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_8f2c9_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_8f2c9_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_8f2c9_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_8f2c9_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_8f2c9_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_8f2c9_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_8f2c9_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_8f2c9_row0_col0" class="data row0 col0" >539</td>
      <td id="T_8f2c9_row0_col1" class="data row0 col1" >Fall 2025</td>
      <td id="T_8f2c9_row0_col2" class="data row0 col2" >EGRE539</td>
      <td id="T_8f2c9_row0_col3" class="data row0 col3" >001</td>
      <td id="T_8f2c9_row0_col4" class="data row0 col4" >INTRO TO MICROWAVE ENGINEERING</td>
      <td id="T_8f2c9_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_8f2c9_row0_col6" class="data row0 col6" >6</td>
      <td id="T_8f2c9_row0_col7" class="data row0 col7" >18</td>
      <td id="T_8f2c9_row0_col8" class="data row0 col8" >Suche</td>
    </tr>
    <tr>
      <td id="T_8f2c9_row1_col0" class="data row1 col0" >100</td>
      <td id="T_8f2c9_row1_col1" class="data row1 col1" >Fall 2025</td>
      <td id="T_8f2c9_row1_col2" class="data row1 col2" >ENGR100</td>
      <td id="T_8f2c9_row1_col3" class="data row1 col3" >901</td>
      <td id="T_8f2c9_row1_col4" class="data row1 col4" >ENGINEERING STUDENT SUCCESS</td>
      <td id="T_8f2c9_row1_col5" class="data row1 col5" >SEM</td>
      <td id="T_8f2c9_row1_col6" class="data row1 col6" >26</td>
      <td id="T_8f2c9_row1_col7" class="data row1 col7" >0</td>
      <td id="T_8f2c9_row1_col8" class="data row1 col8" >Rivers</td>
    </tr>
    <tr>
      <td id="T_8f2c9_row2_col0" class="data row2 col0" >395</td>
      <td id="T_8f2c9_row2_col1" class="data row2 col1" >Fall 2025</td>
      <td id="T_8f2c9_row2_col2" class="data row2 col2" >ENGR395</td>
      <td id="T_8f2c9_row2_col3" class="data row2 col3" >001</td>
      <td id="T_8f2c9_row2_col4" class="data row2 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_8f2c9_row2_col5" class="data row2 col5" >LEC</td>
      <td id="T_8f2c9_row2_col6" class="data row2 col6" >75</td>
      <td id="T_8f2c9_row2_col7" class="data row2 col7" >75</td>
      <td id="T_8f2c9_row2_col8" class="data row2 col8" >Walker</td>
    </tr>
    <tr>
      <td id="T_8f2c9_row3_col0" class="data row3 col0" >395</td>
      <td id="T_8f2c9_row3_col1" class="data row3 col1" >Fall 2025</td>
      <td id="T_8f2c9_row3_col2" class="data row3 col2" >ENGR395</td>
      <td id="T_8f2c9_row3_col3" class="data row3 col3" >002</td>
      <td id="T_8f2c9_row3_col4" class="data row3 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_8f2c9_row3_col5" class="data row3 col5" >LEC</td>
      <td id="T_8f2c9_row3_col6" class="data row3 col6" >47</td>
      <td id="T_8f2c9_row3_col7" class="data row3 col7" >47</td>
      <td id="T_8f2c9_row3_col8" class="data row3 col8" >Walker</td>
    </tr>
    <tr>
      <td id="T_8f2c9_row4_col0" class="data row4 col0" >395</td>
      <td id="T_8f2c9_row4_col1" class="data row4 col1" >Fall 2025</td>
      <td id="T_8f2c9_row4_col2" class="data row4 col2" >ENGR395</td>
      <td id="T_8f2c9_row4_col3" class="data row4 col3" >003</td>
      <td id="T_8f2c9_row4_col4" class="data row4 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_8f2c9_row4_col5" class="data row4 col5" >LEC</td>
      <td id="T_8f2c9_row4_col6" class="data row4 col6" >49</td>
      <td id="T_8f2c9_row4_col7" class="data row4 col7" >49</td>
      <td id="T_8f2c9_row4_col8" class="data row4 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_8f2c9_row5_col0" class="data row5 col0" >395</td>
      <td id="T_8f2c9_row5_col1" class="data row5 col1" >Fall 2025</td>
      <td id="T_8f2c9_row5_col2" class="data row5 col2" >ENGR395</td>
      <td id="T_8f2c9_row5_col3" class="data row5 col3" >004</td>
      <td id="T_8f2c9_row5_col4" class="data row5 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_8f2c9_row5_col5" class="data row5 col5" >LEC</td>
      <td id="T_8f2c9_row5_col6" class="data row5 col6" >74</td>
      <td id="T_8f2c9_row5_col7" class="data row5 col7" >74</td>
      <td id="T_8f2c9_row5_col8" class="data row5 col8" >Jones</td>
    </tr>
    <tr>
      <td id="T_8f2c9_row6_col0" class="data row6 col0" >395</td>
      <td id="T_8f2c9_row6_col1" class="data row6 col1" >Fall 2025</td>
      <td id="T_8f2c9_row6_col2" class="data row6 col2" >ENGR395</td>
      <td id="T_8f2c9_row6_col3" class="data row6 col3" >005</td>
      <td id="T_8f2c9_row6_col4" class="data row6 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_8f2c9_row6_col5" class="data row6 col5" >LEC</td>
      <td id="T_8f2c9_row6_col6" class="data row6 col6" >40</td>
      <td id="T_8f2c9_row6_col7" class="data row6 col7" >40</td>
      <td id="T_8f2c9_row6_col8" class="data row6 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_8f2c9_row7_col0" class="data row7 col0" >396</td>
      <td id="T_8f2c9_row7_col1" class="data row7 col1" >Fall 2025</td>
      <td id="T_8f2c9_row7_col2" class="data row7 col2" >ENGR396</td>
      <td id="T_8f2c9_row7_col3" class="data row7 col3" >001</td>
      <td id="T_8f2c9_row7_col4" class="data row7 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_8f2c9_row7_col5" class="data row7 col5" >FLD</td>
      <td id="T_8f2c9_row7_col6" class="data row7 col6" >18</td>
      <td id="T_8f2c9_row7_col7" class="data row7 col7" >0</td>
      <td id="T_8f2c9_row7_col8" class="data row7 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_8f2c9_row8_col0" class="data row8 col0" >398</td>
      <td id="T_8f2c9_row8_col1" class="data row8 col1" >Fall 2025</td>
      <td id="T_8f2c9_row8_col2" class="data row8 col2" >ENGR398</td>
      <td id="T_8f2c9_row8_col3" class="data row8 col3" >001</td>
      <td id="T_8f2c9_row8_col4" class="data row8 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_8f2c9_row8_col5" class="data row8 col5" >FLD</td>
      <td id="T_8f2c9_row8_col6" class="data row8 col6" >4</td>
      <td id="T_8f2c9_row8_col7" class="data row8 col7" >0</td>
      <td id="T_8f2c9_row8_col8" class="data row8 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_8f2c9_row9_col0" class="data row9 col0" >494</td>
      <td id="T_8f2c9_row9_col1" class="data row9 col1" >Fall 2025</td>
      <td id="T_8f2c9_row9_col2" class="data row9 col2" >ENGR494</td>
      <td id="T_8f2c9_row9_col3" class="data row9 col3" >001</td>
      <td id="T_8f2c9_row9_col4" class="data row9 col4" >INTERN OR CO-OP FOR CREDIT</td>
      <td id="T_8f2c9_row9_col5" class="data row9 col5" >FLD</td>
      <td id="T_8f2c9_row9_col6" class="data row9 col6" >9</td>
      <td id="T_8f2c9_row9_col7" class="data row9 col7" >27</td>
      <td id="T_8f2c9_row9_col8" class="data row9 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_8f2c9_row10_col0" class="data row10 col0" >496</td>
      <td id="T_8f2c9_row10_col1" class="data row10 col1" >Fall 2025</td>
      <td id="T_8f2c9_row10_col2" class="data row10 col2" >ENGR496</td>
      <td id="T_8f2c9_row10_col3" class="data row10 col3" >001</td>
      <td id="T_8f2c9_row10_col4" class="data row10 col4" >INTERNSHIP REVIEW</td>
      <td id="T_8f2c9_row10_col5" class="data row10 col5" >FLD</td>
      <td id="T_8f2c9_row10_col6" class="data row10 col6" >62</td>
      <td id="T_8f2c9_row10_col7" class="data row10 col7" >0</td>
      <td id="T_8f2c9_row10_col8" class="data row10 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_8f2c9_row11_col0" class="data row11 col0" >498</td>
      <td id="T_8f2c9_row11_col1" class="data row11 col1" >Fall 2025</td>
      <td id="T_8f2c9_row11_col2" class="data row11 col2" >ENGR498</td>
      <td id="T_8f2c9_row11_col3" class="data row11 col3" >001</td>
      <td id="T_8f2c9_row11_col4" class="data row11 col4" >REVIEW OF COOP EDUCATION EXP</td>
      <td id="T_8f2c9_row11_col5" class="data row11 col5" >FLD</td>
      <td id="T_8f2c9_row11_col6" class="data row11 col6" >3</td>
      <td id="T_8f2c9_row11_col7" class="data row11 col7" >0</td>
      <td id="T_8f2c9_row11_col8" class="data row11 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_8f2c9_row12_col0" class="data row12 col0" >591</td>
      <td id="T_8f2c9_row12_col1" class="data row12 col1" >Fall 2025</td>
      <td id="T_8f2c9_row12_col2" class="data row12 col2" >ENGR591</td>
      <td id="T_8f2c9_row12_col3" class="data row12 col3" >901</td>
      <td id="T_8f2c9_row12_col4" class="data row12 col4" >SPEC TOPICS IN PHARM ENGR</td>
      <td id="T_8f2c9_row12_col5" class="data row12 col5" >LEC</td>
      <td id="T_8f2c9_row12_col6" class="data row12 col6" >1</td>
      <td id="T_8f2c9_row12_col7" class="data row12 col7" >1</td>
      <td id="T_8f2c9_row12_col8" class="data row12 col8" >Roper</td>
    </tr>
    <tr>
      <td id="T_8f2c9_row13_col0" class="data row13 col0" >591</td>
      <td id="T_8f2c9_row13_col1" class="data row13 col1" >Fall 2025</td>
      <td id="T_8f2c9_row13_col2" class="data row13 col2" >ENGR591</td>
      <td id="T_8f2c9_row13_col3" class="data row13 col3" >C06</td>
      <td id="T_8f2c9_row13_col4" class="data row13 col4" >TOP:COMPUTATIONAL FLUID DYNAMI</td>
      <td id="T_8f2c9_row13_col5" class="data row13 col5" >LEC</td>
      <td id="T_8f2c9_row13_col6" class="data row13 col6" >6</td>
      <td id="T_8f2c9_row13_col7" class="data row13 col7" >20</td>
      <td id="T_8f2c9_row13_col8" class="data row13 col8" >Roper</td>
    </tr>
    <tr>
      <td id="T_8f2c9_row14_col0" class="data row14 col0" >591</td>
      <td id="T_8f2c9_row14_col1" class="data row14 col1" >Fall 2025</td>
      <td id="T_8f2c9_row14_col2" class="data row14 col2" >ENGR591</td>
      <td id="T_8f2c9_row14_col3" class="data row14 col3" >C08</td>
      <td id="T_8f2c9_row14_col4" class="data row14 col4" >ST: COMPUTATIONAL FLUID DYN</td>
      <td id="T_8f2c9_row14_col5" class="data row14 col5" >LEC</td>
      <td id="T_8f2c9_row14_col6" class="data row14 col6" >7</td>
      <td id="T_8f2c9_row14_col7" class="data row14 col7" >21</td>
      <td id="T_8f2c9_row14_col8" class="data row14 col8" >Roper</td>
    </tr>
    <tr>
      <td id="T_8f2c9_row15_col0" class="data row15 col0" >691</td>
      <td id="T_8f2c9_row15_col1" class="data row15 col1" >Fall 2025</td>
      <td id="T_8f2c9_row15_col2" class="data row15 col2" >ENGR691</td>
      <td id="T_8f2c9_row15_col3" class="data row15 col3" >001</td>
      <td id="T_8f2c9_row15_col4" class="data row15 col4" >ST: CAREER READINESS</td>
      <td id="T_8f2c9_row15_col5" class="data row15 col5" >LEC</td>
      <td id="T_8f2c9_row15_col6" class="data row15 col6" >2</td>
      <td id="T_8f2c9_row15_col7" class="data row15 col7" >2</td>
      <td id="T_8f2c9_row15_col8" class="data row15 col8" >Avasthi</td>
    </tr>
  </tbody>
</table>

:::

# AY24-25

This section list instructor activity for the academic year AY24-25 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## Fall 2024

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_e9a4d table {
  width: 100%;
  border-collapse: collapse;
}
#T_e9a4d th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_e9a4d th {
  border: 0;
}
#T_e9a4d thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_e9a4d tbody td:nth-child(1) {
  display: none;
}
#T_e9a4d thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_e9a4d tbody td:nth-child(2) {
  display: none;
}
#T_e9a4d thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_e9a4d tbody td:nth-child(8) {
  display: none;
}
#T_e9a4d td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_e9a4d td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_e9a4d td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_e9a4d td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_e9a4d td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_e9a4d td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_e9a4d_row0_col0, #T_e9a4d_row0_col1, #T_e9a4d_row0_col2, #T_e9a4d_row0_col3, #T_e9a4d_row0_col4, #T_e9a4d_row0_col5, #T_e9a4d_row0_col6, #T_e9a4d_row0_col7, #T_e9a4d_row0_col8, #T_e9a4d_row3_col0, #T_e9a4d_row3_col1, #T_e9a4d_row3_col2, #T_e9a4d_row3_col3, #T_e9a4d_row3_col4, #T_e9a4d_row3_col5, #T_e9a4d_row3_col6, #T_e9a4d_row3_col7, #T_e9a4d_row3_col8, #T_e9a4d_row4_col0, #T_e9a4d_row4_col1, #T_e9a4d_row4_col2, #T_e9a4d_row4_col3, #T_e9a4d_row4_col4, #T_e9a4d_row4_col5, #T_e9a4d_row4_col6, #T_e9a4d_row4_col7, #T_e9a4d_row4_col8, #T_e9a4d_row5_col0, #T_e9a4d_row5_col1, #T_e9a4d_row5_col2, #T_e9a4d_row5_col3, #T_e9a4d_row5_col4, #T_e9a4d_row5_col5, #T_e9a4d_row5_col6, #T_e9a4d_row5_col7, #T_e9a4d_row5_col8, #T_e9a4d_row6_col0, #T_e9a4d_row6_col1, #T_e9a4d_row6_col2, #T_e9a4d_row6_col3, #T_e9a4d_row6_col4, #T_e9a4d_row6_col5, #T_e9a4d_row6_col6, #T_e9a4d_row6_col7, #T_e9a4d_row6_col8, #T_e9a4d_row7_col0, #T_e9a4d_row7_col1, #T_e9a4d_row7_col2, #T_e9a4d_row7_col3, #T_e9a4d_row7_col4, #T_e9a4d_row7_col5, #T_e9a4d_row7_col6, #T_e9a4d_row7_col7, #T_e9a4d_row7_col8, #T_e9a4d_row8_col0, #T_e9a4d_row8_col1, #T_e9a4d_row8_col2, #T_e9a4d_row8_col3, #T_e9a4d_row8_col4, #T_e9a4d_row8_col5, #T_e9a4d_row8_col6, #T_e9a4d_row8_col7, #T_e9a4d_row8_col8, #T_e9a4d_row9_col0, #T_e9a4d_row9_col1, #T_e9a4d_row9_col2, #T_e9a4d_row9_col3, #T_e9a4d_row9_col4, #T_e9a4d_row9_col5, #T_e9a4d_row9_col6, #T_e9a4d_row9_col7, #T_e9a4d_row9_col8, #T_e9a4d_row10_col0, #T_e9a4d_row10_col1, #T_e9a4d_row10_col2, #T_e9a4d_row10_col3, #T_e9a4d_row10_col4, #T_e9a4d_row10_col5, #T_e9a4d_row10_col6, #T_e9a4d_row10_col7, #T_e9a4d_row10_col8, #T_e9a4d_row14_col0, #T_e9a4d_row14_col1, #T_e9a4d_row14_col2, #T_e9a4d_row14_col3, #T_e9a4d_row14_col4, #T_e9a4d_row14_col5, #T_e9a4d_row14_col6, #T_e9a4d_row14_col7, #T_e9a4d_row14_col8, #T_e9a4d_row15_col0, #T_e9a4d_row15_col1, #T_e9a4d_row15_col2, #T_e9a4d_row15_col3, #T_e9a4d_row15_col4, #T_e9a4d_row15_col5, #T_e9a4d_row15_col6, #T_e9a4d_row15_col7, #T_e9a4d_row15_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
#T_e9a4d_row1_col0, #T_e9a4d_row1_col1, #T_e9a4d_row1_col2, #T_e9a4d_row1_col3, #T_e9a4d_row1_col4, #T_e9a4d_row1_col5, #T_e9a4d_row1_col6, #T_e9a4d_row1_col7, #T_e9a4d_row1_col8, #T_e9a4d_row2_col0, #T_e9a4d_row2_col1, #T_e9a4d_row2_col2, #T_e9a4d_row2_col3, #T_e9a4d_row2_col4, #T_e9a4d_row2_col5, #T_e9a4d_row2_col6, #T_e9a4d_row2_col7, #T_e9a4d_row2_col8, #T_e9a4d_row11_col0, #T_e9a4d_row11_col1, #T_e9a4d_row11_col2, #T_e9a4d_row11_col3, #T_e9a4d_row11_col4, #T_e9a4d_row11_col5, #T_e9a4d_row11_col6, #T_e9a4d_row11_col7, #T_e9a4d_row11_col8, #T_e9a4d_row12_col0, #T_e9a4d_row12_col1, #T_e9a4d_row12_col2, #T_e9a4d_row12_col3, #T_e9a4d_row12_col4, #T_e9a4d_row12_col5, #T_e9a4d_row12_col6, #T_e9a4d_row12_col7, #T_e9a4d_row12_col8, #T_e9a4d_row13_col0, #T_e9a4d_row13_col1, #T_e9a4d_row13_col2, #T_e9a4d_row13_col3, #T_e9a4d_row13_col4, #T_e9a4d_row13_col5, #T_e9a4d_row13_col6, #T_e9a4d_row13_col7, #T_e9a4d_row13_col8, #T_e9a4d_row16_col0, #T_e9a4d_row16_col1, #T_e9a4d_row16_col2, #T_e9a4d_row16_col3, #T_e9a4d_row16_col4, #T_e9a4d_row16_col5, #T_e9a4d_row16_col6, #T_e9a4d_row16_col7, #T_e9a4d_row16_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
</style>
<table id="T_e9a4d">
  <thead>
    <tr>
      <th id="T_e9a4d_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_e9a4d_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_e9a4d_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_e9a4d_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_e9a4d_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_e9a4d_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_e9a4d_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_e9a4d_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_e9a4d_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_e9a4d_row0_col0" class="data row0 col0" >539</td>
      <td id="T_e9a4d_row0_col1" class="data row0 col1" >Fall 2024</td>
      <td id="T_e9a4d_row0_col2" class="data row0 col2" >EGRE539</td>
      <td id="T_e9a4d_row0_col3" class="data row0 col3" >001</td>
      <td id="T_e9a4d_row0_col4" class="data row0 col4" >INTRO TO MICROWAVE ENGINEERING</td>
      <td id="T_e9a4d_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_e9a4d_row0_col6" class="data row0 col6" >4</td>
      <td id="T_e9a4d_row0_col7" class="data row0 col7" >12</td>
      <td id="T_e9a4d_row0_col8" class="data row0 col8" >Suche</td>
    </tr>
    <tr>
      <td id="T_e9a4d_row1_col0" class="data row1 col0" >100</td>
      <td id="T_e9a4d_row1_col1" class="data row1 col1" >Fall 2024</td>
      <td id="T_e9a4d_row1_col2" class="data row1 col2" >ENGR100</td>
      <td id="T_e9a4d_row1_col3" class="data row1 col3" >901</td>
      <td id="T_e9a4d_row1_col4" class="data row1 col4" >ENGINEERING STUDENT SUCCESS</td>
      <td id="T_e9a4d_row1_col5" class="data row1 col5" >SEM</td>
      <td id="T_e9a4d_row1_col6" class="data row1 col6" >22</td>
      <td id="T_e9a4d_row1_col7" class="data row1 col7" >0</td>
      <td id="T_e9a4d_row1_col8" class="data row1 col8" >Rivers</td>
    </tr>
    <tr>
      <td id="T_e9a4d_row2_col0" class="data row2 col0" >101</td>
      <td id="T_e9a4d_row2_col1" class="data row2 col1" >Fall 2024</td>
      <td id="T_e9a4d_row2_col2" class="data row2 col2" >ENGR101</td>
      <td id="T_e9a4d_row2_col3" class="data row2 col3" >C01</td>
      <td id="T_e9a4d_row2_col4" class="data row2 col4" >INTRODUCTION TO ENGINEERING</td>
      <td id="T_e9a4d_row2_col5" class="data row2 col5" >LEC</td>
      <td id="T_e9a4d_row2_col6" class="data row2 col6" >10</td>
      <td id="T_e9a4d_row2_col7" class="data row2 col7" >40</td>
      <td id="T_e9a4d_row2_col8" class="data row2 col8" >Draper</td>
    </tr>
    <tr>
      <td id="T_e9a4d_row3_col0" class="data row3 col0" >395</td>
      <td id="T_e9a4d_row3_col1" class="data row3 col1" >Fall 2024</td>
      <td id="T_e9a4d_row3_col2" class="data row3 col2" >ENGR395</td>
      <td id="T_e9a4d_row3_col3" class="data row3 col3" >001</td>
      <td id="T_e9a4d_row3_col4" class="data row3 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_e9a4d_row3_col5" class="data row3 col5" >LEC</td>
      <td id="T_e9a4d_row3_col6" class="data row3 col6" >69</td>
      <td id="T_e9a4d_row3_col7" class="data row3 col7" >69</td>
      <td id="T_e9a4d_row3_col8" class="data row3 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_e9a4d_row4_col0" class="data row4 col0" >395</td>
      <td id="T_e9a4d_row4_col1" class="data row4 col1" >Fall 2024</td>
      <td id="T_e9a4d_row4_col2" class="data row4 col2" >ENGR395</td>
      <td id="T_e9a4d_row4_col3" class="data row4 col3" >002</td>
      <td id="T_e9a4d_row4_col4" class="data row4 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_e9a4d_row4_col5" class="data row4 col5" >LEC</td>
      <td id="T_e9a4d_row4_col6" class="data row4 col6" >72</td>
      <td id="T_e9a4d_row4_col7" class="data row4 col7" >72</td>
      <td id="T_e9a4d_row4_col8" class="data row4 col8" >Walker</td>
    </tr>
    <tr>
      <td id="T_e9a4d_row5_col0" class="data row5 col0" >395</td>
      <td id="T_e9a4d_row5_col1" class="data row5 col1" >Fall 2024</td>
      <td id="T_e9a4d_row5_col2" class="data row5 col2" >ENGR395</td>
      <td id="T_e9a4d_row5_col3" class="data row5 col3" >003</td>
      <td id="T_e9a4d_row5_col4" class="data row5 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_e9a4d_row5_col5" class="data row5 col5" >LEC</td>
      <td id="T_e9a4d_row5_col6" class="data row5 col6" >70</td>
      <td id="T_e9a4d_row5_col7" class="data row5 col7" >70</td>
      <td id="T_e9a4d_row5_col8" class="data row5 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_e9a4d_row6_col0" class="data row6 col0" >395</td>
      <td id="T_e9a4d_row6_col1" class="data row6 col1" >Fall 2024</td>
      <td id="T_e9a4d_row6_col2" class="data row6 col2" >ENGR395</td>
      <td id="T_e9a4d_row6_col3" class="data row6 col3" >004</td>
      <td id="T_e9a4d_row6_col4" class="data row6 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_e9a4d_row6_col5" class="data row6 col5" >LEC</td>
      <td id="T_e9a4d_row6_col6" class="data row6 col6" >72</td>
      <td id="T_e9a4d_row6_col7" class="data row6 col7" >72</td>
      <td id="T_e9a4d_row6_col8" class="data row6 col8" >Jones</td>
    </tr>
    <tr>
      <td id="T_e9a4d_row7_col0" class="data row7 col0" >395</td>
      <td id="T_e9a4d_row7_col1" class="data row7 col1" >Fall 2024</td>
      <td id="T_e9a4d_row7_col2" class="data row7 col2" >ENGR395</td>
      <td id="T_e9a4d_row7_col3" class="data row7 col3" >005</td>
      <td id="T_e9a4d_row7_col4" class="data row7 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_e9a4d_row7_col5" class="data row7 col5" >LEC</td>
      <td id="T_e9a4d_row7_col6" class="data row7 col6" >75</td>
      <td id="T_e9a4d_row7_col7" class="data row7 col7" >75</td>
      <td id="T_e9a4d_row7_col8" class="data row7 col8" >Kinchlow</td>
    </tr>
    <tr>
      <td id="T_e9a4d_row8_col0" class="data row8 col0" >396</td>
      <td id="T_e9a4d_row8_col1" class="data row8 col1" >Fall 2024</td>
      <td id="T_e9a4d_row8_col2" class="data row8 col2" >ENGR396</td>
      <td id="T_e9a4d_row8_col3" class="data row8 col3" >001</td>
      <td id="T_e9a4d_row8_col4" class="data row8 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_e9a4d_row8_col5" class="data row8 col5" >FLD</td>
      <td id="T_e9a4d_row8_col6" class="data row8 col6" >14</td>
      <td id="T_e9a4d_row8_col7" class="data row8 col7" >0</td>
      <td id="T_e9a4d_row8_col8" class="data row8 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_e9a4d_row9_col0" class="data row9 col0" >396</td>
      <td id="T_e9a4d_row9_col1" class="data row9 col1" >Fall 2024</td>
      <td id="T_e9a4d_row9_col2" class="data row9 col2" >ENGR396</td>
      <td id="T_e9a4d_row9_col3" class="data row9 col3" >001</td>
      <td id="T_e9a4d_row9_col4" class="data row9 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_e9a4d_row9_col5" class="data row9 col5" >FLD</td>
      <td id="T_e9a4d_row9_col6" class="data row9 col6" >14</td>
      <td id="T_e9a4d_row9_col7" class="data row9 col7" >0</td>
      <td id="T_e9a4d_row9_col8" class="data row9 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_e9a4d_row10_col0" class="data row10 col0" >398</td>
      <td id="T_e9a4d_row10_col1" class="data row10 col1" >Fall 2024</td>
      <td id="T_e9a4d_row10_col2" class="data row10 col2" >ENGR398</td>
      <td id="T_e9a4d_row10_col3" class="data row10 col3" >001</td>
      <td id="T_e9a4d_row10_col4" class="data row10 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_e9a4d_row10_col5" class="data row10 col5" >FLD</td>
      <td id="T_e9a4d_row10_col6" class="data row10 col6" >8</td>
      <td id="T_e9a4d_row10_col7" class="data row10 col7" >0</td>
      <td id="T_e9a4d_row10_col8" class="data row10 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_e9a4d_row11_col0" class="data row11 col0" >496</td>
      <td id="T_e9a4d_row11_col1" class="data row11 col1" >Fall 2024</td>
      <td id="T_e9a4d_row11_col2" class="data row11 col2" >ENGR496</td>
      <td id="T_e9a4d_row11_col3" class="data row11 col3" >001</td>
      <td id="T_e9a4d_row11_col4" class="data row11 col4" >INTERNSHIP REVIEW</td>
      <td id="T_e9a4d_row11_col5" class="data row11 col5" >FLD</td>
      <td id="T_e9a4d_row11_col6" class="data row11 col6" >36</td>
      <td id="T_e9a4d_row11_col7" class="data row11 col7" >0</td>
      <td id="T_e9a4d_row11_col8" class="data row11 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_e9a4d_row12_col0" class="data row12 col0" >496</td>
      <td id="T_e9a4d_row12_col1" class="data row12 col1" >Fall 2024</td>
      <td id="T_e9a4d_row12_col2" class="data row12 col2" >ENGR496</td>
      <td id="T_e9a4d_row12_col3" class="data row12 col3" >001</td>
      <td id="T_e9a4d_row12_col4" class="data row12 col4" >INTERNSHIP REVIEW</td>
      <td id="T_e9a4d_row12_col5" class="data row12 col5" >FLD</td>
      <td id="T_e9a4d_row12_col6" class="data row12 col6" >36</td>
      <td id="T_e9a4d_row12_col7" class="data row12 col7" >0</td>
      <td id="T_e9a4d_row12_col8" class="data row12 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_e9a4d_row13_col0" class="data row13 col0" >498</td>
      <td id="T_e9a4d_row13_col1" class="data row13 col1" >Fall 2024</td>
      <td id="T_e9a4d_row13_col2" class="data row13 col2" >ENGR498</td>
      <td id="T_e9a4d_row13_col3" class="data row13 col3" >001</td>
      <td id="T_e9a4d_row13_col4" class="data row13 col4" >REVIEW OF COOP EDUCATION EXP</td>
      <td id="T_e9a4d_row13_col5" class="data row13 col5" >FLD</td>
      <td id="T_e9a4d_row13_col6" class="data row13 col6" >4</td>
      <td id="T_e9a4d_row13_col7" class="data row13 col7" >0</td>
      <td id="T_e9a4d_row13_col8" class="data row13 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_e9a4d_row14_col0" class="data row14 col0" >591</td>
      <td id="T_e9a4d_row14_col1" class="data row14 col1" >Fall 2024</td>
      <td id="T_e9a4d_row14_col2" class="data row14 col2" >ENGR591</td>
      <td id="T_e9a4d_row14_col3" class="data row14 col3" >002</td>
      <td id="T_e9a4d_row14_col4" class="data row14 col4" >TOP:COMPUTATIONAL FLUID DYNAMI</td>
      <td id="T_e9a4d_row14_col5" class="data row14 col5" >LEC</td>
      <td id="T_e9a4d_row14_col6" class="data row14 col6" >7</td>
      <td id="T_e9a4d_row14_col7" class="data row14 col7" >21</td>
      <td id="T_e9a4d_row14_col8" class="data row14 col8" >Roper</td>
    </tr>
    <tr>
      <td id="T_e9a4d_row15_col0" class="data row15 col0" >591</td>
      <td id="T_e9a4d_row15_col1" class="data row15 col1" >Fall 2024</td>
      <td id="T_e9a4d_row15_col2" class="data row15 col2" >ENGR591</td>
      <td id="T_e9a4d_row15_col3" class="data row15 col3" >C07</td>
      <td id="T_e9a4d_row15_col4" class="data row15 col4" >ST: INTRO TO CATALYSIS</td>
      <td id="T_e9a4d_row15_col5" class="data row15 col5" >LEC</td>
      <td id="T_e9a4d_row15_col6" class="data row15 col6" >11</td>
      <td id="T_e9a4d_row15_col7" class="data row15 col7" >33</td>
      <td id="T_e9a4d_row15_col8" class="data row15 col8" >Gregory</td>
    </tr>
    <tr>
      <td id="T_e9a4d_row16_col0" class="data row16 col0" >691</td>
      <td id="T_e9a4d_row16_col1" class="data row16 col1" >Fall 2024</td>
      <td id="T_e9a4d_row16_col2" class="data row16 col2" >ENGR691</td>
      <td id="T_e9a4d_row16_col3" class="data row16 col3" >001</td>
      <td id="T_e9a4d_row16_col4" class="data row16 col4" >ST: CAREER READINESS</td>
      <td id="T_e9a4d_row16_col5" class="data row16 col5" >LEC</td>
      <td id="T_e9a4d_row16_col6" class="data row16 col6" >21</td>
      <td id="T_e9a4d_row16_col7" class="data row16 col7" >21</td>
      <td id="T_e9a4d_row16_col8" class="data row16 col8" >Avasthi</td>
    </tr>
  </tbody>
</table>

:::

## Spring 2025

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_92c22 table {
  width: 100%;
  border-collapse: collapse;
}
#T_92c22 th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_92c22 th {
  border: 0;
}
#T_92c22 thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_92c22 tbody td:nth-child(1) {
  display: none;
}
#T_92c22 thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_92c22 tbody td:nth-child(2) {
  display: none;
}
#T_92c22 thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_92c22 tbody td:nth-child(8) {
  display: none;
}
#T_92c22 td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_92c22 td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_92c22 td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_92c22 td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_92c22 td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_92c22 td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_92c22_row0_col0, #T_92c22_row0_col1, #T_92c22_row0_col2, #T_92c22_row0_col3, #T_92c22_row0_col4, #T_92c22_row0_col5, #T_92c22_row0_col6, #T_92c22_row0_col7, #T_92c22_row0_col8, #T_92c22_row1_col0, #T_92c22_row1_col1, #T_92c22_row1_col2, #T_92c22_row1_col3, #T_92c22_row1_col4, #T_92c22_row1_col5, #T_92c22_row1_col6, #T_92c22_row1_col7, #T_92c22_row1_col8, #T_92c22_row2_col0, #T_92c22_row2_col1, #T_92c22_row2_col2, #T_92c22_row2_col3, #T_92c22_row2_col4, #T_92c22_row2_col5, #T_92c22_row2_col6, #T_92c22_row2_col7, #T_92c22_row2_col8, #T_92c22_row3_col0, #T_92c22_row3_col1, #T_92c22_row3_col2, #T_92c22_row3_col3, #T_92c22_row3_col4, #T_92c22_row3_col5, #T_92c22_row3_col6, #T_92c22_row3_col7, #T_92c22_row3_col8, #T_92c22_row4_col0, #T_92c22_row4_col1, #T_92c22_row4_col2, #T_92c22_row4_col3, #T_92c22_row4_col4, #T_92c22_row4_col5, #T_92c22_row4_col6, #T_92c22_row4_col7, #T_92c22_row4_col8, #T_92c22_row5_col0, #T_92c22_row5_col1, #T_92c22_row5_col2, #T_92c22_row5_col3, #T_92c22_row5_col4, #T_92c22_row5_col5, #T_92c22_row5_col6, #T_92c22_row5_col7, #T_92c22_row5_col8, #T_92c22_row6_col0, #T_92c22_row6_col1, #T_92c22_row6_col2, #T_92c22_row6_col3, #T_92c22_row6_col4, #T_92c22_row6_col5, #T_92c22_row6_col6, #T_92c22_row6_col7, #T_92c22_row6_col8, #T_92c22_row7_col0, #T_92c22_row7_col1, #T_92c22_row7_col2, #T_92c22_row7_col3, #T_92c22_row7_col4, #T_92c22_row7_col5, #T_92c22_row7_col6, #T_92c22_row7_col7, #T_92c22_row7_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_92c22_row8_col0, #T_92c22_row8_col1, #T_92c22_row8_col2, #T_92c22_row8_col3, #T_92c22_row8_col4, #T_92c22_row8_col5, #T_92c22_row8_col6, #T_92c22_row8_col7, #T_92c22_row8_col8, #T_92c22_row9_col0, #T_92c22_row9_col1, #T_92c22_row9_col2, #T_92c22_row9_col3, #T_92c22_row9_col4, #T_92c22_row9_col5, #T_92c22_row9_col6, #T_92c22_row9_col7, #T_92c22_row9_col8, #T_92c22_row10_col0, #T_92c22_row10_col1, #T_92c22_row10_col2, #T_92c22_row10_col3, #T_92c22_row10_col4, #T_92c22_row10_col5, #T_92c22_row10_col6, #T_92c22_row10_col7, #T_92c22_row10_col8, #T_92c22_row11_col0, #T_92c22_row11_col1, #T_92c22_row11_col2, #T_92c22_row11_col3, #T_92c22_row11_col4, #T_92c22_row11_col5, #T_92c22_row11_col6, #T_92c22_row11_col7, #T_92c22_row11_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_92c22">
  <thead>
    <tr>
      <th id="T_92c22_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_92c22_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_92c22_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_92c22_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_92c22_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_92c22_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_92c22_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_92c22_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_92c22_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_92c22_row0_col0" class="data row0 col0" >540</td>
      <td id="T_92c22_row0_col1" class="data row0 col1" >Spring 2025</td>
      <td id="T_92c22_row0_col2" class="data row0 col2" >EGRE540</td>
      <td id="T_92c22_row0_col3" class="data row0 col3" >001</td>
      <td id="T_92c22_row0_col4" class="data row0 col4" >MICROWAVE SYSTEM DESIGN</td>
      <td id="T_92c22_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_92c22_row0_col6" class="data row0 col6" >9</td>
      <td id="T_92c22_row0_col7" class="data row0 col7" >27</td>
      <td id="T_92c22_row0_col8" class="data row0 col8" >Suche</td>
    </tr>
    <tr>
      <td id="T_92c22_row1_col0" class="data row1 col0" >395</td>
      <td id="T_92c22_row1_col1" class="data row1 col1" >Spring 2025</td>
      <td id="T_92c22_row1_col2" class="data row1 col2" >ENGR395</td>
      <td id="T_92c22_row1_col3" class="data row1 col3" >001</td>
      <td id="T_92c22_row1_col4" class="data row1 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_92c22_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_92c22_row1_col6" class="data row1 col6" >56</td>
      <td id="T_92c22_row1_col7" class="data row1 col7" >56</td>
      <td id="T_92c22_row1_col8" class="data row1 col8" >Jones</td>
    </tr>
    <tr>
      <td id="T_92c22_row2_col0" class="data row2 col0" >395</td>
      <td id="T_92c22_row2_col1" class="data row2 col1" >Spring 2025</td>
      <td id="T_92c22_row2_col2" class="data row2 col2" >ENGR395</td>
      <td id="T_92c22_row2_col3" class="data row2 col3" >003</td>
      <td id="T_92c22_row2_col4" class="data row2 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_92c22_row2_col5" class="data row2 col5" >LEC</td>
      <td id="T_92c22_row2_col6" class="data row2 col6" >55</td>
      <td id="T_92c22_row2_col7" class="data row2 col7" >55</td>
      <td id="T_92c22_row2_col8" class="data row2 col8" >Walker</td>
    </tr>
    <tr>
      <td id="T_92c22_row3_col0" class="data row3 col0" >395</td>
      <td id="T_92c22_row3_col1" class="data row3 col1" >Spring 2025</td>
      <td id="T_92c22_row3_col2" class="data row3 col2" >ENGR395</td>
      <td id="T_92c22_row3_col3" class="data row3 col3" >004</td>
      <td id="T_92c22_row3_col4" class="data row3 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_92c22_row3_col5" class="data row3 col5" >LEC</td>
      <td id="T_92c22_row3_col6" class="data row3 col6" >58</td>
      <td id="T_92c22_row3_col7" class="data row3 col7" >58</td>
      <td id="T_92c22_row3_col8" class="data row3 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_92c22_row4_col0" class="data row4 col0" >395</td>
      <td id="T_92c22_row4_col1" class="data row4 col1" >Spring 2025</td>
      <td id="T_92c22_row4_col2" class="data row4 col2" >ENGR395</td>
      <td id="T_92c22_row4_col3" class="data row4 col3" >005</td>
      <td id="T_92c22_row4_col4" class="data row4 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_92c22_row4_col5" class="data row4 col5" >LEC</td>
      <td id="T_92c22_row4_col6" class="data row4 col6" >70</td>
      <td id="T_92c22_row4_col7" class="data row4 col7" >70</td>
      <td id="T_92c22_row4_col8" class="data row4 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_92c22_row5_col0" class="data row5 col0" >396</td>
      <td id="T_92c22_row5_col1" class="data row5 col1" >Spring 2025</td>
      <td id="T_92c22_row5_col2" class="data row5 col2" >ENGR396</td>
      <td id="T_92c22_row5_col3" class="data row5 col3" >001</td>
      <td id="T_92c22_row5_col4" class="data row5 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_92c22_row5_col5" class="data row5 col5" >FLD</td>
      <td id="T_92c22_row5_col6" class="data row5 col6" >14</td>
      <td id="T_92c22_row5_col7" class="data row5 col7" >0</td>
      <td id="T_92c22_row5_col8" class="data row5 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_92c22_row6_col0" class="data row6 col0" >398</td>
      <td id="T_92c22_row6_col1" class="data row6 col1" >Spring 2025</td>
      <td id="T_92c22_row6_col2" class="data row6 col2" >ENGR398</td>
      <td id="T_92c22_row6_col3" class="data row6 col3" >001</td>
      <td id="T_92c22_row6_col4" class="data row6 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_92c22_row6_col5" class="data row6 col5" >FLD</td>
      <td id="T_92c22_row6_col6" class="data row6 col6" >10</td>
      <td id="T_92c22_row6_col7" class="data row6 col7" >0</td>
      <td id="T_92c22_row6_col8" class="data row6 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_92c22_row7_col0" class="data row7 col0" >398</td>
      <td id="T_92c22_row7_col1" class="data row7 col1" >Spring 2025</td>
      <td id="T_92c22_row7_col2" class="data row7 col2" >ENGR398</td>
      <td id="T_92c22_row7_col3" class="data row7 col3" >002</td>
      <td id="T_92c22_row7_col4" class="data row7 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_92c22_row7_col5" class="data row7 col5" >FLD</td>
      <td id="T_92c22_row7_col6" class="data row7 col6" >1</td>
      <td id="T_92c22_row7_col7" class="data row7 col7" >0</td>
      <td id="T_92c22_row7_col8" class="data row7 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_92c22_row8_col0" class="data row8 col0" >496</td>
      <td id="T_92c22_row8_col1" class="data row8 col1" >Spring 2025</td>
      <td id="T_92c22_row8_col2" class="data row8 col2" >ENGR496</td>
      <td id="T_92c22_row8_col3" class="data row8 col3" >001</td>
      <td id="T_92c22_row8_col4" class="data row8 col4" >INTERNSHIP REVIEW</td>
      <td id="T_92c22_row8_col5" class="data row8 col5" >FLD</td>
      <td id="T_92c22_row8_col6" class="data row8 col6" >34</td>
      <td id="T_92c22_row8_col7" class="data row8 col7" >0</td>
      <td id="T_92c22_row8_col8" class="data row8 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_92c22_row9_col0" class="data row9 col0" >496</td>
      <td id="T_92c22_row9_col1" class="data row9 col1" >Spring 2025</td>
      <td id="T_92c22_row9_col2" class="data row9 col2" >ENGR496</td>
      <td id="T_92c22_row9_col3" class="data row9 col3" >002</td>
      <td id="T_92c22_row9_col4" class="data row9 col4" >INTERNSHIP REVIEW</td>
      <td id="T_92c22_row9_col5" class="data row9 col5" >FLD</td>
      <td id="T_92c22_row9_col6" class="data row9 col6" >1</td>
      <td id="T_92c22_row9_col7" class="data row9 col7" >0</td>
      <td id="T_92c22_row9_col8" class="data row9 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_92c22_row10_col0" class="data row10 col0" >498</td>
      <td id="T_92c22_row10_col1" class="data row10 col1" >Spring 2025</td>
      <td id="T_92c22_row10_col2" class="data row10 col2" >ENGR498</td>
      <td id="T_92c22_row10_col3" class="data row10 col3" >001</td>
      <td id="T_92c22_row10_col4" class="data row10 col4" >REVIEW OF COOP EDUCATION EXP</td>
      <td id="T_92c22_row10_col5" class="data row10 col5" >FLD</td>
      <td id="T_92c22_row10_col6" class="data row10 col6" >0</td>
      <td id="T_92c22_row10_col7" class="data row10 col7" >0</td>
      <td id="T_92c22_row10_col8" class="data row10 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_92c22_row11_col0" class="data row11 col0" >691</td>
      <td id="T_92c22_row11_col1" class="data row11 col1" >Spring 2025</td>
      <td id="T_92c22_row11_col2" class="data row11 col2" >ENGR691</td>
      <td id="T_92c22_row11_col3" class="data row11 col3" >001</td>
      <td id="T_92c22_row11_col4" class="data row11 col4" >ST: CAREER READINESS</td>
      <td id="T_92c22_row11_col5" class="data row11 col5" >LEC</td>
      <td id="T_92c22_row11_col6" class="data row11 col6" >8</td>
      <td id="T_92c22_row11_col7" class="data row11 col7" >8</td>
      <td id="T_92c22_row11_col8" class="data row11 col8" >Avasthi</td>
    </tr>
  </tbody>
</table>

:::

## Summer 2025

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_e851b table {
  width: 100%;
  border-collapse: collapse;
}
#T_e851b th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_e851b th {
  border: 0;
}
#T_e851b thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_e851b tbody td:nth-child(1) {
  display: none;
}
#T_e851b thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_e851b tbody td:nth-child(2) {
  display: none;
}
#T_e851b thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_e851b tbody td:nth-child(8) {
  display: none;
}
#T_e851b td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_e851b td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_e851b td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_e851b td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_e851b td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_e851b td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_e851b_row0_col0, #T_e851b_row0_col1, #T_e851b_row0_col2, #T_e851b_row0_col3, #T_e851b_row0_col4, #T_e851b_row0_col5, #T_e851b_row0_col6, #T_e851b_row0_col7, #T_e851b_row0_col8, #T_e851b_row1_col0, #T_e851b_row1_col1, #T_e851b_row1_col2, #T_e851b_row1_col3, #T_e851b_row1_col4, #T_e851b_row1_col5, #T_e851b_row1_col6, #T_e851b_row1_col7, #T_e851b_row1_col8, #T_e851b_row2_col0, #T_e851b_row2_col1, #T_e851b_row2_col2, #T_e851b_row2_col3, #T_e851b_row2_col4, #T_e851b_row2_col5, #T_e851b_row2_col6, #T_e851b_row2_col7, #T_e851b_row2_col8, #T_e851b_row4_col0, #T_e851b_row4_col1, #T_e851b_row4_col2, #T_e851b_row4_col3, #T_e851b_row4_col4, #T_e851b_row4_col5, #T_e851b_row4_col6, #T_e851b_row4_col7, #T_e851b_row4_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_e851b_row3_col0, #T_e851b_row3_col1, #T_e851b_row3_col2, #T_e851b_row3_col3, #T_e851b_row3_col4, #T_e851b_row3_col5, #T_e851b_row3_col6, #T_e851b_row3_col7, #T_e851b_row3_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_e851b">
  <thead>
    <tr>
      <th id="T_e851b_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_e851b_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_e851b_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_e851b_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_e851b_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_e851b_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_e851b_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_e851b_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_e851b_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_e851b_row0_col0" class="data row0 col0" >396</td>
      <td id="T_e851b_row0_col1" class="data row0 col1" >Summer 2025</td>
      <td id="T_e851b_row0_col2" class="data row0 col2" >ENGR396</td>
      <td id="T_e851b_row0_col3" class="data row0 col3" >001</td>
      <td id="T_e851b_row0_col4" class="data row0 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_e851b_row0_col5" class="data row0 col5" >FLD</td>
      <td id="T_e851b_row0_col6" class="data row0 col6" >90</td>
      <td id="T_e851b_row0_col7" class="data row0 col7" >0</td>
      <td id="T_e851b_row0_col8" class="data row0 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_e851b_row1_col0" class="data row1 col0" >396</td>
      <td id="T_e851b_row1_col1" class="data row1 col1" >Summer 2025</td>
      <td id="T_e851b_row1_col2" class="data row1 col2" >ENGR396</td>
      <td id="T_e851b_row1_col3" class="data row1 col3" >002</td>
      <td id="T_e851b_row1_col4" class="data row1 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_e851b_row1_col5" class="data row1 col5" >FLD</td>
      <td id="T_e851b_row1_col6" class="data row1 col6" >19</td>
      <td id="T_e851b_row1_col7" class="data row1 col7" >0</td>
      <td id="T_e851b_row1_col8" class="data row1 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_e851b_row2_col0" class="data row2 col0" >398</td>
      <td id="T_e851b_row2_col1" class="data row2 col1" >Summer 2025</td>
      <td id="T_e851b_row2_col2" class="data row2 col2" >ENGR398</td>
      <td id="T_e851b_row2_col3" class="data row2 col3" >001</td>
      <td id="T_e851b_row2_col4" class="data row2 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_e851b_row2_col5" class="data row2 col5" >FLD</td>
      <td id="T_e851b_row2_col6" class="data row2 col6" >4</td>
      <td id="T_e851b_row2_col7" class="data row2 col7" >0</td>
      <td id="T_e851b_row2_col8" class="data row2 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_e851b_row3_col0" class="data row3 col0" >496</td>
      <td id="T_e851b_row3_col1" class="data row3 col1" >Summer 2025</td>
      <td id="T_e851b_row3_col2" class="data row3 col2" >ENGR496</td>
      <td id="T_e851b_row3_col3" class="data row3 col3" >001</td>
      <td id="T_e851b_row3_col4" class="data row3 col4" >INTERNSHIP REVIEW</td>
      <td id="T_e851b_row3_col5" class="data row3 col5" >FLD</td>
      <td id="T_e851b_row3_col6" class="data row3 col6" >4</td>
      <td id="T_e851b_row3_col7" class="data row3 col7" >0</td>
      <td id="T_e851b_row3_col8" class="data row3 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_e851b_row4_col0" class="data row4 col0" >696</td>
      <td id="T_e851b_row4_col1" class="data row4 col1" >Summer 2025</td>
      <td id="T_e851b_row4_col2" class="data row4 col2" >ENGR696</td>
      <td id="T_e851b_row4_col3" class="data row4 col3" >C21</td>
      <td id="T_e851b_row4_col4" class="data row4 col4" >ENGRNG PRODUCTS & ECON CONSID</td>
      <td id="T_e851b_row4_col5" class="data row4 col5" >LEC</td>
      <td id="T_e851b_row4_col6" class="data row4 col6" >46</td>
      <td id="T_e851b_row4_col7" class="data row4 col7" >138</td>
      <td id="T_e851b_row4_col8" class="data row4 col8" >Avasthi</td>
    </tr>
  </tbody>
</table>

:::

# AY23-24

This section list instructor activity for the academic year AY23-24 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## Fall 2023

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_c8e8d table {
  width: 100%;
  border-collapse: collapse;
}
#T_c8e8d th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_c8e8d th {
  border: 0;
}
#T_c8e8d thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_c8e8d tbody td:nth-child(1) {
  display: none;
}
#T_c8e8d thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_c8e8d tbody td:nth-child(2) {
  display: none;
}
#T_c8e8d thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_c8e8d tbody td:nth-child(8) {
  display: none;
}
#T_c8e8d td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_c8e8d td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_c8e8d td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_c8e8d td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_c8e8d td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_c8e8d td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_c8e8d_row0_col0, #T_c8e8d_row0_col1, #T_c8e8d_row0_col2, #T_c8e8d_row0_col3, #T_c8e8d_row0_col4, #T_c8e8d_row0_col5, #T_c8e8d_row0_col6, #T_c8e8d_row0_col7, #T_c8e8d_row0_col8, #T_c8e8d_row9_col0, #T_c8e8d_row9_col1, #T_c8e8d_row9_col2, #T_c8e8d_row9_col3, #T_c8e8d_row9_col4, #T_c8e8d_row9_col5, #T_c8e8d_row9_col6, #T_c8e8d_row9_col7, #T_c8e8d_row9_col8, #T_c8e8d_row10_col0, #T_c8e8d_row10_col1, #T_c8e8d_row10_col2, #T_c8e8d_row10_col3, #T_c8e8d_row10_col4, #T_c8e8d_row10_col5, #T_c8e8d_row10_col6, #T_c8e8d_row10_col7, #T_c8e8d_row10_col8, #T_c8e8d_row11_col0, #T_c8e8d_row11_col1, #T_c8e8d_row11_col2, #T_c8e8d_row11_col3, #T_c8e8d_row11_col4, #T_c8e8d_row11_col5, #T_c8e8d_row11_col6, #T_c8e8d_row11_col7, #T_c8e8d_row11_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_c8e8d_row1_col0, #T_c8e8d_row1_col1, #T_c8e8d_row1_col2, #T_c8e8d_row1_col3, #T_c8e8d_row1_col4, #T_c8e8d_row1_col5, #T_c8e8d_row1_col6, #T_c8e8d_row1_col7, #T_c8e8d_row1_col8, #T_c8e8d_row2_col0, #T_c8e8d_row2_col1, #T_c8e8d_row2_col2, #T_c8e8d_row2_col3, #T_c8e8d_row2_col4, #T_c8e8d_row2_col5, #T_c8e8d_row2_col6, #T_c8e8d_row2_col7, #T_c8e8d_row2_col8, #T_c8e8d_row3_col0, #T_c8e8d_row3_col1, #T_c8e8d_row3_col2, #T_c8e8d_row3_col3, #T_c8e8d_row3_col4, #T_c8e8d_row3_col5, #T_c8e8d_row3_col6, #T_c8e8d_row3_col7, #T_c8e8d_row3_col8, #T_c8e8d_row4_col0, #T_c8e8d_row4_col1, #T_c8e8d_row4_col2, #T_c8e8d_row4_col3, #T_c8e8d_row4_col4, #T_c8e8d_row4_col5, #T_c8e8d_row4_col6, #T_c8e8d_row4_col7, #T_c8e8d_row4_col8, #T_c8e8d_row5_col0, #T_c8e8d_row5_col1, #T_c8e8d_row5_col2, #T_c8e8d_row5_col3, #T_c8e8d_row5_col4, #T_c8e8d_row5_col5, #T_c8e8d_row5_col6, #T_c8e8d_row5_col7, #T_c8e8d_row5_col8, #T_c8e8d_row6_col0, #T_c8e8d_row6_col1, #T_c8e8d_row6_col2, #T_c8e8d_row6_col3, #T_c8e8d_row6_col4, #T_c8e8d_row6_col5, #T_c8e8d_row6_col6, #T_c8e8d_row6_col7, #T_c8e8d_row6_col8, #T_c8e8d_row7_col0, #T_c8e8d_row7_col1, #T_c8e8d_row7_col2, #T_c8e8d_row7_col3, #T_c8e8d_row7_col4, #T_c8e8d_row7_col5, #T_c8e8d_row7_col6, #T_c8e8d_row7_col7, #T_c8e8d_row7_col8, #T_c8e8d_row8_col0, #T_c8e8d_row8_col1, #T_c8e8d_row8_col2, #T_c8e8d_row8_col3, #T_c8e8d_row8_col4, #T_c8e8d_row8_col5, #T_c8e8d_row8_col6, #T_c8e8d_row8_col7, #T_c8e8d_row8_col8, #T_c8e8d_row12_col0, #T_c8e8d_row12_col1, #T_c8e8d_row12_col2, #T_c8e8d_row12_col3, #T_c8e8d_row12_col4, #T_c8e8d_row12_col5, #T_c8e8d_row12_col6, #T_c8e8d_row12_col7, #T_c8e8d_row12_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_c8e8d">
  <thead>
    <tr>
      <th id="T_c8e8d_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_c8e8d_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_c8e8d_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_c8e8d_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_c8e8d_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_c8e8d_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_c8e8d_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_c8e8d_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_c8e8d_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_c8e8d_row0_col0" class="data row0 col0" >100</td>
      <td id="T_c8e8d_row0_col1" class="data row0 col1" >Fall 2023</td>
      <td id="T_c8e8d_row0_col2" class="data row0 col2" >ENGR100</td>
      <td id="T_c8e8d_row0_col3" class="data row0 col3" >901</td>
      <td id="T_c8e8d_row0_col4" class="data row0 col4" >ENGINEERING STUDENT SUCCESS</td>
      <td id="T_c8e8d_row0_col5" class="data row0 col5" >SEM</td>
      <td id="T_c8e8d_row0_col6" class="data row0 col6" >38</td>
      <td id="T_c8e8d_row0_col7" class="data row0 col7" >0</td>
      <td id="T_c8e8d_row0_col8" class="data row0 col8" >Rivers</td>
    </tr>
    <tr>
      <td id="T_c8e8d_row1_col0" class="data row1 col0" >395</td>
      <td id="T_c8e8d_row1_col1" class="data row1 col1" >Fall 2023</td>
      <td id="T_c8e8d_row1_col2" class="data row1 col2" >ENGR395</td>
      <td id="T_c8e8d_row1_col3" class="data row1 col3" >001</td>
      <td id="T_c8e8d_row1_col4" class="data row1 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c8e8d_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_c8e8d_row1_col6" class="data row1 col6" >68</td>
      <td id="T_c8e8d_row1_col7" class="data row1 col7" >68</td>
      <td id="T_c8e8d_row1_col8" class="data row1 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c8e8d_row2_col0" class="data row2 col0" >395</td>
      <td id="T_c8e8d_row2_col1" class="data row2 col1" >Fall 2023</td>
      <td id="T_c8e8d_row2_col2" class="data row2 col2" >ENGR395</td>
      <td id="T_c8e8d_row2_col3" class="data row2 col3" >002</td>
      <td id="T_c8e8d_row2_col4" class="data row2 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c8e8d_row2_col5" class="data row2 col5" >LEC</td>
      <td id="T_c8e8d_row2_col6" class="data row2 col6" >58</td>
      <td id="T_c8e8d_row2_col7" class="data row2 col7" >58</td>
      <td id="T_c8e8d_row2_col8" class="data row2 col8" >Sonnie</td>
    </tr>
    <tr>
      <td id="T_c8e8d_row3_col0" class="data row3 col0" >395</td>
      <td id="T_c8e8d_row3_col1" class="data row3 col1" >Fall 2023</td>
      <td id="T_c8e8d_row3_col2" class="data row3 col2" >ENGR395</td>
      <td id="T_c8e8d_row3_col3" class="data row3 col3" >003</td>
      <td id="T_c8e8d_row3_col4" class="data row3 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c8e8d_row3_col5" class="data row3 col5" >LEC</td>
      <td id="T_c8e8d_row3_col6" class="data row3 col6" >57</td>
      <td id="T_c8e8d_row3_col7" class="data row3 col7" >57</td>
      <td id="T_c8e8d_row3_col8" class="data row3 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c8e8d_row4_col0" class="data row4 col0" >395</td>
      <td id="T_c8e8d_row4_col1" class="data row4 col1" >Fall 2023</td>
      <td id="T_c8e8d_row4_col2" class="data row4 col2" >ENGR395</td>
      <td id="T_c8e8d_row4_col3" class="data row4 col3" >004</td>
      <td id="T_c8e8d_row4_col4" class="data row4 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c8e8d_row4_col5" class="data row4 col5" >LEC</td>
      <td id="T_c8e8d_row4_col6" class="data row4 col6" >61</td>
      <td id="T_c8e8d_row4_col7" class="data row4 col7" >61</td>
      <td id="T_c8e8d_row4_col8" class="data row4 col8" >Jones</td>
    </tr>
    <tr>
      <td id="T_c8e8d_row5_col0" class="data row5 col0" >395</td>
      <td id="T_c8e8d_row5_col1" class="data row5 col1" >Fall 2023</td>
      <td id="T_c8e8d_row5_col2" class="data row5 col2" >ENGR395</td>
      <td id="T_c8e8d_row5_col3" class="data row5 col3" >005</td>
      <td id="T_c8e8d_row5_col4" class="data row5 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c8e8d_row5_col5" class="data row5 col5" >LEC</td>
      <td id="T_c8e8d_row5_col6" class="data row5 col6" >50</td>
      <td id="T_c8e8d_row5_col7" class="data row5 col7" >50</td>
      <td id="T_c8e8d_row5_col8" class="data row5 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c8e8d_row6_col0" class="data row6 col0" >396</td>
      <td id="T_c8e8d_row6_col1" class="data row6 col1" >Fall 2023</td>
      <td id="T_c8e8d_row6_col2" class="data row6 col2" >ENGR396</td>
      <td id="T_c8e8d_row6_col3" class="data row6 col3" >001</td>
      <td id="T_c8e8d_row6_col4" class="data row6 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_c8e8d_row6_col5" class="data row6 col5" >FLD</td>
      <td id="T_c8e8d_row6_col6" class="data row6 col6" >8</td>
      <td id="T_c8e8d_row6_col7" class="data row6 col7" >0</td>
      <td id="T_c8e8d_row6_col8" class="data row6 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c8e8d_row7_col0" class="data row7 col0" >396</td>
      <td id="T_c8e8d_row7_col1" class="data row7 col1" >Fall 2023</td>
      <td id="T_c8e8d_row7_col2" class="data row7 col2" >ENGR396</td>
      <td id="T_c8e8d_row7_col3" class="data row7 col3" >001</td>
      <td id="T_c8e8d_row7_col4" class="data row7 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_c8e8d_row7_col5" class="data row7 col5" >FLD</td>
      <td id="T_c8e8d_row7_col6" class="data row7 col6" >8</td>
      <td id="T_c8e8d_row7_col7" class="data row7 col7" >0</td>
      <td id="T_c8e8d_row7_col8" class="data row7 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_c8e8d_row8_col0" class="data row8 col0" >398</td>
      <td id="T_c8e8d_row8_col1" class="data row8 col1" >Fall 2023</td>
      <td id="T_c8e8d_row8_col2" class="data row8 col2" >ENGR398</td>
      <td id="T_c8e8d_row8_col3" class="data row8 col3" >001</td>
      <td id="T_c8e8d_row8_col4" class="data row8 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_c8e8d_row8_col5" class="data row8 col5" >FLD</td>
      <td id="T_c8e8d_row8_col6" class="data row8 col6" >5</td>
      <td id="T_c8e8d_row8_col7" class="data row8 col7" >0</td>
      <td id="T_c8e8d_row8_col8" class="data row8 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c8e8d_row9_col0" class="data row9 col0" >496</td>
      <td id="T_c8e8d_row9_col1" class="data row9 col1" >Fall 2023</td>
      <td id="T_c8e8d_row9_col2" class="data row9 col2" >ENGR496</td>
      <td id="T_c8e8d_row9_col3" class="data row9 col3" >001</td>
      <td id="T_c8e8d_row9_col4" class="data row9 col4" >INTERNSHIP REVIEW</td>
      <td id="T_c8e8d_row9_col5" class="data row9 col5" >FLD</td>
      <td id="T_c8e8d_row9_col6" class="data row9 col6" >44</td>
      <td id="T_c8e8d_row9_col7" class="data row9 col7" >0</td>
      <td id="T_c8e8d_row9_col8" class="data row9 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c8e8d_row10_col0" class="data row10 col0" >496</td>
      <td id="T_c8e8d_row10_col1" class="data row10 col1" >Fall 2023</td>
      <td id="T_c8e8d_row10_col2" class="data row10 col2" >ENGR496</td>
      <td id="T_c8e8d_row10_col3" class="data row10 col3" >001</td>
      <td id="T_c8e8d_row10_col4" class="data row10 col4" >INTERNSHIP REVIEW</td>
      <td id="T_c8e8d_row10_col5" class="data row10 col5" >FLD</td>
      <td id="T_c8e8d_row10_col6" class="data row10 col6" >44</td>
      <td id="T_c8e8d_row10_col7" class="data row10 col7" >0</td>
      <td id="T_c8e8d_row10_col8" class="data row10 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_c8e8d_row11_col0" class="data row11 col0" >498</td>
      <td id="T_c8e8d_row11_col1" class="data row11 col1" >Fall 2023</td>
      <td id="T_c8e8d_row11_col2" class="data row11 col2" >ENGR498</td>
      <td id="T_c8e8d_row11_col3" class="data row11 col3" >001</td>
      <td id="T_c8e8d_row11_col4" class="data row11 col4" >REVIEW OF COOP EDUCATION EXP</td>
      <td id="T_c8e8d_row11_col5" class="data row11 col5" >FLD</td>
      <td id="T_c8e8d_row11_col6" class="data row11 col6" >4</td>
      <td id="T_c8e8d_row11_col7" class="data row11 col7" >0</td>
      <td id="T_c8e8d_row11_col8" class="data row11 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c8e8d_row12_col0" class="data row12 col0" >591</td>
      <td id="T_c8e8d_row12_col1" class="data row12 col1" >Fall 2023</td>
      <td id="T_c8e8d_row12_col2" class="data row12 col2" >ENGR591</td>
      <td id="T_c8e8d_row12_col3" class="data row12 col3" >002</td>
      <td id="T_c8e8d_row12_col4" class="data row12 col4" >TOP:COMPUTATIONAL FLUID DYNAMI</td>
      <td id="T_c8e8d_row12_col5" class="data row12 col5" >LEC</td>
      <td id="T_c8e8d_row12_col6" class="data row12 col6" >5</td>
      <td id="T_c8e8d_row12_col7" class="data row12 col7" >15</td>
      <td id="T_c8e8d_row12_col8" class="data row12 col8" >Roper</td>
    </tr>
  </tbody>
</table>

:::

## Spring 2024

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_c64d1 table {
  width: 100%;
  border-collapse: collapse;
}
#T_c64d1 th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_c64d1 th {
  border: 0;
}
#T_c64d1 thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_c64d1 tbody td:nth-child(1) {
  display: none;
}
#T_c64d1 thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_c64d1 tbody td:nth-child(2) {
  display: none;
}
#T_c64d1 thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_c64d1 tbody td:nth-child(8) {
  display: none;
}
#T_c64d1 td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_c64d1 td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_c64d1 td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_c64d1 td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_c64d1 td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_c64d1 td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_c64d1_row0_col0, #T_c64d1_row0_col1, #T_c64d1_row0_col2, #T_c64d1_row0_col3, #T_c64d1_row0_col4, #T_c64d1_row0_col5, #T_c64d1_row0_col6, #T_c64d1_row0_col7, #T_c64d1_row0_col8, #T_c64d1_row1_col0, #T_c64d1_row1_col1, #T_c64d1_row1_col2, #T_c64d1_row1_col3, #T_c64d1_row1_col4, #T_c64d1_row1_col5, #T_c64d1_row1_col6, #T_c64d1_row1_col7, #T_c64d1_row1_col8, #T_c64d1_row2_col0, #T_c64d1_row2_col1, #T_c64d1_row2_col2, #T_c64d1_row2_col3, #T_c64d1_row2_col4, #T_c64d1_row2_col5, #T_c64d1_row2_col6, #T_c64d1_row2_col7, #T_c64d1_row2_col8, #T_c64d1_row3_col0, #T_c64d1_row3_col1, #T_c64d1_row3_col2, #T_c64d1_row3_col3, #T_c64d1_row3_col4, #T_c64d1_row3_col5, #T_c64d1_row3_col6, #T_c64d1_row3_col7, #T_c64d1_row3_col8, #T_c64d1_row4_col0, #T_c64d1_row4_col1, #T_c64d1_row4_col2, #T_c64d1_row4_col3, #T_c64d1_row4_col4, #T_c64d1_row4_col5, #T_c64d1_row4_col6, #T_c64d1_row4_col7, #T_c64d1_row4_col8, #T_c64d1_row5_col0, #T_c64d1_row5_col1, #T_c64d1_row5_col2, #T_c64d1_row5_col3, #T_c64d1_row5_col4, #T_c64d1_row5_col5, #T_c64d1_row5_col6, #T_c64d1_row5_col7, #T_c64d1_row5_col8, #T_c64d1_row9_col0, #T_c64d1_row9_col1, #T_c64d1_row9_col2, #T_c64d1_row9_col3, #T_c64d1_row9_col4, #T_c64d1_row9_col5, #T_c64d1_row9_col6, #T_c64d1_row9_col7, #T_c64d1_row9_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_c64d1_row6_col0, #T_c64d1_row6_col1, #T_c64d1_row6_col2, #T_c64d1_row6_col3, #T_c64d1_row6_col4, #T_c64d1_row6_col5, #T_c64d1_row6_col6, #T_c64d1_row6_col7, #T_c64d1_row6_col8, #T_c64d1_row7_col0, #T_c64d1_row7_col1, #T_c64d1_row7_col2, #T_c64d1_row7_col3, #T_c64d1_row7_col4, #T_c64d1_row7_col5, #T_c64d1_row7_col6, #T_c64d1_row7_col7, #T_c64d1_row7_col8, #T_c64d1_row8_col0, #T_c64d1_row8_col1, #T_c64d1_row8_col2, #T_c64d1_row8_col3, #T_c64d1_row8_col4, #T_c64d1_row8_col5, #T_c64d1_row8_col6, #T_c64d1_row8_col7, #T_c64d1_row8_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_c64d1">
  <thead>
    <tr>
      <th id="T_c64d1_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_c64d1_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_c64d1_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_c64d1_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_c64d1_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_c64d1_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_c64d1_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_c64d1_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_c64d1_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_c64d1_row0_col0" class="data row0 col0" >395</td>
      <td id="T_c64d1_row0_col1" class="data row0 col1" >Spring 2024</td>
      <td id="T_c64d1_row0_col2" class="data row0 col2" >ENGR395</td>
      <td id="T_c64d1_row0_col3" class="data row0 col3" >001</td>
      <td id="T_c64d1_row0_col4" class="data row0 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c64d1_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_c64d1_row0_col6" class="data row0 col6" >67</td>
      <td id="T_c64d1_row0_col7" class="data row0 col7" >67</td>
      <td id="T_c64d1_row0_col8" class="data row0 col8" >Jones</td>
    </tr>
    <tr>
      <td id="T_c64d1_row1_col0" class="data row1 col0" >395</td>
      <td id="T_c64d1_row1_col1" class="data row1 col1" >Spring 2024</td>
      <td id="T_c64d1_row1_col2" class="data row1 col2" >ENGR395</td>
      <td id="T_c64d1_row1_col3" class="data row1 col3" >003</td>
      <td id="T_c64d1_row1_col4" class="data row1 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c64d1_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_c64d1_row1_col6" class="data row1 col6" >43</td>
      <td id="T_c64d1_row1_col7" class="data row1 col7" >43</td>
      <td id="T_c64d1_row1_col8" class="data row1 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c64d1_row2_col0" class="data row2 col0" >395</td>
      <td id="T_c64d1_row2_col1" class="data row2 col1" >Spring 2024</td>
      <td id="T_c64d1_row2_col2" class="data row2 col2" >ENGR395</td>
      <td id="T_c64d1_row2_col3" class="data row2 col3" >004</td>
      <td id="T_c64d1_row2_col4" class="data row2 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c64d1_row2_col5" class="data row2 col5" >LEC</td>
      <td id="T_c64d1_row2_col6" class="data row2 col6" >70</td>
      <td id="T_c64d1_row2_col7" class="data row2 col7" >70</td>
      <td id="T_c64d1_row2_col8" class="data row2 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c64d1_row3_col0" class="data row3 col0" >395</td>
      <td id="T_c64d1_row3_col1" class="data row3 col1" >Spring 2024</td>
      <td id="T_c64d1_row3_col2" class="data row3 col2" >ENGR395</td>
      <td id="T_c64d1_row3_col3" class="data row3 col3" >005</td>
      <td id="T_c64d1_row3_col4" class="data row3 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c64d1_row3_col5" class="data row3 col5" >LEC</td>
      <td id="T_c64d1_row3_col6" class="data row3 col6" >69</td>
      <td id="T_c64d1_row3_col7" class="data row3 col7" >69</td>
      <td id="T_c64d1_row3_col8" class="data row3 col8" >Sonnie</td>
    </tr>
    <tr>
      <td id="T_c64d1_row4_col0" class="data row4 col0" >396</td>
      <td id="T_c64d1_row4_col1" class="data row4 col1" >Spring 2024</td>
      <td id="T_c64d1_row4_col2" class="data row4 col2" >ENGR396</td>
      <td id="T_c64d1_row4_col3" class="data row4 col3" >001</td>
      <td id="T_c64d1_row4_col4" class="data row4 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_c64d1_row4_col5" class="data row4 col5" >FLD</td>
      <td id="T_c64d1_row4_col6" class="data row4 col6" >9</td>
      <td id="T_c64d1_row4_col7" class="data row4 col7" >0</td>
      <td id="T_c64d1_row4_col8" class="data row4 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c64d1_row5_col0" class="data row5 col0" >398</td>
      <td id="T_c64d1_row5_col1" class="data row5 col1" >Spring 2024</td>
      <td id="T_c64d1_row5_col2" class="data row5 col2" >ENGR398</td>
      <td id="T_c64d1_row5_col3" class="data row5 col3" >001</td>
      <td id="T_c64d1_row5_col4" class="data row5 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_c64d1_row5_col5" class="data row5 col5" >FLD</td>
      <td id="T_c64d1_row5_col6" class="data row5 col6" >8</td>
      <td id="T_c64d1_row5_col7" class="data row5 col7" >0</td>
      <td id="T_c64d1_row5_col8" class="data row5 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c64d1_row6_col0" class="data row6 col0" >496</td>
      <td id="T_c64d1_row6_col1" class="data row6 col1" >Spring 2024</td>
      <td id="T_c64d1_row6_col2" class="data row6 col2" >ENGR496</td>
      <td id="T_c64d1_row6_col3" class="data row6 col3" >001</td>
      <td id="T_c64d1_row6_col4" class="data row6 col4" >INTERNSHIP REVIEW</td>
      <td id="T_c64d1_row6_col5" class="data row6 col5" >FLD</td>
      <td id="T_c64d1_row6_col6" class="data row6 col6" >23</td>
      <td id="T_c64d1_row6_col7" class="data row6 col7" >0</td>
      <td id="T_c64d1_row6_col8" class="data row6 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c64d1_row7_col0" class="data row7 col0" >497</td>
      <td id="T_c64d1_row7_col1" class="data row7 col1" >Spring 2024</td>
      <td id="T_c64d1_row7_col2" class="data row7 col2" >ENGR497</td>
      <td id="T_c64d1_row7_col3" class="data row7 col3" >L60</td>
      <td id="T_c64d1_row7_col4" class="data row7 col4" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_c64d1_row7_col5" class="data row7 col5" >VIP</td>
      <td id="T_c64d1_row7_col6" class="data row7 col6" >1</td>
      <td id="T_c64d1_row7_col7" class="data row7 col7" >2</td>
      <td id="T_c64d1_row7_col8" class="data row7 col8" >Wijesinghe</td>
    </tr>
    <tr>
      <td id="T_c64d1_row8_col0" class="data row8 col0" >498</td>
      <td id="T_c64d1_row8_col1" class="data row8 col1" >Spring 2024</td>
      <td id="T_c64d1_row8_col2" class="data row8 col2" >ENGR498</td>
      <td id="T_c64d1_row8_col3" class="data row8 col3" >001</td>
      <td id="T_c64d1_row8_col4" class="data row8 col4" >REVIEW OF COOP EDUCATION EXP</td>
      <td id="T_c64d1_row8_col5" class="data row8 col5" >FLD</td>
      <td id="T_c64d1_row8_col6" class="data row8 col6" >2</td>
      <td id="T_c64d1_row8_col7" class="data row8 col7" >0</td>
      <td id="T_c64d1_row8_col8" class="data row8 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c64d1_row9_col0" class="data row9 col0" >591</td>
      <td id="T_c64d1_row9_col1" class="data row9 col1" >Spring 2024</td>
      <td id="T_c64d1_row9_col2" class="data row9 col2" >ENGR591</td>
      <td id="T_c64d1_row9_col3" class="data row9 col3" >005</td>
      <td id="T_c64d1_row9_col4" class="data row9 col4" >TOP: DESIGN OF REHAB TECH</td>
      <td id="T_c64d1_row9_col5" class="data row9 col5" >LEC</td>
      <td id="T_c64d1_row9_col6" class="data row9 col6" >3</td>
      <td id="T_c64d1_row9_col7" class="data row9 col7" >9</td>
      <td id="T_c64d1_row9_col8" class="data row9 col8" >Pidcoe</td>
    </tr>
  </tbody>
</table>

:::

## Summer 2024

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_b9c67 table {
  width: 100%;
  border-collapse: collapse;
}
#T_b9c67 th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_b9c67 th {
  border: 0;
}
#T_b9c67 thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_b9c67 tbody td:nth-child(1) {
  display: none;
}
#T_b9c67 thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_b9c67 tbody td:nth-child(2) {
  display: none;
}
#T_b9c67 thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_b9c67 tbody td:nth-child(8) {
  display: none;
}
#T_b9c67 td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_b9c67 td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_b9c67 td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_b9c67 td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_b9c67 td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_b9c67 td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_b9c67_row0_col0, #T_b9c67_row0_col1, #T_b9c67_row0_col2, #T_b9c67_row0_col3, #T_b9c67_row0_col4, #T_b9c67_row0_col5, #T_b9c67_row0_col6, #T_b9c67_row0_col7, #T_b9c67_row0_col8, #T_b9c67_row1_col0, #T_b9c67_row1_col1, #T_b9c67_row1_col2, #T_b9c67_row1_col3, #T_b9c67_row1_col4, #T_b9c67_row1_col5, #T_b9c67_row1_col6, #T_b9c67_row1_col7, #T_b9c67_row1_col8, #T_b9c67_row2_col0, #T_b9c67_row2_col1, #T_b9c67_row2_col2, #T_b9c67_row2_col3, #T_b9c67_row2_col4, #T_b9c67_row2_col5, #T_b9c67_row2_col6, #T_b9c67_row2_col7, #T_b9c67_row2_col8, #T_b9c67_row3_col0, #T_b9c67_row3_col1, #T_b9c67_row3_col2, #T_b9c67_row3_col3, #T_b9c67_row3_col4, #T_b9c67_row3_col5, #T_b9c67_row3_col6, #T_b9c67_row3_col7, #T_b9c67_row3_col8, #T_b9c67_row4_col0, #T_b9c67_row4_col1, #T_b9c67_row4_col2, #T_b9c67_row4_col3, #T_b9c67_row4_col4, #T_b9c67_row4_col5, #T_b9c67_row4_col6, #T_b9c67_row4_col7, #T_b9c67_row4_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_b9c67_row5_col0, #T_b9c67_row5_col1, #T_b9c67_row5_col2, #T_b9c67_row5_col3, #T_b9c67_row5_col4, #T_b9c67_row5_col5, #T_b9c67_row5_col6, #T_b9c67_row5_col7, #T_b9c67_row5_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_b9c67">
  <thead>
    <tr>
      <th id="T_b9c67_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_b9c67_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_b9c67_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_b9c67_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_b9c67_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_b9c67_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_b9c67_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_b9c67_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_b9c67_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_b9c67_row0_col0" class="data row0 col0" >396</td>
      <td id="T_b9c67_row0_col1" class="data row0 col1" >Summer 2024</td>
      <td id="T_b9c67_row0_col2" class="data row0 col2" >ENGR396</td>
      <td id="T_b9c67_row0_col3" class="data row0 col3" >001</td>
      <td id="T_b9c67_row0_col4" class="data row0 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_b9c67_row0_col5" class="data row0 col5" >FLD</td>
      <td id="T_b9c67_row0_col6" class="data row0 col6" >66</td>
      <td id="T_b9c67_row0_col7" class="data row0 col7" >0</td>
      <td id="T_b9c67_row0_col8" class="data row0 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_b9c67_row1_col0" class="data row1 col0" >396</td>
      <td id="T_b9c67_row1_col1" class="data row1 col1" >Summer 2024</td>
      <td id="T_b9c67_row1_col2" class="data row1 col2" >ENGR396</td>
      <td id="T_b9c67_row1_col3" class="data row1 col3" >002</td>
      <td id="T_b9c67_row1_col4" class="data row1 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_b9c67_row1_col5" class="data row1 col5" >FLD</td>
      <td id="T_b9c67_row1_col6" class="data row1 col6" >17</td>
      <td id="T_b9c67_row1_col7" class="data row1 col7" >0</td>
      <td id="T_b9c67_row1_col8" class="data row1 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_b9c67_row2_col0" class="data row2 col0" >396</td>
      <td id="T_b9c67_row2_col1" class="data row2 col1" >Summer 2024</td>
      <td id="T_b9c67_row2_col2" class="data row2 col2" >ENGR396</td>
      <td id="T_b9c67_row2_col3" class="data row2 col3" >003</td>
      <td id="T_b9c67_row2_col4" class="data row2 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_b9c67_row2_col5" class="data row2 col5" >FLD</td>
      <td id="T_b9c67_row2_col6" class="data row2 col6" >7</td>
      <td id="T_b9c67_row2_col7" class="data row2 col7" >0</td>
      <td id="T_b9c67_row2_col8" class="data row2 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_b9c67_row3_col0" class="data row3 col0" >398</td>
      <td id="T_b9c67_row3_col1" class="data row3 col1" >Summer 2024</td>
      <td id="T_b9c67_row3_col2" class="data row3 col2" >ENGR398</td>
      <td id="T_b9c67_row3_col3" class="data row3 col3" >001</td>
      <td id="T_b9c67_row3_col4" class="data row3 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_b9c67_row3_col5" class="data row3 col5" >FLD</td>
      <td id="T_b9c67_row3_col6" class="data row3 col6" >5</td>
      <td id="T_b9c67_row3_col7" class="data row3 col7" >0</td>
      <td id="T_b9c67_row3_col8" class="data row3 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_b9c67_row4_col0" class="data row4 col0" >398</td>
      <td id="T_b9c67_row4_col1" class="data row4 col1" >Summer 2024</td>
      <td id="T_b9c67_row4_col2" class="data row4 col2" >ENGR398</td>
      <td id="T_b9c67_row4_col3" class="data row4 col3" >003</td>
      <td id="T_b9c67_row4_col4" class="data row4 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_b9c67_row4_col5" class="data row4 col5" >FLD</td>
      <td id="T_b9c67_row4_col6" class="data row4 col6" >1</td>
      <td id="T_b9c67_row4_col7" class="data row4 col7" >0</td>
      <td id="T_b9c67_row4_col8" class="data row4 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_b9c67_row5_col0" class="data row5 col0" >496</td>
      <td id="T_b9c67_row5_col1" class="data row5 col1" >Summer 2024</td>
      <td id="T_b9c67_row5_col2" class="data row5 col2" >ENGR496</td>
      <td id="T_b9c67_row5_col3" class="data row5 col3" >001</td>
      <td id="T_b9c67_row5_col4" class="data row5 col4" >INTERNSHIP REVIEW</td>
      <td id="T_b9c67_row5_col5" class="data row5 col5" >FLD</td>
      <td id="T_b9c67_row5_col6" class="data row5 col6" >10</td>
      <td id="T_b9c67_row5_col7" class="data row5 col7" >0</td>
      <td id="T_b9c67_row5_col8" class="data row5 col8" >Avasthi</td>
    </tr>
  </tbody>
</table>

:::

# AY22-23

This section list instructor activity for the academic year AY22-23 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## Fall 2022

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_74104 table {
  width: 100%;
  border-collapse: collapse;
}
#T_74104 th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_74104 th {
  border: 0;
}
#T_74104 thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_74104 tbody td:nth-child(1) {
  display: none;
}
#T_74104 thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_74104 tbody td:nth-child(2) {
  display: none;
}
#T_74104 thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_74104 tbody td:nth-child(8) {
  display: none;
}
#T_74104 td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_74104 td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_74104 td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_74104 td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_74104 td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_74104 td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_74104_row0_col0, #T_74104_row0_col1, #T_74104_row0_col2, #T_74104_row0_col3, #T_74104_row0_col4, #T_74104_row0_col5, #T_74104_row0_col6, #T_74104_row0_col7, #T_74104_row0_col8, #T_74104_row14_col0, #T_74104_row14_col1, #T_74104_row14_col2, #T_74104_row14_col3, #T_74104_row14_col4, #T_74104_row14_col5, #T_74104_row14_col6, #T_74104_row14_col7, #T_74104_row14_col8, #T_74104_row15_col0, #T_74104_row15_col1, #T_74104_row15_col2, #T_74104_row15_col3, #T_74104_row15_col4, #T_74104_row15_col5, #T_74104_row15_col6, #T_74104_row15_col7, #T_74104_row15_col8, #T_74104_row16_col0, #T_74104_row16_col1, #T_74104_row16_col2, #T_74104_row16_col3, #T_74104_row16_col4, #T_74104_row16_col5, #T_74104_row16_col6, #T_74104_row16_col7, #T_74104_row16_col8, #T_74104_row18_col0, #T_74104_row18_col1, #T_74104_row18_col2, #T_74104_row18_col3, #T_74104_row18_col4, #T_74104_row18_col5, #T_74104_row18_col6, #T_74104_row18_col7, #T_74104_row18_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_74104_row1_col0, #T_74104_row1_col1, #T_74104_row1_col2, #T_74104_row1_col3, #T_74104_row1_col4, #T_74104_row1_col5, #T_74104_row1_col6, #T_74104_row1_col7, #T_74104_row1_col8, #T_74104_row2_col0, #T_74104_row2_col1, #T_74104_row2_col2, #T_74104_row2_col3, #T_74104_row2_col4, #T_74104_row2_col5, #T_74104_row2_col6, #T_74104_row2_col7, #T_74104_row2_col8, #T_74104_row3_col0, #T_74104_row3_col1, #T_74104_row3_col2, #T_74104_row3_col3, #T_74104_row3_col4, #T_74104_row3_col5, #T_74104_row3_col6, #T_74104_row3_col7, #T_74104_row3_col8, #T_74104_row4_col0, #T_74104_row4_col1, #T_74104_row4_col2, #T_74104_row4_col3, #T_74104_row4_col4, #T_74104_row4_col5, #T_74104_row4_col6, #T_74104_row4_col7, #T_74104_row4_col8, #T_74104_row5_col0, #T_74104_row5_col1, #T_74104_row5_col2, #T_74104_row5_col3, #T_74104_row5_col4, #T_74104_row5_col5, #T_74104_row5_col6, #T_74104_row5_col7, #T_74104_row5_col8, #T_74104_row6_col0, #T_74104_row6_col1, #T_74104_row6_col2, #T_74104_row6_col3, #T_74104_row6_col4, #T_74104_row6_col5, #T_74104_row6_col6, #T_74104_row6_col7, #T_74104_row6_col8, #T_74104_row7_col0, #T_74104_row7_col1, #T_74104_row7_col2, #T_74104_row7_col3, #T_74104_row7_col4, #T_74104_row7_col5, #T_74104_row7_col6, #T_74104_row7_col7, #T_74104_row7_col8, #T_74104_row8_col0, #T_74104_row8_col1, #T_74104_row8_col2, #T_74104_row8_col3, #T_74104_row8_col4, #T_74104_row8_col5, #T_74104_row8_col6, #T_74104_row8_col7, #T_74104_row8_col8, #T_74104_row9_col0, #T_74104_row9_col1, #T_74104_row9_col2, #T_74104_row9_col3, #T_74104_row9_col4, #T_74104_row9_col5, #T_74104_row9_col6, #T_74104_row9_col7, #T_74104_row9_col8, #T_74104_row10_col0, #T_74104_row10_col1, #T_74104_row10_col2, #T_74104_row10_col3, #T_74104_row10_col4, #T_74104_row10_col5, #T_74104_row10_col6, #T_74104_row10_col7, #T_74104_row10_col8, #T_74104_row11_col0, #T_74104_row11_col1, #T_74104_row11_col2, #T_74104_row11_col3, #T_74104_row11_col4, #T_74104_row11_col5, #T_74104_row11_col6, #T_74104_row11_col7, #T_74104_row11_col8, #T_74104_row12_col0, #T_74104_row12_col1, #T_74104_row12_col2, #T_74104_row12_col3, #T_74104_row12_col4, #T_74104_row12_col5, #T_74104_row12_col6, #T_74104_row12_col7, #T_74104_row12_col8, #T_74104_row13_col0, #T_74104_row13_col1, #T_74104_row13_col2, #T_74104_row13_col3, #T_74104_row13_col4, #T_74104_row13_col5, #T_74104_row13_col6, #T_74104_row13_col7, #T_74104_row13_col8, #T_74104_row17_col0, #T_74104_row17_col1, #T_74104_row17_col2, #T_74104_row17_col3, #T_74104_row17_col4, #T_74104_row17_col5, #T_74104_row17_col6, #T_74104_row17_col7, #T_74104_row17_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_74104">
  <thead>
    <tr>
      <th id="T_74104_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_74104_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_74104_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_74104_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_74104_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_74104_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_74104_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_74104_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_74104_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_74104_row0_col0" class="data row0 col0" >100</td>
      <td id="T_74104_row0_col1" class="data row0 col1" >Fall 2022</td>
      <td id="T_74104_row0_col2" class="data row0 col2" >ENGR100</td>
      <td id="T_74104_row0_col3" class="data row0 col3" >901</td>
      <td id="T_74104_row0_col4" class="data row0 col4" >ENGINEERING STUDENT SUCCESS</td>
      <td id="T_74104_row0_col5" class="data row0 col5" >SEM</td>
      <td id="T_74104_row0_col6" class="data row0 col6" >45</td>
      <td id="T_74104_row0_col7" class="data row0 col7" >0</td>
      <td id="T_74104_row0_col8" class="data row0 col8" >Rivers</td>
    </tr>
    <tr>
      <td id="T_74104_row1_col0" class="data row1 col0" >395</td>
      <td id="T_74104_row1_col1" class="data row1 col1" >Fall 2022</td>
      <td id="T_74104_row1_col2" class="data row1 col2" >ENGR395</td>
      <td id="T_74104_row1_col3" class="data row1 col3" >001</td>
      <td id="T_74104_row1_col4" class="data row1 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_74104_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_74104_row1_col6" class="data row1 col6" >18</td>
      <td id="T_74104_row1_col7" class="data row1 col7" >18</td>
      <td id="T_74104_row1_col8" class="data row1 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_74104_row2_col0" class="data row2 col0" >395</td>
      <td id="T_74104_row2_col1" class="data row2 col1" >Fall 2022</td>
      <td id="T_74104_row2_col2" class="data row2 col2" >ENGR395</td>
      <td id="T_74104_row2_col3" class="data row2 col3" >001</td>
      <td id="T_74104_row2_col4" class="data row2 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_74104_row2_col5" class="data row2 col5" >LEC</td>
      <td id="T_74104_row2_col6" class="data row2 col6" >18</td>
      <td id="T_74104_row2_col7" class="data row2 col7" >18</td>
      <td id="T_74104_row2_col8" class="data row2 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_74104_row3_col0" class="data row3 col0" >395</td>
      <td id="T_74104_row3_col1" class="data row3 col1" >Fall 2022</td>
      <td id="T_74104_row3_col2" class="data row3 col2" >ENGR395</td>
      <td id="T_74104_row3_col3" class="data row3 col3" >002</td>
      <td id="T_74104_row3_col4" class="data row3 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_74104_row3_col5" class="data row3 col5" >LEC</td>
      <td id="T_74104_row3_col6" class="data row3 col6" >25</td>
      <td id="T_74104_row3_col7" class="data row3 col7" >25</td>
      <td id="T_74104_row3_col8" class="data row3 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_74104_row4_col0" class="data row4 col0" >395</td>
      <td id="T_74104_row4_col1" class="data row4 col1" >Fall 2022</td>
      <td id="T_74104_row4_col2" class="data row4 col2" >ENGR395</td>
      <td id="T_74104_row4_col3" class="data row4 col3" >003</td>
      <td id="T_74104_row4_col4" class="data row4 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_74104_row4_col5" class="data row4 col5" >LEC</td>
      <td id="T_74104_row4_col6" class="data row4 col6" >18</td>
      <td id="T_74104_row4_col7" class="data row4 col7" >18</td>
      <td id="T_74104_row4_col8" class="data row4 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_74104_row5_col0" class="data row5 col0" >395</td>
      <td id="T_74104_row5_col1" class="data row5 col1" >Fall 2022</td>
      <td id="T_74104_row5_col2" class="data row5 col2" >ENGR395</td>
      <td id="T_74104_row5_col3" class="data row5 col3" >003</td>
      <td id="T_74104_row5_col4" class="data row5 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_74104_row5_col5" class="data row5 col5" >LEC</td>
      <td id="T_74104_row5_col6" class="data row5 col6" >18</td>
      <td id="T_74104_row5_col7" class="data row5 col7" >18</td>
      <td id="T_74104_row5_col8" class="data row5 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_74104_row6_col0" class="data row6 col0" >395</td>
      <td id="T_74104_row6_col1" class="data row6 col1" >Fall 2022</td>
      <td id="T_74104_row6_col2" class="data row6 col2" >ENGR395</td>
      <td id="T_74104_row6_col3" class="data row6 col3" >004</td>
      <td id="T_74104_row6_col4" class="data row6 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_74104_row6_col5" class="data row6 col5" >LEC</td>
      <td id="T_74104_row6_col6" class="data row6 col6" >12</td>
      <td id="T_74104_row6_col7" class="data row6 col7" >12</td>
      <td id="T_74104_row6_col8" class="data row6 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_74104_row7_col0" class="data row7 col0" >395</td>
      <td id="T_74104_row7_col1" class="data row7 col1" >Fall 2022</td>
      <td id="T_74104_row7_col2" class="data row7 col2" >ENGR395</td>
      <td id="T_74104_row7_col3" class="data row7 col3" >004</td>
      <td id="T_74104_row7_col4" class="data row7 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_74104_row7_col5" class="data row7 col5" >LEC</td>
      <td id="T_74104_row7_col6" class="data row7 col6" >12</td>
      <td id="T_74104_row7_col7" class="data row7 col7" >12</td>
      <td id="T_74104_row7_col8" class="data row7 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_74104_row8_col0" class="data row8 col0" >395</td>
      <td id="T_74104_row8_col1" class="data row8 col1" >Fall 2022</td>
      <td id="T_74104_row8_col2" class="data row8 col2" >ENGR395</td>
      <td id="T_74104_row8_col3" class="data row8 col3" >005</td>
      <td id="T_74104_row8_col4" class="data row8 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_74104_row8_col5" class="data row8 col5" >LEC</td>
      <td id="T_74104_row8_col6" class="data row8 col6" >18</td>
      <td id="T_74104_row8_col7" class="data row8 col7" >18</td>
      <td id="T_74104_row8_col8" class="data row8 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_74104_row9_col0" class="data row9 col0" >395</td>
      <td id="T_74104_row9_col1" class="data row9 col1" >Fall 2022</td>
      <td id="T_74104_row9_col2" class="data row9 col2" >ENGR395</td>
      <td id="T_74104_row9_col3" class="data row9 col3" >005</td>
      <td id="T_74104_row9_col4" class="data row9 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_74104_row9_col5" class="data row9 col5" >LEC</td>
      <td id="T_74104_row9_col6" class="data row9 col6" >18</td>
      <td id="T_74104_row9_col7" class="data row9 col7" >18</td>
      <td id="T_74104_row9_col8" class="data row9 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_74104_row10_col0" class="data row10 col0" >395</td>
      <td id="T_74104_row10_col1" class="data row10 col1" >Fall 2022</td>
      <td id="T_74104_row10_col2" class="data row10 col2" >ENGR395</td>
      <td id="T_74104_row10_col3" class="data row10 col3" >006</td>
      <td id="T_74104_row10_col4" class="data row10 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_74104_row10_col5" class="data row10 col5" >LEC</td>
      <td id="T_74104_row10_col6" class="data row10 col6" >27</td>
      <td id="T_74104_row10_col7" class="data row10 col7" >27</td>
      <td id="T_74104_row10_col8" class="data row10 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_74104_row11_col0" class="data row11 col0" >396</td>
      <td id="T_74104_row11_col1" class="data row11 col1" >Fall 2022</td>
      <td id="T_74104_row11_col2" class="data row11 col2" >ENGR396</td>
      <td id="T_74104_row11_col3" class="data row11 col3" >001</td>
      <td id="T_74104_row11_col4" class="data row11 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_74104_row11_col5" class="data row11 col5" >FLD</td>
      <td id="T_74104_row11_col6" class="data row11 col6" >10</td>
      <td id="T_74104_row11_col7" class="data row11 col7" >0</td>
      <td id="T_74104_row11_col8" class="data row11 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_74104_row12_col0" class="data row12 col0" >396</td>
      <td id="T_74104_row12_col1" class="data row12 col1" >Fall 2022</td>
      <td id="T_74104_row12_col2" class="data row12 col2" >ENGR396</td>
      <td id="T_74104_row12_col3" class="data row12 col3" >001</td>
      <td id="T_74104_row12_col4" class="data row12 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_74104_row12_col5" class="data row12 col5" >FLD</td>
      <td id="T_74104_row12_col6" class="data row12 col6" >10</td>
      <td id="T_74104_row12_col7" class="data row12 col7" >0</td>
      <td id="T_74104_row12_col8" class="data row12 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_74104_row13_col0" class="data row13 col0" >398</td>
      <td id="T_74104_row13_col1" class="data row13 col1" >Fall 2022</td>
      <td id="T_74104_row13_col2" class="data row13 col2" >ENGR398</td>
      <td id="T_74104_row13_col3" class="data row13 col3" >001</td>
      <td id="T_74104_row13_col4" class="data row13 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_74104_row13_col5" class="data row13 col5" >FLD</td>
      <td id="T_74104_row13_col6" class="data row13 col6" >6</td>
      <td id="T_74104_row13_col7" class="data row13 col7" >0</td>
      <td id="T_74104_row13_col8" class="data row13 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_74104_row14_col0" class="data row14 col0" >496</td>
      <td id="T_74104_row14_col1" class="data row14 col1" >Fall 2022</td>
      <td id="T_74104_row14_col2" class="data row14 col2" >ENGR496</td>
      <td id="T_74104_row14_col3" class="data row14 col3" >001</td>
      <td id="T_74104_row14_col4" class="data row14 col4" >INTERNSHIP REVIEW</td>
      <td id="T_74104_row14_col5" class="data row14 col5" >FLD</td>
      <td id="T_74104_row14_col6" class="data row14 col6" >59</td>
      <td id="T_74104_row14_col7" class="data row14 col7" >0</td>
      <td id="T_74104_row14_col8" class="data row14 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_74104_row15_col0" class="data row15 col0" >496</td>
      <td id="T_74104_row15_col1" class="data row15 col1" >Fall 2022</td>
      <td id="T_74104_row15_col2" class="data row15 col2" >ENGR496</td>
      <td id="T_74104_row15_col3" class="data row15 col3" >001</td>
      <td id="T_74104_row15_col4" class="data row15 col4" >INTERNSHIP REVIEW</td>
      <td id="T_74104_row15_col5" class="data row15 col5" >FLD</td>
      <td id="T_74104_row15_col6" class="data row15 col6" >59</td>
      <td id="T_74104_row15_col7" class="data row15 col7" >0</td>
      <td id="T_74104_row15_col8" class="data row15 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_74104_row16_col0" class="data row16 col0" >498</td>
      <td id="T_74104_row16_col1" class="data row16 col1" >Fall 2022</td>
      <td id="T_74104_row16_col2" class="data row16 col2" >ENGR498</td>
      <td id="T_74104_row16_col3" class="data row16 col3" >001</td>
      <td id="T_74104_row16_col4" class="data row16 col4" >REVIEW OF COOP EDUCATION EXP</td>
      <td id="T_74104_row16_col5" class="data row16 col5" >FLD</td>
      <td id="T_74104_row16_col6" class="data row16 col6" >2</td>
      <td id="T_74104_row16_col7" class="data row16 col7" >0</td>
      <td id="T_74104_row16_col8" class="data row16 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_74104_row17_col0" class="data row17 col0" >591</td>
      <td id="T_74104_row17_col1" class="data row17 col1" >Fall 2022</td>
      <td id="T_74104_row17_col2" class="data row17 col2" >ENGR591</td>
      <td id="T_74104_row17_col3" class="data row17 col3" >002</td>
      <td id="T_74104_row17_col4" class="data row17 col4" >TOP:COMPUTATIONAL FLUID DYNAMI</td>
      <td id="T_74104_row17_col5" class="data row17 col5" >LEC</td>
      <td id="T_74104_row17_col6" class="data row17 col6" >8</td>
      <td id="T_74104_row17_col7" class="data row17 col7" >24</td>
      <td id="T_74104_row17_col8" class="data row17 col8" >Roper</td>
    </tr>
    <tr>
      <td id="T_74104_row18_col0" class="data row18 col0" >691</td>
      <td id="T_74104_row18_col1" class="data row18 col1" >Fall 2022</td>
      <td id="T_74104_row18_col2" class="data row18 col2" >ENGR691</td>
      <td id="T_74104_row18_col3" class="data row18 col3" >008</td>
      <td id="T_74104_row18_col4" class="data row18 col4" >SPTP:RESEARCH ETHICS& PROF DEV</td>
      <td id="T_74104_row18_col5" class="data row18 col5" >LEC</td>
      <td id="T_74104_row18_col6" class="data row18 col6" >3</td>
      <td id="T_74104_row18_col7" class="data row18 col7" >6</td>
      <td id="T_74104_row18_col8" class="data row18 col8" >Avasthi</td>
    </tr>
  </tbody>
</table>

:::

## Spring 2023

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_a3eb3 table {
  width: 100%;
  border-collapse: collapse;
}
#T_a3eb3 th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_a3eb3 th {
  border: 0;
}
#T_a3eb3 thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_a3eb3 tbody td:nth-child(1) {
  display: none;
}
#T_a3eb3 thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_a3eb3 tbody td:nth-child(2) {
  display: none;
}
#T_a3eb3 thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_a3eb3 tbody td:nth-child(8) {
  display: none;
}
#T_a3eb3 td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_a3eb3 td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_a3eb3 td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_a3eb3 td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_a3eb3 td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_a3eb3 td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_a3eb3_row0_col0, #T_a3eb3_row0_col1, #T_a3eb3_row0_col2, #T_a3eb3_row0_col3, #T_a3eb3_row0_col4, #T_a3eb3_row0_col5, #T_a3eb3_row0_col6, #T_a3eb3_row0_col7, #T_a3eb3_row0_col8, #T_a3eb3_row1_col0, #T_a3eb3_row1_col1, #T_a3eb3_row1_col2, #T_a3eb3_row1_col3, #T_a3eb3_row1_col4, #T_a3eb3_row1_col5, #T_a3eb3_row1_col6, #T_a3eb3_row1_col7, #T_a3eb3_row1_col8, #T_a3eb3_row2_col0, #T_a3eb3_row2_col1, #T_a3eb3_row2_col2, #T_a3eb3_row2_col3, #T_a3eb3_row2_col4, #T_a3eb3_row2_col5, #T_a3eb3_row2_col6, #T_a3eb3_row2_col7, #T_a3eb3_row2_col8, #T_a3eb3_row3_col0, #T_a3eb3_row3_col1, #T_a3eb3_row3_col2, #T_a3eb3_row3_col3, #T_a3eb3_row3_col4, #T_a3eb3_row3_col5, #T_a3eb3_row3_col6, #T_a3eb3_row3_col7, #T_a3eb3_row3_col8, #T_a3eb3_row4_col0, #T_a3eb3_row4_col1, #T_a3eb3_row4_col2, #T_a3eb3_row4_col3, #T_a3eb3_row4_col4, #T_a3eb3_row4_col5, #T_a3eb3_row4_col6, #T_a3eb3_row4_col7, #T_a3eb3_row4_col8, #T_a3eb3_row5_col0, #T_a3eb3_row5_col1, #T_a3eb3_row5_col2, #T_a3eb3_row5_col3, #T_a3eb3_row5_col4, #T_a3eb3_row5_col5, #T_a3eb3_row5_col6, #T_a3eb3_row5_col7, #T_a3eb3_row5_col8, #T_a3eb3_row6_col0, #T_a3eb3_row6_col1, #T_a3eb3_row6_col2, #T_a3eb3_row6_col3, #T_a3eb3_row6_col4, #T_a3eb3_row6_col5, #T_a3eb3_row6_col6, #T_a3eb3_row6_col7, #T_a3eb3_row6_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_a3eb3_row7_col0, #T_a3eb3_row7_col1, #T_a3eb3_row7_col2, #T_a3eb3_row7_col3, #T_a3eb3_row7_col4, #T_a3eb3_row7_col5, #T_a3eb3_row7_col6, #T_a3eb3_row7_col7, #T_a3eb3_row7_col8, #T_a3eb3_row8_col0, #T_a3eb3_row8_col1, #T_a3eb3_row8_col2, #T_a3eb3_row8_col3, #T_a3eb3_row8_col4, #T_a3eb3_row8_col5, #T_a3eb3_row8_col6, #T_a3eb3_row8_col7, #T_a3eb3_row8_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_a3eb3">
  <thead>
    <tr>
      <th id="T_a3eb3_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_a3eb3_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_a3eb3_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_a3eb3_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_a3eb3_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_a3eb3_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_a3eb3_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_a3eb3_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_a3eb3_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_a3eb3_row0_col0" class="data row0 col0" >395</td>
      <td id="T_a3eb3_row0_col1" class="data row0 col1" >Spring 2023</td>
      <td id="T_a3eb3_row0_col2" class="data row0 col2" >ENGR395</td>
      <td id="T_a3eb3_row0_col3" class="data row0 col3" >001</td>
      <td id="T_a3eb3_row0_col4" class="data row0 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_a3eb3_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_a3eb3_row0_col6" class="data row0 col6" >33</td>
      <td id="T_a3eb3_row0_col7" class="data row0 col7" >33</td>
      <td id="T_a3eb3_row0_col8" class="data row0 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_a3eb3_row1_col0" class="data row1 col0" >395</td>
      <td id="T_a3eb3_row1_col1" class="data row1 col1" >Spring 2023</td>
      <td id="T_a3eb3_row1_col2" class="data row1 col2" >ENGR395</td>
      <td id="T_a3eb3_row1_col3" class="data row1 col3" >002</td>
      <td id="T_a3eb3_row1_col4" class="data row1 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_a3eb3_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_a3eb3_row1_col6" class="data row1 col6" >40</td>
      <td id="T_a3eb3_row1_col7" class="data row1 col7" >40</td>
      <td id="T_a3eb3_row1_col8" class="data row1 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_a3eb3_row2_col0" class="data row2 col0" >395</td>
      <td id="T_a3eb3_row2_col1" class="data row2 col1" >Spring 2023</td>
      <td id="T_a3eb3_row2_col2" class="data row2 col2" >ENGR395</td>
      <td id="T_a3eb3_row2_col3" class="data row2 col3" >003</td>
      <td id="T_a3eb3_row2_col4" class="data row2 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_a3eb3_row2_col5" class="data row2 col5" >LEC</td>
      <td id="T_a3eb3_row2_col6" class="data row2 col6" >26</td>
      <td id="T_a3eb3_row2_col7" class="data row2 col7" >26</td>
      <td id="T_a3eb3_row2_col8" class="data row2 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_a3eb3_row3_col0" class="data row3 col0" >395</td>
      <td id="T_a3eb3_row3_col1" class="data row3 col1" >Spring 2023</td>
      <td id="T_a3eb3_row3_col2" class="data row3 col2" >ENGR395</td>
      <td id="T_a3eb3_row3_col3" class="data row3 col3" >004</td>
      <td id="T_a3eb3_row3_col4" class="data row3 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_a3eb3_row3_col5" class="data row3 col5" >LEC</td>
      <td id="T_a3eb3_row3_col6" class="data row3 col6" >40</td>
      <td id="T_a3eb3_row3_col7" class="data row3 col7" >40</td>
      <td id="T_a3eb3_row3_col8" class="data row3 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_a3eb3_row4_col0" class="data row4 col0" >395</td>
      <td id="T_a3eb3_row4_col1" class="data row4 col1" >Spring 2023</td>
      <td id="T_a3eb3_row4_col2" class="data row4 col2" >ENGR395</td>
      <td id="T_a3eb3_row4_col3" class="data row4 col3" >005</td>
      <td id="T_a3eb3_row4_col4" class="data row4 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_a3eb3_row4_col5" class="data row4 col5" >LEC</td>
      <td id="T_a3eb3_row4_col6" class="data row4 col6" >45</td>
      <td id="T_a3eb3_row4_col7" class="data row4 col7" >45</td>
      <td id="T_a3eb3_row4_col8" class="data row4 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_a3eb3_row5_col0" class="data row5 col0" >396</td>
      <td id="T_a3eb3_row5_col1" class="data row5 col1" >Spring 2023</td>
      <td id="T_a3eb3_row5_col2" class="data row5 col2" >ENGR396</td>
      <td id="T_a3eb3_row5_col3" class="data row5 col3" >001</td>
      <td id="T_a3eb3_row5_col4" class="data row5 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_a3eb3_row5_col5" class="data row5 col5" >FLD</td>
      <td id="T_a3eb3_row5_col6" class="data row5 col6" >20</td>
      <td id="T_a3eb3_row5_col7" class="data row5 col7" >0</td>
      <td id="T_a3eb3_row5_col8" class="data row5 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_a3eb3_row6_col0" class="data row6 col0" >398</td>
      <td id="T_a3eb3_row6_col1" class="data row6 col1" >Spring 2023</td>
      <td id="T_a3eb3_row6_col2" class="data row6 col2" >ENGR398</td>
      <td id="T_a3eb3_row6_col3" class="data row6 col3" >001</td>
      <td id="T_a3eb3_row6_col4" class="data row6 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_a3eb3_row6_col5" class="data row6 col5" >FLD</td>
      <td id="T_a3eb3_row6_col6" class="data row6 col6" >10</td>
      <td id="T_a3eb3_row6_col7" class="data row6 col7" >0</td>
      <td id="T_a3eb3_row6_col8" class="data row6 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_a3eb3_row7_col0" class="data row7 col0" >496</td>
      <td id="T_a3eb3_row7_col1" class="data row7 col1" >Spring 2023</td>
      <td id="T_a3eb3_row7_col2" class="data row7 col2" >ENGR496</td>
      <td id="T_a3eb3_row7_col3" class="data row7 col3" >001</td>
      <td id="T_a3eb3_row7_col4" class="data row7 col4" >INTERNSHIP REVIEW</td>
      <td id="T_a3eb3_row7_col5" class="data row7 col5" >FLD</td>
      <td id="T_a3eb3_row7_col6" class="data row7 col6" >30</td>
      <td id="T_a3eb3_row7_col7" class="data row7 col7" >0</td>
      <td id="T_a3eb3_row7_col8" class="data row7 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_a3eb3_row8_col0" class="data row8 col0" >498</td>
      <td id="T_a3eb3_row8_col1" class="data row8 col1" >Spring 2023</td>
      <td id="T_a3eb3_row8_col2" class="data row8 col2" >ENGR498</td>
      <td id="T_a3eb3_row8_col3" class="data row8 col3" >001</td>
      <td id="T_a3eb3_row8_col4" class="data row8 col4" >REVIEW OF COOP EDUCATION EXP</td>
      <td id="T_a3eb3_row8_col5" class="data row8 col5" >FLD</td>
      <td id="T_a3eb3_row8_col6" class="data row8 col6" >2</td>
      <td id="T_a3eb3_row8_col7" class="data row8 col7" >0</td>
      <td id="T_a3eb3_row8_col8" class="data row8 col8" >Avasthi</td>
    </tr>
  </tbody>
</table>

:::

## Summer 2023

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_e8d4d table {
  width: 100%;
  border-collapse: collapse;
}
#T_e8d4d th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_e8d4d th {
  border: 0;
}
#T_e8d4d thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_e8d4d tbody td:nth-child(1) {
  display: none;
}
#T_e8d4d thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_e8d4d tbody td:nth-child(2) {
  display: none;
}
#T_e8d4d thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_e8d4d tbody td:nth-child(8) {
  display: none;
}
#T_e8d4d td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_e8d4d td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_e8d4d td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_e8d4d td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_e8d4d td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_e8d4d td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_e8d4d_row0_col0, #T_e8d4d_row0_col1, #T_e8d4d_row0_col2, #T_e8d4d_row0_col3, #T_e8d4d_row0_col4, #T_e8d4d_row0_col5, #T_e8d4d_row0_col6, #T_e8d4d_row0_col7, #T_e8d4d_row0_col8, #T_e8d4d_row1_col0, #T_e8d4d_row1_col1, #T_e8d4d_row1_col2, #T_e8d4d_row1_col3, #T_e8d4d_row1_col4, #T_e8d4d_row1_col5, #T_e8d4d_row1_col6, #T_e8d4d_row1_col7, #T_e8d4d_row1_col8, #T_e8d4d_row2_col0, #T_e8d4d_row2_col1, #T_e8d4d_row2_col2, #T_e8d4d_row2_col3, #T_e8d4d_row2_col4, #T_e8d4d_row2_col5, #T_e8d4d_row2_col6, #T_e8d4d_row2_col7, #T_e8d4d_row2_col8, #T_e8d4d_row3_col0, #T_e8d4d_row3_col1, #T_e8d4d_row3_col2, #T_e8d4d_row3_col3, #T_e8d4d_row3_col4, #T_e8d4d_row3_col5, #T_e8d4d_row3_col6, #T_e8d4d_row3_col7, #T_e8d4d_row3_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_e8d4d_row4_col0, #T_e8d4d_row4_col1, #T_e8d4d_row4_col2, #T_e8d4d_row4_col3, #T_e8d4d_row4_col4, #T_e8d4d_row4_col5, #T_e8d4d_row4_col6, #T_e8d4d_row4_col7, #T_e8d4d_row4_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_e8d4d">
  <thead>
    <tr>
      <th id="T_e8d4d_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_e8d4d_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_e8d4d_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_e8d4d_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_e8d4d_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_e8d4d_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_e8d4d_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_e8d4d_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_e8d4d_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_e8d4d_row0_col0" class="data row0 col0" >395</td>
      <td id="T_e8d4d_row0_col1" class="data row0 col1" >Summer 2023</td>
      <td id="T_e8d4d_row0_col2" class="data row0 col2" >ENGR395</td>
      <td id="T_e8d4d_row0_col3" class="data row0 col3" >001</td>
      <td id="T_e8d4d_row0_col4" class="data row0 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_e8d4d_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_e8d4d_row0_col6" class="data row0 col6" >23</td>
      <td id="T_e8d4d_row0_col7" class="data row0 col7" >23</td>
      <td id="T_e8d4d_row0_col8" class="data row0 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_e8d4d_row1_col0" class="data row1 col0" >396</td>
      <td id="T_e8d4d_row1_col1" class="data row1 col1" >Summer 2023</td>
      <td id="T_e8d4d_row1_col2" class="data row1 col2" >ENGR396</td>
      <td id="T_e8d4d_row1_col3" class="data row1 col3" >001</td>
      <td id="T_e8d4d_row1_col4" class="data row1 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_e8d4d_row1_col5" class="data row1 col5" >FLD</td>
      <td id="T_e8d4d_row1_col6" class="data row1 col6" >86</td>
      <td id="T_e8d4d_row1_col7" class="data row1 col7" >0</td>
      <td id="T_e8d4d_row1_col8" class="data row1 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_e8d4d_row2_col0" class="data row2 col0" >396</td>
      <td id="T_e8d4d_row2_col1" class="data row2 col1" >Summer 2023</td>
      <td id="T_e8d4d_row2_col2" class="data row2 col2" >ENGR396</td>
      <td id="T_e8d4d_row2_col3" class="data row2 col3" >002</td>
      <td id="T_e8d4d_row2_col4" class="data row2 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_e8d4d_row2_col5" class="data row2 col5" >FLD</td>
      <td id="T_e8d4d_row2_col6" class="data row2 col6" >12</td>
      <td id="T_e8d4d_row2_col7" class="data row2 col7" >0</td>
      <td id="T_e8d4d_row2_col8" class="data row2 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_e8d4d_row3_col0" class="data row3 col0" >398</td>
      <td id="T_e8d4d_row3_col1" class="data row3 col1" >Summer 2023</td>
      <td id="T_e8d4d_row3_col2" class="data row3 col2" >ENGR398</td>
      <td id="T_e8d4d_row3_col3" class="data row3 col3" >001</td>
      <td id="T_e8d4d_row3_col4" class="data row3 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_e8d4d_row3_col5" class="data row3 col5" >FLD</td>
      <td id="T_e8d4d_row3_col6" class="data row3 col6" >6</td>
      <td id="T_e8d4d_row3_col7" class="data row3 col7" >0</td>
      <td id="T_e8d4d_row3_col8" class="data row3 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_e8d4d_row4_col0" class="data row4 col0" >496</td>
      <td id="T_e8d4d_row4_col1" class="data row4 col1" >Summer 2023</td>
      <td id="T_e8d4d_row4_col2" class="data row4 col2" >ENGR496</td>
      <td id="T_e8d4d_row4_col3" class="data row4 col3" >001</td>
      <td id="T_e8d4d_row4_col4" class="data row4 col4" >INTERNSHIP REVIEW</td>
      <td id="T_e8d4d_row4_col5" class="data row4 col5" >FLD</td>
      <td id="T_e8d4d_row4_col6" class="data row4 col6" >8</td>
      <td id="T_e8d4d_row4_col7" class="data row4 col7" >0</td>
      <td id="T_e8d4d_row4_col8" class="data row4 col8" >Avasthi</td>
    </tr>
  </tbody>
</table>

:::

# AY21-22

This section list instructor activity for the academic year AY21-22 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## Fall 2021

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_c904e table {
  width: 100%;
  border-collapse: collapse;
}
#T_c904e th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_c904e th {
  border: 0;
}
#T_c904e thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_c904e tbody td:nth-child(1) {
  display: none;
}
#T_c904e thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_c904e tbody td:nth-child(2) {
  display: none;
}
#T_c904e thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_c904e tbody td:nth-child(8) {
  display: none;
}
#T_c904e td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_c904e td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_c904e td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_c904e td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_c904e td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_c904e td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_c904e_row0_col0, #T_c904e_row0_col1, #T_c904e_row0_col2, #T_c904e_row0_col3, #T_c904e_row0_col4, #T_c904e_row0_col5, #T_c904e_row0_col6, #T_c904e_row0_col7, #T_c904e_row0_col8, #T_c904e_row1_col0, #T_c904e_row1_col1, #T_c904e_row1_col2, #T_c904e_row1_col3, #T_c904e_row1_col4, #T_c904e_row1_col5, #T_c904e_row1_col6, #T_c904e_row1_col7, #T_c904e_row1_col8, #T_c904e_row17_col0, #T_c904e_row17_col1, #T_c904e_row17_col2, #T_c904e_row17_col3, #T_c904e_row17_col4, #T_c904e_row17_col5, #T_c904e_row17_col6, #T_c904e_row17_col7, #T_c904e_row17_col8, #T_c904e_row18_col0, #T_c904e_row18_col1, #T_c904e_row18_col2, #T_c904e_row18_col3, #T_c904e_row18_col4, #T_c904e_row18_col5, #T_c904e_row18_col6, #T_c904e_row18_col7, #T_c904e_row18_col8, #T_c904e_row19_col0, #T_c904e_row19_col1, #T_c904e_row19_col2, #T_c904e_row19_col3, #T_c904e_row19_col4, #T_c904e_row19_col5, #T_c904e_row19_col6, #T_c904e_row19_col7, #T_c904e_row19_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_c904e_row2_col0, #T_c904e_row2_col1, #T_c904e_row2_col2, #T_c904e_row2_col3, #T_c904e_row2_col4, #T_c904e_row2_col5, #T_c904e_row2_col6, #T_c904e_row2_col7, #T_c904e_row2_col8, #T_c904e_row3_col0, #T_c904e_row3_col1, #T_c904e_row3_col2, #T_c904e_row3_col3, #T_c904e_row3_col4, #T_c904e_row3_col5, #T_c904e_row3_col6, #T_c904e_row3_col7, #T_c904e_row3_col8, #T_c904e_row4_col0, #T_c904e_row4_col1, #T_c904e_row4_col2, #T_c904e_row4_col3, #T_c904e_row4_col4, #T_c904e_row4_col5, #T_c904e_row4_col6, #T_c904e_row4_col7, #T_c904e_row4_col8, #T_c904e_row5_col0, #T_c904e_row5_col1, #T_c904e_row5_col2, #T_c904e_row5_col3, #T_c904e_row5_col4, #T_c904e_row5_col5, #T_c904e_row5_col6, #T_c904e_row5_col7, #T_c904e_row5_col8, #T_c904e_row6_col0, #T_c904e_row6_col1, #T_c904e_row6_col2, #T_c904e_row6_col3, #T_c904e_row6_col4, #T_c904e_row6_col5, #T_c904e_row6_col6, #T_c904e_row6_col7, #T_c904e_row6_col8, #T_c904e_row7_col0, #T_c904e_row7_col1, #T_c904e_row7_col2, #T_c904e_row7_col3, #T_c904e_row7_col4, #T_c904e_row7_col5, #T_c904e_row7_col6, #T_c904e_row7_col7, #T_c904e_row7_col8, #T_c904e_row8_col0, #T_c904e_row8_col1, #T_c904e_row8_col2, #T_c904e_row8_col3, #T_c904e_row8_col4, #T_c904e_row8_col5, #T_c904e_row8_col6, #T_c904e_row8_col7, #T_c904e_row8_col8, #T_c904e_row9_col0, #T_c904e_row9_col1, #T_c904e_row9_col2, #T_c904e_row9_col3, #T_c904e_row9_col4, #T_c904e_row9_col5, #T_c904e_row9_col6, #T_c904e_row9_col7, #T_c904e_row9_col8, #T_c904e_row10_col0, #T_c904e_row10_col1, #T_c904e_row10_col2, #T_c904e_row10_col3, #T_c904e_row10_col4, #T_c904e_row10_col5, #T_c904e_row10_col6, #T_c904e_row10_col7, #T_c904e_row10_col8, #T_c904e_row11_col0, #T_c904e_row11_col1, #T_c904e_row11_col2, #T_c904e_row11_col3, #T_c904e_row11_col4, #T_c904e_row11_col5, #T_c904e_row11_col6, #T_c904e_row11_col7, #T_c904e_row11_col8, #T_c904e_row12_col0, #T_c904e_row12_col1, #T_c904e_row12_col2, #T_c904e_row12_col3, #T_c904e_row12_col4, #T_c904e_row12_col5, #T_c904e_row12_col6, #T_c904e_row12_col7, #T_c904e_row12_col8, #T_c904e_row13_col0, #T_c904e_row13_col1, #T_c904e_row13_col2, #T_c904e_row13_col3, #T_c904e_row13_col4, #T_c904e_row13_col5, #T_c904e_row13_col6, #T_c904e_row13_col7, #T_c904e_row13_col8, #T_c904e_row14_col0, #T_c904e_row14_col1, #T_c904e_row14_col2, #T_c904e_row14_col3, #T_c904e_row14_col4, #T_c904e_row14_col5, #T_c904e_row14_col6, #T_c904e_row14_col7, #T_c904e_row14_col8, #T_c904e_row15_col0, #T_c904e_row15_col1, #T_c904e_row15_col2, #T_c904e_row15_col3, #T_c904e_row15_col4, #T_c904e_row15_col5, #T_c904e_row15_col6, #T_c904e_row15_col7, #T_c904e_row15_col8, #T_c904e_row16_col0, #T_c904e_row16_col1, #T_c904e_row16_col2, #T_c904e_row16_col3, #T_c904e_row16_col4, #T_c904e_row16_col5, #T_c904e_row16_col6, #T_c904e_row16_col7, #T_c904e_row16_col8, #T_c904e_row20_col0, #T_c904e_row20_col1, #T_c904e_row20_col2, #T_c904e_row20_col3, #T_c904e_row20_col4, #T_c904e_row20_col5, #T_c904e_row20_col6, #T_c904e_row20_col7, #T_c904e_row20_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_c904e">
  <thead>
    <tr>
      <th id="T_c904e_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_c904e_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_c904e_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_c904e_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_c904e_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_c904e_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_c904e_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_c904e_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_c904e_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_c904e_row0_col0" class="data row0 col0" >101</td>
      <td id="T_c904e_row0_col1" class="data row0 col1" >Fall 2021</td>
      <td id="T_c904e_row0_col2" class="data row0 col2" >CLSE101</td>
      <td id="T_c904e_row0_col3" class="data row0 col3" >001</td>
      <td id="T_c904e_row0_col4" class="data row0 col4" >INTRO TO ENGINEERING</td>
      <td id="T_c904e_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_c904e_row0_col6" class="data row0 col6" >49</td>
      <td id="T_c904e_row0_col7" class="data row0 col7" >147</td>
      <td id="T_c904e_row0_col8" class="data row0 col8" >Roper</td>
    </tr>
    <tr>
      <td id="T_c904e_row1_col0" class="data row1 col0" >100</td>
      <td id="T_c904e_row1_col1" class="data row1 col1" >Fall 2021</td>
      <td id="T_c904e_row1_col2" class="data row1 col2" >ENGR100</td>
      <td id="T_c904e_row1_col3" class="data row1 col3" >901</td>
      <td id="T_c904e_row1_col4" class="data row1 col4" >ENGINEERING STUDENT SUCCESS</td>
      <td id="T_c904e_row1_col5" class="data row1 col5" >SEM</td>
      <td id="T_c904e_row1_col6" class="data row1 col6" >31</td>
      <td id="T_c904e_row1_col7" class="data row1 col7" >0</td>
      <td id="T_c904e_row1_col8" class="data row1 col8" >Rivers</td>
    </tr>
    <tr>
      <td id="T_c904e_row2_col0" class="data row2 col0" >395</td>
      <td id="T_c904e_row2_col1" class="data row2 col1" >Fall 2021</td>
      <td id="T_c904e_row2_col2" class="data row2 col2" >ENGR395</td>
      <td id="T_c904e_row2_col3" class="data row2 col3" >001</td>
      <td id="T_c904e_row2_col4" class="data row2 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c904e_row2_col5" class="data row2 col5" >LEC</td>
      <td id="T_c904e_row2_col6" class="data row2 col6" >16</td>
      <td id="T_c904e_row2_col7" class="data row2 col7" >16</td>
      <td id="T_c904e_row2_col8" class="data row2 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c904e_row3_col0" class="data row3 col0" >395</td>
      <td id="T_c904e_row3_col1" class="data row3 col1" >Fall 2021</td>
      <td id="T_c904e_row3_col2" class="data row3 col2" >ENGR395</td>
      <td id="T_c904e_row3_col3" class="data row3 col3" >001</td>
      <td id="T_c904e_row3_col4" class="data row3 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c904e_row3_col5" class="data row3 col5" >LEC</td>
      <td id="T_c904e_row3_col6" class="data row3 col6" >16</td>
      <td id="T_c904e_row3_col7" class="data row3 col7" >16</td>
      <td id="T_c904e_row3_col8" class="data row3 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_c904e_row4_col0" class="data row4 col0" >395</td>
      <td id="T_c904e_row4_col1" class="data row4 col1" >Fall 2021</td>
      <td id="T_c904e_row4_col2" class="data row4 col2" >ENGR395</td>
      <td id="T_c904e_row4_col3" class="data row4 col3" >002</td>
      <td id="T_c904e_row4_col4" class="data row4 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c904e_row4_col5" class="data row4 col5" >LEC</td>
      <td id="T_c904e_row4_col6" class="data row4 col6" >16</td>
      <td id="T_c904e_row4_col7" class="data row4 col7" >16</td>
      <td id="T_c904e_row4_col8" class="data row4 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c904e_row5_col0" class="data row5 col0" >395</td>
      <td id="T_c904e_row5_col1" class="data row5 col1" >Fall 2021</td>
      <td id="T_c904e_row5_col2" class="data row5 col2" >ENGR395</td>
      <td id="T_c904e_row5_col3" class="data row5 col3" >002</td>
      <td id="T_c904e_row5_col4" class="data row5 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c904e_row5_col5" class="data row5 col5" >LEC</td>
      <td id="T_c904e_row5_col6" class="data row5 col6" >16</td>
      <td id="T_c904e_row5_col7" class="data row5 col7" >16</td>
      <td id="T_c904e_row5_col8" class="data row5 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_c904e_row6_col0" class="data row6 col0" >395</td>
      <td id="T_c904e_row6_col1" class="data row6 col1" >Fall 2021</td>
      <td id="T_c904e_row6_col2" class="data row6 col2" >ENGR395</td>
      <td id="T_c904e_row6_col3" class="data row6 col3" >003</td>
      <td id="T_c904e_row6_col4" class="data row6 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c904e_row6_col5" class="data row6 col5" >LEC</td>
      <td id="T_c904e_row6_col6" class="data row6 col6" >16</td>
      <td id="T_c904e_row6_col7" class="data row6 col7" >16</td>
      <td id="T_c904e_row6_col8" class="data row6 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c904e_row7_col0" class="data row7 col0" >395</td>
      <td id="T_c904e_row7_col1" class="data row7 col1" >Fall 2021</td>
      <td id="T_c904e_row7_col2" class="data row7 col2" >ENGR395</td>
      <td id="T_c904e_row7_col3" class="data row7 col3" >003</td>
      <td id="T_c904e_row7_col4" class="data row7 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c904e_row7_col5" class="data row7 col5" >LEC</td>
      <td id="T_c904e_row7_col6" class="data row7 col6" >16</td>
      <td id="T_c904e_row7_col7" class="data row7 col7" >16</td>
      <td id="T_c904e_row7_col8" class="data row7 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_c904e_row8_col0" class="data row8 col0" >395</td>
      <td id="T_c904e_row8_col1" class="data row8 col1" >Fall 2021</td>
      <td id="T_c904e_row8_col2" class="data row8 col2" >ENGR395</td>
      <td id="T_c904e_row8_col3" class="data row8 col3" >004</td>
      <td id="T_c904e_row8_col4" class="data row8 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c904e_row8_col5" class="data row8 col5" >LEC</td>
      <td id="T_c904e_row8_col6" class="data row8 col6" >6</td>
      <td id="T_c904e_row8_col7" class="data row8 col7" >6</td>
      <td id="T_c904e_row8_col8" class="data row8 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c904e_row9_col0" class="data row9 col0" >395</td>
      <td id="T_c904e_row9_col1" class="data row9 col1" >Fall 2021</td>
      <td id="T_c904e_row9_col2" class="data row9 col2" >ENGR395</td>
      <td id="T_c904e_row9_col3" class="data row9 col3" >004</td>
      <td id="T_c904e_row9_col4" class="data row9 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c904e_row9_col5" class="data row9 col5" >LEC</td>
      <td id="T_c904e_row9_col6" class="data row9 col6" >6</td>
      <td id="T_c904e_row9_col7" class="data row9 col7" >6</td>
      <td id="T_c904e_row9_col8" class="data row9 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_c904e_row10_col0" class="data row10 col0" >395</td>
      <td id="T_c904e_row10_col1" class="data row10 col1" >Fall 2021</td>
      <td id="T_c904e_row10_col2" class="data row10 col2" >ENGR395</td>
      <td id="T_c904e_row10_col3" class="data row10 col3" >005</td>
      <td id="T_c904e_row10_col4" class="data row10 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c904e_row10_col5" class="data row10 col5" >LEC</td>
      <td id="T_c904e_row10_col6" class="data row10 col6" >16</td>
      <td id="T_c904e_row10_col7" class="data row10 col7" >16</td>
      <td id="T_c904e_row10_col8" class="data row10 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c904e_row11_col0" class="data row11 col0" >395</td>
      <td id="T_c904e_row11_col1" class="data row11 col1" >Fall 2021</td>
      <td id="T_c904e_row11_col2" class="data row11 col2" >ENGR395</td>
      <td id="T_c904e_row11_col3" class="data row11 col3" >005</td>
      <td id="T_c904e_row11_col4" class="data row11 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c904e_row11_col5" class="data row11 col5" >LEC</td>
      <td id="T_c904e_row11_col6" class="data row11 col6" >16</td>
      <td id="T_c904e_row11_col7" class="data row11 col7" >16</td>
      <td id="T_c904e_row11_col8" class="data row11 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_c904e_row12_col0" class="data row12 col0" >395</td>
      <td id="T_c904e_row12_col1" class="data row12 col1" >Fall 2021</td>
      <td id="T_c904e_row12_col2" class="data row12 col2" >ENGR395</td>
      <td id="T_c904e_row12_col3" class="data row12 col3" >901</td>
      <td id="T_c904e_row12_col4" class="data row12 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c904e_row12_col5" class="data row12 col5" >LEC</td>
      <td id="T_c904e_row12_col6" class="data row12 col6" >14</td>
      <td id="T_c904e_row12_col7" class="data row12 col7" >14</td>
      <td id="T_c904e_row12_col8" class="data row12 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c904e_row13_col0" class="data row13 col0" >395</td>
      <td id="T_c904e_row13_col1" class="data row13 col1" >Fall 2021</td>
      <td id="T_c904e_row13_col2" class="data row13 col2" >ENGR395</td>
      <td id="T_c904e_row13_col3" class="data row13 col3" >901</td>
      <td id="T_c904e_row13_col4" class="data row13 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c904e_row13_col5" class="data row13 col5" >LEC</td>
      <td id="T_c904e_row13_col6" class="data row13 col6" >14</td>
      <td id="T_c904e_row13_col7" class="data row13 col7" >14</td>
      <td id="T_c904e_row13_col8" class="data row13 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_c904e_row14_col0" class="data row14 col0" >396</td>
      <td id="T_c904e_row14_col1" class="data row14 col1" >Fall 2021</td>
      <td id="T_c904e_row14_col2" class="data row14 col2" >ENGR396</td>
      <td id="T_c904e_row14_col3" class="data row14 col3" >001</td>
      <td id="T_c904e_row14_col4" class="data row14 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_c904e_row14_col5" class="data row14 col5" >FLD</td>
      <td id="T_c904e_row14_col6" class="data row14 col6" >12</td>
      <td id="T_c904e_row14_col7" class="data row14 col7" >0</td>
      <td id="T_c904e_row14_col8" class="data row14 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c904e_row15_col0" class="data row15 col0" >396</td>
      <td id="T_c904e_row15_col1" class="data row15 col1" >Fall 2021</td>
      <td id="T_c904e_row15_col2" class="data row15 col2" >ENGR396</td>
      <td id="T_c904e_row15_col3" class="data row15 col3" >001</td>
      <td id="T_c904e_row15_col4" class="data row15 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_c904e_row15_col5" class="data row15 col5" >FLD</td>
      <td id="T_c904e_row15_col6" class="data row15 col6" >12</td>
      <td id="T_c904e_row15_col7" class="data row15 col7" >0</td>
      <td id="T_c904e_row15_col8" class="data row15 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_c904e_row16_col0" class="data row16 col0" >398</td>
      <td id="T_c904e_row16_col1" class="data row16 col1" >Fall 2021</td>
      <td id="T_c904e_row16_col2" class="data row16 col2" >ENGR398</td>
      <td id="T_c904e_row16_col3" class="data row16 col3" >001</td>
      <td id="T_c904e_row16_col4" class="data row16 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_c904e_row16_col5" class="data row16 col5" >FLD</td>
      <td id="T_c904e_row16_col6" class="data row16 col6" >5</td>
      <td id="T_c904e_row16_col7" class="data row16 col7" >0</td>
      <td id="T_c904e_row16_col8" class="data row16 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c904e_row17_col0" class="data row17 col0" >496</td>
      <td id="T_c904e_row17_col1" class="data row17 col1" >Fall 2021</td>
      <td id="T_c904e_row17_col2" class="data row17 col2" >ENGR496</td>
      <td id="T_c904e_row17_col3" class="data row17 col3" >001</td>
      <td id="T_c904e_row17_col4" class="data row17 col4" >INTERNSHIP REVIEW</td>
      <td id="T_c904e_row17_col5" class="data row17 col5" >FLD</td>
      <td id="T_c904e_row17_col6" class="data row17 col6" >39</td>
      <td id="T_c904e_row17_col7" class="data row17 col7" >0</td>
      <td id="T_c904e_row17_col8" class="data row17 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c904e_row18_col0" class="data row18 col0" >496</td>
      <td id="T_c904e_row18_col1" class="data row18 col1" >Fall 2021</td>
      <td id="T_c904e_row18_col2" class="data row18 col2" >ENGR496</td>
      <td id="T_c904e_row18_col3" class="data row18 col3" >001</td>
      <td id="T_c904e_row18_col4" class="data row18 col4" >INTERNSHIP REVIEW</td>
      <td id="T_c904e_row18_col5" class="data row18 col5" >FLD</td>
      <td id="T_c904e_row18_col6" class="data row18 col6" >39</td>
      <td id="T_c904e_row18_col7" class="data row18 col7" >0</td>
      <td id="T_c904e_row18_col8" class="data row18 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_c904e_row19_col0" class="data row19 col0" >498</td>
      <td id="T_c904e_row19_col1" class="data row19 col1" >Fall 2021</td>
      <td id="T_c904e_row19_col2" class="data row19 col2" >ENGR498</td>
      <td id="T_c904e_row19_col3" class="data row19 col3" >001</td>
      <td id="T_c904e_row19_col4" class="data row19 col4" >REVIEW OF COOP EDUCATION EXP</td>
      <td id="T_c904e_row19_col5" class="data row19 col5" >FLD</td>
      <td id="T_c904e_row19_col6" class="data row19 col6" >6</td>
      <td id="T_c904e_row19_col7" class="data row19 col7" >0</td>
      <td id="T_c904e_row19_col8" class="data row19 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c904e_row20_col0" class="data row20 col0" >691</td>
      <td id="T_c904e_row20_col1" class="data row20 col1" >Fall 2021</td>
      <td id="T_c904e_row20_col2" class="data row20 col2" >ENGR691</td>
      <td id="T_c904e_row20_col3" class="data row20 col3" >008</td>
      <td id="T_c904e_row20_col4" class="data row20 col4" >SPTP:RESEARCH ETHICS& PROF DEV</td>
      <td id="T_c904e_row20_col5" class="data row20 col5" >LEC</td>
      <td id="T_c904e_row20_col6" class="data row20 col6" >4</td>
      <td id="T_c904e_row20_col7" class="data row20 col7" >7</td>
      <td id="T_c904e_row20_col8" class="data row20 col8" >Sharpe</td>
    </tr>
  </tbody>
</table>

:::

## Spring 2022

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_88c5a table {
  width: 100%;
  border-collapse: collapse;
}
#T_88c5a th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_88c5a th {
  border: 0;
}
#T_88c5a thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_88c5a tbody td:nth-child(1) {
  display: none;
}
#T_88c5a thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_88c5a tbody td:nth-child(2) {
  display: none;
}
#T_88c5a thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_88c5a tbody td:nth-child(8) {
  display: none;
}
#T_88c5a td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_88c5a td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_88c5a td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_88c5a td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_88c5a td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_88c5a td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_88c5a_row0_col0, #T_88c5a_row0_col1, #T_88c5a_row0_col2, #T_88c5a_row0_col3, #T_88c5a_row0_col4, #T_88c5a_row0_col5, #T_88c5a_row0_col6, #T_88c5a_row0_col7, #T_88c5a_row0_col8, #T_88c5a_row1_col0, #T_88c5a_row1_col1, #T_88c5a_row1_col2, #T_88c5a_row1_col3, #T_88c5a_row1_col4, #T_88c5a_row1_col5, #T_88c5a_row1_col6, #T_88c5a_row1_col7, #T_88c5a_row1_col8, #T_88c5a_row2_col0, #T_88c5a_row2_col1, #T_88c5a_row2_col2, #T_88c5a_row2_col3, #T_88c5a_row2_col4, #T_88c5a_row2_col5, #T_88c5a_row2_col6, #T_88c5a_row2_col7, #T_88c5a_row2_col8, #T_88c5a_row3_col0, #T_88c5a_row3_col1, #T_88c5a_row3_col2, #T_88c5a_row3_col3, #T_88c5a_row3_col4, #T_88c5a_row3_col5, #T_88c5a_row3_col6, #T_88c5a_row3_col7, #T_88c5a_row3_col8, #T_88c5a_row4_col0, #T_88c5a_row4_col1, #T_88c5a_row4_col2, #T_88c5a_row4_col3, #T_88c5a_row4_col4, #T_88c5a_row4_col5, #T_88c5a_row4_col6, #T_88c5a_row4_col7, #T_88c5a_row4_col8, #T_88c5a_row5_col0, #T_88c5a_row5_col1, #T_88c5a_row5_col2, #T_88c5a_row5_col3, #T_88c5a_row5_col4, #T_88c5a_row5_col5, #T_88c5a_row5_col6, #T_88c5a_row5_col7, #T_88c5a_row5_col8, #T_88c5a_row6_col0, #T_88c5a_row6_col1, #T_88c5a_row6_col2, #T_88c5a_row6_col3, #T_88c5a_row6_col4, #T_88c5a_row6_col5, #T_88c5a_row6_col6, #T_88c5a_row6_col7, #T_88c5a_row6_col8, #T_88c5a_row9_col0, #T_88c5a_row9_col1, #T_88c5a_row9_col2, #T_88c5a_row9_col3, #T_88c5a_row9_col4, #T_88c5a_row9_col5, #T_88c5a_row9_col6, #T_88c5a_row9_col7, #T_88c5a_row9_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_88c5a_row7_col0, #T_88c5a_row7_col1, #T_88c5a_row7_col2, #T_88c5a_row7_col3, #T_88c5a_row7_col4, #T_88c5a_row7_col5, #T_88c5a_row7_col6, #T_88c5a_row7_col7, #T_88c5a_row7_col8, #T_88c5a_row8_col0, #T_88c5a_row8_col1, #T_88c5a_row8_col2, #T_88c5a_row8_col3, #T_88c5a_row8_col4, #T_88c5a_row8_col5, #T_88c5a_row8_col6, #T_88c5a_row8_col7, #T_88c5a_row8_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_88c5a">
  <thead>
    <tr>
      <th id="T_88c5a_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_88c5a_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_88c5a_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_88c5a_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_88c5a_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_88c5a_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_88c5a_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_88c5a_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_88c5a_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_88c5a_row0_col0" class="data row0 col0" >395</td>
      <td id="T_88c5a_row0_col1" class="data row0 col1" >Spring 2022</td>
      <td id="T_88c5a_row0_col2" class="data row0 col2" >ENGR395</td>
      <td id="T_88c5a_row0_col3" class="data row0 col3" >001</td>
      <td id="T_88c5a_row0_col4" class="data row0 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_88c5a_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_88c5a_row0_col6" class="data row0 col6" >31</td>
      <td id="T_88c5a_row0_col7" class="data row0 col7" >31</td>
      <td id="T_88c5a_row0_col8" class="data row0 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_88c5a_row1_col0" class="data row1 col0" >395</td>
      <td id="T_88c5a_row1_col1" class="data row1 col1" >Spring 2022</td>
      <td id="T_88c5a_row1_col2" class="data row1 col2" >ENGR395</td>
      <td id="T_88c5a_row1_col3" class="data row1 col3" >002</td>
      <td id="T_88c5a_row1_col4" class="data row1 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_88c5a_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_88c5a_row1_col6" class="data row1 col6" >37</td>
      <td id="T_88c5a_row1_col7" class="data row1 col7" >37</td>
      <td id="T_88c5a_row1_col8" class="data row1 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_88c5a_row2_col0" class="data row2 col0" >395</td>
      <td id="T_88c5a_row2_col1" class="data row2 col1" >Spring 2022</td>
      <td id="T_88c5a_row2_col2" class="data row2 col2" >ENGR395</td>
      <td id="T_88c5a_row2_col3" class="data row2 col3" >003</td>
      <td id="T_88c5a_row2_col4" class="data row2 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_88c5a_row2_col5" class="data row2 col5" >LEC</td>
      <td id="T_88c5a_row2_col6" class="data row2 col6" >29</td>
      <td id="T_88c5a_row2_col7" class="data row2 col7" >29</td>
      <td id="T_88c5a_row2_col8" class="data row2 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_88c5a_row3_col0" class="data row3 col0" >395</td>
      <td id="T_88c5a_row3_col1" class="data row3 col1" >Spring 2022</td>
      <td id="T_88c5a_row3_col2" class="data row3 col2" >ENGR395</td>
      <td id="T_88c5a_row3_col3" class="data row3 col3" >004</td>
      <td id="T_88c5a_row3_col4" class="data row3 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_88c5a_row3_col5" class="data row3 col5" >LEC</td>
      <td id="T_88c5a_row3_col6" class="data row3 col6" >21</td>
      <td id="T_88c5a_row3_col7" class="data row3 col7" >21</td>
      <td id="T_88c5a_row3_col8" class="data row3 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_88c5a_row4_col0" class="data row4 col0" >395</td>
      <td id="T_88c5a_row4_col1" class="data row4 col1" >Spring 2022</td>
      <td id="T_88c5a_row4_col2" class="data row4 col2" >ENGR395</td>
      <td id="T_88c5a_row4_col3" class="data row4 col3" >005</td>
      <td id="T_88c5a_row4_col4" class="data row4 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_88c5a_row4_col5" class="data row4 col5" >LEC</td>
      <td id="T_88c5a_row4_col6" class="data row4 col6" >11</td>
      <td id="T_88c5a_row4_col7" class="data row4 col7" >11</td>
      <td id="T_88c5a_row4_col8" class="data row4 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_88c5a_row5_col0" class="data row5 col0" >396</td>
      <td id="T_88c5a_row5_col1" class="data row5 col1" >Spring 2022</td>
      <td id="T_88c5a_row5_col2" class="data row5 col2" >ENGR396</td>
      <td id="T_88c5a_row5_col3" class="data row5 col3" >001</td>
      <td id="T_88c5a_row5_col4" class="data row5 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_88c5a_row5_col5" class="data row5 col5" >FLD</td>
      <td id="T_88c5a_row5_col6" class="data row5 col6" >24</td>
      <td id="T_88c5a_row5_col7" class="data row5 col7" >0</td>
      <td id="T_88c5a_row5_col8" class="data row5 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_88c5a_row6_col0" class="data row6 col0" >398</td>
      <td id="T_88c5a_row6_col1" class="data row6 col1" >Spring 2022</td>
      <td id="T_88c5a_row6_col2" class="data row6 col2" >ENGR398</td>
      <td id="T_88c5a_row6_col3" class="data row6 col3" >001</td>
      <td id="T_88c5a_row6_col4" class="data row6 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_88c5a_row6_col5" class="data row6 col5" >FLD</td>
      <td id="T_88c5a_row6_col6" class="data row6 col6" >4</td>
      <td id="T_88c5a_row6_col7" class="data row6 col7" >0</td>
      <td id="T_88c5a_row6_col8" class="data row6 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_88c5a_row7_col0" class="data row7 col0" >496</td>
      <td id="T_88c5a_row7_col1" class="data row7 col1" >Spring 2022</td>
      <td id="T_88c5a_row7_col2" class="data row7 col2" >ENGR496</td>
      <td id="T_88c5a_row7_col3" class="data row7 col3" >001</td>
      <td id="T_88c5a_row7_col4" class="data row7 col4" >INTERNSHIP REVIEW</td>
      <td id="T_88c5a_row7_col5" class="data row7 col5" >FLD</td>
      <td id="T_88c5a_row7_col6" class="data row7 col6" >41</td>
      <td id="T_88c5a_row7_col7" class="data row7 col7" >0</td>
      <td id="T_88c5a_row7_col8" class="data row7 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_88c5a_row8_col0" class="data row8 col0" >498</td>
      <td id="T_88c5a_row8_col1" class="data row8 col1" >Spring 2022</td>
      <td id="T_88c5a_row8_col2" class="data row8 col2" >ENGR498</td>
      <td id="T_88c5a_row8_col3" class="data row8 col3" >001</td>
      <td id="T_88c5a_row8_col4" class="data row8 col4" >REVIEW OF COOP EDUCATION EXP</td>
      <td id="T_88c5a_row8_col5" class="data row8 col5" >FLD</td>
      <td id="T_88c5a_row8_col6" class="data row8 col6" >1</td>
      <td id="T_88c5a_row8_col7" class="data row8 col7" >0</td>
      <td id="T_88c5a_row8_col8" class="data row8 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_88c5a_row9_col0" class="data row9 col0" >591</td>
      <td id="T_88c5a_row9_col1" class="data row9 col1" >Spring 2022</td>
      <td id="T_88c5a_row9_col2" class="data row9 col2" >ENGR591</td>
      <td id="T_88c5a_row9_col3" class="data row9 col3" >005</td>
      <td id="T_88c5a_row9_col4" class="data row9 col4" >TOP: DESIGN OF REHAB TECH</td>
      <td id="T_88c5a_row9_col5" class="data row9 col5" >LEC</td>
      <td id="T_88c5a_row9_col6" class="data row9 col6" >4</td>
      <td id="T_88c5a_row9_col7" class="data row9 col7" >12</td>
      <td id="T_88c5a_row9_col8" class="data row9 col8" >Pidcoe</td>
    </tr>
  </tbody>
</table>

:::

## Summer 2022

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_80199 table {
  width: 100%;
  border-collapse: collapse;
}
#T_80199 th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_80199 th {
  border: 0;
}
#T_80199 thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_80199 tbody td:nth-child(1) {
  display: none;
}
#T_80199 thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_80199 tbody td:nth-child(2) {
  display: none;
}
#T_80199 thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_80199 tbody td:nth-child(8) {
  display: none;
}
#T_80199 td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_80199 td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_80199 td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_80199 td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_80199 td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_80199 td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_80199_row0_col0, #T_80199_row0_col1, #T_80199_row0_col2, #T_80199_row0_col3, #T_80199_row0_col4, #T_80199_row0_col5, #T_80199_row0_col6, #T_80199_row0_col7, #T_80199_row0_col8, #T_80199_row1_col0, #T_80199_row1_col1, #T_80199_row1_col2, #T_80199_row1_col3, #T_80199_row1_col4, #T_80199_row1_col5, #T_80199_row1_col6, #T_80199_row1_col7, #T_80199_row1_col8, #T_80199_row2_col0, #T_80199_row2_col1, #T_80199_row2_col2, #T_80199_row2_col3, #T_80199_row2_col4, #T_80199_row2_col5, #T_80199_row2_col6, #T_80199_row2_col7, #T_80199_row2_col8, #T_80199_row3_col0, #T_80199_row3_col1, #T_80199_row3_col2, #T_80199_row3_col3, #T_80199_row3_col4, #T_80199_row3_col5, #T_80199_row3_col6, #T_80199_row3_col7, #T_80199_row3_col8, #T_80199_row4_col0, #T_80199_row4_col1, #T_80199_row4_col2, #T_80199_row4_col3, #T_80199_row4_col4, #T_80199_row4_col5, #T_80199_row4_col6, #T_80199_row4_col7, #T_80199_row4_col8, #T_80199_row5_col0, #T_80199_row5_col1, #T_80199_row5_col2, #T_80199_row5_col3, #T_80199_row5_col4, #T_80199_row5_col5, #T_80199_row5_col6, #T_80199_row5_col7, #T_80199_row5_col8, #T_80199_row6_col0, #T_80199_row6_col1, #T_80199_row6_col2, #T_80199_row6_col3, #T_80199_row6_col4, #T_80199_row6_col5, #T_80199_row6_col6, #T_80199_row6_col7, #T_80199_row6_col8, #T_80199_row7_col0, #T_80199_row7_col1, #T_80199_row7_col2, #T_80199_row7_col3, #T_80199_row7_col4, #T_80199_row7_col5, #T_80199_row7_col6, #T_80199_row7_col7, #T_80199_row7_col8, #T_80199_row8_col0, #T_80199_row8_col1, #T_80199_row8_col2, #T_80199_row8_col3, #T_80199_row8_col4, #T_80199_row8_col5, #T_80199_row8_col6, #T_80199_row8_col7, #T_80199_row8_col8, #T_80199_row9_col0, #T_80199_row9_col1, #T_80199_row9_col2, #T_80199_row9_col3, #T_80199_row9_col4, #T_80199_row9_col5, #T_80199_row9_col6, #T_80199_row9_col7, #T_80199_row9_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_80199_row10_col0, #T_80199_row10_col1, #T_80199_row10_col2, #T_80199_row10_col3, #T_80199_row10_col4, #T_80199_row10_col5, #T_80199_row10_col6, #T_80199_row10_col7, #T_80199_row10_col8, #T_80199_row11_col0, #T_80199_row11_col1, #T_80199_row11_col2, #T_80199_row11_col3, #T_80199_row11_col4, #T_80199_row11_col5, #T_80199_row11_col6, #T_80199_row11_col7, #T_80199_row11_col8, #T_80199_row12_col0, #T_80199_row12_col1, #T_80199_row12_col2, #T_80199_row12_col3, #T_80199_row12_col4, #T_80199_row12_col5, #T_80199_row12_col6, #T_80199_row12_col7, #T_80199_row12_col8, #T_80199_row13_col0, #T_80199_row13_col1, #T_80199_row13_col2, #T_80199_row13_col3, #T_80199_row13_col4, #T_80199_row13_col5, #T_80199_row13_col6, #T_80199_row13_col7, #T_80199_row13_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_80199">
  <thead>
    <tr>
      <th id="T_80199_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_80199_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_80199_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_80199_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_80199_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_80199_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_80199_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_80199_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_80199_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_80199_row0_col0" class="data row0 col0" >395</td>
      <td id="T_80199_row0_col1" class="data row0 col1" >Summer 2022</td>
      <td id="T_80199_row0_col2" class="data row0 col2" >ENGR395</td>
      <td id="T_80199_row0_col3" class="data row0 col3" >001</td>
      <td id="T_80199_row0_col4" class="data row0 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_80199_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_80199_row0_col6" class="data row0 col6" >6</td>
      <td id="T_80199_row0_col7" class="data row0 col7" >6</td>
      <td id="T_80199_row0_col8" class="data row0 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_80199_row1_col0" class="data row1 col0" >395</td>
      <td id="T_80199_row1_col1" class="data row1 col1" >Summer 2022</td>
      <td id="T_80199_row1_col2" class="data row1 col2" >ENGR395</td>
      <td id="T_80199_row1_col3" class="data row1 col3" >001</td>
      <td id="T_80199_row1_col4" class="data row1 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_80199_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_80199_row1_col6" class="data row1 col6" >6</td>
      <td id="T_80199_row1_col7" class="data row1 col7" >6</td>
      <td id="T_80199_row1_col8" class="data row1 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_80199_row2_col0" class="data row2 col0" >396</td>
      <td id="T_80199_row2_col1" class="data row2 col1" >Summer 2022</td>
      <td id="T_80199_row2_col2" class="data row2 col2" >ENGR396</td>
      <td id="T_80199_row2_col3" class="data row2 col3" >001</td>
      <td id="T_80199_row2_col4" class="data row2 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_80199_row2_col5" class="data row2 col5" >FLD</td>
      <td id="T_80199_row2_col6" class="data row2 col6" >48</td>
      <td id="T_80199_row2_col7" class="data row2 col7" >0</td>
      <td id="T_80199_row2_col8" class="data row2 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_80199_row3_col0" class="data row3 col0" >396</td>
      <td id="T_80199_row3_col1" class="data row3 col1" >Summer 2022</td>
      <td id="T_80199_row3_col2" class="data row3 col2" >ENGR396</td>
      <td id="T_80199_row3_col3" class="data row3 col3" >001</td>
      <td id="T_80199_row3_col4" class="data row3 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_80199_row3_col5" class="data row3 col5" >FLD</td>
      <td id="T_80199_row3_col6" class="data row3 col6" >48</td>
      <td id="T_80199_row3_col7" class="data row3 col7" >0</td>
      <td id="T_80199_row3_col8" class="data row3 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_80199_row4_col0" class="data row4 col0" >396</td>
      <td id="T_80199_row4_col1" class="data row4 col1" >Summer 2022</td>
      <td id="T_80199_row4_col2" class="data row4 col2" >ENGR396</td>
      <td id="T_80199_row4_col3" class="data row4 col3" >002</td>
      <td id="T_80199_row4_col4" class="data row4 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_80199_row4_col5" class="data row4 col5" >FLD</td>
      <td id="T_80199_row4_col6" class="data row4 col6" >18</td>
      <td id="T_80199_row4_col7" class="data row4 col7" >0</td>
      <td id="T_80199_row4_col8" class="data row4 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_80199_row5_col0" class="data row5 col0" >396</td>
      <td id="T_80199_row5_col1" class="data row5 col1" >Summer 2022</td>
      <td id="T_80199_row5_col2" class="data row5 col2" >ENGR396</td>
      <td id="T_80199_row5_col3" class="data row5 col3" >002</td>
      <td id="T_80199_row5_col4" class="data row5 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_80199_row5_col5" class="data row5 col5" >FLD</td>
      <td id="T_80199_row5_col6" class="data row5 col6" >18</td>
      <td id="T_80199_row5_col7" class="data row5 col7" >0</td>
      <td id="T_80199_row5_col8" class="data row5 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_80199_row6_col0" class="data row6 col0" >398</td>
      <td id="T_80199_row6_col1" class="data row6 col1" >Summer 2022</td>
      <td id="T_80199_row6_col2" class="data row6 col2" >ENGR398</td>
      <td id="T_80199_row6_col3" class="data row6 col3" >001</td>
      <td id="T_80199_row6_col4" class="data row6 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_80199_row6_col5" class="data row6 col5" >FLD</td>
      <td id="T_80199_row6_col6" class="data row6 col6" >2</td>
      <td id="T_80199_row6_col7" class="data row6 col7" >0</td>
      <td id="T_80199_row6_col8" class="data row6 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_80199_row7_col0" class="data row7 col0" >398</td>
      <td id="T_80199_row7_col1" class="data row7 col1" >Summer 2022</td>
      <td id="T_80199_row7_col2" class="data row7 col2" >ENGR398</td>
      <td id="T_80199_row7_col3" class="data row7 col3" >001</td>
      <td id="T_80199_row7_col4" class="data row7 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_80199_row7_col5" class="data row7 col5" >FLD</td>
      <td id="T_80199_row7_col6" class="data row7 col6" >2</td>
      <td id="T_80199_row7_col7" class="data row7 col7" >0</td>
      <td id="T_80199_row7_col8" class="data row7 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_80199_row8_col0" class="data row8 col0" >398</td>
      <td id="T_80199_row8_col1" class="data row8 col1" >Summer 2022</td>
      <td id="T_80199_row8_col2" class="data row8 col2" >ENGR398</td>
      <td id="T_80199_row8_col3" class="data row8 col3" >002</td>
      <td id="T_80199_row8_col4" class="data row8 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_80199_row8_col5" class="data row8 col5" >FLD</td>
      <td id="T_80199_row8_col6" class="data row8 col6" >0</td>
      <td id="T_80199_row8_col7" class="data row8 col7" >0</td>
      <td id="T_80199_row8_col8" class="data row8 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_80199_row9_col0" class="data row9 col0" >398</td>
      <td id="T_80199_row9_col1" class="data row9 col1" >Summer 2022</td>
      <td id="T_80199_row9_col2" class="data row9 col2" >ENGR398</td>
      <td id="T_80199_row9_col3" class="data row9 col3" >002</td>
      <td id="T_80199_row9_col4" class="data row9 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_80199_row9_col5" class="data row9 col5" >FLD</td>
      <td id="T_80199_row9_col6" class="data row9 col6" >0</td>
      <td id="T_80199_row9_col7" class="data row9 col7" >0</td>
      <td id="T_80199_row9_col8" class="data row9 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_80199_row10_col0" class="data row10 col0" >496</td>
      <td id="T_80199_row10_col1" class="data row10 col1" >Summer 2022</td>
      <td id="T_80199_row10_col2" class="data row10 col2" >ENGR496</td>
      <td id="T_80199_row10_col3" class="data row10 col3" >001</td>
      <td id="T_80199_row10_col4" class="data row10 col4" >INTERNSHIP REVIEW</td>
      <td id="T_80199_row10_col5" class="data row10 col5" >FLD</td>
      <td id="T_80199_row10_col6" class="data row10 col6" >1</td>
      <td id="T_80199_row10_col7" class="data row10 col7" >0</td>
      <td id="T_80199_row10_col8" class="data row10 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_80199_row11_col0" class="data row11 col0" >496</td>
      <td id="T_80199_row11_col1" class="data row11 col1" >Summer 2022</td>
      <td id="T_80199_row11_col2" class="data row11 col2" >ENGR496</td>
      <td id="T_80199_row11_col3" class="data row11 col3" >001</td>
      <td id="T_80199_row11_col4" class="data row11 col4" >INTERNSHIP REVIEW</td>
      <td id="T_80199_row11_col5" class="data row11 col5" >FLD</td>
      <td id="T_80199_row11_col6" class="data row11 col6" >1</td>
      <td id="T_80199_row11_col7" class="data row11 col7" >0</td>
      <td id="T_80199_row11_col8" class="data row11 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_80199_row12_col0" class="data row12 col0" >496</td>
      <td id="T_80199_row12_col1" class="data row12 col1" >Summer 2022</td>
      <td id="T_80199_row12_col2" class="data row12 col2" >ENGR496</td>
      <td id="T_80199_row12_col3" class="data row12 col3" >002</td>
      <td id="T_80199_row12_col4" class="data row12 col4" >INTERNSHIP REVIEW</td>
      <td id="T_80199_row12_col5" class="data row12 col5" >FLD</td>
      <td id="T_80199_row12_col6" class="data row12 col6" >2</td>
      <td id="T_80199_row12_col7" class="data row12 col7" >0</td>
      <td id="T_80199_row12_col8" class="data row12 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_80199_row13_col0" class="data row13 col0" >496</td>
      <td id="T_80199_row13_col1" class="data row13 col1" >Summer 2022</td>
      <td id="T_80199_row13_col2" class="data row13 col2" >ENGR496</td>
      <td id="T_80199_row13_col3" class="data row13 col3" >002</td>
      <td id="T_80199_row13_col4" class="data row13 col4" >INTERNSHIP REVIEW</td>
      <td id="T_80199_row13_col5" class="data row13 col5" >FLD</td>
      <td id="T_80199_row13_col6" class="data row13 col6" >2</td>
      <td id="T_80199_row13_col7" class="data row13 col7" >0</td>
      <td id="T_80199_row13_col8" class="data row13 col8" >Sharpe</td>
    </tr>
  </tbody>
</table>

:::

# AY20-21

This section list instructor activity for the academic year AY20-21 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## Fall 2020

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_7cbfd table {
  width: 100%;
  border-collapse: collapse;
}
#T_7cbfd th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_7cbfd th {
  border: 0;
}
#T_7cbfd thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_7cbfd tbody td:nth-child(1) {
  display: none;
}
#T_7cbfd thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_7cbfd tbody td:nth-child(2) {
  display: none;
}
#T_7cbfd thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_7cbfd tbody td:nth-child(8) {
  display: none;
}
#T_7cbfd td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_7cbfd td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_7cbfd td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_7cbfd td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_7cbfd td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_7cbfd td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_7cbfd_row0_col0, #T_7cbfd_row0_col1, #T_7cbfd_row0_col2, #T_7cbfd_row0_col3, #T_7cbfd_row0_col4, #T_7cbfd_row0_col5, #T_7cbfd_row0_col6, #T_7cbfd_row0_col7, #T_7cbfd_row0_col8, #T_7cbfd_row1_col0, #T_7cbfd_row1_col1, #T_7cbfd_row1_col2, #T_7cbfd_row1_col3, #T_7cbfd_row1_col4, #T_7cbfd_row1_col5, #T_7cbfd_row1_col6, #T_7cbfd_row1_col7, #T_7cbfd_row1_col8, #T_7cbfd_row2_col0, #T_7cbfd_row2_col1, #T_7cbfd_row2_col2, #T_7cbfd_row2_col3, #T_7cbfd_row2_col4, #T_7cbfd_row2_col5, #T_7cbfd_row2_col6, #T_7cbfd_row2_col7, #T_7cbfd_row2_col8, #T_7cbfd_row3_col0, #T_7cbfd_row3_col1, #T_7cbfd_row3_col2, #T_7cbfd_row3_col3, #T_7cbfd_row3_col4, #T_7cbfd_row3_col5, #T_7cbfd_row3_col6, #T_7cbfd_row3_col7, #T_7cbfd_row3_col8, #T_7cbfd_row10_col0, #T_7cbfd_row10_col1, #T_7cbfd_row10_col2, #T_7cbfd_row10_col3, #T_7cbfd_row10_col4, #T_7cbfd_row10_col5, #T_7cbfd_row10_col6, #T_7cbfd_row10_col7, #T_7cbfd_row10_col8, #T_7cbfd_row11_col0, #T_7cbfd_row11_col1, #T_7cbfd_row11_col2, #T_7cbfd_row11_col3, #T_7cbfd_row11_col4, #T_7cbfd_row11_col5, #T_7cbfd_row11_col6, #T_7cbfd_row11_col7, #T_7cbfd_row11_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_7cbfd_row4_col0, #T_7cbfd_row4_col1, #T_7cbfd_row4_col2, #T_7cbfd_row4_col3, #T_7cbfd_row4_col4, #T_7cbfd_row4_col5, #T_7cbfd_row4_col6, #T_7cbfd_row4_col7, #T_7cbfd_row4_col8, #T_7cbfd_row5_col0, #T_7cbfd_row5_col1, #T_7cbfd_row5_col2, #T_7cbfd_row5_col3, #T_7cbfd_row5_col4, #T_7cbfd_row5_col5, #T_7cbfd_row5_col6, #T_7cbfd_row5_col7, #T_7cbfd_row5_col8, #T_7cbfd_row6_col0, #T_7cbfd_row6_col1, #T_7cbfd_row6_col2, #T_7cbfd_row6_col3, #T_7cbfd_row6_col4, #T_7cbfd_row6_col5, #T_7cbfd_row6_col6, #T_7cbfd_row6_col7, #T_7cbfd_row6_col8, #T_7cbfd_row7_col0, #T_7cbfd_row7_col1, #T_7cbfd_row7_col2, #T_7cbfd_row7_col3, #T_7cbfd_row7_col4, #T_7cbfd_row7_col5, #T_7cbfd_row7_col6, #T_7cbfd_row7_col7, #T_7cbfd_row7_col8, #T_7cbfd_row8_col0, #T_7cbfd_row8_col1, #T_7cbfd_row8_col2, #T_7cbfd_row8_col3, #T_7cbfd_row8_col4, #T_7cbfd_row8_col5, #T_7cbfd_row8_col6, #T_7cbfd_row8_col7, #T_7cbfd_row8_col8, #T_7cbfd_row9_col0, #T_7cbfd_row9_col1, #T_7cbfd_row9_col2, #T_7cbfd_row9_col3, #T_7cbfd_row9_col4, #T_7cbfd_row9_col5, #T_7cbfd_row9_col6, #T_7cbfd_row9_col7, #T_7cbfd_row9_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_7cbfd">
  <thead>
    <tr>
      <th id="T_7cbfd_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_7cbfd_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_7cbfd_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_7cbfd_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_7cbfd_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_7cbfd_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_7cbfd_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_7cbfd_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_7cbfd_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_7cbfd_row0_col0" class="data row0 col0" >101</td>
      <td id="T_7cbfd_row0_col1" class="data row0 col1" >Fall 2020</td>
      <td id="T_7cbfd_row0_col2" class="data row0 col2" >CLSE101</td>
      <td id="T_7cbfd_row0_col3" class="data row0 col3" >001</td>
      <td id="T_7cbfd_row0_col4" class="data row0 col4" >INTRO TO ENGINEERING</td>
      <td id="T_7cbfd_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_7cbfd_row0_col6" class="data row0 col6" >15</td>
      <td id="T_7cbfd_row0_col7" class="data row0 col7" >22</td>
      <td id="T_7cbfd_row0_col8" class="data row0 col8" >Roper</td>
    </tr>
    <tr>
      <td id="T_7cbfd_row1_col0" class="data row1 col0" >101</td>
      <td id="T_7cbfd_row1_col1" class="data row1 col1" >Fall 2020</td>
      <td id="T_7cbfd_row1_col2" class="data row1 col2" >CLSE101</td>
      <td id="T_7cbfd_row1_col3" class="data row1 col3" >002</td>
      <td id="T_7cbfd_row1_col4" class="data row1 col4" >INTRO TO ENGINEERING</td>
      <td id="T_7cbfd_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_7cbfd_row1_col6" class="data row1 col6" >14</td>
      <td id="T_7cbfd_row1_col7" class="data row1 col7" >21</td>
      <td id="T_7cbfd_row1_col8" class="data row1 col8" >Roper</td>
    </tr>
    <tr>
      <td id="T_7cbfd_row2_col0" class="data row2 col0" >101</td>
      <td id="T_7cbfd_row2_col1" class="data row2 col1" >Fall 2020</td>
      <td id="T_7cbfd_row2_col2" class="data row2 col2" >CLSE101</td>
      <td id="T_7cbfd_row2_col3" class="data row2 col3" >003</td>
      <td id="T_7cbfd_row2_col4" class="data row2 col4" >INTRO TO ENGINEERING</td>
      <td id="T_7cbfd_row2_col5" class="data row2 col5" >LEC</td>
      <td id="T_7cbfd_row2_col6" class="data row2 col6" >16</td>
      <td id="T_7cbfd_row2_col7" class="data row2 col7" >24</td>
      <td id="T_7cbfd_row2_col8" class="data row2 col8" >Roper</td>
    </tr>
    <tr>
      <td id="T_7cbfd_row3_col0" class="data row3 col0" >100</td>
      <td id="T_7cbfd_row3_col1" class="data row3 col1" >Fall 2020</td>
      <td id="T_7cbfd_row3_col2" class="data row3 col2" >ENGR100</td>
      <td id="T_7cbfd_row3_col3" class="data row3 col3" >901</td>
      <td id="T_7cbfd_row3_col4" class="data row3 col4" >ENGINEERING STUDENT SUCCESS</td>
      <td id="T_7cbfd_row3_col5" class="data row3 col5" >SEM</td>
      <td id="T_7cbfd_row3_col6" class="data row3 col6" >34</td>
      <td id="T_7cbfd_row3_col7" class="data row3 col7" >0</td>
      <td id="T_7cbfd_row3_col8" class="data row3 col8" >Rivers</td>
    </tr>
    <tr>
      <td id="T_7cbfd_row4_col0" class="data row4 col0" >395</td>
      <td id="T_7cbfd_row4_col1" class="data row4 col1" >Fall 2020</td>
      <td id="T_7cbfd_row4_col2" class="data row4 col2" >ENGR395</td>
      <td id="T_7cbfd_row4_col3" class="data row4 col3" >001</td>
      <td id="T_7cbfd_row4_col4" class="data row4 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_7cbfd_row4_col5" class="data row4 col5" >LEC</td>
      <td id="T_7cbfd_row4_col6" class="data row4 col6" >16</td>
      <td id="T_7cbfd_row4_col7" class="data row4 col7" >16</td>
      <td id="T_7cbfd_row4_col8" class="data row4 col8" >Carter</td>
    </tr>
    <tr>
      <td id="T_7cbfd_row5_col0" class="data row5 col0" >395</td>
      <td id="T_7cbfd_row5_col1" class="data row5 col1" >Fall 2020</td>
      <td id="T_7cbfd_row5_col2" class="data row5 col2" >ENGR395</td>
      <td id="T_7cbfd_row5_col3" class="data row5 col3" >002</td>
      <td id="T_7cbfd_row5_col4" class="data row5 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_7cbfd_row5_col5" class="data row5 col5" >LEC</td>
      <td id="T_7cbfd_row5_col6" class="data row5 col6" >17</td>
      <td id="T_7cbfd_row5_col7" class="data row5 col7" >17</td>
      <td id="T_7cbfd_row5_col8" class="data row5 col8" >Carter</td>
    </tr>
    <tr>
      <td id="T_7cbfd_row6_col0" class="data row6 col0" >395</td>
      <td id="T_7cbfd_row6_col1" class="data row6 col1" >Fall 2020</td>
      <td id="T_7cbfd_row6_col2" class="data row6 col2" >ENGR395</td>
      <td id="T_7cbfd_row6_col3" class="data row6 col3" >003</td>
      <td id="T_7cbfd_row6_col4" class="data row6 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_7cbfd_row6_col5" class="data row6 col5" >LEC</td>
      <td id="T_7cbfd_row6_col6" class="data row6 col6" >16</td>
      <td id="T_7cbfd_row6_col7" class="data row6 col7" >16</td>
      <td id="T_7cbfd_row6_col8" class="data row6 col8" >Carter</td>
    </tr>
    <tr>
      <td id="T_7cbfd_row7_col0" class="data row7 col0" >395</td>
      <td id="T_7cbfd_row7_col1" class="data row7 col1" >Fall 2020</td>
      <td id="T_7cbfd_row7_col2" class="data row7 col2" >ENGR395</td>
      <td id="T_7cbfd_row7_col3" class="data row7 col3" >901</td>
      <td id="T_7cbfd_row7_col4" class="data row7 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_7cbfd_row7_col5" class="data row7 col5" >LEC</td>
      <td id="T_7cbfd_row7_col6" class="data row7 col6" >16</td>
      <td id="T_7cbfd_row7_col7" class="data row7 col7" >16</td>
      <td id="T_7cbfd_row7_col8" class="data row7 col8" >Carter</td>
    </tr>
    <tr>
      <td id="T_7cbfd_row8_col0" class="data row8 col0" >396</td>
      <td id="T_7cbfd_row8_col1" class="data row8 col1" >Fall 2020</td>
      <td id="T_7cbfd_row8_col2" class="data row8 col2" >ENGR396</td>
      <td id="T_7cbfd_row8_col3" class="data row8 col3" >001</td>
      <td id="T_7cbfd_row8_col4" class="data row8 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_7cbfd_row8_col5" class="data row8 col5" >FLD</td>
      <td id="T_7cbfd_row8_col6" class="data row8 col6" >18</td>
      <td id="T_7cbfd_row8_col7" class="data row8 col7" >0</td>
      <td id="T_7cbfd_row8_col8" class="data row8 col8" >Carter</td>
    </tr>
    <tr>
      <td id="T_7cbfd_row9_col0" class="data row9 col0" >398</td>
      <td id="T_7cbfd_row9_col1" class="data row9 col1" >Fall 2020</td>
      <td id="T_7cbfd_row9_col2" class="data row9 col2" >ENGR398</td>
      <td id="T_7cbfd_row9_col3" class="data row9 col3" >001</td>
      <td id="T_7cbfd_row9_col4" class="data row9 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_7cbfd_row9_col5" class="data row9 col5" >FLD</td>
      <td id="T_7cbfd_row9_col6" class="data row9 col6" >8</td>
      <td id="T_7cbfd_row9_col7" class="data row9 col7" >0</td>
      <td id="T_7cbfd_row9_col8" class="data row9 col8" >Carter</td>
    </tr>
    <tr>
      <td id="T_7cbfd_row10_col0" class="data row10 col0" >496</td>
      <td id="T_7cbfd_row10_col1" class="data row10 col1" >Fall 2020</td>
      <td id="T_7cbfd_row10_col2" class="data row10 col2" >ENGR496</td>
      <td id="T_7cbfd_row10_col3" class="data row10 col3" >001</td>
      <td id="T_7cbfd_row10_col4" class="data row10 col4" >INTERNSHIP REVIEW</td>
      <td id="T_7cbfd_row10_col5" class="data row10 col5" >FLD</td>
      <td id="T_7cbfd_row10_col6" class="data row10 col6" >32</td>
      <td id="T_7cbfd_row10_col7" class="data row10 col7" >0</td>
      <td id="T_7cbfd_row10_col8" class="data row10 col8" >Carter</td>
    </tr>
    <tr>
      <td id="T_7cbfd_row11_col0" class="data row11 col0" >498</td>
      <td id="T_7cbfd_row11_col1" class="data row11 col1" >Fall 2020</td>
      <td id="T_7cbfd_row11_col2" class="data row11 col2" >ENGR498</td>
      <td id="T_7cbfd_row11_col3" class="data row11 col3" >001</td>
      <td id="T_7cbfd_row11_col4" class="data row11 col4" >REVIEW OF COOP EDUCATION EXP</td>
      <td id="T_7cbfd_row11_col5" class="data row11 col5" >FLD</td>
      <td id="T_7cbfd_row11_col6" class="data row11 col6" >8</td>
      <td id="T_7cbfd_row11_col7" class="data row11 col7" >0</td>
      <td id="T_7cbfd_row11_col8" class="data row11 col8" >Carter</td>
    </tr>
  </tbody>
</table>

:::

## Spring 2021

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_3c77f table {
  width: 100%;
  border-collapse: collapse;
}
#T_3c77f th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_3c77f th {
  border: 0;
}
#T_3c77f thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_3c77f tbody td:nth-child(1) {
  display: none;
}
#T_3c77f thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_3c77f tbody td:nth-child(2) {
  display: none;
}
#T_3c77f thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_3c77f tbody td:nth-child(8) {
  display: none;
}
#T_3c77f td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_3c77f td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_3c77f td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_3c77f td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_3c77f td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_3c77f td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_3c77f_row0_col0, #T_3c77f_row0_col1, #T_3c77f_row0_col2, #T_3c77f_row0_col3, #T_3c77f_row0_col4, #T_3c77f_row0_col5, #T_3c77f_row0_col6, #T_3c77f_row0_col7, #T_3c77f_row0_col8, #T_3c77f_row1_col0, #T_3c77f_row1_col1, #T_3c77f_row1_col2, #T_3c77f_row1_col3, #T_3c77f_row1_col4, #T_3c77f_row1_col5, #T_3c77f_row1_col6, #T_3c77f_row1_col7, #T_3c77f_row1_col8, #T_3c77f_row2_col0, #T_3c77f_row2_col1, #T_3c77f_row2_col2, #T_3c77f_row2_col3, #T_3c77f_row2_col4, #T_3c77f_row2_col5, #T_3c77f_row2_col6, #T_3c77f_row2_col7, #T_3c77f_row2_col8, #T_3c77f_row3_col0, #T_3c77f_row3_col1, #T_3c77f_row3_col2, #T_3c77f_row3_col3, #T_3c77f_row3_col4, #T_3c77f_row3_col5, #T_3c77f_row3_col6, #T_3c77f_row3_col7, #T_3c77f_row3_col8, #T_3c77f_row4_col0, #T_3c77f_row4_col1, #T_3c77f_row4_col2, #T_3c77f_row4_col3, #T_3c77f_row4_col4, #T_3c77f_row4_col5, #T_3c77f_row4_col6, #T_3c77f_row4_col7, #T_3c77f_row4_col8, #T_3c77f_row5_col0, #T_3c77f_row5_col1, #T_3c77f_row5_col2, #T_3c77f_row5_col3, #T_3c77f_row5_col4, #T_3c77f_row5_col5, #T_3c77f_row5_col6, #T_3c77f_row5_col7, #T_3c77f_row5_col8, #T_3c77f_row6_col0, #T_3c77f_row6_col1, #T_3c77f_row6_col2, #T_3c77f_row6_col3, #T_3c77f_row6_col4, #T_3c77f_row6_col5, #T_3c77f_row6_col6, #T_3c77f_row6_col7, #T_3c77f_row6_col8, #T_3c77f_row7_col0, #T_3c77f_row7_col1, #T_3c77f_row7_col2, #T_3c77f_row7_col3, #T_3c77f_row7_col4, #T_3c77f_row7_col5, #T_3c77f_row7_col6, #T_3c77f_row7_col7, #T_3c77f_row7_col8, #T_3c77f_row8_col0, #T_3c77f_row8_col1, #T_3c77f_row8_col2, #T_3c77f_row8_col3, #T_3c77f_row8_col4, #T_3c77f_row8_col5, #T_3c77f_row8_col6, #T_3c77f_row8_col7, #T_3c77f_row8_col8, #T_3c77f_row9_col0, #T_3c77f_row9_col1, #T_3c77f_row9_col2, #T_3c77f_row9_col3, #T_3c77f_row9_col4, #T_3c77f_row9_col5, #T_3c77f_row9_col6, #T_3c77f_row9_col7, #T_3c77f_row9_col8, #T_3c77f_row14_col0, #T_3c77f_row14_col1, #T_3c77f_row14_col2, #T_3c77f_row14_col3, #T_3c77f_row14_col4, #T_3c77f_row14_col5, #T_3c77f_row14_col6, #T_3c77f_row14_col7, #T_3c77f_row14_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_3c77f_row10_col0, #T_3c77f_row10_col1, #T_3c77f_row10_col2, #T_3c77f_row10_col3, #T_3c77f_row10_col4, #T_3c77f_row10_col5, #T_3c77f_row10_col6, #T_3c77f_row10_col7, #T_3c77f_row10_col8, #T_3c77f_row11_col0, #T_3c77f_row11_col1, #T_3c77f_row11_col2, #T_3c77f_row11_col3, #T_3c77f_row11_col4, #T_3c77f_row11_col5, #T_3c77f_row11_col6, #T_3c77f_row11_col7, #T_3c77f_row11_col8, #T_3c77f_row12_col0, #T_3c77f_row12_col1, #T_3c77f_row12_col2, #T_3c77f_row12_col3, #T_3c77f_row12_col4, #T_3c77f_row12_col5, #T_3c77f_row12_col6, #T_3c77f_row12_col7, #T_3c77f_row12_col8, #T_3c77f_row13_col0, #T_3c77f_row13_col1, #T_3c77f_row13_col2, #T_3c77f_row13_col3, #T_3c77f_row13_col4, #T_3c77f_row13_col5, #T_3c77f_row13_col6, #T_3c77f_row13_col7, #T_3c77f_row13_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_3c77f">
  <thead>
    <tr>
      <th id="T_3c77f_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_3c77f_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_3c77f_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_3c77f_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_3c77f_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_3c77f_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_3c77f_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_3c77f_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_3c77f_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_3c77f_row0_col0" class="data row0 col0" >395</td>
      <td id="T_3c77f_row0_col1" class="data row0 col1" >Spring 2021</td>
      <td id="T_3c77f_row0_col2" class="data row0 col2" >ENGR395</td>
      <td id="T_3c77f_row0_col3" class="data row0 col3" >001</td>
      <td id="T_3c77f_row0_col4" class="data row0 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_3c77f_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_3c77f_row0_col6" class="data row0 col6" >16</td>
      <td id="T_3c77f_row0_col7" class="data row0 col7" >16</td>
      <td id="T_3c77f_row0_col8" class="data row0 col8" >Carter</td>
    </tr>
    <tr>
      <td id="T_3c77f_row1_col0" class="data row1 col0" >395</td>
      <td id="T_3c77f_row1_col1" class="data row1 col1" >Spring 2021</td>
      <td id="T_3c77f_row1_col2" class="data row1 col2" >ENGR395</td>
      <td id="T_3c77f_row1_col3" class="data row1 col3" >001</td>
      <td id="T_3c77f_row1_col4" class="data row1 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_3c77f_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_3c77f_row1_col6" class="data row1 col6" >16</td>
      <td id="T_3c77f_row1_col7" class="data row1 col7" >16</td>
      <td id="T_3c77f_row1_col8" class="data row1 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_3c77f_row2_col0" class="data row2 col0" >395</td>
      <td id="T_3c77f_row2_col1" class="data row2 col1" >Spring 2021</td>
      <td id="T_3c77f_row2_col2" class="data row2 col2" >ENGR395</td>
      <td id="T_3c77f_row2_col3" class="data row2 col3" >004</td>
      <td id="T_3c77f_row2_col4" class="data row2 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_3c77f_row2_col5" class="data row2 col5" >LEC</td>
      <td id="T_3c77f_row2_col6" class="data row2 col6" >16</td>
      <td id="T_3c77f_row2_col7" class="data row2 col7" >16</td>
      <td id="T_3c77f_row2_col8" class="data row2 col8" >Carter</td>
    </tr>
    <tr>
      <td id="T_3c77f_row3_col0" class="data row3 col0" >395</td>
      <td id="T_3c77f_row3_col1" class="data row3 col1" >Spring 2021</td>
      <td id="T_3c77f_row3_col2" class="data row3 col2" >ENGR395</td>
      <td id="T_3c77f_row3_col3" class="data row3 col3" >004</td>
      <td id="T_3c77f_row3_col4" class="data row3 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_3c77f_row3_col5" class="data row3 col5" >LEC</td>
      <td id="T_3c77f_row3_col6" class="data row3 col6" >16</td>
      <td id="T_3c77f_row3_col7" class="data row3 col7" >16</td>
      <td id="T_3c77f_row3_col8" class="data row3 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_3c77f_row4_col0" class="data row4 col0" >395</td>
      <td id="T_3c77f_row4_col1" class="data row4 col1" >Spring 2021</td>
      <td id="T_3c77f_row4_col2" class="data row4 col2" >ENGR395</td>
      <td id="T_3c77f_row4_col3" class="data row4 col3" >005</td>
      <td id="T_3c77f_row4_col4" class="data row4 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_3c77f_row4_col5" class="data row4 col5" >LEC</td>
      <td id="T_3c77f_row4_col6" class="data row4 col6" >18</td>
      <td id="T_3c77f_row4_col7" class="data row4 col7" >18</td>
      <td id="T_3c77f_row4_col8" class="data row4 col8" >Carter</td>
    </tr>
    <tr>
      <td id="T_3c77f_row5_col0" class="data row5 col0" >395</td>
      <td id="T_3c77f_row5_col1" class="data row5 col1" >Spring 2021</td>
      <td id="T_3c77f_row5_col2" class="data row5 col2" >ENGR395</td>
      <td id="T_3c77f_row5_col3" class="data row5 col3" >005</td>
      <td id="T_3c77f_row5_col4" class="data row5 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_3c77f_row5_col5" class="data row5 col5" >LEC</td>
      <td id="T_3c77f_row5_col6" class="data row5 col6" >18</td>
      <td id="T_3c77f_row5_col7" class="data row5 col7" >18</td>
      <td id="T_3c77f_row5_col8" class="data row5 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_3c77f_row6_col0" class="data row6 col0" >395</td>
      <td id="T_3c77f_row6_col1" class="data row6 col1" >Spring 2021</td>
      <td id="T_3c77f_row6_col2" class="data row6 col2" >ENGR395</td>
      <td id="T_3c77f_row6_col3" class="data row6 col3" >006</td>
      <td id="T_3c77f_row6_col4" class="data row6 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_3c77f_row6_col5" class="data row6 col5" >LEC</td>
      <td id="T_3c77f_row6_col6" class="data row6 col6" >19</td>
      <td id="T_3c77f_row6_col7" class="data row6 col7" >19</td>
      <td id="T_3c77f_row6_col8" class="data row6 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_3c77f_row7_col0" class="data row7 col0" >395</td>
      <td id="T_3c77f_row7_col1" class="data row7 col1" >Spring 2021</td>
      <td id="T_3c77f_row7_col2" class="data row7 col2" >ENGR395</td>
      <td id="T_3c77f_row7_col3" class="data row7 col3" >902</td>
      <td id="T_3c77f_row7_col4" class="data row7 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_3c77f_row7_col5" class="data row7 col5" >LEC</td>
      <td id="T_3c77f_row7_col6" class="data row7 col6" >20</td>
      <td id="T_3c77f_row7_col7" class="data row7 col7" >20</td>
      <td id="T_3c77f_row7_col8" class="data row7 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_3c77f_row8_col0" class="data row8 col0" >396</td>
      <td id="T_3c77f_row8_col1" class="data row8 col1" >Spring 2021</td>
      <td id="T_3c77f_row8_col2" class="data row8 col2" >ENGR396</td>
      <td id="T_3c77f_row8_col3" class="data row8 col3" >001</td>
      <td id="T_3c77f_row8_col4" class="data row8 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_3c77f_row8_col5" class="data row8 col5" >FLD</td>
      <td id="T_3c77f_row8_col6" class="data row8 col6" >14</td>
      <td id="T_3c77f_row8_col7" class="data row8 col7" >0</td>
      <td id="T_3c77f_row8_col8" class="data row8 col8" >Carter</td>
    </tr>
    <tr>
      <td id="T_3c77f_row9_col0" class="data row9 col0" >398</td>
      <td id="T_3c77f_row9_col1" class="data row9 col1" >Spring 2021</td>
      <td id="T_3c77f_row9_col2" class="data row9 col2" >ENGR398</td>
      <td id="T_3c77f_row9_col3" class="data row9 col3" >001</td>
      <td id="T_3c77f_row9_col4" class="data row9 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_3c77f_row9_col5" class="data row9 col5" >FLD</td>
      <td id="T_3c77f_row9_col6" class="data row9 col6" >6</td>
      <td id="T_3c77f_row9_col7" class="data row9 col7" >0</td>
      <td id="T_3c77f_row9_col8" class="data row9 col8" >Carter</td>
    </tr>
    <tr>
      <td id="T_3c77f_row10_col0" class="data row10 col0" >496</td>
      <td id="T_3c77f_row10_col1" class="data row10 col1" >Spring 2021</td>
      <td id="T_3c77f_row10_col2" class="data row10 col2" >ENGR496</td>
      <td id="T_3c77f_row10_col3" class="data row10 col3" >001</td>
      <td id="T_3c77f_row10_col4" class="data row10 col4" >INTERNSHIP REVIEW</td>
      <td id="T_3c77f_row10_col5" class="data row10 col5" >FLD</td>
      <td id="T_3c77f_row10_col6" class="data row10 col6" >37</td>
      <td id="T_3c77f_row10_col7" class="data row10 col7" >0</td>
      <td id="T_3c77f_row10_col8" class="data row10 col8" >Carter</td>
    </tr>
    <tr>
      <td id="T_3c77f_row11_col0" class="data row11 col0" >496</td>
      <td id="T_3c77f_row11_col1" class="data row11 col1" >Spring 2021</td>
      <td id="T_3c77f_row11_col2" class="data row11 col2" >ENGR496</td>
      <td id="T_3c77f_row11_col3" class="data row11 col3" >J01</td>
      <td id="T_3c77f_row11_col4" class="data row11 col4" >INTERNSHIP REVIEW</td>
      <td id="T_3c77f_row11_col5" class="data row11 col5" >FLD</td>
      <td id="T_3c77f_row11_col6" class="data row11 col6" >1</td>
      <td id="T_3c77f_row11_col7" class="data row11 col7" >0</td>
      <td id="T_3c77f_row11_col8" class="data row11 col8" >Carter</td>
    </tr>
    <tr>
      <td id="T_3c77f_row12_col0" class="data row12 col0" >498</td>
      <td id="T_3c77f_row12_col1" class="data row12 col1" >Spring 2021</td>
      <td id="T_3c77f_row12_col2" class="data row12 col2" >ENGR498</td>
      <td id="T_3c77f_row12_col3" class="data row12 col3" >001</td>
      <td id="T_3c77f_row12_col4" class="data row12 col4" >REVIEW OF COOP EDUCATION EXP</td>
      <td id="T_3c77f_row12_col5" class="data row12 col5" >FLD</td>
      <td id="T_3c77f_row12_col6" class="data row12 col6" >12</td>
      <td id="T_3c77f_row12_col7" class="data row12 col7" >0</td>
      <td id="T_3c77f_row12_col8" class="data row12 col8" >Carter</td>
    </tr>
    <tr>
      <td id="T_3c77f_row13_col0" class="data row13 col0" >498</td>
      <td id="T_3c77f_row13_col1" class="data row13 col1" >Spring 2021</td>
      <td id="T_3c77f_row13_col2" class="data row13 col2" >ENGR498</td>
      <td id="T_3c77f_row13_col3" class="data row13 col3" >J01</td>
      <td id="T_3c77f_row13_col4" class="data row13 col4" >REVIEW OF COOP EDUCATION EXP</td>
      <td id="T_3c77f_row13_col5" class="data row13 col5" >FLD</td>
      <td id="T_3c77f_row13_col6" class="data row13 col6" >1</td>
      <td id="T_3c77f_row13_col7" class="data row13 col7" >0</td>
      <td id="T_3c77f_row13_col8" class="data row13 col8" >Carter</td>
    </tr>
    <tr>
      <td id="T_3c77f_row14_col0" class="data row14 col0" >591</td>
      <td id="T_3c77f_row14_col1" class="data row14 col1" >Spring 2021</td>
      <td id="T_3c77f_row14_col2" class="data row14 col2" >ENGR591</td>
      <td id="T_3c77f_row14_col3" class="data row14 col3" >002</td>
      <td id="T_3c77f_row14_col4" class="data row14 col4" >ST: COMP FLUID DYN CLSE: WKSHP</td>
      <td id="T_3c77f_row14_col5" class="data row14 col5" >LEC</td>
      <td id="T_3c77f_row14_col6" class="data row14 col6" >4</td>
      <td id="T_3c77f_row14_col7" class="data row14 col7" >12</td>
      <td id="T_3c77f_row14_col8" class="data row14 col8" >Roper</td>
    </tr>
  </tbody>
</table>

:::

## Summer 2021

::: {style="font-size:0.9em;"}
<style type="text/css">
#T_c20eb table {
  width: 100%;
  border-collapse: collapse;
}
#T_c20eb th {
  text-align: center;
  padding: 1px;
  border: 0;
}
#T_c20eb th {
  border: 0;
}
#T_c20eb thead th.col_heading.level0:nth-child(1) {
  display: none;
}
#T_c20eb tbody td:nth-child(1) {
  display: none;
}
#T_c20eb thead th.col_heading.level0:nth-child(2) {
  display: none;
}
#T_c20eb tbody td:nth-child(2) {
  display: none;
}
#T_c20eb thead th.col_heading.level0:nth-child(8) {
  display: none;
}
#T_c20eb tbody td:nth-child(8) {
  display: none;
}
#T_c20eb td:nth-child(3) {
  padding-right: 5px;
  text-align: left;
}
#T_c20eb td:nth-child(4) {
  padding-right: 5px;
  text-align: left;
}
#T_c20eb td:nth-child(5) {
  padding-right: 0px;
  text-align: left;
}
#T_c20eb td:nth-child(6) {
  padding-right: 0px;
  text-align: center;
}
#T_c20eb td:nth-child(7) {
  padding-right: 0px;
  text-align: right;
}
#T_c20eb td:nth-child(9) {
  padding-left: 10px;
  text-align: left;
}
#T_c20eb_row0_col0, #T_c20eb_row0_col1, #T_c20eb_row0_col2, #T_c20eb_row0_col3, #T_c20eb_row0_col4, #T_c20eb_row0_col5, #T_c20eb_row0_col6, #T_c20eb_row0_col7, #T_c20eb_row0_col8, #T_c20eb_row1_col0, #T_c20eb_row1_col1, #T_c20eb_row1_col2, #T_c20eb_row1_col3, #T_c20eb_row1_col4, #T_c20eb_row1_col5, #T_c20eb_row1_col6, #T_c20eb_row1_col7, #T_c20eb_row1_col8, #T_c20eb_row2_col0, #T_c20eb_row2_col1, #T_c20eb_row2_col2, #T_c20eb_row2_col3, #T_c20eb_row2_col4, #T_c20eb_row2_col5, #T_c20eb_row2_col6, #T_c20eb_row2_col7, #T_c20eb_row2_col8, #T_c20eb_row3_col0, #T_c20eb_row3_col1, #T_c20eb_row3_col2, #T_c20eb_row3_col3, #T_c20eb_row3_col4, #T_c20eb_row3_col5, #T_c20eb_row3_col6, #T_c20eb_row3_col7, #T_c20eb_row3_col8, #T_c20eb_row4_col0, #T_c20eb_row4_col1, #T_c20eb_row4_col2, #T_c20eb_row4_col3, #T_c20eb_row4_col4, #T_c20eb_row4_col5, #T_c20eb_row4_col6, #T_c20eb_row4_col7, #T_c20eb_row4_col8, #T_c20eb_row5_col0, #T_c20eb_row5_col1, #T_c20eb_row5_col2, #T_c20eb_row5_col3, #T_c20eb_row5_col4, #T_c20eb_row5_col5, #T_c20eb_row5_col6, #T_c20eb_row5_col7, #T_c20eb_row5_col8, #T_c20eb_row6_col0, #T_c20eb_row6_col1, #T_c20eb_row6_col2, #T_c20eb_row6_col3, #T_c20eb_row6_col4, #T_c20eb_row6_col5, #T_c20eb_row6_col6, #T_c20eb_row6_col7, #T_c20eb_row6_col8, #T_c20eb_row7_col0, #T_c20eb_row7_col1, #T_c20eb_row7_col2, #T_c20eb_row7_col3, #T_c20eb_row7_col4, #T_c20eb_row7_col5, #T_c20eb_row7_col6, #T_c20eb_row7_col7, #T_c20eb_row7_col8, #T_c20eb_row8_col0, #T_c20eb_row8_col1, #T_c20eb_row8_col2, #T_c20eb_row8_col3, #T_c20eb_row8_col4, #T_c20eb_row8_col5, #T_c20eb_row8_col6, #T_c20eb_row8_col7, #T_c20eb_row8_col8, #T_c20eb_row9_col0, #T_c20eb_row9_col1, #T_c20eb_row9_col2, #T_c20eb_row9_col3, #T_c20eb_row9_col4, #T_c20eb_row9_col5, #T_c20eb_row9_col6, #T_c20eb_row9_col7, #T_c20eb_row9_col8 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_c20eb_row10_col0, #T_c20eb_row10_col1, #T_c20eb_row10_col2, #T_c20eb_row10_col3, #T_c20eb_row10_col4, #T_c20eb_row10_col5, #T_c20eb_row10_col6, #T_c20eb_row10_col7, #T_c20eb_row10_col8, #T_c20eb_row11_col0, #T_c20eb_row11_col1, #T_c20eb_row11_col2, #T_c20eb_row11_col3, #T_c20eb_row11_col4, #T_c20eb_row11_col5, #T_c20eb_row11_col6, #T_c20eb_row11_col7, #T_c20eb_row11_col8, #T_c20eb_row12_col0, #T_c20eb_row12_col1, #T_c20eb_row12_col2, #T_c20eb_row12_col3, #T_c20eb_row12_col4, #T_c20eb_row12_col5, #T_c20eb_row12_col6, #T_c20eb_row12_col7, #T_c20eb_row12_col8, #T_c20eb_row13_col0, #T_c20eb_row13_col1, #T_c20eb_row13_col2, #T_c20eb_row13_col3, #T_c20eb_row13_col4, #T_c20eb_row13_col5, #T_c20eb_row13_col6, #T_c20eb_row13_col7, #T_c20eb_row13_col8 {
  background-color: #ffffff;
  border-bottom: none;
}
</style>
<table id="T_c20eb">
  <thead>
    <tr>
      <th id="T_c20eb_level0_col0" class="col_heading level0 col0" >course_number</th>
      <th id="T_c20eb_level0_col1" class="col_heading level0 col1" >Term</th>
      <th id="T_c20eb_level0_col2" class="col_heading level0 col2" >Crse</th>
      <th id="T_c20eb_level0_col3" class="col_heading level0 col3" >Sect</th>
      <th id="T_c20eb_level0_col4" class="col_heading level0 col4" >Crse Title</th>
      <th id="T_c20eb_level0_col5" class="col_heading level0 col5" >W.Type</th>
      <th id="T_c20eb_level0_col6" class="col_heading level0 col6" >Stdnts</th>
      <th id="T_c20eb_level0_col7" class="col_heading level0 col7" >Hours</th>
      <th id="T_c20eb_level0_col8" class="col_heading level0 col8" >instructor_name</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_c20eb_row0_col0" class="data row0 col0" >395</td>
      <td id="T_c20eb_row0_col1" class="data row0 col1" >Summer 2021</td>
      <td id="T_c20eb_row0_col2" class="data row0 col2" >ENGR395</td>
      <td id="T_c20eb_row0_col3" class="data row0 col3" >001</td>
      <td id="T_c20eb_row0_col4" class="data row0 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c20eb_row0_col5" class="data row0 col5" >LEC</td>
      <td id="T_c20eb_row0_col6" class="data row0 col6" >8</td>
      <td id="T_c20eb_row0_col7" class="data row0 col7" >8</td>
      <td id="T_c20eb_row0_col8" class="data row0 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c20eb_row1_col0" class="data row1 col0" >395</td>
      <td id="T_c20eb_row1_col1" class="data row1 col1" >Summer 2021</td>
      <td id="T_c20eb_row1_col2" class="data row1 col2" >ENGR395</td>
      <td id="T_c20eb_row1_col3" class="data row1 col3" >001</td>
      <td id="T_c20eb_row1_col4" class="data row1 col4" >PROFESSIONAL DEVELOPMENT</td>
      <td id="T_c20eb_row1_col5" class="data row1 col5" >LEC</td>
      <td id="T_c20eb_row1_col6" class="data row1 col6" >8</td>
      <td id="T_c20eb_row1_col7" class="data row1 col7" >8</td>
      <td id="T_c20eb_row1_col8" class="data row1 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_c20eb_row2_col0" class="data row2 col0" >396</td>
      <td id="T_c20eb_row2_col1" class="data row2 col1" >Summer 2021</td>
      <td id="T_c20eb_row2_col2" class="data row2 col2" >ENGR396</td>
      <td id="T_c20eb_row2_col3" class="data row2 col3" >001</td>
      <td id="T_c20eb_row2_col4" class="data row2 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_c20eb_row2_col5" class="data row2 col5" >FLD</td>
      <td id="T_c20eb_row2_col6" class="data row2 col6" >42</td>
      <td id="T_c20eb_row2_col7" class="data row2 col7" >0</td>
      <td id="T_c20eb_row2_col8" class="data row2 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c20eb_row3_col0" class="data row3 col0" >396</td>
      <td id="T_c20eb_row3_col1" class="data row3 col1" >Summer 2021</td>
      <td id="T_c20eb_row3_col2" class="data row3 col2" >ENGR396</td>
      <td id="T_c20eb_row3_col3" class="data row3 col3" >001</td>
      <td id="T_c20eb_row3_col4" class="data row3 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_c20eb_row3_col5" class="data row3 col5" >FLD</td>
      <td id="T_c20eb_row3_col6" class="data row3 col6" >42</td>
      <td id="T_c20eb_row3_col7" class="data row3 col7" >0</td>
      <td id="T_c20eb_row3_col8" class="data row3 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_c20eb_row4_col0" class="data row4 col0" >396</td>
      <td id="T_c20eb_row4_col1" class="data row4 col1" >Summer 2021</td>
      <td id="T_c20eb_row4_col2" class="data row4 col2" >ENGR396</td>
      <td id="T_c20eb_row4_col3" class="data row4 col3" >002</td>
      <td id="T_c20eb_row4_col4" class="data row4 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_c20eb_row4_col5" class="data row4 col5" >FLD</td>
      <td id="T_c20eb_row4_col6" class="data row4 col6" >10</td>
      <td id="T_c20eb_row4_col7" class="data row4 col7" >0</td>
      <td id="T_c20eb_row4_col8" class="data row4 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c20eb_row5_col0" class="data row5 col0" >396</td>
      <td id="T_c20eb_row5_col1" class="data row5 col1" >Summer 2021</td>
      <td id="T_c20eb_row5_col2" class="data row5 col2" >ENGR396</td>
      <td id="T_c20eb_row5_col3" class="data row5 col3" >002</td>
      <td id="T_c20eb_row5_col4" class="data row5 col4" >INTERSHIP EXPERIENCE</td>
      <td id="T_c20eb_row5_col5" class="data row5 col5" >FLD</td>
      <td id="T_c20eb_row5_col6" class="data row5 col6" >10</td>
      <td id="T_c20eb_row5_col7" class="data row5 col7" >0</td>
      <td id="T_c20eb_row5_col8" class="data row5 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_c20eb_row6_col0" class="data row6 col0" >398</td>
      <td id="T_c20eb_row6_col1" class="data row6 col1" >Summer 2021</td>
      <td id="T_c20eb_row6_col2" class="data row6 col2" >ENGR398</td>
      <td id="T_c20eb_row6_col3" class="data row6 col3" >001</td>
      <td id="T_c20eb_row6_col4" class="data row6 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_c20eb_row6_col5" class="data row6 col5" >FLD</td>
      <td id="T_c20eb_row6_col6" class="data row6 col6" >5</td>
      <td id="T_c20eb_row6_col7" class="data row6 col7" >0</td>
      <td id="T_c20eb_row6_col8" class="data row6 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c20eb_row7_col0" class="data row7 col0" >398</td>
      <td id="T_c20eb_row7_col1" class="data row7 col1" >Summer 2021</td>
      <td id="T_c20eb_row7_col2" class="data row7 col2" >ENGR398</td>
      <td id="T_c20eb_row7_col3" class="data row7 col3" >001</td>
      <td id="T_c20eb_row7_col4" class="data row7 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_c20eb_row7_col5" class="data row7 col5" >FLD</td>
      <td id="T_c20eb_row7_col6" class="data row7 col6" >5</td>
      <td id="T_c20eb_row7_col7" class="data row7 col7" >0</td>
      <td id="T_c20eb_row7_col8" class="data row7 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_c20eb_row8_col0" class="data row8 col0" >398</td>
      <td id="T_c20eb_row8_col1" class="data row8 col1" >Summer 2021</td>
      <td id="T_c20eb_row8_col2" class="data row8 col2" >ENGR398</td>
      <td id="T_c20eb_row8_col3" class="data row8 col3" >002</td>
      <td id="T_c20eb_row8_col4" class="data row8 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_c20eb_row8_col5" class="data row8 col5" >FLD</td>
      <td id="T_c20eb_row8_col6" class="data row8 col6" >2</td>
      <td id="T_c20eb_row8_col7" class="data row8 col7" >0</td>
      <td id="T_c20eb_row8_col8" class="data row8 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c20eb_row9_col0" class="data row9 col0" >398</td>
      <td id="T_c20eb_row9_col1" class="data row9 col1" >Summer 2021</td>
      <td id="T_c20eb_row9_col2" class="data row9 col2" >ENGR398</td>
      <td id="T_c20eb_row9_col3" class="data row9 col3" >002</td>
      <td id="T_c20eb_row9_col4" class="data row9 col4" >COOPERATIVE EDUCATION EXP</td>
      <td id="T_c20eb_row9_col5" class="data row9 col5" >FLD</td>
      <td id="T_c20eb_row9_col6" class="data row9 col6" >2</td>
      <td id="T_c20eb_row9_col7" class="data row9 col7" >0</td>
      <td id="T_c20eb_row9_col8" class="data row9 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_c20eb_row10_col0" class="data row10 col0" >496</td>
      <td id="T_c20eb_row10_col1" class="data row10 col1" >Summer 2021</td>
      <td id="T_c20eb_row10_col2" class="data row10 col2" >ENGR496</td>
      <td id="T_c20eb_row10_col3" class="data row10 col3" >001</td>
      <td id="T_c20eb_row10_col4" class="data row10 col4" >INTERNSHIP REVIEW</td>
      <td id="T_c20eb_row10_col5" class="data row10 col5" >FLD</td>
      <td id="T_c20eb_row10_col6" class="data row10 col6" >2</td>
      <td id="T_c20eb_row10_col7" class="data row10 col7" >0</td>
      <td id="T_c20eb_row10_col8" class="data row10 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c20eb_row11_col0" class="data row11 col0" >496</td>
      <td id="T_c20eb_row11_col1" class="data row11 col1" >Summer 2021</td>
      <td id="T_c20eb_row11_col2" class="data row11 col2" >ENGR496</td>
      <td id="T_c20eb_row11_col3" class="data row11 col3" >001</td>
      <td id="T_c20eb_row11_col4" class="data row11 col4" >INTERNSHIP REVIEW</td>
      <td id="T_c20eb_row11_col5" class="data row11 col5" >FLD</td>
      <td id="T_c20eb_row11_col6" class="data row11 col6" >2</td>
      <td id="T_c20eb_row11_col7" class="data row11 col7" >0</td>
      <td id="T_c20eb_row11_col8" class="data row11 col8" >Sharpe</td>
    </tr>
    <tr>
      <td id="T_c20eb_row12_col0" class="data row12 col0" >496</td>
      <td id="T_c20eb_row12_col1" class="data row12 col1" >Summer 2021</td>
      <td id="T_c20eb_row12_col2" class="data row12 col2" >ENGR496</td>
      <td id="T_c20eb_row12_col3" class="data row12 col3" >002</td>
      <td id="T_c20eb_row12_col4" class="data row12 col4" >INTERNSHIP REVIEW</td>
      <td id="T_c20eb_row12_col5" class="data row12 col5" >FLD</td>
      <td id="T_c20eb_row12_col6" class="data row12 col6" >1</td>
      <td id="T_c20eb_row12_col7" class="data row12 col7" >0</td>
      <td id="T_c20eb_row12_col8" class="data row12 col8" >Avasthi</td>
    </tr>
    <tr>
      <td id="T_c20eb_row13_col0" class="data row13 col0" >496</td>
      <td id="T_c20eb_row13_col1" class="data row13 col1" >Summer 2021</td>
      <td id="T_c20eb_row13_col2" class="data row13 col2" >ENGR496</td>
      <td id="T_c20eb_row13_col3" class="data row13 col3" >002</td>
      <td id="T_c20eb_row13_col4" class="data row13 col4" >INTERNSHIP REVIEW</td>
      <td id="T_c20eb_row13_col5" class="data row13 col5" >FLD</td>
      <td id="T_c20eb_row13_col6" class="data row13 col6" >1</td>
      <td id="T_c20eb_row13_col7" class="data row13 col7" >0</td>
      <td id="T_c20eb_row13_col8" class="data row13 col8" >Sharpe</td>
    </tr>
  </tbody>
</table>

:::
