---
title: Instructor Teaching Activity - Innovation
date: last-modified
---

Instructor teaching activity for Innovation.

# Overview

This report slices and dices instructor teaching activity several ways:

* Recent academic years - a listing of instructor activity 
for a recent academic year for instructors teaching during that academic year.

* All instructors - a listing of instructor activity over time
for all instructors in [the sample](/10_download.html).

The page navigation on the right side of the display can help
as you explore the data.

**Issues and Errors**

Banner doesn’t always reflect reality. Contact John Leonard if you find inconsistences and we'll
incorporate them into the next iteration of the report.  See [this section](/20_clean.html#fix-known-errors) to learn more.


# AY25-26

This section list instructor activity for the academic year AY25-26 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## William Benton

<style type="text/css">
#T_7f809_row0_col0, #T_7f809_row0_col1, #T_7f809_row0_col2, #T_7f809_row0_col3, #T_7f809_row0_col4, #T_7f809_row0_col5, #T_7f809_row0_col6 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_7f809_row1_col0, #T_7f809_row1_col1, #T_7f809_row1_col2, #T_7f809_row1_col3, #T_7f809_row1_col4, #T_7f809_row1_col5, #T_7f809_row1_col6 {
  background-color: #f0f0f0;
  border-bottom: 1px solid #ccc;
}
</style>
<table id="T_7f809">
  <thead>
    <tr>
      <th id="T_7f809_level0_col0" class="col_heading level0 col0" >Term</th>
      <th id="T_7f809_level0_col1" class="col_heading level0 col1" >Crse</th>
      <th id="T_7f809_level0_col2" class="col_heading level0 col2" >Sect</th>
      <th id="T_7f809_level0_col3" class="col_heading level0 col3" >Crse Title</th>
      <th id="T_7f809_level0_col4" class="col_heading level0 col4" >W.Type</th>
      <th id="T_7f809_level0_col5" class="col_heading level0 col5" >Stdnts</th>
      <th id="T_7f809_level0_col6" class="col_heading level0 col6" >Hours</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_7f809_row0_col0" class="data row0 col0" >Fall 2025</td>
      <td id="T_7f809_row0_col1" class="data row0 col1" >ENGR497</td>
      <td id="T_7f809_row0_col2" class="data row0 col2" >L52</td>
      <td id="T_7f809_row0_col3" class="data row0 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_7f809_row0_col4" class="data row0 col4" >VIP</td>
      <td id="T_7f809_row0_col5" class="data row0 col5" >1</td>
      <td id="T_7f809_row0_col6" class="data row0 col6" >1</td>
    </tr>
    <tr>
      <td id="T_7f809_row1_col0" class="data row1 col0" >Fall 2025</td>
      <td id="T_7f809_row1_col1" class="data row1 col1" >ENGR497</td>
      <td id="T_7f809_row1_col2" class="data row1 col2" >L53</td>
      <td id="T_7f809_row1_col3" class="data row1 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_7f809_row1_col4" class="data row1 col4" >VIP</td>
      <td id="T_7f809_row1_col5" class="data row1 col5" >1</td>
      <td id="T_7f809_row1_col6" class="data row1 col6" >2</td>
    </tr>
  </tbody>
</table>



# AY24-25

This section list instructor activity for the academic year AY24-25 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## William Benton

<style type="text/css">
#T_e30d4_row0_col0, #T_e30d4_row0_col1, #T_e30d4_row0_col2, #T_e30d4_row0_col3, #T_e30d4_row0_col4, #T_e30d4_row0_col5, #T_e30d4_row0_col6 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_e30d4_row1_col0, #T_e30d4_row1_col1, #T_e30d4_row1_col2, #T_e30d4_row1_col3, #T_e30d4_row1_col4, #T_e30d4_row1_col5, #T_e30d4_row1_col6 {
  background-color: #f0f0f0;
  border-bottom: 1px solid #ccc;
}
#T_e30d4_row2_col0, #T_e30d4_row2_col1, #T_e30d4_row2_col2, #T_e30d4_row2_col3, #T_e30d4_row2_col4, #T_e30d4_row2_col5, #T_e30d4_row2_col6 {
  background-color: #ffffff;
  border-bottom: none;
}
#T_e30d4_row3_col0, #T_e30d4_row3_col1, #T_e30d4_row3_col2, #T_e30d4_row3_col3, #T_e30d4_row3_col4, #T_e30d4_row3_col5, #T_e30d4_row3_col6 {
  background-color: #ffffff;
  border-bottom: 1px solid #ccc;
}
</style>
<table id="T_e30d4">
  <thead>
    <tr>
      <th id="T_e30d4_level0_col0" class="col_heading level0 col0" >Term</th>
      <th id="T_e30d4_level0_col1" class="col_heading level0 col1" >Crse</th>
      <th id="T_e30d4_level0_col2" class="col_heading level0 col2" >Sect</th>
      <th id="T_e30d4_level0_col3" class="col_heading level0 col3" >Crse Title</th>
      <th id="T_e30d4_level0_col4" class="col_heading level0 col4" >W.Type</th>
      <th id="T_e30d4_level0_col5" class="col_heading level0 col5" >Stdnts</th>
      <th id="T_e30d4_level0_col6" class="col_heading level0 col6" >Hours</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_e30d4_row0_col0" class="data row0 col0" >Fall 2024</td>
      <td id="T_e30d4_row0_col1" class="data row0 col1" >ENGR497</td>
      <td id="T_e30d4_row0_col2" class="data row0 col2" >L52</td>
      <td id="T_e30d4_row0_col3" class="data row0 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_e30d4_row0_col4" class="data row0 col4" >VIP</td>
      <td id="T_e30d4_row0_col5" class="data row0 col5" >3</td>
      <td id="T_e30d4_row0_col6" class="data row0 col6" >3</td>
    </tr>
    <tr>
      <td id="T_e30d4_row1_col0" class="data row1 col0" >Fall 2024</td>
      <td id="T_e30d4_row1_col1" class="data row1 col1" >ENGR497</td>
      <td id="T_e30d4_row1_col2" class="data row1 col2" >L53</td>
      <td id="T_e30d4_row1_col3" class="data row1 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_e30d4_row1_col4" class="data row1 col4" >VIP</td>
      <td id="T_e30d4_row1_col5" class="data row1 col5" >2</td>
      <td id="T_e30d4_row1_col6" class="data row1 col6" >3</td>
    </tr>
    <tr>
      <td id="T_e30d4_row2_col0" class="data row2 col0" >Spring 2025</td>
      <td id="T_e30d4_row2_col1" class="data row2 col1" >ENGR497</td>
      <td id="T_e30d4_row2_col2" class="data row2 col2" >L56</td>
      <td id="T_e30d4_row2_col3" class="data row2 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_e30d4_row2_col4" class="data row2 col4" >VIP</td>
      <td id="T_e30d4_row2_col5" class="data row2 col5" >2</td>
      <td id="T_e30d4_row2_col6" class="data row2 col6" >2</td>
    </tr>
    <tr>
      <td id="T_e30d4_row3_col0" class="data row3 col0" >Spring 2025</td>
      <td id="T_e30d4_row3_col1" class="data row3 col1" >ENGR497</td>
      <td id="T_e30d4_row3_col2" class="data row3 col2" >L57</td>
      <td id="T_e30d4_row3_col3" class="data row3 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_e30d4_row3_col4" class="data row3 col4" >VIP</td>
      <td id="T_e30d4_row3_col5" class="data row3 col5" >2</td>
      <td id="T_e30d4_row3_col6" class="data row3 col6" >3</td>
    </tr>
  </tbody>
</table>



# AY23-24

This section list instructor activity for the academic year AY23-24 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## William Benton

<style type="text/css">
#T_e1d02_row0_col0, #T_e1d02_row0_col1, #T_e1d02_row0_col2, #T_e1d02_row0_col3, #T_e1d02_row0_col4, #T_e1d02_row0_col5, #T_e1d02_row0_col6 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_e1d02_row1_col0, #T_e1d02_row1_col1, #T_e1d02_row1_col2, #T_e1d02_row1_col3, #T_e1d02_row1_col4, #T_e1d02_row1_col5, #T_e1d02_row1_col6 {
  background-color: #f0f0f0;
  border-bottom: 1px solid #ccc;
}
#T_e1d02_row2_col0, #T_e1d02_row2_col1, #T_e1d02_row2_col2, #T_e1d02_row2_col3, #T_e1d02_row2_col4, #T_e1d02_row2_col5, #T_e1d02_row2_col6 {
  background-color: #ffffff;
  border-bottom: none;
}
#T_e1d02_row3_col0, #T_e1d02_row3_col1, #T_e1d02_row3_col2, #T_e1d02_row3_col3, #T_e1d02_row3_col4, #T_e1d02_row3_col5, #T_e1d02_row3_col6 {
  background-color: #ffffff;
  border-bottom: 1px solid #ccc;
}
</style>
<table id="T_e1d02">
  <thead>
    <tr>
      <th id="T_e1d02_level0_col0" class="col_heading level0 col0" >Term</th>
      <th id="T_e1d02_level0_col1" class="col_heading level0 col1" >Crse</th>
      <th id="T_e1d02_level0_col2" class="col_heading level0 col2" >Sect</th>
      <th id="T_e1d02_level0_col3" class="col_heading level0 col3" >Crse Title</th>
      <th id="T_e1d02_level0_col4" class="col_heading level0 col4" >W.Type</th>
      <th id="T_e1d02_level0_col5" class="col_heading level0 col5" >Stdnts</th>
      <th id="T_e1d02_level0_col6" class="col_heading level0 col6" >Hours</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_e1d02_row0_col0" class="data row0 col0" >Fall 2023</td>
      <td id="T_e1d02_row0_col1" class="data row0 col1" >ENGR497</td>
      <td id="T_e1d02_row0_col2" class="data row0 col2" >L52</td>
      <td id="T_e1d02_row0_col3" class="data row0 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_e1d02_row0_col4" class="data row0 col4" >VIP</td>
      <td id="T_e1d02_row0_col5" class="data row0 col5" >3</td>
      <td id="T_e1d02_row0_col6" class="data row0 col6" >3</td>
    </tr>
    <tr>
      <td id="T_e1d02_row1_col0" class="data row1 col0" >Fall 2023</td>
      <td id="T_e1d02_row1_col1" class="data row1 col1" >ENGR497</td>
      <td id="T_e1d02_row1_col2" class="data row1 col2" >L53</td>
      <td id="T_e1d02_row1_col3" class="data row1 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_e1d02_row1_col4" class="data row1 col4" >VIP</td>
      <td id="T_e1d02_row1_col5" class="data row1 col5" >2</td>
      <td id="T_e1d02_row1_col6" class="data row1 col6" >3</td>
    </tr>
    <tr>
      <td id="T_e1d02_row2_col0" class="data row2 col0" >Spring 2024</td>
      <td id="T_e1d02_row2_col1" class="data row2 col1" >ENGR497</td>
      <td id="T_e1d02_row2_col2" class="data row2 col2" >L56</td>
      <td id="T_e1d02_row2_col3" class="data row2 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_e1d02_row2_col4" class="data row2 col4" >VIP</td>
      <td id="T_e1d02_row2_col5" class="data row2 col5" >4</td>
      <td id="T_e1d02_row2_col6" class="data row2 col6" >4</td>
    </tr>
    <tr>
      <td id="T_e1d02_row3_col0" class="data row3 col0" >Spring 2024</td>
      <td id="T_e1d02_row3_col1" class="data row3 col1" >ENGR497</td>
      <td id="T_e1d02_row3_col2" class="data row3 col2" >L57</td>
      <td id="T_e1d02_row3_col3" class="data row3 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_e1d02_row3_col4" class="data row3 col4" >VIP</td>
      <td id="T_e1d02_row3_col5" class="data row3 col5" >0</td>
      <td id="T_e1d02_row3_col6" class="data row3 col6" >1</td>
    </tr>
  </tbody>
</table>



# AY22-23

This section list instructor activity for the academic year AY22-23 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


## William Benton

<style type="text/css">
#T_941b2_row0_col0, #T_941b2_row0_col1, #T_941b2_row0_col2, #T_941b2_row0_col3, #T_941b2_row0_col4, #T_941b2_row0_col5, #T_941b2_row0_col6 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_941b2_row1_col0, #T_941b2_row1_col1, #T_941b2_row1_col2, #T_941b2_row1_col3, #T_941b2_row1_col4, #T_941b2_row1_col5, #T_941b2_row1_col6 {
  background-color: #f0f0f0;
  border-bottom: 1px solid #ccc;
}
#T_941b2_row2_col0, #T_941b2_row2_col1, #T_941b2_row2_col2, #T_941b2_row2_col3, #T_941b2_row2_col4, #T_941b2_row2_col5, #T_941b2_row2_col6 {
  background-color: #ffffff;
  border-bottom: none;
}
#T_941b2_row3_col0, #T_941b2_row3_col1, #T_941b2_row3_col2, #T_941b2_row3_col3, #T_941b2_row3_col4, #T_941b2_row3_col5, #T_941b2_row3_col6 {
  background-color: #ffffff;
  border-bottom: 1px solid #ccc;
}
</style>
<table id="T_941b2">
  <thead>
    <tr>
      <th id="T_941b2_level0_col0" class="col_heading level0 col0" >Term</th>
      <th id="T_941b2_level0_col1" class="col_heading level0 col1" >Crse</th>
      <th id="T_941b2_level0_col2" class="col_heading level0 col2" >Sect</th>
      <th id="T_941b2_level0_col3" class="col_heading level0 col3" >Crse Title</th>
      <th id="T_941b2_level0_col4" class="col_heading level0 col4" >W.Type</th>
      <th id="T_941b2_level0_col5" class="col_heading level0 col5" >Stdnts</th>
      <th id="T_941b2_level0_col6" class="col_heading level0 col6" >Hours</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_941b2_row0_col0" class="data row0 col0" >Fall 2022</td>
      <td id="T_941b2_row0_col1" class="data row0 col1" >ENGR497</td>
      <td id="T_941b2_row0_col2" class="data row0 col2" >L52</td>
      <td id="T_941b2_row0_col3" class="data row0 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_941b2_row0_col4" class="data row0 col4" >VIP</td>
      <td id="T_941b2_row0_col5" class="data row0 col5" >6</td>
      <td id="T_941b2_row0_col6" class="data row0 col6" >6</td>
    </tr>
    <tr>
      <td id="T_941b2_row1_col0" class="data row1 col0" >Fall 2022</td>
      <td id="T_941b2_row1_col1" class="data row1 col1" >ENGR497</td>
      <td id="T_941b2_row1_col2" class="data row1 col2" >L53</td>
      <td id="T_941b2_row1_col3" class="data row1 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_941b2_row1_col4" class="data row1 col4" >VIP</td>
      <td id="T_941b2_row1_col5" class="data row1 col5" >2</td>
      <td id="T_941b2_row1_col6" class="data row1 col6" >4</td>
    </tr>
    <tr>
      <td id="T_941b2_row2_col0" class="data row2 col0" >Spring 2023</td>
      <td id="T_941b2_row2_col1" class="data row2 col1" >ENGR497</td>
      <td id="T_941b2_row2_col2" class="data row2 col2" >L56</td>
      <td id="T_941b2_row2_col3" class="data row2 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_941b2_row2_col4" class="data row2 col4" >VIP</td>
      <td id="T_941b2_row2_col5" class="data row2 col5" >7</td>
      <td id="T_941b2_row2_col6" class="data row2 col6" >7</td>
    </tr>
    <tr>
      <td id="T_941b2_row3_col0" class="data row3 col0" >Spring 2023</td>
      <td id="T_941b2_row3_col1" class="data row3 col1" >ENGR497</td>
      <td id="T_941b2_row3_col2" class="data row3 col2" >L57</td>
      <td id="T_941b2_row3_col3" class="data row3 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_941b2_row3_col4" class="data row3 col4" >VIP</td>
      <td id="T_941b2_row3_col5" class="data row3 col5" >4</td>
      <td id="T_941b2_row3_col6" class="data row3 col6" >9</td>
    </tr>
  </tbody>
</table>



# AY21-22

This section list instructor activity for the academic year AY21-22 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


# AY20-21

This section list instructor activity for the academic year AY20-21 for faculty teaching during that academic year.

The current / most recent academic year might not be complete and will only show data from the terms that have been taught.


# All Instructors


## William Benton

<style type="text/css">
#T_3c5e9_row0_col0, #T_3c5e9_row0_col1, #T_3c5e9_row0_col2, #T_3c5e9_row0_col3, #T_3c5e9_row0_col4, #T_3c5e9_row0_col5, #T_3c5e9_row0_col6, #T_3c5e9_row4_col0, #T_3c5e9_row4_col1, #T_3c5e9_row4_col2, #T_3c5e9_row4_col3, #T_3c5e9_row4_col4, #T_3c5e9_row4_col5, #T_3c5e9_row4_col6, #T_3c5e9_row8_col0, #T_3c5e9_row8_col1, #T_3c5e9_row8_col2, #T_3c5e9_row8_col3, #T_3c5e9_row8_col4, #T_3c5e9_row8_col5, #T_3c5e9_row8_col6, #T_3c5e9_row12_col0, #T_3c5e9_row12_col1, #T_3c5e9_row12_col2, #T_3c5e9_row12_col3, #T_3c5e9_row12_col4, #T_3c5e9_row12_col5, #T_3c5e9_row12_col6 {
  background-color: #f0f0f0;
  border-bottom: none;
}
#T_3c5e9_row1_col0, #T_3c5e9_row1_col1, #T_3c5e9_row1_col2, #T_3c5e9_row1_col3, #T_3c5e9_row1_col4, #T_3c5e9_row1_col5, #T_3c5e9_row1_col6, #T_3c5e9_row5_col0, #T_3c5e9_row5_col1, #T_3c5e9_row5_col2, #T_3c5e9_row5_col3, #T_3c5e9_row5_col4, #T_3c5e9_row5_col5, #T_3c5e9_row5_col6, #T_3c5e9_row9_col0, #T_3c5e9_row9_col1, #T_3c5e9_row9_col2, #T_3c5e9_row9_col3, #T_3c5e9_row9_col4, #T_3c5e9_row9_col5, #T_3c5e9_row9_col6, #T_3c5e9_row13_col0, #T_3c5e9_row13_col1, #T_3c5e9_row13_col2, #T_3c5e9_row13_col3, #T_3c5e9_row13_col4, #T_3c5e9_row13_col5, #T_3c5e9_row13_col6 {
  background-color: #f0f0f0;
  border-bottom: 1px solid #ccc;
}
#T_3c5e9_row2_col0, #T_3c5e9_row2_col1, #T_3c5e9_row2_col2, #T_3c5e9_row2_col3, #T_3c5e9_row2_col4, #T_3c5e9_row2_col5, #T_3c5e9_row2_col6, #T_3c5e9_row6_col0, #T_3c5e9_row6_col1, #T_3c5e9_row6_col2, #T_3c5e9_row6_col3, #T_3c5e9_row6_col4, #T_3c5e9_row6_col5, #T_3c5e9_row6_col6, #T_3c5e9_row10_col0, #T_3c5e9_row10_col1, #T_3c5e9_row10_col2, #T_3c5e9_row10_col3, #T_3c5e9_row10_col4, #T_3c5e9_row10_col5, #T_3c5e9_row10_col6 {
  background-color: #ffffff;
  border-bottom: none;
}
#T_3c5e9_row3_col0, #T_3c5e9_row3_col1, #T_3c5e9_row3_col2, #T_3c5e9_row3_col3, #T_3c5e9_row3_col4, #T_3c5e9_row3_col5, #T_3c5e9_row3_col6, #T_3c5e9_row7_col0, #T_3c5e9_row7_col1, #T_3c5e9_row7_col2, #T_3c5e9_row7_col3, #T_3c5e9_row7_col4, #T_3c5e9_row7_col5, #T_3c5e9_row7_col6, #T_3c5e9_row11_col0, #T_3c5e9_row11_col1, #T_3c5e9_row11_col2, #T_3c5e9_row11_col3, #T_3c5e9_row11_col4, #T_3c5e9_row11_col5, #T_3c5e9_row11_col6 {
  background-color: #ffffff;
  border-bottom: 1px solid #ccc;
}
</style>
<table id="T_3c5e9">
  <thead>
    <tr>
      <th id="T_3c5e9_level0_col0" class="col_heading level0 col0" >Term</th>
      <th id="T_3c5e9_level0_col1" class="col_heading level0 col1" >Crse</th>
      <th id="T_3c5e9_level0_col2" class="col_heading level0 col2" >Sect</th>
      <th id="T_3c5e9_level0_col3" class="col_heading level0 col3" >Crse Title</th>
      <th id="T_3c5e9_level0_col4" class="col_heading level0 col4" >W.Type</th>
      <th id="T_3c5e9_level0_col5" class="col_heading level0 col5" >Stdnts</th>
      <th id="T_3c5e9_level0_col6" class="col_heading level0 col6" >Hours</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="T_3c5e9_row0_col0" class="data row0 col0" >Fall 2022</td>
      <td id="T_3c5e9_row0_col1" class="data row0 col1" >ENGR497</td>
      <td id="T_3c5e9_row0_col2" class="data row0 col2" >L52</td>
      <td id="T_3c5e9_row0_col3" class="data row0 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_3c5e9_row0_col4" class="data row0 col4" >VIP</td>
      <td id="T_3c5e9_row0_col5" class="data row0 col5" >6</td>
      <td id="T_3c5e9_row0_col6" class="data row0 col6" >6</td>
    </tr>
    <tr>
      <td id="T_3c5e9_row1_col0" class="data row1 col0" >Fall 2022</td>
      <td id="T_3c5e9_row1_col1" class="data row1 col1" >ENGR497</td>
      <td id="T_3c5e9_row1_col2" class="data row1 col2" >L53</td>
      <td id="T_3c5e9_row1_col3" class="data row1 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_3c5e9_row1_col4" class="data row1 col4" >VIP</td>
      <td id="T_3c5e9_row1_col5" class="data row1 col5" >2</td>
      <td id="T_3c5e9_row1_col6" class="data row1 col6" >4</td>
    </tr>
    <tr>
      <td id="T_3c5e9_row2_col0" class="data row2 col0" >Spring 2023</td>
      <td id="T_3c5e9_row2_col1" class="data row2 col1" >ENGR497</td>
      <td id="T_3c5e9_row2_col2" class="data row2 col2" >L56</td>
      <td id="T_3c5e9_row2_col3" class="data row2 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_3c5e9_row2_col4" class="data row2 col4" >VIP</td>
      <td id="T_3c5e9_row2_col5" class="data row2 col5" >7</td>
      <td id="T_3c5e9_row2_col6" class="data row2 col6" >7</td>
    </tr>
    <tr>
      <td id="T_3c5e9_row3_col0" class="data row3 col0" >Spring 2023</td>
      <td id="T_3c5e9_row3_col1" class="data row3 col1" >ENGR497</td>
      <td id="T_3c5e9_row3_col2" class="data row3 col2" >L57</td>
      <td id="T_3c5e9_row3_col3" class="data row3 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_3c5e9_row3_col4" class="data row3 col4" >VIP</td>
      <td id="T_3c5e9_row3_col5" class="data row3 col5" >4</td>
      <td id="T_3c5e9_row3_col6" class="data row3 col6" >9</td>
    </tr>
    <tr>
      <td id="T_3c5e9_row4_col0" class="data row4 col0" >Fall 2023</td>
      <td id="T_3c5e9_row4_col1" class="data row4 col1" >ENGR497</td>
      <td id="T_3c5e9_row4_col2" class="data row4 col2" >L52</td>
      <td id="T_3c5e9_row4_col3" class="data row4 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_3c5e9_row4_col4" class="data row4 col4" >VIP</td>
      <td id="T_3c5e9_row4_col5" class="data row4 col5" >3</td>
      <td id="T_3c5e9_row4_col6" class="data row4 col6" >3</td>
    </tr>
    <tr>
      <td id="T_3c5e9_row5_col0" class="data row5 col0" >Fall 2023</td>
      <td id="T_3c5e9_row5_col1" class="data row5 col1" >ENGR497</td>
      <td id="T_3c5e9_row5_col2" class="data row5 col2" >L53</td>
      <td id="T_3c5e9_row5_col3" class="data row5 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_3c5e9_row5_col4" class="data row5 col4" >VIP</td>
      <td id="T_3c5e9_row5_col5" class="data row5 col5" >2</td>
      <td id="T_3c5e9_row5_col6" class="data row5 col6" >3</td>
    </tr>
    <tr>
      <td id="T_3c5e9_row6_col0" class="data row6 col0" >Spring 2024</td>
      <td id="T_3c5e9_row6_col1" class="data row6 col1" >ENGR497</td>
      <td id="T_3c5e9_row6_col2" class="data row6 col2" >L56</td>
      <td id="T_3c5e9_row6_col3" class="data row6 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_3c5e9_row6_col4" class="data row6 col4" >VIP</td>
      <td id="T_3c5e9_row6_col5" class="data row6 col5" >4</td>
      <td id="T_3c5e9_row6_col6" class="data row6 col6" >4</td>
    </tr>
    <tr>
      <td id="T_3c5e9_row7_col0" class="data row7 col0" >Spring 2024</td>
      <td id="T_3c5e9_row7_col1" class="data row7 col1" >ENGR497</td>
      <td id="T_3c5e9_row7_col2" class="data row7 col2" >L57</td>
      <td id="T_3c5e9_row7_col3" class="data row7 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_3c5e9_row7_col4" class="data row7 col4" >VIP</td>
      <td id="T_3c5e9_row7_col5" class="data row7 col5" >0</td>
      <td id="T_3c5e9_row7_col6" class="data row7 col6" >1</td>
    </tr>
    <tr>
      <td id="T_3c5e9_row8_col0" class="data row8 col0" >Fall 2024</td>
      <td id="T_3c5e9_row8_col1" class="data row8 col1" >ENGR497</td>
      <td id="T_3c5e9_row8_col2" class="data row8 col2" >L52</td>
      <td id="T_3c5e9_row8_col3" class="data row8 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_3c5e9_row8_col4" class="data row8 col4" >VIP</td>
      <td id="T_3c5e9_row8_col5" class="data row8 col5" >3</td>
      <td id="T_3c5e9_row8_col6" class="data row8 col6" >3</td>
    </tr>
    <tr>
      <td id="T_3c5e9_row9_col0" class="data row9 col0" >Fall 2024</td>
      <td id="T_3c5e9_row9_col1" class="data row9 col1" >ENGR497</td>
      <td id="T_3c5e9_row9_col2" class="data row9 col2" >L53</td>
      <td id="T_3c5e9_row9_col3" class="data row9 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_3c5e9_row9_col4" class="data row9 col4" >VIP</td>
      <td id="T_3c5e9_row9_col5" class="data row9 col5" >2</td>
      <td id="T_3c5e9_row9_col6" class="data row9 col6" >3</td>
    </tr>
    <tr>
      <td id="T_3c5e9_row10_col0" class="data row10 col0" >Spring 2025</td>
      <td id="T_3c5e9_row10_col1" class="data row10 col1" >ENGR497</td>
      <td id="T_3c5e9_row10_col2" class="data row10 col2" >L56</td>
      <td id="T_3c5e9_row10_col3" class="data row10 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_3c5e9_row10_col4" class="data row10 col4" >VIP</td>
      <td id="T_3c5e9_row10_col5" class="data row10 col5" >2</td>
      <td id="T_3c5e9_row10_col6" class="data row10 col6" >2</td>
    </tr>
    <tr>
      <td id="T_3c5e9_row11_col0" class="data row11 col0" >Spring 2025</td>
      <td id="T_3c5e9_row11_col1" class="data row11 col1" >ENGR497</td>
      <td id="T_3c5e9_row11_col2" class="data row11 col2" >L57</td>
      <td id="T_3c5e9_row11_col3" class="data row11 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_3c5e9_row11_col4" class="data row11 col4" >VIP</td>
      <td id="T_3c5e9_row11_col5" class="data row11 col5" >2</td>
      <td id="T_3c5e9_row11_col6" class="data row11 col6" >3</td>
    </tr>
    <tr>
      <td id="T_3c5e9_row12_col0" class="data row12 col0" >Fall 2025</td>
      <td id="T_3c5e9_row12_col1" class="data row12 col1" >ENGR497</td>
      <td id="T_3c5e9_row12_col2" class="data row12 col2" >L52</td>
      <td id="T_3c5e9_row12_col3" class="data row12 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_3c5e9_row12_col4" class="data row12 col4" >VIP</td>
      <td id="T_3c5e9_row12_col5" class="data row12 col5" >1</td>
      <td id="T_3c5e9_row12_col6" class="data row12 col6" >1</td>
    </tr>
    <tr>
      <td id="T_3c5e9_row13_col0" class="data row13 col0" >Fall 2025</td>
      <td id="T_3c5e9_row13_col1" class="data row13 col1" >ENGR497</td>
      <td id="T_3c5e9_row13_col2" class="data row13 col2" >L53</td>
      <td id="T_3c5e9_row13_col3" class="data row13 col3" >VERTICALLY INTEGRATED PROJECTS</td>
      <td id="T_3c5e9_row13_col4" class="data row13 col4" >VIP</td>
      <td id="T_3c5e9_row13_col5" class="data row13 col5" >1</td>
      <td id="T_3c5e9_row13_col6" class="data row13 col6" >2</td>
    </tr>
  </tbody>
</table>


